xonsh/aliases.py
This is how cd works in bash, zsh, etc.
=> cd with no arguments now changes to home dir.

xonsh/built_ins.py
This makes returning values optional, supports tuples of both sizes, along with a return type str, and most importantly, supports interactive output.
=> changed aliasing to support optional return values, and interactive prompts

xonsh/aliases.py
I would suggest adding a newline to the cd error message about the number of arguments
it requires, and adding a new error message to distinguish between "this
doesn't exist" and "this isn't a directory" as bash does.
=> Slightly modified cd error messages

xonsh/environ.py, xonsh/shell.py
Changing the prompt in a meaningful way usually requires me to write a function, but I found myself duplicating a lot of the code in `default_prompt()` for that. Small changes could also be made by doing
```
from xonsh import environ
environ.default_prompt_template = ...
```
but this feels a bit hacky. I wondered if it wouldn't be more convenient if $PROMPT would automatically format itself if it's a string. Setting the prompt to a static string seems rather unusual to me. What do you think?
=> Auto-formatting prompt string

xonsh/shell.py
This is a proposed change that lets xonsh update the title of a virtual terminal to show a message (specified via a function or a string in the `XONSH_TITLE` environment variable).  Currently defaults to showing the current working directory.  I do a lot of work in tabbed terminals, and this small addition has made a world of difference for me.
The check in lines 172-173 is so that xonsh doesn't try to set the title when running in a tty.  I am not sure if there is actually a robust cross-platform way to detect whether one is running in a tty or not; if so, then this check should definitely be replaced.
=> change terminal title to show message or current directory

xonsh/shell.py
This patch tries to make sure that xonsh only tries to set the title when running in a virtual terminal.
=> Update to #38 (Virtual Terminal Title)

xonsh/environ.py
The length of the multiline prompt should be based on the length of the prompt _after_ calling `format_prompt`, not before.
=> fix for multiline prompt (given the update from #31)

xonsh/main.py
This patch allows xonsh to run a single command with the -c argument, similar to bash (though not quite 100% compatable since here the command to be run must follow -c directly).
This seems to allow running a single command through ssh to a machine running xonsh (which is what I was hoping to accomplish), e.g. `ssh machine_running_xonsh echo "hello"`
=> Accept -c argument (a la bash)

docs/tutorial.rst, xonsh/environ.py
I kept this pretty short for now.
I agree that a separate doc page for environment variables would be nice, but I wasn't sure how to best fit that into the current structure of the docs. Split up the tutorial into several files? Make a subsection "User guide" that contains more detailed information than the tutorial? Just make another page on the same level as the others?
=> Prompt documentation (for #31)

setup.py
Python2 won't even parse Unicode files without a #coding declaration, because it assumes ascii.
This way, at least you get a sane error (`xonsh currently requires Python 3.4+`).
=> Add a #coding declaration to setup.py

xonsh/completer.py
This is a first attempt to have the tab-completer add quotes to paths where necessary.
It does not go all the way (see the discussion for #68), but it may be a start.
=> Auto-completer: wrap paths in quotes where necessary

xonsh/shell.py
This works for me for fixing #44!  Sorry it took so long...
I do think `reset_screen_size` has to be called every time a new prompt is made for this to work.  As it stands now, this still requires forcing a new prompt after resizing the window, but that's not a real issue.
=> minimize calls to reset_screen_size

xonsh/aliases.py, xonsh/built_ins.py
Not sure if the split and stripping of 'alias ' and the single quotes is right, but it seems to work here.
I chose to add it to aliases.py instead of extending bash_env() in environ.py since it felt better that way.
BTW, in built_ins.py calling builtins.aliases.update instead of builtins.aliases._raw.update failed with NoneType iterable error.
=> Fixes #56 about taking over bash aliases into xonsh.

xonsh/main.py
This is an attempt to fix issue #92.
main.py now takes an optional positional argument, the filename of a script to be run.  If present, xonsh will execute that script and exit, rather than entering the command loop (e.g., `xonsh some_xonsh_script`)
If stdin is non-empty and no filename is specified, xonsh will run the contents of stdin as a xonsh script and exit, rather than entering the command loop (e.g., `echo "print(7+3)" | xonsh`).
=> main.py takes script file or script on stdin

xonsh/aliases.py
The cd alias now updates $OLDPWD and also checks if the argument is a
‘-‘ (single dash) and cd to $OLDPWD if it is. Based on bash’s cd
behaviour. http://ss64.com/bash/cd.html
=> update oldpwd when using cd

xonsh/ast.py, xonsh/built_ins.py, xonsh/execer.py, xonsh/parser.py, xonsh/tools.py
`subproc_line` wasn't used and probably contained a bug (I think there should be a `not` in the if clause, only way it makes sense), so I just assumed it could be removed. I could be mistaken.
I haven't actually tested the changes as I'm running python 3.2, so I made sure to not to change behavior, but there's a risk of typo-type errors.
=> Removed `subproc_line`, fixed typos, small changes

docs/tutorial.rst, xonsh/environ.py, xonsh/shell.py, xonsh/tools.py
Documentation for the environment variables for setting the window title and offering suggestions for mis-typed commands.  
I renamed some of these variables and shuffled things around a little bit, in an attempt to avoid screwing up the table of environment variables in the docs, and for more consistent (I think) naming of environment variables.
=> Documentation and refactoring of window title and suggestions

xonsh/parser.py
This is an attempt to deal with part of #86 by converting the results of `${...}` expressions to strings automatically.  Now, for example, the following works:
```
$ echo ${20+2.}
22.0
```
=> convert result of ${} expression to string

xonsh/environ.py
Resurrecting #74 (in response to issue #73), this time using the git binary only as a fallback, for when the current method fails.
=> Fall back to using git binary to determine branch when necessary

tests/test_parser.py, xonsh/lexer.py, xonsh/parser.py
Add support for complex numbers syntax (e.g., `1+2j`) to xonsh
=> Complex numbers

xonsh/built_ins.py
This changeset allows xonsh to run scripts with shebang lines as in bash, rather than having to invoke other interpreters directly.  Even though `subprocess` can handle shebang lines on its own, falling back to using xonsh as the default interpreter necessitates doing a little bit of checking.
=> Allow running scripts not in the path

xonsh/aliases.py, xonsh/parser.py
This is an attempt to fix xonsh's handling of `~` (issue #127).
The substantive changes are in `cd` in aliases.py, and in `p_subproc_arg` in parser.py (lines 2110-2114 after changes).  This has worked for me so far, but I would appreciate more eyes on it.
=> Handling of ~

xonsh/built_ins.py, xonsh/main.py, xonsh/parser.py
This change allows scripts to be run from xonsh with additional arguments (e.g., `xonsh test.sh uno zwei trois`), and for these arguments to be referenced within the script in bash style (with `$0`, `$1`, ...) by loading them into the script's environment.
=> Allow arguments for xonsh shell scripts

xonsh/main.py, xonsh/shell.py
Just a minor addition: a command-line switch to prevent parsing the .xonshrc file.
Useful when a recent change broke something in your .xonshrc file, and probably in other scenarios. Bash has it as well.
=> Command line switch --no-rc

xonsh/lexer.py
This change causes xonsh to throw an error when a regex expression started with a backtick doesn't have a matching backtick on the same line (if a newline is found when scanning forward to find the matching backtick).
=> xonsh should error on finding a line break inside a regex path (backtick)

xonsh/lexer.py
Currently, xonsh gets confused by Python keywords showing up in subprocess mode (since they are tokenized differently from other names).  For example:
`git config --global ...`
This change causes all names (regardless of whether they are Python keywords) to be tokenized as `NAME` tokens when in subprocess mode, so that they can be interpreted properly.
=> Ignore Python keywords in subprocess mode

docs/api/index.rst, docs/api/jobs.rst, xonsh/aliases.py, xonsh/built_ins.py, xonsh/jobs.py, xonsh/main.py
This PR is an attempt to implement some amount of job control in xonsh, as mentioned in #141.
This changeset implements the following:
* suspending foreground process with ctrl-z
* resuming suspended process in foreground or background
* listing of all current jobs
* killing foreground process with ctrl-c
It also:
* documents the `jobs`, `fg`, and `bg` commands
* modifies `exit` to kill (maybe too forcefully?) all subprocesses, suspended or otherwise, before exiting
* fixes a bug where ctrl-c would kill all child processes, including those running in the background
=> Job control

xonsh/execer.py
xonsh sometimes has a tendency to fall into infinite loops of wrapping statements in `$[]` upon encountering a syntax error.  This patch is an attempt to fix this issue.
An example of code that fails in this way is:
```
def foo(x):
print x
```
=> Error Reporting

xonsh/lexer.py
You were right, @scopatz, the handling of `#` in the lexer was totally bogus (a trivial case where it breaks down is an octothorpe inside of a string).  After some testing, I think the main code in `lexer.py` should handle comments appropriately, so just removing that silly regex replacement seems to fix this.
Amusingly, I ran into this issue when trying to run a `git commit -m` with an issue number in the commit message.
=> Fix lexer's handling of #

xonsh/built_ins.py
This patch changes the semantics of handling executables from outside the path to more closely match what bash does with these kinds of files.
* if the file is a binary (defined as in bash), run it
* otherwise:
* if the first line is a shebang, use that result as the interpreter
* otherwise, use xonsh as the interpreter
This also includes several PEP8 formatting changes, but the substantive changes are 352-368, and 378-387, and 442 in the updated file.
=> Change semantics for running executables from outside the path

xonsh/jobs.py
This fixes a bug in #152 (Job Control).
The old method for waiting for child processes to terminate/stop was to wait for a `SIGCHLD` signal; when that signal was received, the active job was considered done.  The problem with this approach is that processes earlier in the pipeline also send `SIGCHLD` to the parent upon terminating/stopping.  It was possible to construct a pipeline such that the last process would be interpreted as terminated before it actually was, and it and xonsh would be left fighting over the input to the terminal.
This change implements a much simpler and more robust check for a change of status in a child process.
=> Job control bugfix

xonsh/built_ins.py, xonsh/jobs.py
This patch improves the `wait_for_active_job` method.  Rather than polling, we can just wait for `os.waitpid` to return.  This minimizes the time delay between the process actually ending and the next prompt being displayed, and probably saves some extra CPU churning by eliminating the loop.
=> Optimization for waiting for active job to stop

xonsh/main.py, xonsh/parser.py
Two changes here:
* Include a boolean environment variable called `$XONSH_INTERACTIVE` (#166), which is `True` if we are running in interactive mode and `False` otherwise (running a single command or running a script).
* Modify `parser.py` to convert environment variables to strings when they are part of a subprocess expression (so that, e.g., `echo $SOMETHING` can be called, where `$SOMETHING` is neither a string nor a list of strings).
=> Interactive Flag, and Parser Bugfix

docs/api/index.rst, docs/api/pyghooks.rst, docs/tutorial.rst, setup.py, xonsh/pyghooks.py
Here are hooks into pygments that add `xonsh` and `xonshcon` (xonsh console, like pycon) lexers if setuptools is available on install.  This is not 100% in that:
* closing braces in switching between pymode and subproc mode can mess up after multiple nestings
* naked subproc lines (`ls -l` rather than `$[ls -l]`) will receive Python mode highlighting. I am not actually sure that there is a way around this.
Even with these deficiencies, this is still *much* better than nothing and makes our docs a ton more readable. Thus, I think that it should be merged in after review.
=> Pygments Hooks

xonsh/built_ins.py
This is an attempt to fix #148, implementing @SmartViking's suggestion of feeding an appropriate file object directly into the constructor for `Popen`.
=> Attempt to fix #148

tests/test_builtins.py, tests/test_tools.py, xonsh/ast.py, xonsh/built_ins.py, xonsh/execer.py, xonsh/pyghooks.py, xonsh/tools.py
This should fix #174 and is built on #168 (because my text editor needs to have syntax highlighting ~_~)
=> Un-detypes env for mutable value access

docs/tutorial.rst, xonsh/environ.py
Fixes #171.  Clarifies documentation on the use of `BASH_COMPLETIONS` variable, and provides sane defaults for Homebrew and MacPorts standard locations on OSX.
=> Bash completion clarifications

xonsh/completer.py
This is an attempt to deal with the issue from #101, as well as some lingering issues from #68 (and now #181).  The completer now tries a little harder to decide whether to complete only paths, only Python, or both.
One downside is that `Cmd` seems to ignore the order in which the completions are given (I tried to provide a more sane ordering, but it was ignored).  Though, looking at the source for `Cmd`, I'm not sure where that is happening.  For example, reversing the order of the returned lists caused the return value of `xonsh.Shell.completedefault` to be reversed, but hitting tab a second time to show all completions leads to the options being presented in the normal (un-reversed) order.  So as of right now, strings come first, then `..`, then `.`, then capitalized names, then …
=> Completer Updates

docs/tutorial.rst, xonsh/environ.py, xonsh/shell.py
This is a proof-of-concept for an alternative prompt formatter implementation.
New variables for the format string are added to the environment variable `$FORMAT_DICT`.  They can either be strings (which are inserted into the template verbatim) or callables (which are called each time, and whose result is inserted into the template).
`$PROMPT` can still be a callable (which returns the template string) or a string itself.
Values are only computed/used if they show up in the template string.
I have not written tests yet, but I like this structure a lot.  I would be happy to write tests if this is what we want to go with.
Examples:
```
>>> $FORMAT_DICT['test'] = "hey"
>>> $PROMPT = "{test} {cwd} $ "
hey ~ $
```
```
>>> import random
>>> $FORMAT_DICT['test'] = lambda: random.randint(1,9)
>>> …
```
=> Alternative Prompt Format Refactor

docs/devguide.rst, docs/tutorial.rst
This changeset updates a couple of things in the documentation:
* fix some lingering references to PyNE in the dev guide
* change the scripts example in the tutorial to avoid using `$[...]` where it is no longer necessary
In addition, I'm not sure whether this is intentional or not, but the `license` file contains a placeholder for `<COPYRIGHT HOLDER>` and a reference to `THE PYNE DEVELOPMENT TEAM`.  Should those be updated?
=> Documentation Updates

xonsh/tools.py
This is not a big change, but in my experience, it leads xonsh to give better suggestions to incorrect commands.  The change is essentially to ignore case when deciding what commands to suggest, and also when deciding how to order the suggestions.
=> Improved Command Suggestions

tests/test_builtins.py, xonsh/built_ins.py
I found this with respect to running xonsh in bash in xonsh with the new `$FORMATTER_DICT`
=> prevents detyping mappings as string to env.

xonsh/execer.py
This may not be the most elegant solution, but I think it is robust in that it should only consider "standalone" semicolons as terminators for commands (should fix #188).
=> Attempt to fix #188

xonsh/built_ins.py, xonsh/shell.py, xonsh/tools.py
This fixes an issue with #192 by causing invalid commands actually to cause an error to be thrown, including a modification to `Shell` to report those errors in a nicer way.
=> Completer Bugfix

docs/tutorial.rst
This modifies the tutorial to describe the job control features of xonsh.  Also fixes two typos.
=> Documentation for Job Control

xonsh/completer.py, xonsh/tools.py
Modify the completer by changing when it calls `path_complete` as discussed in #192.
This change makes it so that `attr_complete` is called in the following cases, rather than `path_complete`:
`x = "cat".<TAB>`
and
`{"cat": "dog".<TAB>`
=> Completer Update

xonsh/built_ins.py, xonsh/jobs.py
I believe this should fix #201 and #202.  I made the following changes to the job control code:
* moved the logic of creating a new job out of `built_ins.py` and into `jobs.py` where it belongs.
* handled `ProcessLookupError` when trying to add the new job (if we fail to determine the new job's pgroup, don't add to the jobs list).
* handled `KeyError` when trying to print the active job (if no such job exists, don't try to print anything)
=> Reorganize Job Control Code and Fix Bugs

xonsh/aliases.py, xonsh/dirstack.py, xonsh/environ.py
This changeset includes the following:
* implements `AUTO_PUSHD` as an environment variable, to have `cd` automatically push directories to the directory stack
* implements the behavior described in #48, where `cd -<integer>` changes to a previous directory (though as of right now, this operates on the directory stack rather than on some separate history, so `AUTO_PUSHD` must be set to `True` to get the behavior that most people probably want).
* makes `cd` prefer changing to actual directories where there is ambiguity (e.g., running `cd -` when there is a directory called `-` should change to that directory, rather than to `OLDPWD`)
* moves `cd` to the `dirstack` module
* fixes #207
=> cd Changes

xonsh/lexer.py
This changeset includes some refactoring of the lexer module, as well as a change that allows more names in subprocess mode (e.g., `!!`), as discussed in #205.
=> Names in subprocess mode

docs/api/index.rst, docs/api/lazyjson.rst, tests/test_lazyjson.py, xonsh/lazyjson.py
Here are some tools for representing lazily loadable JSON files. This has a lot of potential use for history objects as discussed in #213.  @aig787, this one is for you, but @wrywerytwreywery will have to merge.  If you could both take a look that'd be great!
I haven't gone through the work of making all of the output as pretty as possible because I don't want this to block the progress on the history object any longer.  Sorry this took me so long to get around to.  
The basic idea is that for any `obj` that is JSON convertible, you can use the module as follows:
```python
from xonsh.lazyjson import dump, LazyJSON
obj = {....}
with open('/path/to/file', 'w') as f:
dump(obj, f)  # writes the JSON file with an index inserted
lj = LazyJSON('/path/to/file')  
lj[x][y][z]
lj.load() …
```
=> Lazy JSON File

xonsh/parser.py
This changeset allows string literals to be subproc atoms, which I believe this should fix #217.
=> Fix For Quoted Args

xonsh/built_ins.py
The first of hopefully not too many :)
We want to wait for the active job regardless of whether the command we have just run is a Python function or not (this fixes an issue where `fg`, for example, would go into the first branch, and we would not end up actually waiting for the job that we had just `fg`-ed to finish).
=> small fix from ProcProxy changes

docs/tutorial.rst, xonsh/environ.py
Maybe it's a little presumptuous for my first PR to the project to modify something as fundamental as the default prompt, but I find it incredibly informative to know from the prompt whether the current git repository is clean or dirty.
This PR sets changes the color of the `curr_branch` to be green if git is clean, or red if there are uncommitted files, and updates the documentation with the added `$FORMATTER_DICT` setting.
=> Update prompt to display different color branch name if git is dirty

tests/test_builtins.py, tests/test_environ.py, tests/test_tools.py, xonsh/built_ins.py, xonsh/environ.py, xonsh/main.py, xonsh/tools.py
This PR does a few important things all related to the Env class:
1. It moves it to the environ module
2. It abstracts the notion of validating that an environment variable is well formed, converting a non-well-formed value, and detyping based on the name/key of the variable.
3. It adds the capability to set env vars from the command line with the `-D` flag.
Adding new keys and patterns to the validation should be easy.
=> Env overhaul

docs/api/base_shell.rst, docs/api/history.rst, docs/api/index.rst, docs/api/prompt_toolkit_completer.rst, docs/api/prompt_toolkit_shell.rst, docs/api/readline_shell.rst, tests/test_prompt_toolkit_tools.py, xonsh/base_shell.py, xonsh/environ.py, xonsh/history.py, xonsh/prompt_toolkit_completer.py, xonsh/prompt_toolkit_shell.py, xonsh/readline_shell.py, xonsh/shell.py, xonsh/tools.py
Sorry that it took so long, but here is the first version of xonsh using prompt_toolkit.
First of all it introduces a new env variable: $PROMPT_TOOLKIT_SHELL and prompt_toolkit version of xonsh is launched only if this one is set to True and prompt_toolkit can be imported. Otherwise it runs readline version. This variable is by default set to False.
Prompt_toolkit shell also introduces another variable: $LEXER which specifies what lexer should be used to highlight syntax (None by default).
So, for example, following ~/.xonshrc will make xonsh use prompt_toolkit version of the shell with syntax highlighting:
```
$PROMPT_TOOLKIT_SHELL = True
from xonsh.pyghooks import XonshLexer
$LEXER = XonshLexer
```
Completion also works and generally it has most of the functionality of readline shell. …
=> Prompt toolkit as alternative shell

xonsh/environ.py
This expands the existing default prompt to output hg branch and bookmark information.  I've also taken the opportunity to generalize the existing prompt logic that deal with VCS information so it should be easier to add support for e.g. SVN in the future if anyone wants or needs it.
~~I've implemented this using the python bindings to the mercurial command server (python-hglib on pypi):~~
~~http://mercurial.selenic.com/wiki/PythonHglib~~
~~This is an LGPL library so no worries about mercurial being GPL.~~
~~This functionality depends on installing an optional package from pypi. Arguably, it's one that hg users will likely have installed, but it does add a new soft dependency.  I don't know how sensitive xonsh is to adding dependencies from pypi.~~
I'm happy to bikeshed the inclusion of …
=> Add prompt output for mercurial repository branches and bookmarks

xonsh/built_ins.py
On Windows, xonsh couldn't find some files to run, especially script files ending in .cmd.  In addition, the shebang parsing defaults to using xonsh as the interpreter if it is a text file with no '#!' in the first line.  This caused '.cmd' files to be run by xonsh instead of the Windows cmd.exe.
This patch enables xonsh to use the PATHEXT environment variable to determine which files Windows can run directly.  Also, when a file is in PATHEXT, it skips shebang parsing for that file since Windows will be able to run the file directly.
(The above issues were manifesting when attempting to run 'ack' as installed from chocolatey.org, which provides an 'ack.cmd' file to run it).
=> windows: use PATHEXT to find runnable files and skip shebang parsing

xonsh/prompt_toolkit_completer.py
There was a small bug that caused autocompletion to work properly only when started at the end of a line. 
Here is appropriately small fix.
=> Fix prompt_toolkit autocompletion bug

xonsh/prompt_toolkit_key_bindings.py, xonsh/prompt_toolkit_shell.py
I have been playing a bit with this, and decided that when you use this kind of autocompletion that prompt_toolkit provides (that is autocompletion in a box) it is highly unintuitive for Shift-Tab to insert sudden indentation instead of simply going back in autocompletions list. I guess it is common behavior that if some key iterates forward (Tab in this case) then Shift plus the key should iterate backward.
So I decided to make Tab the key for indentation (it is just more intuitive), and now it behaves like this:
- if there are only whitespaces before cursor position Tab inserts indent
- otherwise it starts autocompletion.
Surely I can map <Shift-TAB> to behave like this (that it inserts indent only if there are only whitespaces) if you think that would be better, or maybe just reproduce …
=> Add possibility to insert indent in prompt_toolkit shell.

docs/tutorial.rst, xonsh/environ.py, xonsh/main.py, xonsh/shell.py
Simply adding possibility to run xonsh in "prompt toolkit mode" from command line, as @scopatz mentioned in #229 .
One can now simply run xonsh like that:
```
xonsh --prompt_toolkit_shell
```
to run it in prompt_toolkit mode.
=> Add option to run xonsh in prompt_toolkit mode from command line.

xonsh/aliases.py
Implementation of the `source` alias as discussed in #262.
=> "source" alias

.appveyor.yml, README.rst, appveyor.yml
@scopatz mentioned Appveyor a few weeks back.  This changeset, when merged, should start reporting the xonsh build status on Windows via appveyor.com.  Currently it's using my appveyor account which was a snap to create by linking it to my github account.  @scopatz, if you'd like to run the main build status through your own Appveyor account that should be pretty easy.  After you create a xonsh project in appveyor, in the General tab you need to specify that it must use ``.appveyor.yml`` with the leading ``.``.  It's also handy to tell it to "skip branches without 'appveyor.yml'".  Then you'd need to update the xonsh ``README.rst`` to fetch the status from your account.
=> windows: automated builds via appveyor

xonsh/aliases.py
The old code for parsing bash alias values did not work for aliases that contain single quotes.
For example,
the following lines in `.bashrc`
alias foo="ls '-l'"
alias bar="ls '-l' -a"
lead to the following output of `bash alias -p`
alias foo='ls '\''-l'\'''
alias bar='ls '\''-l'\'' -a'
Note that all single quotes are weirdly escaped. The behavior is not documented, and thinking about why those escapes happen like this makes my head hurt, but the [source](http://git.savannah.gnu.org/cgit/bash.git/tree/lib/sh/shquote.c#n88) proves that this is the only replacement that happens.
Anyways, because of this, xonsh's current code passes invalid input to `shlex.split`:
aliases.py:90: RuntimeWarning: could not parse Bash alias "foo": ValueError('No escaped character',)
aliases.py:90: …
=> aliases: fixed bash aliases with single quotes

xonsh/built_ins.py
`xonsh` favors extensionless files with shebangs on Windows which
is causing certain issues when some packages come with both Linux
and Windows runnables where the Linux version is extensionless.
This patch favors files ending with any extension listed in
`PATHEXT` over extensionless files on Windows.
Fixes the issue mentioned in here:
https://groups.google.com/d/msg/xonsh/nYraaPmewP0/as6d5TrrBU8J
=> Favor runnable extensions on Windows

recipe/bld.bat, recipe/meta.yaml
Update the conda recipe to build directly from the git repository, and use the tags in git to create the right version number. Also added some fixes to make build work on windows.
=> Update to conda recipe 

docs/tutorial.rst, tests/test_dirstack.py, xonsh/completer.py, xonsh/dirstack.py
CDPATH works like PATH for `cd`, no CDPATH is like CDPATH=. but more prefixes can be added.
=> Add support for CDPATH

recipe/meta.yaml
Removing (>=) in the version specification should allow conda convert to correctly convert conda packages build for linux can be converted to windows.
=> Temporary work-around for bug in conda-build

xonsh/completer.py
This changes `_load_bash_complete_files` to get the definition for each
bash completion function only once, and uses a single call to `declare
-F`.
The output of `complete -p`, which is used in
`completer._load_bash_complete_funcs` is rather large on my system, with a lot of duplicates, especially from 
Most of it appears to come from ubuntu-dev-tools's
``/etc/bash_completion.d/pbuilder-dist`, where a list of aliases is
being setup:
[ "$have" ] && _pbuilder-aliases()
{
local distro builder arch
for distro in $(ubuntu-distro-info --all; debian-distro-info --all) stable testing unstable; do
for builder in pbuilder cowbuilder; do
echo "$builder-$distro"
for arch in i386 amd64 armel armhf; do
echo "$builder-$distro-$arch"
done
done
done
return 0
}
[ "$have" ] && complete -F _pbuilder-dist -o …
=> bash completions: use set() with `declare -F`

xonsh/aliases.py, xonsh/completer.py, xonsh/environ.py
subprocess.CalledProcessError is only raised if the command is found but returns a non-zero exit code. 
This will allow the code to work on windows where the bash command is not on the path. The reason it hasn't been a problem for users is that most people have MsysGit installed on windows, and that adds the bash command to the path.
=> Catch cases where the commands launched by subprocess are not found. 

recipe/meta.yaml
conda build adds this to the package automatically.
=> Remove the Python version restriction from the conda recipe

xonsh/environ.py
xonsh throws an exception and quits when I `cd` into a Mercurial
directory. This patch fixes a few issues causing it to throw exceptions
on Windows when trying to get the `hg` branch name and info.
=> Fix a bunch of `hg` related errors on Windows

xonsh/jobs.py
This is an attempt to fix #265.  It isn't perfect (if you suspend vim, then kill the PID, then `fg` it, you are left with an unusable terminal), but I think it works better than before since that is an edge-case.
=> fix for vim/emacs not coming back from background

.binstar.yml, recipe/meta.yaml
I thought it would be nice to automate the creation of the conda builds on Anaconda.org (formerly binstar.org)
This PR adds a config file to use the free build server on anaconda.org. 
It builds using the linux-64 worker on Anaconda.org, then converts the conda packages to osx-64, linux-32, win-32, win-64. 
@scopatz : To make it work you need to configure the build server for your account.
With "binstar-build" client installed run this command:
binstar-build save  https://github.com/scopatz/xonsh
Then go to http://anaconda.org/scopatz/xonsh/settings/ci and make it look like this:
You may need to enable the webhook to github. 
That should ensure that new conda builds are added to your "dev" channel on Anaconda.org every time you push something to master. You can, of course, configure it as …
=> Added config file for binstar build service

docs/devguide.rst, docs/faq.rst, docs/tutorial.rst
As this is only docs, I thought I start helping with some cleanup of typos.
=> Fixing typos and end of line white space in docs

docs/index.rst
Instructions for installing xonsh on ArchLinux from AUR added.
If merged, this closes #275.
=> ArchLinux installation instructions

docs/index.rst
Add link to IRC channel #xonsh on [OFTC](http://www.oftc.net/).
=> Add link to IRC

xonsh/main.py
Command line switches `-V`/`--version` added (these are the same switches that the Python interpreter uses):
```sh
$ xonsh --version
xonsh/0.1.6
$ 
```
=> Add -V/--version

xonsh/aliases.py
Now moved inside a `with` context.
=> open()'ed files were never closed

docs/tutorial.rst, xonsh/base_shell.py
Hi 
This one is for discussion. I find it a bit annoying to get full tracebacks when working in the shell. If I just try a few things that fail and my screen is complely full of junk. 
So I thought that it may be an idea to hide the traceback by default, and only show the exception. 
This pull request implements that idea. Let me know what you think.
------------------------------------------
The functionality can be controlled with the environment variable $XONSH_SHOW_TRACEBACK
If the variable is not set, the default is to hide the traceback but with an extra notice that the traceback can be enabled:
mel@home ~ $x = {foo:1, bar}
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK=True
ValueError: Dict doesn't have the same number of keys as values
mel@home ~ $
=> Hiding traceback in the shell

xonsh/aliases.py, xonsh/environ.py
=> added login shell to bash

xonsh/completer.py
The previous fix didn't take other current dirs and other path separators into consideration, and so it fixed the `./` problem on Linux/Unix but not e.g. `.\` on Windows.
In an attempt to be platform agnostic this patch uses `os.curdir` and `os.sep`.
Fixes #307.
=> Prevent os.path.normpath() from removing current dir

docs/tutorial.rst, tests/test_environ.py, xonsh/environ.py, xonsh/readline_shell.py
This implements automatic indentation after lines that start with a colon. This implementation is readline specific. Should close #296, as requested by @asmeurer.
=> Prompt Indentation After Colon

xonsh/base_shell.py
This should prevent xonsh from dying if there is an error evaluating a prompt. Closes #301.
=> add exception handling to prompt evaluation

xonsh/main.py
This bug was mentioned by @BYK in a [post on the mailing list](https://groups.google.com/d/msg/xonsh/fRoEQR0QGeA/6mNa83TABAAJ).  It seems not to be something specific to that example, though, but rather something completely general: on Windows only, any time we attempt to pretty-print a Python value, this error occurs.
This patch should fix (tested quickly on Windows 8 and Debian Jessie).
=> fix pretty printing bug on windows

tests/test_execer.py, xonsh/execer.py
I have the following portion in my `.xonshrc` file:
if not pid_exists($SSH_AGENT_PID):
for l in re.split(r'[\n;]', $('ssh-agent')):
if '=' not in l: continue
parts = l.split('=', 1)
os.system("SETX {0} {1}".format(*parts))
builtins.__xonsh_env__[parts[0]] = parts[1]
ssh-add ~/.ssh/id_rsa
And it was throwing an error at the last line saying index was out of range. Figure it was because `lines[idx-1].rstrip()` was an empty string so `lines[idx-1].rstrip()[-1]` was the culprit.
Not sure if this is the best way to fix it and how I can add tests for this.
=> Fix error when checking for indentation

setup.py
it serves no higher purpose and breaks usage in pipsi
also it wouldn't happen for wheels
addresses #288
=> remove logo printing from setup.py

docs/tutorial.rst, xonsh/environ.py
Appearently, some people - like the [freedesktop standards](http://standards.freedesktop.org/basedir-spec/latest/ar01s02.html) - use `DIRS` instead of `PATH`.  A bit odd, but easy to support.
=> Added DIRS rule to environ

xonsh/completer.py
This is a small update to _normpath() wrapper function. Right now it removes any trailing slashes (at least on Windows), which is annoying when completing directory names. 
I have been thinking a bit about the path completion in general. On windows, it doesn't work well when there are white spaces in the files names. I tried different things to fix the path_complete(). But the real problem is that the completions are only done from the last white space. I haven't any real fixes for this yet.
=> Update _normpath wrapper to prevent removing a trailing slash

xonsh/completer.py
It was failing on Linux where os.altsep evaluates to None. Turned out that |= operator does not work quite as I expected. It only operates on boolean values. That was a problem when mixed with the traditional operators (and/or). (None and False) will for example evaluate to None that can't be feed to '|='
=> Fix regression in _normpath. 

xonsh/completer.py
This fixes yet another oversight where _normpath does not handle './' or '.\' correctly. The current code turns './' into '././', because it sees it as having both an initial 'dot-slash' and a trailing 'slash'.
=> Fix error where _normpath wrapper converted ./ to ././

xonsh/prompt_toolkit_history.py
There was a very small change in the `History` class. `History` is now an abstract base class, which means that it only specifies the interface and doesn't contain any actual implementation.
This pull request makes it compatible again.
=> One fix to be compatible with prompt_toolkit==0.47

tests/test_prompt_toolkit_tools.py, xonsh/prompt_toolkit_shell.py, xonsh/tools.py
This may not be ready for merging yet.
I made an attempt to implement the suggestions from @jonathanslenders to get coloring working with prompt toolkit. Some part of it is quite a hack, but it works without changing the current way prompt colors are set in xonsh. So it basically strips the color codes from the prompt string and converts them to pygments tokens. It makes a reversed lookup in the TERM_COLORS dictionary (that is the hack-ish part) 
The good thing about this setup is that it only recomputes the prompt once for every input. That seems to speed things up quite a lot. 
I still haven't found out how to reserve the lower lines the terminal. So the prompt still jumps up/down when the completer list pops up (https://github.com/scopatz/xonsh/issues/362).
=> First attempt to make a hack for prompt-toolkit coloring

xonsh/completer.py
This was introduced in 1a31c82abdca3ad31ef3299d5b91fc3c88f44d97
=> Fix bug in attribute completer: unresolved reference `oattr`

xonsh/prompt_toolkit_shell.py
Feel free to merge this or not.
This will show the completions in multiple columns instead of one dropdown menu.
I think it makes sense for a shell, but maybe you want to have this configurable.
=> Display completions in columns.

docs/tutorial.rst, xonsh/environ.py
xonsh rocks.
Coming over from zsh, I found it handy to display environment variables in a PROMPT.  For example, to print out the current pyenv by displaying `$PYENV_VERSION`.
This is a simple hack to allow that.  Alternatively, we could treat only `${FOO}` as environment variables, but that would require writing a simple parser for the `PROMPT` language.
Obviously this needs a test, but I thought I'd get some feedback on the concept first.
=> Allow environment variables in PROMPT

xonsh/built_ins.py
This is a critical bug fix that makes sure that the if xonsh receives non-SIGINT signals, that it will actually exit.  This is blocking v0.2.  It is only two lines of code so hopefully it can be reviewed quickly :)
=> fix to actually quit on certain signals

xonsh/prompt_toolkit_shell.py
This change is required to make sure that the search (Ctrl-R) and exit (ctrl-D) key bindings keep working with the latest prompt-toolkit.
=> Enable search/abort/exit bindings again. (For prompt-toolkit upgrade.)

.binstar.yml, recipe/bld.bat, recipe/meta.yaml, setup.py
This will ensure that conda build can create packages that also install the jupyter kernel spec
=> Conda build w kernelspec

xonsh/ast.py, xonsh/completer.py, xonsh/execer.py, xonsh/imphooks.py, xonsh/inspectors.py, xonsh/lazyjson.py, xonsh/lexer.py, xonsh/openpy.py, xonsh/parser.py, xonsh/pretty.py, xonsh/pyghooks.py, xonsh/timings.py
Since Python > 3.4 is required no need for __future__.
=> Remove from __future__ import

xonsh/aliases.py
* Call bash with `-c alias` rather than passing `alias` through stdin, to avoid `$PROMPT_COMMAND` giving us garbage.
* Check each alias read in is really an alias, to make doubly-sure we don't get garbage in our aliases.
We should have a way of disabling the bash alias extraction altogether though. After all, not everyone uses bash as their main shell, and the idea of a shell calling another shell to automatically pull in aliases scares me.
Fixes: #204
=> aliases: make bash_aliases() more robust

docs/envvars.rst, xonsh/base_shell.py, xonsh/built_ins.py, xonsh/completer.py, xonsh/dirstack.py, xonsh/environ.py, xonsh/history.py, xonsh/prompt_toolkit_shell.py, xonsh/readline_shell.py, xonsh/shell.py, xonsh/tools.py
This PR adds a single place for environment variable defaults to be stored and used.  It also updates the `Env.get()` method to look at these defaults first if a default value is not explicitly given. It will return None if a value cannot be found. 
This solves the problem of having to recall and reimplement the default in several points across the code base. For example, `$XONSH_HISTORY_SIZE` comes up quite a lot and has a less than trivial specification.
This also trims down the `BASE_ENV` to explicitly what is needed.  This saves on a bit of space in the history files.
=> Environment Defaults

xonsh/prompt_toolkit_key_bindings.py
This adds a key handle to insert a literal tab character when the user hits `Shift+Tab`. 
I just copied the readline keybinding, but it can be changed if folks want a different choice.
Resolves #408
=> Add literal tab insert to prompt tk keybinding

docs/envvars.rst, xonsh/environ.py, xonsh/shell.py
As discussed in #277 
Linux and OSX will look for a system-wide config file in  `/etc/xonshrc` in addition to the user's config file.  
Windows system config file is stored in `%ALLUSERSPROFILE%\Application Data\xonsh\xonshrc`
I don't have a windows machine to try this out on, but this is the same way that pip handles global configuration files, so it should work(?).  If a windows user ( @melund ?) can try this out to make sure it's grabbing both configuration files, that would be great.  
The way it's set up now, user `.xonshrc` will override system `xonshrc` if there are conflicting `$env` names.
Also, apologies.  Would've rebased but I wasn't sure if it would re-notify the linked issues and commits in one of the commit messages and opted for less noise.
=> Add support for system-wide xonshrc

docs/envvars.rst, xonsh/environ.py, xonsh/tools.py
Arch places the default bash_completion scriptlet in
`/usr/share/bash-completion`, not in `/etc/bash_completion` as in most *nix
systems.
This adds an extra flag to tools.py to check if the current OS is
Arch, `ON_ARCH`, (according to `platform.linux_distribution`) and if it is, adjusts
the default location for bash_completion accordingly.
This fixes one of the issues in #421 -- the sudo aliasing isn't handled here, though
=> add ON_ARCH env to adjust $BASH_COMPLETIONS per os

docs/envvars.rst, xonsh/environ.py, xonsh/prompt_toolkit_shell.py
Introducing the new AUTO_SUGGEST environment variable for this,
which can either be True or False. Default is True.
In addition, make mouse_support a class variable of PromptToolkitShell
for consistency's sake.
=> Make prompt_toolkit's auto_suggest optional

xonsh/aliases.py
Similar to bash and zsh behavior, this will allow the `source` command
to be used for files not in the current working directory that are
contained in $PATH.
=> have source_alias search on $PATH if not in cwd

docs/aliases.rst, docs/xonshconfig.rst, xonsh/aliases.py, xonsh/foreign_shells.py
This adds the ability to describe functions that are written in foreign shells (such as Bash) and then automatically wrap them as xonsh aliases.  This should happen when you load a foreign shell at startup or when you source a foreign shell file.  
This should fix #420 and builds off of #458.  I'd really appreciate it if someone - and particularly @masasin could try this out. Thanks!
=> Foreign Shell Function Aliases

setup.py
Windows install is faulty, "xonsh.bat" is not created when installed as reported in issue #457.
Pull request to resolve issue.
=> bugfix for install missing scripts/xonsh.bat (windows)

docs/envvars.rst, xonsh/environ.py, xonsh/prompt_toolkit_shell.py, xonsh/tools.py
Completions provided by prompt_toolkit are now configurable
by setting $COMPLETIONS_DISPLAY.
Changing it at runtime will take immediate effect, so you can quickly
disable and enable completions during shell sessions.
Possible values for $COMPLETIONS_DISPLAY are:
- 'none' for no completions,
- 'single' for single-column completions,
- 'multi' for multi-column completions (default).
=> Make prompt_toolkit Python completions configurable

docs/envvars.rst, xonsh/built_ins.py, xonsh/environ.py
As suggested in #439 
I couldn't find a better place to insert this other than `base_shell.py` -- it might be a bit too hacky, but I'm open to suggestions.
If user enters the name of a directory, e.g.
```
gil@theo ~ $ /usr/bin
```
then Xonsh will first try to run that command.  When it fails and raises
a XonshError, if the env variable `$AUTO_CD=True` then Xonsh will check
to see if the input is a valid directory and that there is no binary in
`$PATH` that matches the input (this last bit is likely redundant).
If all conditions are met, it reruns the "command" but prepends `cd` to it.
=> add `AUTO_CD` functionality

xonsh/prompt_toolkit_completer.py
prompt_toolkit completion wasn't triggering for command arguments unless
the first letter was entered.  now it shows all the options when the
user hits tab, which matches the readline functionality and also the
default behavior in bash, zsh, fish, etc...
previously
```
git <TAB>
```
would return nothing, while
```
git s<TAB>
```
would offer `send-email`, `stage`, `stash`, `status`, etc...
Now 
```
git <TAB>
```
will show all available git arguments so long as `$BASH_COMPLETIONS` is set.
=> set prompt_toolkit completion to trigger on tab

xonsh/built_ins.py, xonsh/parser.py
This should address #469 by calling `expand_path()` in the relevant places.  @Carreau, would you mind testing this out.  If people really want raw tildes in subproc mode they can always do `@('~')`
=> call expand_path() in more places

docs/tutorial.rst, xonsh/environ.py, xonsh/tools.py
Adds a new `prompt_end` formatter variable for prompt. The value is `$`
for normal users and `#` for root users.
=> Add equivalent of `\$` in bash as `prompt_end`

tests/test_history.py, xonsh/history.py
Fix the handling of negative history indexes where a slice specification
is involved. Negative indexes not part of a slice specification worked by
accident because the argparse module (see section "16.4.4.3 Arguments
containing --") treats such values as positional arguments (which is a
misfeature of argparse in my opinion). I've also added unit tests for
"history show" to keep this from being broken in the future.
=> Correct handling of negative history indexes.

setup.py
Installation on Archlinux using AUR does not work, because destination dir of jupyter hook cannot be changed.
=> installation of jupyter hook to given destination

docs/index.rst
There are many tools to download packages from the Arch User Repository apart from the ones included in the installation instructions.
=> Mention where the Arch linux package can be found

xonsh/prompt_toolkit_shell.py
h/t @jonathanslenders
When using the prompt_toolkit shell, user can press Ctrl-X Ctrl-E to
open the current line in $EDITOR.
Limitations -- it can only open the _current_ line, so if you are
already in a multiline prompt, you can't edit what is already entered in
lines above.
However, you can enter multiline commands in the editor and these are
correctly interpreted by xonsh (assuming correct syntax, etc)
Resolves #445
=> add open in editor to prompt_toolkit_shell

xonsh/prompt_toolkit_shell.py
Quick change removing the deprecated `get_input` and replacing it with
`prompt`
=> replace `get_input` with `prompt`

setup.py
This is better than writing platform-dependant scripts to provide an entry point. The old way is kept as a fallback when setuptools is not available.
Should address #466 (at least when `setuptools` is available).
Reference:
http://python-packaging.readthedocs.org/en/latest/command-line-scripts.html#the-console-scripts-entry-point
=> Use console_scripts to generate entry point

docs/envvars.rst, xonsh/environ.py, xonsh/prompt_toolkit_shell.py
This adds the envvar `VI_MODE`, (default `False`).  If it is set to `True`,
either in a `.xonshrc` or dynamically, then the prompt is switched to
`vi_mode`.
`vi_mode` defaults to an `--insert--` environment, then user can hit ESC
to enter command mode, etc...'
Resolves #491
=> allow user to enable vi_mode in prompt_toolkit

tests/test_history.py, xonsh/history.py
This fixes most of the lint errors in the history code. It also fixes
two bugs that were found by pylint due to misnamed variables. This patch
does not make any functional changes. I'll fix the remaining lint errors
in a subsequent patch when I tackle cross-module issues.
=> Make history module mostly lint clean.

xonsh/ast.py
Note that while I am personally comfortable with the use of functional programming idioms such as the map() function I'm removing them in this change because pylint complains about their use. Which is reasonable given the Python maxim that there should be one, and only one, obvious way to achieve a result. Which means in this instance using a list comprehension.
=> Make ast lint clean.

xonsh/jobs.py
To reproduce:
```bash
$ sleep 10
Ctrl-Z
$ bg
```
The job is stopped state instead of runniong (T stat code in 'ps') and stays that way.
=> Fixed 'bg' for Popen

xonsh/completer.py
If the command is 'sudo', this short-circuits the completion and just
cuts sudo out of the logic entirely, allowing the completer to act as if
it weren't there.
This might be a little too hacky, but it works on my machines without issue and enables completion lines beginning with `sudo` for both `prompt_toolkit` and `readline`.  
I'm also submitting this because `sudo` completion doesn't work for me even though it's in my `$BASH_COMPLETIONS`.  If others have `sudo` completion working already, then I'll dig around more to try and determine the root cause of the issue.
=> enable sudo completion in pt and readline shells

scripts/run_tests.xsh
In the case that a test was edited, "make test" would erroneously
attempt to add `test_fname` to the list of files to test...which doesn't
exist in that branch. Instead, it should be adding `edited_fname` in
that case.
=> Fix use-before-define error in "make test"

docs/envvars.rst, tests/test_main.py, tests/test_man.py, xonsh/environ.py, xonsh/main.py
Support for the login option is very minimal, but the `XONSH_LOGIN` variable is set in this case so that scripts may take an appropriate action.
I know that the guidelines call for all new code to have tests, but I'm unclear what the right way to test this is; we currently have no tests that actually check the `main` function at all, and at any rate, I'd usually prefer using a tool like [cram](https://pypi.python.org/pypi/cram) to test this certain class of feature anyway. I'm happy to amend the PR with guidance.
Fixes #517
=> Add support for -i and -l options

xonsh/built_ins.py, xonsh/completer.py
Adds a function to expand aliases in the completer to allow completion
for user-defined aliases.
e.g.
```Bash
aliases['g'] = 'git'
aliases['ck'] = 'checkout'
```
then `'g ck' TAB` will show available branches for checkout.
This is currently restricted to single item aliases.
I think this helps satisfy #391 but it may not work exactly as expected -- I'm not sure if the `aliases` dict pulls in aliases from `~/.gitconfig`
Other questions:
Is there a use case for expanding multiple word aliases?  That would be relatively easy to add in.
Should this be optional?  It does have to run the expansion every time the completer is called though it is quite fast.  A failed search through a 500 key-pair dictionary takes on the order of 1e-8 seconds.
=> add alias expansion to completer

xonsh/lexer.py, xonsh/prompt_toolkit_shell.py
rely on Pygments Python Lexer for now,
One need to write a XonshLexer, but lexers based on the current one dont'
work as they don't return whitespace.
--- 
Also cleanup unused import in lexer. I've tried to write a simple PygmentsLexer around lexer:get_tokens but the python tokenizer does not yield whitespace, which make it annoying. 
I suppose it would be possible to wrap the tokenizer, and in case of "missing" token, fill in the [literally] blanks.
We can also lookup the first token and see if it's the list of known executable and highlight it differently:
But that's more work.
=> Highlight (python) code when using prompt_toolkit

xonsh/completer.py
I believe this should fix the issue in #364.
Since we only want attribute completion for Python objects, I think we can get away with using `eval` instead of `evalx`.
It also kind of bothered me that something like `7.<tab>` gave suggestions that are actually not valid Python, so I hacked in something to take care of that as well.  Maybe it's too hacky?
Really, I think it would be nice to avoid doing the `eval` at all (since, depending on what we are evaling, it might take time).  I had a version that just checked for `expr` as a key in `ctx` and `builtins.__dict__` and did completions based on that.  No `eval` involved, but it doesn't quite get us to the same place (e.g., if `c` is a number, we would lose `c.imag.<tab>`).  Maybe that's better anyway, though...
=> prevent completer from launching executables

xonsh/environ.py
In the prompt and in the title, `$HOME` is currently replaced everywhere in the PWD, when it should really only be replaced at the very beginning.  This changeset implements this fix.  Not yet tested on Windows.
Examples:
Old:
```
hartz@compy-488 ~ $ cd backups/
hartz@compy-488 ~/backups $ cd home/
hartz@compy-488 ~/backups/home $ cd hartz/
hartz@compy-488 ~/backups~ $ 
```
New:
```
hartz@compy-488 ~ $ cd backups/
hartz@compy-488 ~/backups $ cd home/
hartz@compy-488 ~/backups/home $ cd hartz/
hartz@compy-488 ~/backups/home/hartz $ 
```
=> modify twiddle replacement to happen only at the start of the path

xonsh/completer.py
This should fix a silly bug in the cache validation code for the completer (whereby changes in the alias dictionary during runtime would not be noticed).
=> bug fix for cache validation in completer

docs/index.rst, xonsh/environ.py
Not sure whether this should just stay at home in my `.xonshrc` or whether it's something worth including...
I do a lot of work deep in directory trees, and so I found fish's shortening of the CWD in the prompt to be useful.  This changeset implements a shortened CWD as a new entry in the formatter dict, `short_cwd`.
If it's not useful (or too adqm-specific) to have this in the main codebase, I'm happy to close this and just leave it to live on my own machines, but I thought it might be useful.
=> fish-style shortened cwd as short_cwd

tests/test_prompt_toolkit_tools.py, xonsh/environ.py, xonsh/tools.py
This updates the colors for prompt_toolkit to work better on a black background. On windows, it also changes the default prompt to use CYAN instead of BLUE, which is more readable in cmd.exe. 
On cmd.exe  (windows 10)
In cmder (windows 10)
I also added a color mapping for colors that work best on light backgrounds. Just haven't made anything that uses it yet.
=> Better default colors for promt tk

docs/envvars.rst, xonsh/main.py, xonsh/shell.py
This implements a random shell type that decides randomly which shell type to use at start up.  This is mostly for devs (such as myself) who want to consistently use all shell interfaces.  I feel like I haven't been using prompt-toolkit as much as I would have liked just because I also feel it is important to maintain a high-quality readline shell.  Hopefully this will help balance these two problems.
Also some minor doc fixes.
=> Random shell type

xonsh/foreign_shells.py
@melund, maybe you could take this for a spin.  This is as an alternative to #552.  The reason that I wanted to do this solely in Bash is it simplifies the Python a lot if different shells know that they have to communicate this information in the same way.  I change the protocol from a whitespace separated list to a JSON object.  Testing this locally seems to work on files with spaces in the name.
=> fixes bash funcscmd to allow for spaces in filenames

xonsh/completer.py, xonsh/tools.py
This supercedes #560 
From #560 --
> On Linux, if there's a foldername with a space in it, like "bad folder"
> then tab-completion using `cd` will wrap single quotes around the name,
> e.g.
> 
> ```
> cd bad(TAB)
> ```
> 
> completes to
> 
> ```
> cd 'bad folder/'
> ```
> 
> This behavior is encoded in `path_complete` in `completer.py`.  But if
> you want to remove that poorly named folder, the argument to `rm` is
> completed by `bash_complete` which didn't have this tweak and so the
> result is
> 
> ```
> rm -r bad(TAB)
> ```
> leads to
> 
> ```
> rm -r bad folder
> /usr/bin/rm: cannot remove 'bad': No such file or directory
> /usr/bin/rm: cannot remove 'folder/': No such file or directory
> ```
> 
> This tweaks the `bash_complete` function so that
> 
> ```
> rm -r bad(TAB)
> ```
> 
> …
=> Bash Completer $XONSH_TOKEN wrapping

docs/tutorial.rst, tests/test_imphooks.py, tests/tools.py, xonsh/base_shell.py, xonsh/built_ins.py, xonsh/environ.py
This is a little modification (again, another idea borrowed from fish) to make the console title, by default, show the name of the command being run (the current active foreground job).  I often have a bunch of terminals open, and this makes it easier for me to switch between them.
Normal title on my machine is:
`hartz@compy-488: ~ | xonsh`
Opening, e.g., `python` makes it:
`python | hartz@compy-488: ~ | xonsh`
Programs like `vim` that set titles themselves are unaffected.
Also works with pipelines.  So opening `echo "hello" | gedit -` makes it:
`gedit | hartz@compy-488: ~ | xonsh`
Tested to work with `fg`, `bg`, and friends.
=> include the command being run in the default title

xonsh/parser.py, xonsh/tools.py
I believe this should resolve the issue described in #569, which caused a `compile` error when running xonsh under Python 3.5.1.
Tested on Python 3.5.1 and 3.4 on my machine, but more eyes on it would be appreciated.
=> ast.arg needs lineno and col_offset in Python 3.5.1

tests/test_tools.py, xonsh/completer.py, xonsh/prompt_toolkit_completer.py, xonsh/readline_shell.py, xonsh/tools.py
This changeset is a long-overdue continuation of #72.  It implements a couple of fixes/changes for the completer, basically trying to mimic the way Windows cmd.exe handles quoted paths:
* implements completion of partial strings (e.g, `"name with spa<tab>` will now complete to include the full name, as well as the proper ending quote)
* implements completion of full strings (e.g. `"name with spaces/"<tab>` will complete to show subdirectories of `name with spaces`, properly quoted [I think])
As it always has (modulo the issue in #181), it still wraps names containing spaces in quotes if they aren't already there.
The main reason I am marking as a work-in-progress is that I haven't yet gotten it to work in readline mode (nor have I tried yet).  Also, I'm not 100% sure I haven't broken …
=> Improvements for Completer: Names with Spaces, and Partial Strings

xonsh/completer.py
Small bugfix for the big completer merge.  Right now, trailing slashes aren't added to paths in quotes if those paths include ~.  For example, `~/Docum<tab>` would not add a trailing slash.  This should fix.
=> add slashes to quoted strings with, e.g., ~ in them

tests/test_prompt_toolkit_history.py, xonsh/prompt_toolkit_history.py, xonsh/prompt_toolkit_shell.py
=> prompt-toolkit history now reads from xonsh history rather its own custom pickle method.

xonsh/built_ins.py, xonsh/environ.py
On Windows, when you both have `command` and `command.bat` files Xonsh
always prefers the `command` version because `'' in PATHEXT` check
always returns `True` (because of the empty string).
This patch fixes this by treating `PATHEXT` as "env path" so Xonsh 
prefers the file with extension first.
=> Fix error when trying to run commands on Windows

xonsh/completer.py
This should keep the same quoting semantics for path names, but should avoid quoting environment variables.
=> Fix for Dollar Signs In Path Completion

xonsh/completer.py
Reported by @denfromufa in #597 -- a quick fix since the `get_completions` methods expect a list of strings (and then themselves return a generator)
=> fix module import to return list instead of generator

CHANGELOG.rst, xonsh/ptk/history.py
This only affected prompt-toolkit.
=> made obtaining buffer in history thread safe.

CHANGELOG.rst, xonsh/ptk/key_bindings.py
I'm not sure this is done but I wanted to put it in front of a few more eyes to see if there's anything big that's missing.  This is my crack at a more robust multiline environment in PTK, as per #507.  
It remaps `Enter` to run through a preliminary parser that tries to determine whether to send the current buffer off for evaluation, or to insert a newline instead.  
Current 'triggers' for inserting a newline are:
- Not on first line of buffer and line is non-empty
- Previous character is a colon (covers if, for, etc...) 
- User is in an open paren-block
- Line ends with backslash
- Any text exists below cursor position (relevant when editing previous multiline blocks)
(Anything big missing here?)
If the character before the cursor is a colon, it also indents the following line -- …
=> "True" multiline in PTK (WIP)

xonsh/ptk/history.py
If this is only `buf.reset()`, it's possible to begin entering text in a
new terminal window which is then cleared shortly after startup
(depending, I imagine, on how much history is being loaded and how long
that takes).  Passing in the current document as `initial_document`
fixes this and history is still accessible as before.
=> fix buffer reset in ptk history

xonsh/ptk/key_bindings.py
Another fix here for multiline.  
I noticed some strange behavior, like typing `import os` would trigger a newline insertion instead of just running.  It turns out that `'import os'` comes back as a `SyntaxError` from `execer.compile` which was a little confusing but, in fact, it's just that `execer.compile` expects to be run after someone hits Enter, so it also expects a newline at the end of the input.  
One other odd thing -- in trying to fix this I was trying out different "typos" and when I typed
```
print('abc'
```
and his Enter `xonsh` froze up completely -- some kind of trouble with adding a newline character to the end of a single quote.
Anyway, this fixes all the cases I came up with.
=> help `compile` not lose its mind

xonsh/completer.py
I believe this should address #613.  Also adds quotes, comma, question mark, and ampersand to the list of characters that need to be quoted.
=> fix for quotes in filenames when completing

xonsh/ptk/key_bindings.py, xonsh/ptk/shell.py
This change makes it so that hitting enter in the middle of a line does not create a newline, but rather runs the line as normal.
@gforsyth, was there a reason to include this case that I am not seeing?
=> be less aggressive about adding newlines in multiline mode

xonsh/aliases.py
Reported by @frol [here](https://github.com/scopatz/xonsh/issues/108#issuecomment-169996770), this fixes and issue with source-foreign if the envvar is callable, not peristable, or otherwise not detypable.
1 char change.
=> check correct env (denv may not persist some Python objects)

xonsh/execer.py
This should fix an infinite loop of wrapping certain syntactically-invalid subproc expressions with `$[...]`.
Previously, typing `(7+2<enter>` at the xonsh prompt would enter an infinite loop.
=> don't double-wrap things in $[...]

xonsh/jobs.py
It's possible that there is a tty, but we are a detached subprocess and don't control it, in which case `_give_terminal_to` will fail with OSError.
This came up during testing of `setsid` in Jupyter, which seem to cause this to be the case.
=> check that we own _shell_tty before passing ownership

xonsh/foreign_shells.py
avoids hangs potentially caused by setpgrp
possible or partial fix for #624
=> setsid on foreign shell setup to avoid hangs

CHANGELOG.rst, xonsh/built_ins.py
This fixes the following problem:
```console
scopatz@localhost ~/fc-bench-method master $ $(echo "wow mom" > x)
File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 143, in default
self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 126, in exec
return exec(code, glbs, locs)
File "<xonsh-code>", line 1, in <module>
File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 646, in subproc_captured
return run_subproc(cmds, captured=True)
File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 634, in run_subproc
output = output.decode(encoding=ENV.get('XONSH_ENCODING'),
AttributeError: …
```
=> capturing redirection fix

tests/test_ptk_multiline.py, xonsh/ptk/key_bindings.py
Partial fix for #644 
If user is on Windows and has `FORCE_POSIX_PATHS` set to False, then
trailing backslash will not enter multiline mode as this messes up
directory navigation
@melund, can you see if this works on your end?  
Note that this doesn't preclude changing the default of `FORCE_POSIX_PATHS` to `True`
=> disable multiline for '\' on windows without POSIX

tests/test_ptk_tools.py, xonsh/environ.py, xonsh/ptk/shell.py, xonsh/pyghooks.py, xonsh/tools.py
Background colors in PTK doesn't work at all. This patch makes a weak attempt to make them work. Definitely not a great or permanent solution but should be a good start.
=> Fix background colors for PTK

xonsh/ptk/completer.py
This is a temporary fix until there's a new release of `prompt_toolkit` to address the differences in the default `prompt` layout between 0.5.7 and current git master.  
This should address #643
=> add temporary fix for diverging prompt_toolkit layout

CHANGELOG.rst, docs/tutorial.rst, xonsh/built_ins.py, xonsh/environ.py, xonsh/main.py
This adds the capability to raise a subprocess error whenever the subprocess returns a greater-than-zero exits status.  This is most useful for scripts and sometimes modules.
This was inspired by Bash's `set -e`.  For xonsh, it turns out, we only needed to add this behaviour for subproc mode, because Python mode will already throw an error.
Hopefully, `set -x` behaviour will come soon too, but that is a little more complicated.
=> Raise subproc error

CHANGELOG.rst, xonsh/built_ins.py, xonsh/completer.py, xonsh/tools.py
When using `glob` on Windows, case-insensitive conversion converts a
glob path like `~\D*` to
`[cC]:\[uU][sS][eE][rR][sS]\[bB][yY][kK]\[dD]*`. The `[cC]` part at the
beginning breaks `glob` and fails to yield any results, probably because
it cannot extract the base path.
This patch fixes the issue by skipping the conversion for a sequence
like `\w:` at the beginning.
=> Fix case-insensitive match breaking for paths in Windows

xonsh/aliases.py, xonsh/built_ins.py, xonsh/environ.py
We already had a Python implementation for `which`/`where`
functionality but for some reason we were not making enough use of it.
This patch moves ` built_ins._get_runnable_name` to
`environ.locate_binary` and makes everything use it. This improves `git`
and `hg` querying speeds for prompt on Windows.
=> Eliminate `locate_binary` and use a native Python implementation instead

xonsh/aliases.py
the replacement of `locate_binary` in #650 changed the way filenames are returned -- the `[:-1]` truncation in `source_alias` means that files not in the current directory are not found, despite being on `$PATH`
=> stop source alias from truncating filename

CHANGELOG.rst, docs/index.rst, xonsh/main.py
This adds `setproctitle` as an optional dependency to enable setting the process (rather than terminal) title. This will make xonsh appear as `"xonsh"` to ps and other process monitors, rather than `/path/to/python /path/to/xonsh` 
Inspired by @asmeurer. Also @asmeurer, note: https://anaconda.org/asmeurer/setproctitle :)
=> set process title

xonsh/environ.py
This will hopefully fix the link in the docs: http://xonsh.org/envvars.html#shell-type
=> Space after close bracket

CHANGELOG.rst, xonsh/environ.py
This should fix #661. @ngoldbaum and @moigagoo, would you mind taking a look please?
=> make call_hg_command() use the correct environment

xonsh/environ.py
Workaround bug in ConEmu/cmder which prevented get_git_branch() from working in these terminal emulators on windows.
=> Workaround bug in ConEmu/cmder (windows terminal emulators)

docs/index.rst
Note, 
The old domain name  `xonsh.org` is 42% longer than the new one `xon.sh`.
=> More puns in docs

CHANGELOG.rst, xonsh/environ.py, xonsh/main.py, xonsh/shell.py
This adds a 'best' shell type that tries to discover the best available shell from those available on the system. This PR also changes the default to 'best'.  This is meant to address the issue of people needing to manually switch to prompt-toolkit, if it is available.  If and when future shells are implemented, best can be adjusted as needed.
This is a relatively minor change, but I think it is worth it.
=> best shell type

xonsh/completer.py
This is an attempt to fix #682, but probably should have been done a long time ago anyway.
=> Pass in env to subproc calls in Completer

xonsh/environ.py
This is similar to #667, but this one fixes git_dirty_working_directory()
=> Workaround bug in ConEmu/cmder (windows terminal emulators) 

setup.py
one line change to move `from tempfile import TemporaryDirectory` inside
the try statement so that the install will reach the `sys.version_info`
check and let a user know that Legacy Python is not supported in xonsh.
as per @tmbdev's request in #646
=> add `tempfile` import to try statement to fail py27 gracefully

docs/index.rst
It's actually quite hard to figure out the right way to phoneticize `xonsh` in Japanese.  Which is also wonderful and kind of the point.
=> Small addition to index.rst

CHANGELOG.rst, docs/xonshrc.rst, xonsh/environ.py
This is up for discussion... Most of my other tools don't consider the workdir to be dirty if there are untracked files.
=> Ignore untracked files when considering if git workdir is dirty

xonsh/execer.py
This slight change modifies the way we check for double-wrapping lines in `$[...]`, to avoid the issue in #710 while still preserving the benefits of the original fix.
=> better check for avoiding double-wrapping with $[...]

tests/test_ptk_multiline.py, xonsh/ptk/key_bindings.py
This is a bit of an edge case, but the password manager `pass` causes a
few headaches with the multiline carriage return logic.  Specifically,
because `pass` is a `DEDENT_TOKEN` when running `pass` as the password
manager the prompt will delete one indent-length's worth of characters
on a `<ENTER>` press.  This is a one-line fix to make sure that people
can use `pass` in the PTK shell by assuming (correctly) that if the buffer 
document is only one line long, then dedenting is meaningless.
Just running `pass` will be interpreted as a Pythonic `pass`, but
commands like `pass git init` will work.
If someone has a xsh script that uses `pass` it should be wrapped in
`$[]`.
=> fix collision with ptk multiline dedent and `pass`

CHANGELOG.rst, docs/windows.rst, xonsh/environ.py, xonsh/main.py, xonsh/tools.py
It enables utf-8 support in windows terminals. ( https://pypi.python.org/pypi/win_unicode_console )
It is only active if win_unicode_console is installed, and it can be disabled by setting `$WIN_UNICODE_CONSOLE` to False. Setting the env-var also enables/disables on the fly.
We better test for a while our self ( @BYK ) to see if there are any unwanted side-effects. 
Install with:
```
conda install -c xonsh win_unicode_console
pip install win_unicode_console
```
=> Add optional dependency on the win_unicode_console library

CHANGELOG.rst, xonsh/built_ins.py
This patch modifies regular expression globbing as per the discussion in #711 .  For experimentation/discussion.
Also fixes a separate issue I had with regex globbing, whereby returning an empty list would result in that argument disappearing from the args list.
=> modify regular expression globbing

xonsh/pyghooks.py
Step toward #726
The mapping names are weird (cause of Pygments historical reason) , and there might be a small issue with the BOLD marker leaking. 
@asmeurer does that fix things for you ? 
(note you need pygments master, put it **should** be possible to avoid that. )
=> Fix colors on recent enough pygments

recipe/meta.yaml
This fixes a problem when building on a anaconda.org. I hope anaconda.org will soon stabilize
=> Update recipe to use git_url specification.

xonsh/built_ins.py
This should fix the int and None ordering issue as also fixed in ab781a96fdd95501f0fd497d322dc470601d8115
=> fix type order error as seen in ab781a9

tests/test_parser.py, xonsh/ast.py, xonsh/parsers/base.py
This adds support for 2d and 3d slicing to the xonsh parser.  This is my first outing with `yacc` and there's probably a cleaner way to do it, but this works.
=> Add numpy slicing to the parser

xonsh/ptk/completer.py
This fixes a bug I got with the newest version of prompt_toolkit. 
The fix is to check that window and window.render_info are valid. This is what @jonathanslenders  does here:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/scroll.py#L67
```
mel@ANYBODY-MEL ~/Documents/xonsh                                                                              (master)
$ gi <tab>
Exception in thread Thread-12:
File "C:\Users\mel\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
self.run()
File "C:\Users\mel\Anaconda3\lib\threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\mel\Anaconda3\lib\site-packages\prompt_toolkit\interface.py", line 742, in run
completions …
```
=> Ensure that window and window.render_info exist.

CHANGELOG.rst, tests/test_parser.py, xonsh/parsers/base.py
Also enables slicing like `[True,0:42]` where booleans and masks are mixed in with slices.  Probably for @gforsyth to take a look at.
=> some logic fixes to ndslicing

tests/test_parser.py, xonsh/built_ins.py, xonsh/parsers/base.py, xonsh/proc.py
This changeset includes a couple of fixes:
* It addresses #738 by removing erroneous cases from the parser.
* It addresses #737 by adding some test cases related to the new syntax (mostly copied and modified from the $() and $[] tests).
* It addresses #740 by adding timestamps to the `CompletedCommand` object.
=> Fixes for !() and ![]

CHANGELOG.rst, xonsh/environ.py, xonsh/pyghooks.py, xonsh/tools.py, xonsh/xonfig.py
This improves the usefullnes of xonsh in cmd.exe.
It eliminates some of the dark blue and dark red colors when using cmd.exe and the default style. 
I reused one of the old environment variables from the previous colors system ( $PROMPT_TOOLKIT_STYLES)  So it now does the same as it did before. We should consider changing the name though, to something more saying. Any good ideas?
=> Fix colors for cmd exe

.gitattributes
I finally figured why some history tests were failing only for me. https://github.com/scopatz/xonsh/issues/758
My git is configured to automatically handle windows line-endings. `git config --global core.autocrlf true` which is the recomended default on windows. All text files are checkout with `crlf`and commited with only `lf`
Checking out with `crlf` screwed up the semi-binary json files in the history tests. Basically, the indexes were off because of the extra characters in the file. 
This PR adds a `.gitattributes` file to ensure that test/histories/*.json files are checked out with `lf` line-endings even on windows.
=> Ensure line endings in git checkout

xonsh/environ.py
If a user has an empty `xonshrc` file lying around, the `exec(ccode, env, None)` prevents `xonsh` from starting
=> quick fix for empty xonshrc files

xonsh/diff_history.py, xonsh/execer.py, xonsh/jupyter_kernel.py, xonsh/parsers/base.py, xonsh/parsers/v34.py, xonsh/parsers/v35.py, xonsh/ptk/history.py, xonsh/ptk/shell.py, xonsh/readline_shell.py, xonsh/wizard.py, xonsh/xonfig.py
I should never have clicked on the Landscape icon...
But there are a bunch of unused imports lying around (and also a bunch that pylint misidentifies as unused) and it's good to keep the house in order.
=> remove (actually) unused imports

CHANGELOG.rst, docs/tutorial.rst, xonsh/environ.py
Supports usage of `'HOME' in ${...}`-style lookups as suggested by @melund
=> add ellipsis lookup to xonsh environ

CHANGELOG.rst, xonsh/ptk/key_bindings.py
In a multiline statement, the left- and right-arrow keys will now wrap
to the previous or next line, respectively.  If you are at the beginning
of the document, the left-arrow key does nothing.  Same for the
right-arrow at the end of the document.
=> Add line wrapping to PTK multiline using arrows

CHANGELOG.rst, xonsh/ptk/completer.py
As reported by @asmeurer, the completer had incorrect index values for
completion when the cursor was located before a space, that is
`~/Do<C>emacsclient -nw`
would not offer file path completions (where the cursor is marked by
`<C>`). This was because of (my) naive searching for indices, now
slightly less naive.
=> fix ptk completer to allow completion earlier in line

CHANGELOG.rst, xonsh/environ.py
This adds a new option `$UPDATE_OS_ENVIRON`. If set, it will update the os.environ mapping whenever the __xonsh_env__ mapping changes.
This could be useful if you are running scripts that use subprocess calls, and you don't have the option of modifying the code to parse in the `__xonsh_env__`
=> Add option to update os.environ when __xonsh_env__ changes.

CHANGELOG.rst, xonsh/built_ins.py, xonsh/parsers/base.py
Return an empty list instead of the regex expression when regexpath doesn't find any matches
=> Fix regexpath

CHANGELOG.rst, xonsh/environ.py
@scopatz .. This fix ensures that environment variables from os.environ are always loaded and that $XONSH_VERSION is always set. Even when running scripts.
#782 #
=> Load os.environ env-vars when running scripts

CHANGELOG.rst, recipe/meta.yaml
Since prompt_toolkit no longer includes it explicitly
=> Add pygments as a conda dependency.

xonsh/pyghooks.py
This aligns the colors with the specification used by prompt_toolkit. 
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/win32_output.py#L442
Without this, some colors were simply mapped incorrectly, at least for me on windows. For example 'INTENSE_GREEN' is not just normal green. 
This will not be a problem as soon as pygments 2.2 is released because prompt_toolkit will then used the `#ansicolors` specification instead.
=> Aligns the colors with prompt_toolkit specification of colors.

CHANGELOG.rst, tests/batch.bat, tests/test_foreign_shells.py, xonsh/aliases.py, xonsh/environ.py, xonsh/foreign_shells.py
This is best effort to fit cmd.exe support into the framework of foreign_shells. There are a number of places where it doesn't align with the POSIX shells. 
The first commit adds the ability to source *.bat files on Windows. 
The second commit uses `source_cmd()` to add an alias for the activate/deactivate scripts that are used to switch Conda environments on windows. 
The current implementation contains a few hacks in the attempt to change the existing structure of foreign_shells.py as little as possible. It only supports sourcing batch scripts, not reading functions or aliases. I have no idea if the latter is even possible.
I don't think it is ready for merging, but it may help @scopatz figure out how `foreign_shells should be changed to accommodate cmd.exe...
=> Sourcing Windows batch files

CHANGELOG.rst, recipe/meta.yaml
This makes conda packages create a xonsh menu entry when installing.
=> Re-enabled the app section in the meta.yaml (conda build script)

CHANGELOG.rst, xonsh/aliases.py
Maybe not the most important PR. We already had `call` as an alias. Anyway, since @scopatz suggested in #800 I had to implement it.
=> Added `source-bat` as an alias for `source-cmd`

tests/test_tools.py, xonsh/aliases.py, xonsh/base_shell.py, xonsh/tools.py
This adds code to quote arguments for cmd.exe, which was needed for source_cmd. It implements the suggestion from @BYK's link on how to quote arguments (what I except Popen also does). It also adds ^escapes requred by cmd.exe. Here it reuses the code from `escape_windows_title_string()` which already did similar stuff. I just renamed the function to  `escape_windows_cmd_string()`
=> quote arguments for cmd.exe

CHANGELOG.rst, xonsh/aliases.py
Caveats:  
1. I think Windows will just ignore this entirely
2. Some, but not all, `which` flags are supported
As requested by @scopatz in #809 
```console
(xonshtest)gil@theo~/git/myxonsh alias_which$ which ls
ls -> ['ls', '--color=auto', '-v']
(xonshtest)gil@theo~/git/myxonsh alias_which$ which -a ls
ls -> ['ls', '--color=auto', '-v']
/usr/bin/ls
(xonshtest)gil@theo~/git/myxonsh alias_which$ which timeit
timeit -> <function timeit_alias at 0x7f6558ec3d08>
(xonshtest)gil@theo~/git/myxonsh alias_which$ which -a timeit
timeit -> <function timeit_alias at 0x7f6558ec3d08>
(xonshtest)gil@theo~/git/myxonsh alias_which$ which DERP
xonsh.tools.XonshError: DERP not in /home/gil/anaconda/bin:/usr/bin:/usr/local/bin:/usr/bin/vendor_perl/:/usr/bin/core_perl/:/opt/cuda/bin or xonsh.builtins.aliases …
```
=> Alias for `which` to support alias lookups

docs/faq.rst, xonsh/built_ins.py
Not as advance as using a package like glob2, but allow simple use of
double start to match recursively in subdirectory.
e.g:
$ ls -1 **p.py
docs/cmdhelp.py
setup.py
Which match both in CWD and Subdirectory.
See #451,
Also consolidate `globpath` and `iglobpath` (see #733)
---- 
I'm sure there are probably side effects, and It's just one of the annoying behavior that upset me,  so i'm just submitting for people to try it out.
Also the `recursive=True` kwarg-only is only a 3.5+ thing. So it might not be a good thing to get in now.
=> Improve double-star globing.

xonsh/environ.py
When ```.hg/branch``` doesn't exist, ```hg branch``` is used to determine the branch.
If the file does not exist it will be the ```default``` branch.
=> Prevented hg branch call for default branch

CHANGELOG.rst, xonsh/jobs.py
@BYK and @scopatz  This is a fix for deadlock on windows when running subproc that generates enough data to fill the os pipe. 
This may be a hacky way to solve it, but it is a minimal change and it seems to work.
=> Fix deadlock on windows

CHANGELOG.rst, xonsh/ptk/shortcuts.py
hat tip and congratulations to @jonathanslenders in #819 
This makes exactly the same changes but doesn't break `xonsh` for people using `prompt_toolkit` versions `0.57` or `0.58`.  
Is it time that we start thinking about a deprecation schedule for those?
=> add support for prompt_toolkit-1.0.0 and preserve support for previous versions

tests/test_tools.py, xonsh/tools.py
Partially solved. Still throwing error in another part of the code.
=> #763 fixed ';' input on tools.subproc_toks()

CHANGELOG.rst, docs/xonshconfig.rst, xonsh/aliases.py, xonsh/foreign_shells.py
This should address #817.  Not sure what the value of this should be for `cmd.exe`.  @melund or @BYK do you have any idea?
=> set error on exit for foriegn shells

tests/test_tools.py, xonsh/tools.py
I tested every case I could think of, except for possible weird scenarios with single expression spread over multiple lines.  If this breaks in that case, it is probably just safer to have folks use `![...]` anyway.  This should fix #828
=> Fix for balancing parens in subproc wrapping.

xonsh/aliases.py, xonsh/environ.py, xonsh/tools.py
This is a no brainer....
It fixes the check  if we are runnning in an Anaconda distribution. 
It seems that 'Anaconda' is not always part of the sys.version string. Sometimes it writes 'Continuum Analytics' instead. 
'3.5.1 |Anaconda custom (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]'
'3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]'
Also the check has been moved to xonsh.tools as ON_ANACONDA
=> Fix Anaconda check. 

xonsh/tools.py
This makes it possible to have:
```
$XONSH_HISTORY_SIZE = '1 GB'
```
Right now this will error out because the history tuple parsing only knows about lower-case units names. This behavior is supposed to work, I think, since upper-case `GB` is documented here: http://xon.sh/envvars.html#xonsh-history-size
=> lower-case xonsh history string specs before parsing

xonsh/aliases.py
CROWD:  A `which`!  A `which`!  A `which`!  We've got a `which`!  A `which`!
GFORSYTH:  We have found a `which`, might we burn it?
CROWD:  Burn it!  Burn!
SCOPATZ:  How do you know it is a `which`?
CARREAU:  It looks like one.
SCOPATZ:  Bring it forward.
WITCH:  I'm not a `gnu-which`.  I'm not a `gnu-which`.
SCOPATZ:  But you have a `-v` flag.
WITCH:  They monkey patched me.
CROWD:  No, we didn't... no.
WITCH:  And this isn't my source code, it's a false one.
SCOPATZ:  Well?
GFORSYTH:  Well, we did do the `-v` flag.
SCOPATZ:  The source code?
GFORSYTH:  And the function signature -- but it is a `which`!
CROWD:  Burn it!  `which`!  `which`!  Burn it!
SCOPATZ:  Did you dress it up like this?
CROWD:  No, no... no ... yes.  Yes, yes, a bit, a bit.
---- 
Note, above text is the commit text, …
=> An commit `which` fixes #833

xonsh/aliases.py
probably for @gforsyth, just a couple of small changes
=> cache which_version() to prevent excessive subproc calls

xonsh/base_shell.py
This gets triggered in the weirdest way (completer accessing a property), but it is a legit bug. This shoudl fix #826.
=> fix for key error when completing __xonsh_shell__.shell.<TAB>

CHANGELOG.rst, xonsh/environ.py
the '--untracked-files=yes' option for 'git status' returns an error, which causes this function to return False even when there are untracked files present. I referred to this post for the correct argument of 'normal' instead of 'yes' ('no' still seems to work):
https://stackoverflow.com/questions/31708427/cant-see-untracked-files
=> Fix 'git status' option for include_untracked=True

CHANGELOG.rst, setup.py
Feeling productive and useful today. Have another fix, this time for #879.
I've tested this on Windows, both as 'setup.py install', and via a wheel (which should be equivalent to pip).
I haven't tested for regressions on Linux, because I won't be near a Linux machine until Monday. There should be absolutely no reason why this does break something on Linux, but better safe than sorry.
=> Fix launcher for Windows install dirs with a space

xonsh/execer.py
This is for correct error reporting for the ";" alone case.
=> Report only Syntax error for semi-colon.

xonsh/built_ins.py, xonsh/jobs.py
It turns out the issue described in #798 is not specific to Windows.  If the PIPE used by a captured subproc gets filled, everything blocks.
This implements a general fix, using a `NamedTemporaryFile` instead of a `PIPE` as the process's `stdout`.  It is likely to be slow as it uses a file on disk, but nothing else I tried got around this quite so nicely, and the speed wasn't a noticeable issue for me.
I ran it through some quick tests that had been locking things up both on GNU/Linux and on Windows, and it seems to pass those cases now.
=> Fix For Deadlock On Captured stdout/stderr

CHANGELOG.rst, setup.py, tests/test_aliases.py, xonsh/aliases.py, xonsh/xoreutils/_which.py
@gforsyth I added the pure python 'which' which you suggested :)
I include the `which.py` from https://github.com/trentm/which but updated for Python 3. The interface is is still in `aliases.py`, but I imagine that @adqm could move the whole thing to `xoreutils` when that is ready.
This new which have some differences:
- It can handle multiple inputs. 
- it understands PATHEXT and "App Paths" registration on Windows (i.e. it
will find everything that `start` does from the command shell); 
- it can print all matches on the PATH; 
- it can note "near misses" on the PATH (e.g. files that match but may not,
say, have execute permissions)
=> Update which to be a pure python implementation.

xonsh/completer.py
this adds the capability to define directories to load autocompletions from.
i started to move platform-specifics to a new module. this isn't finished yet, though working. i will finish it if there is approving feedback.
unfortunatley i can't rebase onto master as git won't stop to autoconvert `scripts/xonsh.bat` what i also try to tackle in `.gitattributes`. without success.
=> Load autocompletions from directory

CHANGELOG.rst, xonsh/readline_shell.py
This little patch should allow Ctrl-C to exit reverse-i-search mode in the readline shell (see #78).
Should work on Windows and *nix, I believe.
=> Allow Ctrl-C to Exit Reverse-Incremental Search in Readline Shell

xonsh/aliases.py
Once #919 is fixed, I think it would be nice if `which` could be made always to produce a result that could be executed directly by xonsh.  This patch adds the `-p` (`--plain`) option to `which`, which should allow running, e.g., `@($(which -p my_alias).strip())`.
=> Add argument to which, to allow printing only the name of an alias

CHANGELOG.rst, xonsh/environ.py, xonsh/readline_shell.py
This PR adds a few readline related fixes.
1. The readline shell will now load user config files, which was requested by @asmeurer way back in #290
2. Adds some more docs on the $TERM variable.
3. Adds the ability to dump out the current readline configuration. These are mostky meant as a developer/debuging tools. Users shouldn't have to use them ever, but I was getting annoyed at having to reimplement them every time I did readline stuff :)
=> A few readline updates

xonsh/codecache.py
I think this might have been a merge failure on my part (with #757), but an old issue has crept back in, whereby if a user has an empty `.xonshrc` file (rather than no `.xonshrc` at all), xonsh will crash immediately on startup.  This small patch should avoid that issue.
=> don't crash on empty .xonshrc file

CHANGELOG.rst, tests/test_dirstack.py, xonsh/dirstack.py
The following script
```
mkdir ~/TEST
cd ~/TEST
mkdir A
ln -s A LINK
cd ~
$CDPATH=("~/TEST")
cd LINK
```
yields
```cd: no such file or directory: LINK```
=> Fixed dirstack._try_cdpath to work with CDPATH values prefixed with ~/

xonsh/xontribs.json
What is the difference between ```name``` and ```package```?
Currently package is the Python package name to install with pip.
The name is the name of the new module that will be added to ```xontrib```.
Ref: https://github.com/scopatz/xonsh/pull/816
=> Adding xontrib-prompt-ret-code extension

xonsh/built_ins.py, xonsh/execer.py, xonsh/main.py, xonsh/shell.py, xonsh/xontribs.py
Thanks to @Siecje, I found many logic issues with the xontribs module:
1. Inability to import *.xsh files before the Shell was initialized (ie in the config or rc files)
2. Import warnings were silently suppressed by default
3. xontrib context would be overwritten as `__xonsh_ctx__` by the time the actual prompt was reached.
This should clear all of these up.
=> Fix many logic issues with xontribs

tests/test_aliases.py, xonsh/aliases.py, xonsh/xoreutils/_which.py
This updates the `which` alias so both '-v/-V/--version' triggers the version output. Similar to gnu-which. 
It also makes it the default to show where binaries are found, similar to how we by default show where aliases come from: 
``` bash
snail@sea ~ $ which ipconfig
C:\Windows\system32\ipconfig.exe -> (from given path element 6)
snail@sea ~ $ which ls
ls -> ['ls', '--show-control-chars', '--color', '-X']
```
The `-p/--pain` can still be used to hide this. 
```bash
snail@sea ~ $ which ipconfig -p
C:\Windows\system32\ipconfig.exe
snail@sea ~ $ which ls -p
ls
```
The `-a/--all` option is unchanged. 
```bash
snail@sea ~ $ which ls -a
ls -> ['ls', '--show-control-chars', '--color', '-X']
C:\Program Files\Git\usr\bin\ls.exe -> (from given path element 17)
```
The `--verbose` has a much more …
=> Which updates

tests/test_environ.py, tests/test_history.py, tests/test_imphooks.py, tests/test_man.py
these were introduced in a few places but there is no __init__.py file
in the tests directory so the import breaks (at least on my machine)
=> fix broken imports in certain tests

CHANGELOG.rst, setup.py, tests/test_lexer.py, tests/test_parser.py, xonsh/lexer.py, xonsh/tokenize/__init__.py, xonsh/tokenize/tokenize_34.py, xonsh/tokenize/tokenize_35.py
The built-in `tokenize` module was getting confused with "comments" between backticks (anything with an octothorpe).  See the end of #268.  The first of many parser fixes over the next few days, I hope.
This changeset should fix that problem, though it may not yet fix the original issue.  The fix is a little more involved than I would have liked (including a modified version of `tokenize.py` that knows that regex globbing is special), but I could see no other way.  In fact, it may make sense to move much more of the logic into `xonsh.tokenize` in time.
Also includes a slight refactor to the rest of the lexer (part of a first failed attempt, but still not a bad change).
This is a big diff, so it may be easier to see the changes by looking at individual commits.  The commits for the …
=> Tokenizer Fix

tests/test_execer.py, xonsh/execer.py
This was a subtle bug caused by the new and/or stuff.  Should close #927
=> str().split() | grep exit now throws a SyntaxError

xonsh/wizard.py, xonsh/xonfig.py
This patch changes the question that is asked when a user starts xonsh with no configuration files to allow a third option (specifically, the option not to run the wizard now _or ever_).
When I was doing some testing after removing my `.xonshrc` file, I found it a little annoying that I was asked whether I wanted to run the wizard every time I opened a new terminal.  I'm not sure if I'm alone in this (if so, or if there is a better way to implement this, we can close this PR).
I suppose it is a little bit dangerous as written, as it will blow away an existing config file if one exists _and_ for some reason the wizard is run with `confirm=True` _and_ the user chooses option 3.  But I imagine it would be hard to do that acidentally, and xonsh backs up the old file anyway, so I don't think …
=> Add option to prevent config wizard starting every time xonsh is run

docs/linux.rst
Updated the docs to include a description of why functions defined at the end of Ubuntu's default ~/.bashrc will fail upon execution in xonsh. 
I did not suggest any workarounds as I don't really know the consequences of removing the exit-on-non-interactive-shell behaviour. I figure uses should be able to work out they can either remove the check or add needed functions before this check.
=> Documenting issue of functions appended to Ubuntu's default .bashrc failing

xonsh/built_ins.py
#958 broke master for windows. This commit ensures that POSIX only signals are not used on Windows
=> Fix broken master on Windows introduced by #958.

CHANGELOG.rst, docs/bash_to_xsh.rst, docs/tutorial.rst, tests/test_lexer.py, tests/test_parser.py, xonsh/built_ins.py, xonsh/lexer.py, xonsh/parsers/base.py, xonsh/pyghooks.py, xonsh/tokenize/tokenize_34.py, xonsh/tokenize/tokenize_35.py, xonsh/tools.py
Per the discussion in  #921, this changeset introduces a couple of changes to the syntax of the xonsh language, relating to the handling of subprocess args:
* `$(cmd)` ~~is unchanged~~ now _always_ gives the whole string as a single element, even in subproc mode
* `?(cmd)` does the super-captured subproc (with return code, etc)
* `!(cmd)` does, effectively: `@([i.strip() for i in $(cmd).split()])`
Quoting a relevant piece of that discussion:
> That said, no matter what, it still feels a little painful to me to have to call two functions to inject output back into the command line: @($(which python)), not to mention the need for strip. I'm not sure what that syntax would be, but it would be nice if this could be done in a single operation.
>Really, I would vote for !(...) having this …
=> Proposal: Syntax Changes (from #921)

CHANGELOG.rst, xonsh/built_ins.py, xonsh/environ.py, xonsh/jobs.py, xonsh/lexer.py
This builds on @GuillaumeLeclerc's great work in #867 refactoring xonsh's job control.  I think all of those changes are ready to be merged in.
Beyond the changes made there, this patch:
* fixes a few PEP8 issues
* brings back the "current job" text in the title bar
* makes windows job control kind of work again (as well as it ever did)
* should fix the issue with launching commands in the background (by bringing back code that looks like it got lost as part of #672)
@scopatz, et al, do you mind taking a look?
=> Job Control Fixes (Built on #867)

xonsh/__main__.py
It seems more pythonistic than `python -m xonsh.main`
--- 
Thoughts?
=> Allow python -m xonsh

xonsh/main.py, xonsh/shell.py
I believe this should fix the issue described in #961 where `$SHELL_TYPE` was always being set to `"best"` if the `--shell-type` flag was not used, _after_ the rc files were executed (thus overriding values set there).
=> Respect decisions made about SHELL_TYPE in rc files

xonsh/completer.py
This does not completely fix the issue described in #983 (see continued discussion there), but it makes progress by forcing paths with backslashes in the middle of them to be completed using raw strings.
=> (slightly) better string quoting for windows completion

CHANGELOG.rst, xonsh/ptk/completer.py, xonsh/ptk/history.py, xonsh/ptk/key_bindings.py, xonsh/ptk/shell.py, xonsh/ptk/shortcuts.py, xonsh/shell.py
As per #980 this removes all of the cased code for dealing with various
versions of prompt_toolkit in favor of supporting only v1.0.0+
=> remove prompt_toolkit < v1.0.0 support

xonsh/tools.py
#902 fixed an issue with `xonsh.tools.CommandsCache`, but it also introduced a bug which prevented the cache from noticing most executables in the path.  This patch fixes that issue.
=> fix for command cache

.gitattributes
Follow-on from discussion in https://github.com/scopatz/xonsh/pull/984, recreating since I can't reopen it.
This makes all the existing extensions in the repo explicitly text or binary. I changed the existing *.json rule that was forcing LF for text to just being text, is there a reason it should have unix line endings? Alternatively, could keep that, and force .bat files to have CRLF.
=> Add explicit extension ->text/binary mapping in .gitattributes

xonsh/aliases.py
Adds 'clear' as an alias to 'cls' on windows. Even if 'clear' is available from MSYS it doesn't have any effect in cmd.exe or ConEmu.
Also sneaks in a verbose options '--all' to the which alias.
=> Small alias updates

CHANGELOG.rst, xonsh/foreign_shells.py
@scopatz .. I realized that bash foreign_shell_data always failed for me. I experimented a bit and this PR is what solved it for me.
I am not completely sure what the change to `DEFAULT_BASH_FUNCSCMD` does. But it was necessary to get the subprocess calling bash to succeed. I have no idea if messes things up on other platforms.
The second change in `parse_func()` was necessary to get `json.loads()` to work.
=> Fix bash foreign_shell_data on Windows

CHANGELOG.rst, xonsh/platform.py
Add defaults for $BASH_COMPLETIONS on windows. The default values are where GitForWindows stores the completions files in a standard installation. 
This should hopefully ensure that more people get the full xonsh experience by default.
=> Defaults for bash completions file on Windows

CHANGELOG.rst, xonsh/completer.py
This fixes bash completions so path-completions are no longer added to the suggestions. It also sorts the result so the resembles the suggestions in bash
See: https://github.com/scopatz/xonsh/issues/981#issuecomment-220867257
=> Bash completions fixes

CHANGELOG.rst, tests/test_execer.py, tests/test_parser.py, xonsh/ast.py, xonsh/lexer.py, xonsh/parsers/base.py
I was getting annoyed by having to put some compiler options in strings.  This doesn't seems to adversely affect anything, and even supports the sort of ridiculous and ambiguous case of `echo ,`
=> Added comma literals to subproc mode

docs/api/platform.rst, docs/conf.py, docs/dependencies.rst, docs/index.rst, tests/test_tools.py, xonsh/aliases.py, xonsh/imphooks.py, xonsh/platform.py, xonsh/tools.py, xonsh/vox.py
as discussed.
i also added docs for the `platform` module. however they render also the values of constants from the build environment. there seems to be no way to disable this on a `automodule` level. i'd rather add them manually to the `rst` file. any other idea?
=> adds scandir to platform

xonsh/completer.py
Speed up attr completions a tiny bit by only calling __xonsh_execer__.eval on the final candidates. Before it was called on all output from `dir(val)`
=> Speed up in attr completer

xonsh/jobs.py
I believe this should fix a bug with inconsistent use of `_kill` on Windows.  Symptom described in #1016.
=> fix bug with killing jobs on windows

xonsh/history.py, xonsh/ptk/history.py, xonsh/readline_shell.py
=> xonsh will read history from locked files at startup to be included in up-arrow history

CHANGELOG.rst, xonsh/tools.py
This is a quick fix for https://github.com/scopatz/xonsh/issues/1033 . Where `executables_in` fails if the directory is read-protected.  It doesn't fix the problem that `executables_in` return all files on windows. 
@asmeurer . Can you test?
=> Fix Permission error when tab-completing

CHANGELOG.rst, tests/test_tools.py, xonsh/environ.py, xonsh/tools.py
This restructures the `executables_in()` function so that also works on windows. On windows files are checked against the $PATHEXT environment variables to determine if it is an executable. 
It also changes the `yield_executables()` function to use the `executables_in()`. This avoids having functionality duplicated. 
It still includes the `scandir()` stuff for 3.5 which @funkyfuture  added to speed up things. I would really like if you could review this for speed as I may have messed things up. 
I have also merged @scopatz updated tests ( https://github.com/scopatz/xonsh/pull/1030 ) and they run fine on windows.
=> Rewrite executable in

CHANGELOG.rst, xonsh/aliases.py
This fixes a bug on Windows where `which` did not include the current directory. It also gives better verbose output on windows. 
The bug was caused by us explicitly giving `which.whichgen` the `__xonsh_env__['PATH']`  That changes the behaviour of the module a bit.
=> Verbose which

xonsh/platform.py, xonsh/shell.py, xonsh/tools.py
This doesn't entirely fix the slow startup time of xonsh, but it makes it so that people using the readline shell explicitly don't have to wait for prompt_toolkit to be loaded, which results in a modest speedup (though it is still quite slow due to loading the bash completion functions).
This should be tested by a Windows user.  Part of the changes were related to `intensify_colors_for_cmd_exe`, and not being around a Windows machine, I haven't been able to test that that function still works as intended on Windows.
=> Lazily load prompt_toolkit

xonsh/parsers/base.py
=> Allow question mark as valid character in subprocess-mode name

docs/tutorial.rst
The code in @ is not run in subprocess mode, but rather, the operator itself
is used in subprocess mode.
=> Clear up sentence about the @ operator in the tutorial

CHANGELOG.rst, xonsh/environ.py
I think this should fix the prompt problem (reported by @phobson)  on windows when no `$PROMPT` was not set in `.xonshrc`
The problem was caused by #989 which basically enabled bash as a foreign shell for windows. This also meant that xonsh would load the `$PROMPT` variable from bash if it were not set in `.xonshrc`. 
@adqm / @scopatz could this also be a problem on other platforms?
=> Fix win prompt

setup.py
Attempting to install in an environment without setuptools generates the following error:
```
File "setup.py", line 194, in <module>
main()
File "setup.py", line 190, in main
setup(**skw)
File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "setup.py", line 105, in run
install.run(self)
File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
self.run_command('build')
File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
FilTraceback (most recent call last):
File "setup.py", …
```
=> Using string in scripts during install without setuptools

docs/osx.rst, xonsh/readline_shell.py
This changeset forks some code from IPython related to reading `.inputrc` on Mac.  Hopefully, it will fix #1049, though I do not have access to a Mac to test.
=> Attempted Fix for Loading .inputrc on Mac

xonsh/xonfig.py
I think this will be useful for troubleshooting as it's something we
often end up asking when users open issues.
=> add current shell_type to xonfig output

CHANGELOG.rst, xonsh/parsers/base.py
As suggested by @asmeurer in #1081, interactive syntax errors print the line in question and a little caret pointer.
```console
gil@bad_cat ~ $ test())
............... 
File "<string>", line None
SyntaxError: <xonsh-code>:1:6: Unmatched ")" at line 1, column 6 
test())
^
gil@bad_cat ~ $ if True:
...............     test())
...............     
File "<string>", line None
SyntaxError: <xonsh-code>:2:10: Unmatched ")" at line 2, column 10 
test())
^
```
=> Syntax error pointer

xonsh/history.py
- Fixes https://github.com/scopatz/xonsh/issues/1000
- Prior unrelated fix: remove 'print's from lambdas (fixes syntax error) was reverted since it didn't work
=> xonsh/history.py: apply os.path.expanduser to XONSH_DATA_DIR in history

xonsh/completers/bash.py
When trying this out on my mac (from master e9a2b96) I ran into this error:
```
% xonsh
File "/usr/local/bin/xonsh", line 9, in <module>
load_entry_point('xonsh', 'console_scripts', 'xonsh')()
File "/Users/william/dev/xonsh/xonsh/main.py", line 230, in main
args = premain(argv)
File "/Users/william/dev/xonsh/xonsh/main.py", line 217, in premain
shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
File "/Users/william/dev/xonsh/xonsh/shell.py", line 72, in __init__
ctx=self.ctx, **kwargs)
File "/Users/william/dev/xonsh/xonsh/readline_shell.py", line 199, in __init__
**kwargs)
File "/Users/william/dev/xonsh/xonsh/base_shell.py", line 118, in __init__
self.completer = Completer()
File "/Users/william/dev/xonsh/xonsh/completer.py", line 13, in __init__ …
```
=> do not require directories in BASH_COMPLETIONS to exist

xonsh/shell.py
`$SHELL_TYPE` is now only used if `--shell-type` is `None`.
=> Fixes shell_type override in #1072

xonsh/completers/python.py
This avoids this error when (for example) completing "rm":
```
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 759, in run
completions = list(buffer.completer.get_completions(document,complete_event))
File "/usr/lib/python3.5/site-packages/xonsh/ptk/completer.py", line 36, in get_completions
self.ctx)
File "/usr/lib/python3.5/site-packages/xonsh/completer.py", line 41, in complete
out = func(prefix, line, begidx, endidx, ctx)
File "/usr/lib/python3.5/site-packages/xonsh/completers/base.py", line 21, in complete_base
complete_command(prefix, line, …
```
=> return empty set instead of None when no python completions match

CHANGELOG.rst, xonsh/main.py
This modifies the semantics of `_` in interactive mode so that it now stores the `CompletedCommand` instance associated with a wrapped subprocess call.
This allows easier access to the previous command's return code (one of the common complains on the slashdot thread), via `_.rtn`.
Not sure whether this is something everyone wants, but I figured I'd put it in, and we can discuss from here.
=> Store result of wrapped subprocess call in _

xonsh/aliases.py
Fixing issue: https://github.com/scopatz/xonsh/issues/1128 - which cannot indicate program inside extend PATH directory
=> Fix which with extended path

xonsh/environ.py
This mentions `xonfig styles` in the docs, removes a double import and fixes some typo's.
=> environ.py: mention `xonfig styles` to see color styles + typo's

CHANGELOG.rst, xonsh/ptk/key_bindings.py
I believe this should resolve the issue from #1127 and #1124 where attempting to delete a literal value in prompt toolkit shell would cause xonsh to crash.
=> fix issue with trying to delete a literal value

docs/tutorial.rst
=> Add note to docs that alias functions should start with underscores

docs/linux.rst, docs/osx.rst, docs/windows.rst
This updates the conda install directions, so it aligns with the suggestions on https://conda-forge.github.io/#about
```
conda config --add channels conda-forge
conda install xonsh
```
It also has the benefit that users can later update with `conda update xonsh` without having to remember the channel.
=> Suggest to add conda-forge as a default channel

CHANGELOG.rst, xonsh/jobs.py, xonsh/xonfig.py
Follow-up from #514.  The signal library doesn't provide `pthread_sigmask()` on Windows or Cygwin.
=> Cygwin: don't use pthread_sigmask

CHANGELOG.rst, tests/test_environ.py, xonsh/environ.py
This fixes a regression in `locate_binary()` which prevented it from finding executables when their exetension was also provided. 
The bug broke the `source-cmd` command and thus  the  `activate`/`deactivate` conda scripts. I am sorry for not noticing.
=> Fix (windows) bug in  locate_binary()

.travis.yml, codecov.yml, requirements-tests.txt
Not sure exactly how xonsh is tested completely, so I expect most of the
coverage process to be wrong (for now)
Codecov have [browser
extensions](https://github.com/codecov/browser-extension) that allow you
to see the coverage directly in the pull requests in GitHub.
We might have to give codecov some limited access to the repo (webhook),
and tell the codecov bot to shut its mouth once it's enabled. But it's
super non intrusive, and kind-of useful when you refactor to see that
your code is tested.
Also set some sensible where coverage would fail only if it drops by 10%
in 1 PR.
=> Enable (some) coverage.

CHANGELOG.rst, xonsh/environ.py, xonsh/main.py
This patch makes two changes:
* Prevents xonsh from crashing if there is an error other than a syntax error in a run control file
* Modifies the behavior of the xonfig wizard so that it only under the following conditions:
* we are running interactively
* no config.json was loaded
* none of the rc files exists
This way, if there are errors in all the rc files, but they do indeed exist, we do not show the wizard.
=> Run Control Fixes

CHANGELOG.rst, xonsh/completers/bash.py, xonsh/platform.py
This fixes a crash when bash is not on PATH on Windows. 
Not having bash on the path is the default if users have installed GitForWindows with default settings.
I have added a functionality to locate GitForWindows Bash binary using the registry if it is not on PATH. This PR will ensure that bash completion will work for all windows users that have GitForWindows installed.
=> Fix crash on win when Bash is not avaiable

CHANGELOG.rst, xonsh/environ.py, xonsh/main.py
I create the path before branching, so the same work (absolutizing and normalizing the path) isn't done twice if the branch is taken. [os.path.abspath](https://docs.python.org/3/library/os.path.html#os.path.abspath) normalizes _and_ absolutizes the path.
=> Implement #1169

CHANGELOG.rst, tests/test_environ.py, xonsh/environ.py
Following @adqm 's fixing prompt in #1150 , this PR try to fix bad `$TITLE` and `$PROMPT` from callables.
The following prompt in xonshrc was causing xonsh crash:
```
def render_prompt():
return '{HELLO'
$PROMPT = render_prompt
```
@adqm @scopatz please help to review it, thanks.
=> Fix crash caused by malformed prompt or title

CHANGELOG.rst, CONTRIBUTING.rst, docs/tutorial.rst, xonsh/jobs.py
This implements '+' and '-' for fg for BASHwards compatibility. I use job control a ton and switch between jobs frequently, so these are important to me. I also modified print_one_job() to include a job's position (indicated with a '+' and '-' after the job number). 
This PR also includes a fix to the developer's guide, fixing a reference to docker.py which was renamed to xonsh-in-docker.py.
=> Implement '+' and '-' for fg, and related changes

CHANGELOG.rst, docs/windows.rst, xonsh/jobs.py
This should fix one of the issues discussed in #514, where xonsh would background itself after every command when running under Cygwin.
There is still one more issue outstanding (discussed in #514, which I have not been able to reproduce), but this should take us most of the way toward being completely functional in Cygwin with no hacks required!
=> Cygwin Fix

CHANGELOG.rst, docs/tutorial.rst, xonsh/built_ins.py, xonsh/proc.py, xonsh/tools.py
Implementation of #1175.
I had to add an additional member to _CCTuple, as the actually-executed command couldn't be reassembled by a user without knowledge of Xonsh internals.  I'm pretty sure this is ready to go.
Example code probably explains it best -- here's usage.
```python
from subprocess import CalledProcessError
mkdir bleh
cd bleh
touch foo.txt bar.txt
for filename in !(ls -1 --color=no):
print(filename)
try:
for filename in !(ls -1 --color=no bar.txt foo.txt baz.txt bing.txt):
print(filename)
except CalledProcessError as error:
print("Error {} while executing {}".format(error.returncode, error.args[1]))
print("stderr output:\n" + error.completed_command.stderr)
#bar.txt
#foo.txt
#Error 2 while executing ['/bin/ls', '--color', '-1', '--color=no', 'bar.txt', 'foo.txt', 'baz.txt', …
```
=> Implementation of #1175, "!(command) could be usefully iterable"

tests/test_ast.py, tests/tools.py, xonsh/ast.py
This fixes an unnoticed, outstanding issue with line numbers on transformed nodes. This was first found by @pelson in #1125
=> Increment line numbers on transformation

CHANGELOG.rst, xonsh/jobs.py
This is the first attempt at a fix for the `ProcessLookupError` and `PermissionError` exceptions under Cygwin (discussed in #541).
@OllieTerrance, @ellocogato, @jivanyatra: would you mind testing this out?  As I mentioned, I am unable to reproduce the issue.
=> Attempted fix for PermissionError and ProcessLookupError on Cygwin

xonsh/jobs.py
On mac, xonsh crashes with the following command (where `which` is aliased by Python func):
```
which -a ls | grep ls
```
@adqm @scopatz Could you please have a review. Thanks.
=> fixed piped jobs including alias on OS X

xonsh/xonfig.py
Noticed a missing word in the config wizard as I was going through it. Hopefully the first of many xonsh contributions from me!
=> Add missing word in text on xontrib

CHANGELOG.rst, docs/tutorial.rst, tests/test_builtins.py, tests/test_execer.py, tests/test_imphooks.py, tests/test_parser.py, xonsh/built_ins.py, xonsh/environ.py, xonsh/parsers/base.py
This grew out of [some conversation in the IRC room](https://gitter.im/xonsh/xonsh?at=5759ba4b1cf76dd64535a84e) about the nature of Python-function aliases.
This changeset allows for invoking functions of the proper form as aliases even if they have not been explicitly added to the `aliases` mapping.  It also allows for escaping such things with `@()`, which enables the use of _anonymous_ aliases.  Three examples:
```
hartz@virtual1 ~ $ def foo(a, s=None):
..................     return a[1]+'\n'
.................. 
hartz@virtual1 ~ $ foo cat dog ferret tomato
dog
hartz@virtual1 ~ $ @(lambda a, stdin=None: a[0]+'\n') laptop
laptop
hartz@virtual1 ~ $ echo "potato" | @(lambda a, s=None: 'mashed '+s.strip()+'es\n')
mashed potatoes
```
=> Proposal: Bare and Anonymous Aliases

news/clean-up-premain.rst, xonsh/main.py
I noticed the strange `undo_args` thing in `premain` while trying to better familiarize myself with xonsh's source code and saw an opportunity for a slight clean up. I tested a few times if the parsing behaviour is identical to that before the changes, and it seems to be the case -- but please test it yourself a bit more extensively!
Something I noticed is, that currently all arguments passed before the positional file argument are silently ignored -- is the current set of switches really always completely irrelevant to the xonsh script-file that is to be run? If that ever changes one could easily implement a set of "whitelisted" arguments that are to be copied over from the old set of parsed arguments to the new one.
=> Clean up argument parsing in premain by removing undo_args hack

news/path_tuple.rst, xonsh/environ.py
This fixes crash when path is tuple and not list.
=> Fix locate_binary assuming path is a list

news/completer_list_bugs.rst, xonsh/completers/_aliases.py
Solves a current bug:
> $ test = lambda a, b, c, d, e: set()
> $ completer add testname test
> $ completer list
>Traceback (most recent call last):
>  File ".../xonsh/0.3.4/libexec/lib/python3.5/site-packages/xonsh/proc.py", line 335, in wrapped_simple_command
>    r = f(args, i)
>  File ".../xonsh/0.3.4/libexec/lib/python3.5/site-packages/xonsh/completers/_aliases.py", line 114, in completer_alias
>    return func(args[1:], stdin=stdin)
>  File ".../xonsh/0.3.4/libexec/lib/python3.5/site-packages/xonsh/completers/_aliases.py", line 42, in _list_completers
>    doc = ' '.join(_comp[c].__doc__.split()) or 'No description provided'
AttributeError: 'NoneType' object has no attribute 'split'
The problem was that the original code called split on the completer function's docstring, which might …
=> Do not throw an exception on 'completer list' if a completer has no docstring

xonsh/built_ins.py
There was some discussion in the IRC channel recently about aliases loading incorrectly (see https://gitter.im/xonsh/xonsh?at=575eef6a6092456f6633c518).  I believe this should fix that issue.
=> possible fix for incorrect alias loading

news/replace_prompt.rst, xonsh/built_ins.py
Reset the PROMPT environment variable before starting subprocesses on Windows. 
The problem is that windows also uses 'PROMPT' to render the prompt in cmd.exe. Thus, if 'echo ON' is set we this a lot when running batch files: 
```cmd
{env_name}{CONEMU_BOLD}{BOLD_INTENSE_GREEN}{user}@{hostname}{INTENSE_CYAN} {cwd} {INTENSE_CYAN}
set "SRC_DIR=C:\Users\mel\Anaconda3\conda-bld\work"
```
This PR avoids that the xonsh prompt template string is shown everywhere by replacing `PROMPT` with '$P$G'. (i.e. `path/to/current/dir>`) 
```cmd
C:\Users\mel\Documents\xonsh>set "SRC_DIR=C:\Users\mel\Anaconda3\conda-bld\work"
```
Is this also a problem on other platforms? 
Alternatively, I could set `PROMPT` to a colorless formatted version of the real xonsh prompt. This PR is just the simplest implementation …
=> Windows: Reset the PROMPT environment variable before starting subprocesses

news/simplify_env_repr.rst, xonsh/environ.py
This simplifies  `__xonsh_env__._repr__()` so it does not print the whole environment dictionary.
It does not change the string representation of the object or the pretty print method. So it does not change what happens if we type: `${...}` at the prompt. 
Before this , calling help on env methods would print the entire enviroment: 
```
snail@sea ~ $ ${...}.swap?   
Type:         method
String form:  <bound method Env.swap of xonsh.environ.Env({'GIT_LFS_PATH': ['C:\\Program Files\\Git LFS'], 'COM <...> 'ANYBODY', 'CONDA_DEFAULT_ENV': 'C:\\Users\\mel\\Anaconda3\\envs\\x', 'SESSIONNAME': 'Console'})>
File:         c:\users\mel\documents\xonsh\xonsh\environ.py
Definition:   (*args, **kwds)
Docstring:
Provides a context manager for temporarily swapping out certain
environment variables with …
```
=> Simplify Env.__repr__

news/vi_mode_change.rst, xonsh/ptk/key_bindings.py, xonsh/ptk/shell.py
When `open_in_editor` is enabled, the `VI_MODE` binding to open the
editor is `v`, which is unexpected, as `v` should be character
selection.
The `open_in_editor` option has been disabled, but the `Ctrl-X Ctrl-E`
shortcut to open the current buffer in an editor has been explicitly
enabled, so there shouldn't be any change of behavior for anyone except
those who were using `v` to open an editor in `VI_MODE` (which I think
is no one).
=> enable character selection in vi_mode

news/source_cmd_prompt.rst, xonsh/aliases.py
This is similar to #1219 . It resets the PROMPT variable before  source'ing `*.bat` files. It also ensures that the xonsh `$PROMPT` variable is restored if it should be afterwards.
=> Source cmd prompt

news/fix_xonfig.rst, xonsh/xonfig.py
#1231 made `docs` a hidden attribute of `builtins.__xonsh_env__`, but `xonfig wizard` still looks for a visible attribute and throws an error on first-time startup.
=> point xonfig wizard to hidden docs attribute

news/rmbash.rst, tests/test_environ.py, xonsh/aliases.py, xonsh/environ.py, xonsh/foreign_shells.py, xonsh/platform.py
This removes Bash from the default foreign shells in an attempt to reduce the startup time.  This adds some platform specific code for the default `$PATH`, and so it probably requires some testing on environments other than my own. @melund @gforsyth @Carreau @OllieTerrance, @ellocogato, @jivanyatra - your feedback and help would be super appreciated.
Here are some timing comparisons on my desktop:
```
scopatz@artemis ~ $ time -p xonsh --shell-type=readline -l -i -c "print(42)"
42
real 0.35
user 0.33
sys 0.01
scopatz@artemis ~ $ time -p xonsh --shell-type=readline -l -i -c "print(42)"
42
real 0.28
user 0.27
sys 0.00
-------------
scopatz@artemis ~ $ time -p xonsh --shell-type=readline -c "print(42)"
42
real 0.28
user 0.27
sys 0.00
scopatz@artemis ~ $ time -p xonsh --shell-type=readline -c …
```
=> Remove Bash from Default Foreign Shells

news/fix_pipeline.rst, xonsh/jobs.py
This small change should fix issues we've had with pipelines, in particular #1102, by giving the terminal to the _first_ process in a pipeline, rather than the last.
=> Fix for pipeline issues

news/sorted_comp.rst, xonsh/completer.py
Ignore case and any leading quotes when sorting the completions. This makes path completions look much nicer. 
Right now sorting is done by the top level completer, but we could consider letting the individual completers sort their own results.
=> Better sorting of completions. 

xonsh/platform.py
Specifically "Ǹone" in the docstring. This should fix #1257
=> removed unicode from platform

amalgamate.py
This is an attempt to make the amalgamte more robust on more systems.  Hopefully this fixes the anaconda build issues.
=> more unicode amalgamate fixes

news/xonsh_darwin.rst, setup.py
If you use macOS, the expression `'win' in sys.platform` is `True`, since `sys.platform == 'darwin'`. This would prevent `xonsh` to be added in the scripts.
=> Fix `xonsh` not being include in setup.py scripts

xonsh/main.py, xonsh/xonfig.py
* main.py ignored `--config-file` command line option
* main.py called the old `xonfig.main` function, which doesn't exists anymore
* the `wiz` variable in xonfig.py was conflicting with the global `wiz`
* `_MAIN_ACTIONS` was renamed to `_XONFIG_MAIN_ACTIONS`
* `make_xonfig_wizard` returned an instance of the `wizard` module instead of an initialized Wizard.
=> Fix xonfig_main bugs

xonsh/environ.py
Somewhere between `0.3.4` and now, `PWD` stopped being defined in the default xonsh environment, which breaks a bunch of things (but only at new logins when `xonsh` is the default shell).  
Simple fix to ensure that it exists, so that `$PROMPT` can be resolved and useful things like `cd` work
=> fix undefined PWD in default environment

tests/test_environ.py, tests/test_tools.py, xonsh/tools.py
This is a hotfix for not expanding relative paths in EnvVar, as reported in #1214.  @melund, would you mind trying this out and merging it :) It seems to work on my machine.  Sorry again about merging the other one. I had no idea Windows had that behaviour. Mea culpa
=> don't abspath in EnvVar

tests/test_tools.py
This fixes a some windows test errors.
Still two more left. @VHarisop . Can you readily see the problem, then you welcome to fix them.
````
======================================================================
FAIL: test_tools.test_is_logfile_opt(True, False)
----------------------------------------------------------------------
File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
self.test(*self.arg)
AssertionError: True != False
======================================================================
FAIL: test_tools.test_to_logfile_opt('/dev/null', None)
----------------------------------------------------------------------
File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", …
```
=> Fix some windows test errors

xonsh/xoreutils/_which.py
This should ensure that `which` can handle the new PathEnv type that PATHEXT gets
=> Ensure that Which can handle PATHEXT

xonsh/base_shell.py
This fixes a crazy recurssion error I was seeing on my chromebook that made it basically unusable:
```
File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12783, in fileno
return sys.stderr.fileno()
RecursionError: maximum recursion depth exceeded
```
=> fixed crazy recurssion error

tests/test_tools.py
I don't think the `/dev/null` test is a) necessary or b) meaningful on
Windows.  And it should fail, if it's passed, since `/dev/null` isn't
writeable or creatable file on Windows (I think).
I believe that the second set of tests that I've changed also have
little to no meaning on Windows.
Definitely need @melund to take a look at this when he has a chance.
=> fixes for windows test failures

.appveyor.yml
Only run appveyor on Py35. This should make it run a bit faster so we avoid waiting for appveyor all the time
=> Only run appveyor on Py35

news/cc.rst, tests/test_aliases.py, tests/test_imphooks.py, tests/test_main.py, tests/test_parser.py, tests/test_tools.py, tests/tools.py, xonsh/aliases.py, xonsh/environ.py, xonsh/tools.py, xonsh/xoreutils/_which.py
atm the only failling test i see in python3.5 is:
```
for inp, exp in getitem_cases:
obs = EnvPath(inp)[0]  # call to __getitem__
>           assert expand(exp) == obs
E           assert '/home/laerus/' == '~/'
E             - /home/laerus/
E             + ~/
tests/test_tools.py:572: AssertionError
```
which seems like a legit bug in EnvPath
=> merge from master and replace some new nose test with pytest

xonsh/built_ins.py
This is an alternative to #1290 that looks up the binary location of the *alias*, if applicable, not the binary location of the original command.
With some of the new command cache behaviour, this is a little more tricky to trigger.  I have been using the following: `aliases['/bin/ls'] = ['echo', '.']`  This should print a single dot, rather than the contents of the current directory:
```console
scopatz@artemis ~ $ aliases['/bin/ls'] = ['echo', '.']
scopatz@artemis ~ $ c = !(/bin/ls); c
CompletedCommand(stdin=None, stdout='.\n', stderr='', pid=7128, returncode=0, args=['/bin/ls'], 
alias=['echo', '.'], stdin_redirect=None, stdout_redirect=None, stderr_redirect=None, 
timestamp=(1466649889.561564, 1466649889.6136434), executed_cmd=['/bin/echo', '.'])
scopatz@artemis ~ $ /bin/ls
.
```
Note …
=> fix alias preference issue

xonsh/platform.py
this same fix is in #1311 but I thought this should go in while I get the pygments fallback stuff working
=> fix `has_prompt_toolkit()`

docs/api/commands_cache.rst, tests/test_tools.py, xonsh/__init__.py, xonsh/built_ins.py, xonsh/commands_cache.py, xonsh/environ.py, xonsh/tools.py
Currently when you do `'git' in builtins.__xonsh_commands_cache__` on Windows you get `False` since the version stored in commands cache is `GIT.EXE`.
This patch amends its getter methods to respond to any version available on Windows. This fixes `curr_branch` not working at all on Windows platform since it only looks for `'git'` in command cache and bailds if its not there.
=> Make CommandsCache play well with Windows

news/completion.rst, xonsh/ptk/key_bindings.py
stop autocomplete from autoselecting first entry
This was mentioned in #1338.  If I have the following directory
structure
```console
foo/
-bar/
-bag/
-bing/
-bong/
```
and have already completed to `cd foo/` and hit TAB, ptk will autoselect
the first entry of the completions.  This is incredibly annoying if
there are many possible selections and you would like to filter through
them by prefix.
This forks the `generate_completions` event from PTK and stops it from
autoselecting the first entry (but still displays possibilities)
=>  stop autocomplete from autoselecting first entry

.gitignore, MANIFEST.in, news/dirtyversion.rst, setup.py, xonsh/platform.py, xonsh/xonfig.py
Ok, here's my first crack at this.  When doing any of `setup.py [install | develop | sdist]`, check if we're in a git repo.  If there is a tag on the most recent commit assume it's a "clean" version and write an empty file `dev.githash`
If there's not a tag, append the number of commits since the most recent version (as given by `git describe --tags`) to `__version__` in `__init__.py` as per PEP440, write git short SHA to dev.githash file (which is ignored in `.gitignore`).  
Then do the actually install, then `checkout --` changes to `__init__.py` if any were made during the course of installation.  
`xonfig` reads the version number as usual.  If it finds a non-empty `dev.githash` file, it adds that on to the end of the `xonfig info` readout.
Possible pitfall:  If you make changes to …
=> Dirty version numbers

amalgamate.py, news/pkgrsrc.rst, xonsh/__init__.py, xonsh/bg_pkg_resources.py, xonsh/ptk/__init__.py, xonsh/pyghooks.py
The ugly head of the terrifying `pkg_resource` module shows its face again.  This provides a mechanism for importing this module in a background thread.  This has serious implications for the startup and load times of xonsh, pygments, and prompt toolkit.  
I have thrown some profiling into https://github.com/xonsh/import-profiling
Importing just pygments:
* with `pkg_resources`, [244 ms](https://xonsh.github.io/import-profiling/with_pkg_resources_pyg.html)
* without `pkg_resources`, [2.65 ms](https://xonsh.github.io/import-profiling/without_pkg_resources_pyg.html)
You can see importing pygments and prompt toolkit:
* with `pkg_resources`, [228 ms](https://xonsh.github.io/import-profiling/with_pkg_resources.html)
* without `pkg_resources`, [73 …
=> Background pkg_resource import

.binstar.yml, recipe/meta.yaml
This updates the conda build configuration for the xonsh/channel/dev packages on Anaconda.org. The packages now get a version that matches what @gforsyth just made. 
```
...
The following packages will be downloaded:
package                    |            build
---------------------------|-----------------
xonsh-0.4.2.dev1           |    py35_g84270d3         950 KB  xonsh
....
```
It also has a potential fix for missing Windows developer builds. Apparently, conda-convert have started to refuse to convert to windows because entry-point conversion is not supported. This is not a problem because we supply a xonsh.bat file in scripts as a fallback.
=> Anaconda config

setup.py
This should fix https://github.com/xonsh/xonsh/issues/1350
=> Catch FileNotFoundError when git is not on PATH

recipe/meta.yaml
Using 'path:' in meta.yaml seems to cause problems for Anaconda.org despite what the documentation says :/
This PR reverts that part.
=> Furthe fixes to meta.yaml

CONTRIBUTING.rst
At least on OSX, `pip install requirements-tests.txt` fails with:
Collecting requirements-tests.txt
Could not find a version that satisfies the requirement requirements-tests.txt (from versions: )
No matching distribution found for requirements-tests.txt
`pip install -h` tells me:
-r, --requirement <file>    Install from the given requirements file. This option can be used
multiple times.
=> Add missing -r flag to pip install command in developer's guide

xonsh/xontribs.json
Added another tab completion that bugged me.
Maybe this should be in the core since vox is part of xonsh, right?
source: https://github.com/Granitas/xonsh-vox-tabcomplete
=> add entry for vox-tabcomplete xontrib

xonsh/xontribs.json
I wrote `xonda` as a thin wrapper around `conda`.  Instead of the (imo) messy activate and deactivate scripts, this just uses `xonsh` `PATH` magic to change environments.  And it has tab completion!  I have no idea if it works on Windows.  @melund -- do you want to try it out?
=> add xonda to xontribs

xonsh/ansi_colors.py, xonsh/built_ins.py, xonsh/codecache.py, xonsh/completers/man.py, xonsh/environ.py, xonsh/jobs.py, xonsh/platform.py, xonsh/pyghooks.py, xonsh/readline_shell.py, xonsh/tokenize.py, xonsh/tools.py
Bare `except:` also [catches](https://docs.python.org/3/library/exceptions.html#exception-hierarchy) SystemExit, KeyboardInterrupt, GeneratorExit, causing unexpected problems.
Fixes #1372
=> Don't use bare `except:`

docs/tutorial.rst, news/prompt-optional-items.rst, tests/test_environ.py, xonsh/base_shell.py, xonsh/environ.py
To describe the situation, let's say my $PROMPT is:
```
{last_return} | {hostname}@{user} | {curr_branch} | {cwd} {prompt_end}
```
`last_return` is just something I came up with - the return status of the last executed program, let's say I don't want it displayed if it's zero. Similarly, `curr_branch` is the current git branch, which is not applicable most of the time. So I don't want my prompt to look like this most of the time:
```
| hostname@user | | ~ $
```
I know that currently this is alleviated by adding spaces to the formatter dict items themselves, so I am supposed to write my prompt like this:
```
{last_return}{hostname}@{user}{curr_branch} {cwd} {prompt_end}
```
... and rely on `last_return` and `curr_branch` appending a space. But as I demonstrated, that is not flexible enough …
=> Proposal: a better way to add optional items to the prompt

amalgamate.py, news/amalup.rst
These don't affect xonsh because they enable Python 2.7 support and relative imports, but I would like to keep this in sync with what is in the xonsh/amalgamate repo.
=> some amalgamate updates from @yaroslavvb

xonsh/lazyasd.py
The only visible result of this error would probably be when not all values from this LazyDict were loaded and xonsh would have been closed at that point. So not very likely :-)
Closes: https://github.com/xonsh/xonsh/issues/1382
[PR done via the github web ui...]
=> Fix typo in LazyDict.__delitem__

docs/osx.rst
- Python 3 default binaries instead of leaving it open for interpretation
- Moved the readline comment up (seems important)
- Put a line about bash-completion
=> update the osx guide

docs/add_to_shell.rst
I'm not sure why it was there, but tested on bash and xonsh and it doesn't seem to be needed.
=> remove unneded echo

news/fix-name-error.rst, xonsh/xonfig.py
A `NameError` appeared in the xonsh wizard.  This PR fixes that.  Would it be
of interest to put a testing harness around this xonsh wizard code?  I'm not
really even sure how to go about doing that, but would be interested in working
on it if some guidance could be provided.
```
$ xonsh wizard
<snip>
Would you like to enable xontribs now, yes or no [default: no]? yes
distributed
url: http://xon.sh
package: xonsh
license: BSD 3-clause
installed? yes
The distributed parallel computing library hooks for xonsh.
Importantly this provides a subsitute 'dworker' command which enables
distributed workers to have access to xonsh builtins.
Furthermore, this xontrib adds a 'DSubmitter' context manager for
executing a block remotely. Moroever, this also adds a convienece
function 'dsubmit()' for …
```
=> Fixing an error I encountered in the intro wizard

news/windows-settitle.rst, xonsh/base_shell.py
$TERM is not set on Windows. This prevented xonsh from ever setting the title on the console window.
=> Fix windows title

news/conda_env_paren.rst, xonsh/environ.py
Conda's own activate/deactivate script has switched from brackets to parentheses when showing the environment name in the prompt. This PR does the same
=> Conda env parentheses

docs/linux.rst, docs/tutorial.rst, news/vte.rst, xonsh/environ.py
Hey @dotsdl @uy-do-or-die can you try this and let us know! You need to add this to the front or end of your prompt, to get this to work:
Try `$PROMPT = '{new_vte_cwd}' + $PROMPT` and if that doesn't work, then please try `$PROMPT = $PROMPT + '{new_vte_cwd}'`
This is an attempt to fix #1253
=> attempt at new tab PWD for vte

docs/python_virtual_environments.rst, news/vox-remove.rst, xonsh/vox.py
I was surprised when `vox rm foo bar` failed, since it only accepts 1 argument. Here's a potential improvement.
I'm not sure if I properly documented the `names` argument to the `remove_envs` function.
Tried to update all references to `vox remove` in the docs.
=> `vox remove` accepts multiple arguments

docs/tutorial.rst
Assuming I don't need a news entry for this
=> Document prompt's `env_name` parameter

xonsh/environ.py
When the branch name in an empty string for the default prompt, there would sometime be two spaces.  This fixes that issue.  @Carreau and I discussed this at SciPy
=> branch space fix

setup.py, xonsh/platform.py
The g in `Git SHA` makes no sense other than look similar to `[9a-f]`.. Let's trim it!
```
+------------------+--------------+
| xonsh            | 0.4.3.dev209 |
| Git SHA          | gd32819f     |
| Python           | 3.5.2        |
| PLY              | 3.7          |
| have readline    | True         |
| prompt toolkit   | 1.0.3        |
| shell type       | readline     |
| pygments         | 2.1.3        |
| on posix         | True         |
| on linux         | False        |
| on darwin        | True         |
| on windows       | False        |
| on cygwin        | False        |
| is superuser     | False        |
| default encoding | utf-8        |
+------------------+--------------+
```
=> Trim the heading g in Git SHA of xonfig

xontrib/voxapi.py
Adds keyword arguments to `Vox.create()` and the method `Vox.upgrade()` so the Vox machinery is at feature parity with the venv module.
Note: The oddities with `Vox.upgrade()` is due to how venv works.
=> Add options and methods to bring voxapi to feature parity with venv.

CONTRIBUTING.rst, docs/index.rst
Prominently explain `$XONSH_DEBUG` and amalgamation. 
Explanations probably aren't perfect, but they will immensely help people make their first contribution.
Also link to the "Developer's Guide" from "Contributing" section of homepage.
https://github.com/xonsh/xonsh/issues/1341
=> Improve first set of "Developer's Guide" instructions

.travis.yml, install.sh, requirements-tests.txt
Using https://docs.travis-ci.com/user/multi-os/ to test on MacOS/OSX with Python version 3.4 and 3.5.
As Travis doesn't support Python on MacOS/OSX yet, it get slightly hacky ... but not too bad.
I also added a `pytest-timeouts` testing dependency. I can definitely remove this, but I find it greatly helps find tests that hang ...
=> WIP: Add MacOS/OSX hosts to CI

amalgamate.py, news/relimps.rst
Not that we'll use this in xonsh, but this is support for amalgamating relative imports from the same package. With this both, 
```python
from xonsh.main import main
from .main import main
```
will be amalgamated equivalently.  Previously, only the top example would amalgamate.
See also xonsh/amalgamate#1 and xonsh/amalgamate#5
=> Amalgamate relative imports

news/set-title.rst, xonsh/base_shell.py
On iterm2 (and maybe other terminals) you have a way to set tab title and window title independent of each other. By changing this escape we set both to the same value, which should be ok until we have a better way to do this.
Documentation for it in http://tldp.org/HOWTO/Xterm-Title-3.html
=> change from set window title to window + icon (tab) title

news/vocal-which.rst, xonsh/aliases.py
Fixes #306 
When you pass the `-v` flag to `which`, it'll now call superhelp.
=> Make `which -v` extremely vocal

news/ply.rst, xonsh/ply/__init__.py, xonsh/xonfig.py
As discussed in #1506 , PLY didn't bump its version number in `__init__.py` when they moved from 3.7 -> 3.8
=> fix reported PLY version in bundled PLY

news/fix-xonsh-python.rst, setup.py
This is to make xon.sh work on os x homebrew or anywhere were the python you install is not the global python3
=> fix xon.sh to make it take the current python and not a generic python3

docs/tutorial_xontrib.rst, news/xontrib-all.rst, tests/test_xontribs.py, xonsh/xontribs.py
In reference to #1464, allow xontribs to explicitly define their public API by defining `__all__`, just like regular Python modules.
The goal is to make `xontrib load spam` and `from xontrib.spam import *` effectively the same.
=> Add support for `__all__` in xontribs

docs/tutorial.rst
s.strip needs to be method call, 's.strip()', for the example  correctly.  While not necessary, adding the newline ('world\n') puts 'hello
world' on its own line of output instead of having the xonsh prompt
appended to it.
=> s.strip needs to be method call, 's.strip()', for the example to work

xontrib/distributed.py, xontrib/mpl.py, xontrib/vox.py, xontrib/voxapi.py
While this isn't strictly necessary, it helps keep the code tidy and keeps the stock xontribs as examples of best practices.
=> Use `__all__` in the included xontribs

xonsh/ptk/key_bindings.py
Add option for carriage return to not autoindent.
Cannot be controlled through the $INDENT option as there is also the
copy_margin kwarg.
Mostly useful when programmatically inserting text in prompt_toolkit
from already indented source.
remove the `indent_` variable and lookup dynamically the $INDENT
variable as well for consistency and reflect the user config at any
instant.
`carriage_return`  now takes the kwonly: `autoindent=True[|False]`
--- 
Mostly need that for a prototype of "Faketyping" in a live Xonsh shell.
=> Paste mode

news/imphook.rst, tests/test_imphooks.py, tests/test_xontribs.py, xonsh/imphooks.py, xonsh/main.py
Reintroduce importhook for developer install
Also to avoid flake8 to tag that as "unused import" also make the
install of the hook explicit. It is anyway a better idea as "explicit is
better than implicit"
Closes #1543 and closes #1535
--- 
This also include @astronouth7303 test, I cherry-picked the commit.
=> Fix importhook

news/history-timestamp-filtering.rst, setup.cfg, tests/test_history.py, tests/test_tools.py, xonsh/environ.py, xonsh/history.py, xonsh/tools.py
added optional `history show` args:
`-T` `+T` to filter by timestamp
`-t` to print the timestamps
`-f` for the datetime format
some refactoring aswell and a `ensure_slice` bugfix
=> history show filter by timestamps

news/noerr.rst, xonsh/parsers/base.py
Sometimes locs report lineno incorrectly, and we should fail correctly.
=> No error in parser error

news/stripfix.rst, xonsh/tools.py
Instead of discarding the last line, we can just strip it.
Fixes https://github.com/xonsh/xonsh/issues/1180
=> xonsh/tools.py: Do not discard last line

news/completer_quotes.rst, xonsh/completers/__init__.py, xonsh/completers/bash.py
This change causes the results of Bash's tab completion to be escaped (quoted) where necessary (e.g., filenames with spaces).
=> Wrap Bash's Tab Completions in Quotes

tests/test_news.py
This small change modifies the news-related test to check that `rst` is a substring of the extension or all news files, rather than matching the extension directly.  This means that the presence of vim's backup files (`.rst~`) doesn't cause the test to fail.
=> temporary files shouldn't cause the news-related test to break

news/codecache_off.rst, xonsh/codecache.py
As mentioned in #1589, disabling the script cache leads to problems.  I think this little patch should fix.
=> Fix broken code cache

news/bare-tuple-of-tuples.rst, tests/test_parser.py, xonsh/parsers/base.py
trying to fix #1593 
I think it's reasonable to set `_real_tuple` to an empty tuple `()`, is that correct? What does `_real_tuple` supposed to mean?
Thanks
=> fix parsing for bare tuple of tuples

docs/faq.rst, docs/tutorial.rst, news/allnames.rst, tests/test_ast.py, xonsh/ast.py
Ok, this was shamefully easy in retrospect.  Note that the actual code diff is only +5/-4 lines, which I guess is a testament to our documentation and testing :)  See #1541 for the inspiration here.
=> Check all names for subproc wrapping

xonsh/completers/python.py, xonsh/ptk/completer.py
Resolves #937 
This was bugging me.  This is only a problem with prompt_toolkit.
Before:
Now:
That ghost space isn't actually present... some weird artifact from interaction with wcwidth and scrot, I think.
And enshorten is a perfectly xromulent word.
=> Enshorten attr comp

xonsh/xontribs.json
This xontrib is no longer needed thanks to improvements in
bash-completion imports.  Yay!  One less thing to maintain!
=> remove pacman completion xontrib

news/completion-confirm.rst, xonsh/environ.py, xonsh/ptk/key_bindings.py
Like fish shell, while completion menu is displayed, pressing `<Enter>` do not run the command.
=> New option to use <Enter> to confirm completion instead of running command

xonsh/ptk/completer.py
I broke this in #1630 -- this is a quick fix to restore broken functionality.  Ideally I'd prefer to have path completion behave the same way as attribute completion and hide common prefixes in the dropdown.
=> fix for envvar expansion completion in ptk

news/more_syntax_errors.rst, tests/test_parser.py, xonsh/execer.py, xonsh/parsers/base.py, xonsh/parsers/context_check.py
This patch allows xonsh to gracefully handle more syntax errors than before.
There is a class of syntax errors that seem not to result from expressions that are invalid as specified by the grammar, but rather from using certain expressions in contexts they aren't made for (e.g., `del 7`).  Previously, xonsh did not report these as syntax errors; rather, they fell through the parsing stage and were reported as other `ValueError`s downstream, which prevented the automatic jump to subprocess mode.
Not a life-changing fix, probably, but it does make all (I think) syntax errors behave in the same way.  Partially addresses #776, though the real error with that particular expression was from the dollar sign.
=> Handle More Syntax Errors

tests/test_events.py
Just a test to detect undeclared core events, ie typos.
=> Add test to detect event typos

xonsh/completers/path.py
Before this commit, `ls /tmp/empty_dir/<TAB>` would results `ls //`,
this commit fixes that bug
=> fix path completion for empty directories

news/test_xsh.rst, setup.py, tests/conftest.py, tests/test_xonsh.xsh, xonsh/__init__.py, xonsh/pytest_plugin.py
Very basic implementation. It runs all `test*.xsh` it finds during tests. Fails if they files raises an exception. 
Any other ideas are welcome.
=> WIP Collecting `test*.xsh` files when testing

news/ptk-completion-display.rst, xonsh/ptk/completer.py
Ok, fingers crossed, but I think I finally cracked this.  @blahgeek, could you take a look at this and see if it covers the corner cases you mentioned in #1639 
Quick summary:
`numpy.<TAB>` will show `abs(, absolute(...`
`cd xon` will show (for example) `xonsh/, xonda/`
`cd git/xon` will show (as above) `xonsh/, xonda/`
file/folder names with dots and spaces seem to work well.  Note that the quotes around file/folders will spaces won't be shown in the completion but will appear when you select that completion.
=> Better ptk completion display

news/pr-params.rst, scripts/xon.sh
In case there are arguments containing spaces, there were splited. For
example:
$ xonsh -c 'echo 123'
['/home/rom1/python/xonsh/__main__.py', '-c', 'echo', '123']
$
With this patch:
$ xonsh -c 'echo 123'
['/home/rom1/python/xonsh/__main__.py', '-c', 'echo 123']
123
$
=> correctly preserve parameters

news/win_test_fixes.rst, tests/conftest.py, tests/test_dirstack_unc.py
This fixes some test problems I was having locally on windows. 
It skips the tests in 'test_dirstack_unc.py' if drive names are already mapped for other things in windows. 
It also disables `win_unicode_console` if that is installed. The module collides with pytests caputure functionality causing some test to error.
=> Fix win tests

news/fix-ptk-completer.rst, xonsh/ptk/completer.py
This is a followup for #1643 
Before: 
---
After:
=> Better completer display in prompt-toolkit

docs/tutorial_macros.rst, news/consist.rst, xonsh/built_ins.py
This changes macro function calls to default to strings, rather than eval.  This makes it more consistent with subprocess macros and context manager macros, which also default to strings.
=> Macro Consistency

news/cmd_cache_lookup_on_win.rst, tests/conftest.py, tests/test_tools.py, xonsh/commands_cache.py
This PR fixes the issue in #1702 which arise because keys in the command_cache are stored in uppercase on Windows. 
It add functionality on windows to the `CommandsCache` such that look up with with a valid command git/Git/git.exe/GIT.EXE all work the same. This fixes the highlight valid commands issue
It also adapts the iterator method of the `CommandsCache` such that it returns the originally cased command instead of the uppercase key. This fixes the command completer showing commands in upper case.
=> Cmd cache lookup on windows

news/fix_shaliases_bug.rst, xonsh/foreign_shells.py
This should fix the crash when `foreign_shell_data` fails and return (None, None). See #1715.  This is code that @laerus  touched last so he better review it so I haven't made stuff worse :)
=> Fix shaliases bug

docs/xonshrc.rst
The xonshrc example imported `git_dirty_working_directory` still from
`xonsh.environ`. Now its located in `xonsh.prompt.vc_branch`.
=> docs: Fixed git_dirty_working_directory location

news/highlight-cmd.rst, tests/test_ptk_highlight.py, xonsh/commands_cache.py, xonsh/pyghooks.py
This is successor of #1688 , hopefully this would resolve #985 #1663 and maybe #1038 later
BashLexer is removed because that's unnecessary and increases complexity. A large amount of keywords/builtins/syntax in BashLexer is invalid for xonsh's subprocess mode.
Dynamic highlighting for command and path is implemented.
---
Updates:
=> New implementation of XonshLexer for pygments

news/fix_win_git_completions.rst, xonsh/platform.py
I noticed that git completions had stopped working for me on windows. I haven't figure when it happen. Maybe xonsh or maybe a restructure of Git For Windows. 
Anyway, this fix makes it work again by adding the `` 'GitForWidnows\\mingw64\\share\\git\\completion\\git-completion.bash'` to the default completion list.
=> Restore bash git completions on Windows

news/events-precmd.rst, tests/test_news.py, xonsh/base_shell.py, xonsh/shell.py
Add events bracketing the execution of commands.
The arguments are heavily based on what's required to implement history.
Note: There's no test because shell itself isn't really tested, and that's a big can of worms.
=> Add on_precommand and on_postcommand

news/nested-vox.rst, tests/test_vox.py, xontrib/voxapi.py
Implements full and proper support for "organized" virtual environments in vox.
Basically, you can use slashes in venv names now.
Fixes #1689
=> Nested vox

.travis.yml, docs/conf.py, xonsh/pyghooks.py
Fix docs building and move docs building to a non-allow-failure version of Python.
=> Build docs on 3.5 otherwise we'll never caught failures.

news/test-dirstack.rst, tests/test_dirstack.py
we should probably use the pytest fixture tmpdir but lets fix that for now.
=> test_cdpath_expansion leaving stray dirs

tests/tools.py, xonsh/parser.py, xonsh/parsers/v36.py
Seem simple enough, and avoid writing a full 3.6 parser for now. 
-- 
I tried to modify the parser to actually recognize actual `async for` comprehensions, but the lexer insist on seeing async as a NAME instead of an async token and thus refuses to match the `async_comp_for` rule...
=> Fix async comprehension on 3.6

tests/test_contexts.py, tests/tools.py, xonsh/parsers/base.py
Don't reuse variables names in tests.
Since http://bugs.python.org/issue27999, global after use is a
SyntaxError; reusing variable name in tests/test_contexts.py
lead to failure.
Should close #1718
--- 
On top of #1717 that fix other things and is necessary for tests to pass.
=> Fix context-manager tests on 3.6

xonsh/completers/path.py
`ls and/or` should be quoted, but `ls andor` should not. only regex `\band\b|\bor\b` is searched
=> do not quote unnessasery and/or

xonsh/prompt/gitstatus.py
builtins.__xonsh_env__.get('XONSH_GITSTATUS_' + key) or _DEFS[key]
swallowed not only None, but also empty strings, and was replaced
with an explicit check for None.
=> Allow empty XONSH_GITSTATUS_ defs

news/fix-complete-alias.rst, xonsh/ptk/completer.py
```
$ aliases['ls'] = ['ls', '-G']
$ ls '/tmp/quoted'<TAB>
```
results incorrect completions.
=> fix completion after alias expansion in prompt_toolkit

xonsh/environ.py, xonsh/ptk/shell.py
$XONSH_UPDATE_PROMPT_ON_KEYPRESS = True (False by default)
disables prompt caching, so that it will be reevaluated on each keypress.
It is crucial, e.g. for exposing vi-input-mode to the prompt (see #1048).
Performance with slow prompts will probably suffer.
=> Add $XONSH_UPDATE_PROMPT_ON_KEYPRESS option

xonsh/xontribs.json
Add xontrib-vi-mode-prompt
xontrib-vi-mode-prompt is a vi-mode status formatter for xonsh prompt.
Homepage: https://github.com/t184256/xontrib-prompt-vi-mode
As it depends on xonsh/xonsh/pull/1761,
I've branched it off t184256/xonsh/reeval-prompt-on-keypress.
I hope I did that right, correct me if I didn't or if I must rebase it onto something else.
=> Add xontrib-vi-mode-prompt

news/win-setconsoletitle.rst, xonsh/base_shell.py
Closes #1753.
This should improve performance (yay one less process to wait on) and potentially improve security (There aren't known issues with the Windows escaping, but shell escaping isn't always clean...)
`kernel32` could be made to be lazy, but it'll be used as part of the first prompt anyway, and since it's already loaded into the process, I'm not sure significant time would be saved.
=> Use SetConsoleTitleW() on Windows

tests/test_path_completers.py, xonsh/completers/path.py, xonsh/xonfig.py, xonsh/xontribs.json
let's users set an argument to preview a color palette, eg `xonfig colors monokai`.
----
(propably should be moved to an issue)
i noticed in the chat that an extension of `xonfig styles` was discussed. i could amend that, provided there's an agreed feature set. i can come up with two proposals:
`xonfig style list` (like `styles`), `xonfig style set <name>`, `xonfig style unset`
or 
`xonfig get color_style`, `xonfig set color_style <name>`, `xonfig set color_style`
whether to store to `xonshrc` or `config.json` could be selected by switches. and by a setting in one of them.
is there already an api to manipulate the config files?
=> xonfig colors preview

docs/dependencies.rst, docs/windows.rst, news/extras.rst, setup.py
Declare all the optional dependencies in a set of pip extras to make them more easily installable.
The biggest thing that fixes is that pygments is now a documented dependency on its own.
The extras declared are `ptk`, `proctitle`, `linux`, `mac`, `win`.
Conda isn't included yet because I couldn't figure out how conda features work. If someone knows conda, please help?
=> pip extras

news/expand_user.rst, xonsh/environ.py
Attempt to fix #1782.  
We were using `expanduser` on the default values but if non-default values are specified in `config.json` then `expanduser` isn't run on them and a bunch of spurious `~` directories might be created.
=> Expand user for non-default data directories

news/vox-reldir.rst, tests/test_vox.py, xontrib/voxapi.py
So that venvs made by other means (eg, `.venv`) are usable within xonsh.
(Also disallow the creation of venvs with reserved names.)
I'm pretty sure this is a good idea, but I'm not certain, so I wanted a second opinion.
=> Allow activation of virtual environments in relative directories.

news/fix_pip_completer.rst, xonsh/completers/pip.py
pip completion results for install/uninstall were returning the entire
list of installed packages in a given python install no matter the
contents of the completion prefix.
Now the results are filtered by a `startswith(prefix)`
=> fix pip completion

news/pygment_plugin_fix.rst, xonsh/commands_cache.py, xonsh/pyghooks.py
This fixes crash when using the pygment plugin from third-party programs. 
It happens because `__xonsh__commands__cache__` and `__xonsh_env__` are not available unless it is used from xonsh. 
In Spyder I got the follow error when opening a '.xsh' file: 
```
...
File "C:\Users\mel\Anaconda3\lib\site-packages\spyder\utils\syntaxhighlighters.py", line 989, in guess_pygments_highlighter
lexer = get_lexer_for_filename(filename)
File "C:\Users\mel\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 150, in get_lexer_for_filename
return res(**options)
File "C:\Users\mel\Anaconda3\lib\site-packages\pygments\lexer.py", line 582, in __call__
return type.__call__(cls, *args, **kwds)
File "c:\users\mel\documents\xonsh\xonsh\pyghooks.py", line 74, in __init__
_ = …
```
=> Fix pygment lexer when used by third party programs

news/perf.rst, xonsh/proc.py
This prevents xonsh from idly spinning it wheels in many cases where it doesn't need to, while still remaining responsive.  For me CPU usage for an open `less` with no input from the user went from 13.5%-45% down to 0.0%-0.5%.  This is more in the acceptable range of most applications. 
@laerus, you mentioned you were also seeing issues.  Would you mind seeing if this helps?
=> Performance Improvements

news/fix_bash_completer.rst, xonsh/completers/bash.py
This fixes the issue that, if there's files and directories under `~/Downloads/`, typing `mv ~/Downloads/<TAB>` would only completes directories, but not files. This only happens for few commands and when the path starts with `~`.
----
Here's the long explanation:
So, basically, while xonsh is completing from `mv ~/Downloads/<TAB>`, it runs:
```
source "/usr/local/share/bash-completion/bash_completion"
COMP_WORDS=(mv '~/Downloads/')
COMP_LINE='mv ~/Downloads/'
COMP_POINT=${#COMP_LINE}
COMP_COUNT=16
COMP_CWORD=1
_longopt mv '~/Downloads/' mv
for ((i=0;i<${#COMPREPLY[*]};i++)) do echo ${COMPREPLY[i]}; done
```
(`_longopt` is returned by `complete -p mv`)
Save the scripts in `test.sh` and run `bash test.sh` does not print files as expected. But running them line by line in bash DOES print …
=> Fix bash completer: some files not showing in completion

news/fix_comma_alias.rst, xonsh/completers/python.py
For 0.4.7 I added in logic to split on commas so that completion worked
inline with comma separated terms.  This inadvertently broke completion
behavior for aliases starting with a comma.  The rest of the characters
that we split on aren't valid syntax for beginning an alias, but commas
are.
=> fix for aliases that start with a comma

.gitignore, news/rediralias.rst, tests/test_integrations.py, xonsh/proc.py
This is basically a one-line change to fix #1836.  However, it also adds some integration tests to the test suite to help insure that this doesn't happen in the future.
=> Redirect aliases

news/which_returns.rst, xonsh/xoreutils/which.py
So I am just opening  a new PR for the `which` stuff, which wasn't addressed in @scopatz's #1803 PR
This fixes the print statements when `which` doesn't find any matches, and ensures they go to stderr.
=> Fix which prints 

news/prompt_xontrib_install.rst, xonsh/shell.py, xonsh/xontribs.py
As per recent discussions on gitter, a simple addition to the load-failure warning in `xontribs.py` to prompt the user to install the appropriate xontrib package
=> prompt user to install xontribs on error

news/not_backgroundable.rst, news/rs.rst, tests/tools.py, xonsh/built_ins.py, xonsh/commands_cache.py, xonsh/proc.py
This should make it more clear whether or not a process is run on a thread and will hopefully prevent confusion with backgrounding a process.
=> Replaced backgroundable with threadable

xonsh/commands_cache.py
I currently get this error when running aliases on windows.  ( `aliases['ls'] = ['ls', '--color']`)
```
snail@sea ~\Documents\xonsh $ ls
xonsh: subprocess mode: permission denied: ls
```
I introduced this bug in #1852. Sorry. Here is the fix. We need to explicitly check that a command is not an alias before returning the path in 'lazy_locate_binary()`. This is necessary since the orignal cased name of an alias is now saved in the first element of the command_cache tuple (i.e. the path element).
=> Fix regression in lazy_locate_binary introduced by #1852

docs/tutorial.rst, news/path-backticks.rst, tests/test_lexer.py, tests/test_parser.py, xonsh/built_ins.py, xonsh/parsers/base.py, xonsh/tokenize.py
This is a split of #1862 containing only the path backticks part.
=> Add support for path-yielding backticks

xonsh/shell.py
I got xontrib prompt info from nothing:
```
Last login: Thu Oct 20 14:23:11 on ttys005
The following xontribs are enabled but not installed:
To install them run
pip install
xonsh $ xontrib list
distributed         installed      not-loaded
mpl                 installed      not-loaded
vox                 installed      loaded
prompt_ret_code     installed      not-loaded
xo                  not-installed  not-loaded
apt_tabcomplete     not-installed  not-loaded
docker_tabcomplete  not-installed  not-loaded
scrapy_tabcomplete  not-installed  not-loaded
vox_tabcomplete     not-installed  not-loaded
autoxsh             not-installed  not-loaded
xonda               not-installed  not-loaded
avox                not-installed  not-loaded
z                   not-installed  not-loaded
powerline …
```
=> fix xontrib prompt for empty list

tests/test_tools.py, xonsh/tools.py
The problem is that `argvquote(r'\\machine\dir\file.bat', force=True)` returns a wrongly quoted string: `"\\\machine\dir\file.bat"` (note the three instead of two `\` in the beginning). This fix adds a testcase for such paths and reimplements the mentioned algorithm in argvquote more closely.
CC: @melund
=> Fix for windows quoting issue with machines

.travis.yml, news/doctr.rst
Ok, last one for now (I hope).  dev docs are working as planned, available here: https://xonsh.github.io/xonsh-docs/dev/
release docs won't work until the next release is pushed, since, of course, the previous releases don't have the encrypted deploy key available to them since I just added it.  I've commented out the relevant parts of the `.travis.yml` to be enabled after the next release, which should stop the test failures on Travis.
=> hold off on release docs until next release

news/fix_stderr_attribute_error.rst, xonsh/proc.py
I cannot provide a concise and reliable repro, but I kept tripping over it when making mistakes in ``git`` commands.  A sample follows below.  And I do not understand what this ``TextTranscodingWrapper`` is that stderr can sometimes be pointed to, so I have not tried to mock up a unit test.  However, I'm willing to do that if given some hints.
The fix was to copy some likely-looking code from ``proc.tee_stdout`` to ``proc.stream_stderr``.  At least it's not likely to break anything.
```cmd
======= n:\DevWork\work\xonsh
> python setup.py develop
running develop
Removed xonsh/parser_table.py
--- snip ---
Installed n:\devwork\work\xonsh
Processing dependencies for xonsh==0.4.7
Finished processing dependencies for xonsh==0.4.7
======= n:\DevWork\work\xonsh
> xonsh
-------------------------- …
```
=> Fix AttributeError: 'TextTranscodingWrapper' object has no attribute 'buffer' in stderr

xonsh/commands_cache.py, xonsh/platform.py, xonsh/proc.py
This should address the issues with less, vim, etc and other non-threadable commands on Windows. @melund  and @BYK, would you mind taking a look please?  
This issue with `git diff` and other similar threadable commands are more deeply seeded with alternate mode. I am looking in to them now.
=> Windows non-threadable fix

news/thread_pred.rst, xonsh/commands_cache.py
I know this is just a bandaid, but for now we can cover a lot of commonly used programs until we come up with a robust way to predict these things.  Also, `pacman` and `macvim` will let us close out at least two issues.
=> more entries in threadable predictors

docs/_templates_overwrite/layout.html, docs/conf.py
We do not want non-canonical versions of xonsh docs to be indexed. OR at
least they should point to the canonical version.
Technically we should even try to have the stable version under a
/stable/ url (to leave us with some freedom of changing things) So that
later we can replace stable with X.y and have a version switcher.
-- 
From experience with the IPython docs.
=> Hack a rel=canonical in the templates.

docs/index.rst
The current ribbon just don't react on click on some platform for
some reason. Mainly because the Image is in the corner, but not the
link.
This fixes it
Though it still look ugly on hi-dpi screen
One might want to consider a pure-css method like
https://simonwhitaker.github.io/github-fork-ribbon-css/
-- 
The hover style is not inline as ~ no browser support an inline hover style.
=> Fix "Fork me on GitHub" ribbons.

docs/index.rst
It's actually a bit more css that I thought it would be. But it looks nice on hi-dpi screen, and don't need to touch Photoshop/Gimp to be modified.
Also fix a bug where the ribbon would "jump" when clicked.
=> Pure-css "Fork me on GitHub" ribbon.

docs/customization.rst
What idiot didn't bother to check if this page in the docs was formatted
correctly?  Couldn't they be bothered to at least check that the docs
compiled without errors?
```
git blame
```
Oh.  It was me.
No news entry on this.
=> add missing newline in code block

news/ansi_colors.rst, xonsh/pyghooks.py, xonsh/tools.py
This PR updates the PTK styles. So now we don't use pygments when the style is set to 'default'. Instead,  we use the `XONSH_BASE_STYLE` dict, which has been updated to match the default pygments style. 
This has the advantage that we can make a version with ansi color code names. 
See this issue: https://github.com/xonsh/xonsh/issues/1821
At the moment, this is a WIP because I think there is a bug in prompt-toolkit which swap the dark and light ansi color names on Windows. https://github.com/jonathanslenders/python-prompt-toolkit/pull/408 
So I think we should wait until that is fixed.
=> Add ansi-color codes to the default style

news/xonfig-commit-date.rst, setup.py, xonsh/platform.py, xonsh/xonfig.py
I feel this info would be helpful for xonsh developers. Does this make sense to you?
```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.4.7.dev1734       |
| Git SHA          | f78a0e1             |
| Commit Date      | Nov 2 01:44:25 2016 |
| Python           | 3.5.1               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.0               |
| shell type       | readline            |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is …
```
=> added commit date in xonfig

news/jupyter-install-root.rst, setup.py
`install_jupyter_hook(prefix, root)` doesn't honour the `root` parameter (since `KernelSpecManager.install_kernel_spec` has only a `prefix` option). When `root` is set (eg, distribution builds), this results in the jupyter kernel being installed in the wrong place.
=> Patch setup:install_jupyter_root to respect the root param

docs/tutorial.rst, docs/xonshrc.rst, news/prompt.rst, tests/test_prompt.py, xonsh/base_shell.py, xonsh/environ.py, xonsh/prompt/base.py, xonsh/ptk/shell.py, xonsh/readline_shell.py, xontrib/prompt_ret_code.xsh
new PromptFormatter class
renamed `FORMATTER_DICT` to `PROMPT_FIELDS`
some caching when building the prompt (we can do better, some details on #1564)
(some shell refactoring on this matter would prolly come after this)
=> prompt mechanism refactor

news/ptk_menu.rst, xonsh/pyghooks.py
This updates the PTK styles to bring the scrollbar back. PTK expect it to defined by the styles  `Token.Scrollbar` and `Token.Scrollbar.Button`. 
It also updates the toolbar styles to more neutral lightgray/darkgray color, instead of the previous turquoise/teal colors. This is a of course a matter of taste, but it is more in line with the default colors in prompt toolkit. 
Let me know what you think.
=> New PTK menu style

news/hg_branch.rst, xonsh/prompt/vc_branch.py
noticed while stracing xonsh that `get_hg_branch` is crawling all the way up to root dir to check if we
are in a repo, this can be slow if we are very deep in a dir tree.
```
$ pwd
/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p
```
part of strace on every prompt update:
```
...
stat("/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/.hg", 0x7ffca79cef30) = -1 ENOENT (No such file or directory)
stat("/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/.hg", 0x7ffca79cef30) = -1 ENOENT (No such file or directory)
stat("/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/m/n/.hg", 0x7ffca79cef30) = -1 ENOENT (No such file or directory)
stat("/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/m/.hg", 0x7ffca79cef30) = -1 ENOENT (No such file or directory)
stat("/home/laerus/lab/a/b/c/d/e/f/g/h/i/j/k/l/.hg", …
```
=> get_hg_branch runs 'hg status' first

xonsh/proc.py
I don't think this needs a news entry, but basically we shouldn't over-close handles on Linux because it can loose data from buffers.  Windows does not seem to operate this way.
=> fixed small regression on linux caused by windows fixes

xonsh/proc.py
I have rearranged some of the string and bytes munging of output to yield a faster runtimes in the test case given in #1932 and #1938. This is about a 25% performance improvement over the sleepless branch, and takes < 6% of the runtime of the original.
|                       | command took [s] | difference in outs |
|-----------------------|------------------|--------------------|
| 3545358a4b (master)   | 20.03104758      | 17                 |
| 5aec225 (1kb)         | 4.678267479      | 0                  |
| 8603909be (sleepless) | 1.552735806      | 0                  |
| b5d63ce               | 1.150137424      | 0                  |
My remaining ideas that don't involve optional external dependencies or writing a regular expression library haven't panned out.  They all added to …
=> some munging speed ups

news/backtab.rst, xonsh/ptk/key_bindings.py
As per discussion on gitter, shift+Tab will move backwards in the prompt toolkit completion list.  when the completion buffer isn't active, shift+tab will still insert an indent
=> Backtab completion

news/ansiwhite.rst, xonsh/pyghooks.py
This fixes hopefully the last inconsistency in the color keywords. Now `WHITE` corresponds to a light gray color (`#ansilightgray`) and `INTENSE_WHITE` to a pure white color (`#ansiwhite`) 
Just as is specified here: https://en.wikipedia.org/wiki/ANSI_escape_code
=> Fix WHITE color keyword

news/hg_branch.rst, xonsh/prompt/vc_branch.py
@Siecje can you check this one out pls?
i believe `_get_parent_dir_for` was a little excessive in that you had to stats every dir for `.hg` up to the filesystem root and that causes a slowdown when not in a hg repo.
there is more room for speed improvements, the plan is to run git/hg only once to get both the branch and if the working directory is 'dirty', i'm currently trying out ways for this.
=> get_hg_status runs 'hg root'

news/fix-readline-completer.rst, xonsh/readline_shell.py
This fix following readline path completion issues on master:
```
$ mkdir -p '/tmp/path with spaces/ok'
$ mkdir -p '/tmp/path with spaces/pok'
$ mkdir -p '/tmp/foo'
$ mkdir -p '/tmp/foo bar'
```
```
$ cd '/tmp/foo <TAB>
$ ls '/tmp/foo'<TAB>
$ ls '/tmp/foo bar/'<TAB>
$ ls '/tmp/foo' /tmp/f<TAB>  # completion for second path param.
$ ls /tmp/p<TAB>
$ ls '/tmp/path with spaces/'o<TAB>
$ ls '/tmp/path with spaces/'po<TAB>
```
=> Fix readline path completion issues

news/not_backgroundable.rst, xonsh/commands_cache.py
as reported in #1947, `pacman` in the `default_threadable_predictors`
disables capture of all `pacman` commands.
=> remove pacman from threadable predictors

tests/test_integrations.py, xonsh/proc.py
This has a couple of fixes that drmatically reduce CPU usage (from 11% down to < 0.5%) for programs that do not output much to stdout or stderr, such as servers.  Doesn't seem to really affect programs that do stream lots of output.
=> Server CPU usage performance improvments

news/history-sort.rst, xonsh/history.py
In this PR, I want to make the history sorted. It still work in progress, but I open it here for comments.
Currently when you run `history show all -t | head`, `history show all -t | tail`, xonsh mess up the order of results (when you have tons of history files). The first commit is sorting them by modify time. Maybe sorting by `ts` attr of cmds is more accurate but needs more work or sacrifice the performance. Ideas on this?
Also fixed a small issue on deleting empty history files.
=> Make history show all sorted

xonsh/proc.py
An addition fix for #1954, fixes issue like following:
```
$ Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.5/bin/xonsh", line 3, in <module>
main()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/main.py", line 221, in main
shell.shell.cmdloop()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 399, in cmdloop
self._cmdloop(intro=intro)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 359, in _cmdloop
line = self.singleline()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 249, in singleline
rtn = …
```
=> fix signal hook issue

news/conda-forge.rst, xonsh/platform.py
The ON_ANACONDA returned false when python was installed from the conda-forge branch.
=> Fix ON_ANACONDA

news/stderr.rst, xonsh/base_shell.py, xonsh/environ.py, xonsh/lazyimps.py, xonsh/proc.py, xonsh/ptk/shell.py, xonsh/pyghooks.py, xonsh/readline_shell.py, xonsh/tools.py
This should supersede the implementation in #1277, which shockingly was only in June.  I think this might have fixed some errant issues with some pygments formatting, but I haven't tested it rigorously.
=> Added ability to format stderr pre- and post-fixes

xonsh/prompt/vc.py
After installing de9e1686353ec1d7a76e76e2c43185406de88e73 I got
FileNotFoundError: [Errno 2] No such file or directory: 'hg'
at every new shell instance. This is due to the fact that my tools are in /opt/local since I'm using MacPorts on macOS but at the time the subprocess is called in get_hg_branch() PATH is just
PATH=/usr/bin:/bin:/usr/sbin:/sbin
I'm adding FileNotFoundError to the None case handler of subprocess.check_output calls where needed, one of those already had the exception.
The rationale is that if the tool is missing then just return None like if there wasn't a repository at all.
=> Add FileNotFoundError exception to the handler returning None

Makefile, news/load-events.rst, tests/test_events.py, update_ply.xsh, xonsh/events.py, xonsh/main.py, xonsh/ptk/shell.py, xonsh/shell.py
Implement #1550.
Add an event species that is single-shot: It is fired once, but guarantees that all handlers (no matter when they are registered) will be called as long as it is fired ever.
Also added a collection of events:
* `on_post_init`
* `on_pre_cmdloop`
* `on_pre_rc`
* `on_post_rc`
* `on_ptk_create`
(As an extra, created a makefile with some of the management commands, because I got tired of remembering the amalgamation-related incantations.)
=> Load events

docs/conf.py
sphinx will implicitly import main, but not before we call
`make_events()`, so only `on_chdir` shows up on the events listing.
explicitly importing `xonsh.main` fixes this up so all of the available
events are documented properly.
=> import xonsh.main to fix events docs generation

xonsh/main.py
`on_post_rc` happens after rc files are loaded.  
no news entry and probably don't need to wait on CI, either.
=> quick docs fix for events

xonsh/ptk/shortcuts.py
This PR try fixes #1998 to prevent xonsh crash. No news item needed.
=> Prevent xonsh crash when ptk cli.run raises error

.travis.yml, docs/aliases.rst
@asmeurer reported that travis doesn't stop a build if the docs fail to build unless there's a `set -e` in there.  Adding it in so that we don't accidentally push broken docs, potentially deleting what we have.
=> stop travis if build fails

tests/test_history.py, xonsh/history/json.py
Since sqlite history backend was just added, it's time to unify the history APIs a bit I think. In this PR I want to make behaviors of `inps`, `tss`, `outs`, and especially `rtns` consistent between history backends.
<del>Haven't dig deep, but it seems that we can remove class `JsonCommandField` and put the ``__getitem__`` logics in `JsonHistory` and only make `inps` searchable.</del>
Ideas on this?
=> Unify History APIs - inps, rtns, etc.

news/xonsh-debug-level.rst, xonsh/environ.py, xonsh/execer.py, xonsh/foreign_shells.py, xonsh/shell.py, xonsh/xontribs.json, xontrib/bashisms.py
There are debug level `+-` outputs with commands like `history info` when `$XONSH_DEBUG = 1`. I believe these outputs should be printed with a higher debug level as the other places of `execer.py` related with `self.debug_level`.
no news items is needed.
=> update info print of debug level

news/xonfig-fix.rst, setup.py, tests/test_platform.py, xonsh/platform.py
Found xonfig is broken when I was trying 0.5.0 in a clean env..
Sorry @scopatz, maybe you could do a 0.5.1 release for it soon?
=> Fixed xonfig raising error when xonsh is not installed from source

news/tests-python-shebangs.rst, tests/bin/cat, tests/bin/pwd, tests/bin/wc
These files contain python3 syntax, which causes the associated tests to fail on a system for which `/usr/bin/python` is python2.
=> Tests python shebangs

.travis.yml
now that we have a release that contains the encrypted deploy key, we
can also have doctr always push the most recent release docs to
`xonsh-docs`.
there may be more fiddling to do to get a documentation selector
working but this is a start
Usual caveat that we won't know if this is working until it's merged, but if anyone spots any obvious problems in the yaml logic, let me know.
=> use doctr to also manage release docs

xonsh/main.py
Missed some info from previous PR.
This PR will turn this:
```
Last login: Wed Dec 21 21:28:23 on ttys010
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17829, in main
return main_xonsh(argv)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17836, in main_xonsh
args = premain(argv)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17775, in premain
builtins.__xonsh_shell__ = Shell(**shell_kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 17001, in __init__
from xonsh.ptk.shell import PromptToolkitShell as shell_class
File …
```
=> print out exception msg when do fail-back

.travis.yml
I think the errors that doctr encounters when pushing the second set of
docs has to do with trying to add to the gh-pages branch when we're
starting from non-HEAD location?
I'm hoping that by manually putting us back onto HEAD that this should
avoid that...
If this does work, it's probably worth putting into doctr itself.
Usually caveats that we can't test this until it's merged...
=> checkout HEAD before attempting second deploy

news/fix_multiline_execution.rst, xonsh/ptk/shell.py
When events were introduced, the PTK shell's `_push` was left behind.
This is the cause of #2036 as the buffer isn't cleared between separate
prompt inputs, leading to very, very strange behavior.
This restores the use of the PTK `_push` that properly resets the buffer
if the AST fails to compile and also adds in the precommand src
transformation so that the bashisms xontrib still works as expected.
=> use ptk-specific `push` when executing commands

docs/tutorial.rst
There is no notion of an escaping character in xonsh, but there is in reStructuredText
=> escape backslash in Tutorial warning

docs/tutorial.rst
`__xonsh_regexpath__` doesn't seem to exist in Xonsh 0.5.1, but `__xonsh_regexsearch__` has the mentioned implementation according to `??`
Also replaced `??` output with the actual (and user-agnostic) one from a Xonsh installed system-wide with `sudo pip install ...`
=> Tutorial: replace regexpath by regexsearch

docs/tutorial.rst
to fix its grammar and increase its clarity
=> Tutorial: Rephrase Bash/Xonsh comparison warning concerning backticks

news/command_cache_additions.rst, xonsh/commands_cache.py
this should fix weechat in xonsh, but the larger issues around ncurses based applications raised in #2056 remains
=> add weechat to default predictors (ncurses based)

news/ret_code_none.rst, xontrib/prompt_ret_code.xsh
When the return code is 0, nothing is displayed in the prompt. Empty string was
returned. Returning None have the same behavior, but allows user to use the
syntax "{retcode:{} }" in the prompt for different spacing.
=> ret_code should return None not '' when rc==0

xonsh/completers/bash.py
=> Ensure input to `commonprefix` is a list (now required by Python 3.6)

docs/tutorial.rst
In Xonsh 0.5.1, an alias function's `stdin` argument receives a `_io.TextIOWrapper` object, which cannot be stripped or be treated as a string as-is. We have to `.read()` it first and then `.strip()` the resulting string instead.
Also, fix the second lambda to output the space and EOL correctly.
=> Tutorial: fix stdin handling in anonymous aliases

news/elision_char_at_the_end_of_last.rst, xonsh/prompt/cwd.py
With ``$DYNAMIC_CWD_ELISION_CHAR='…'``
Before:
```
jben@germinale /tmp $ mkdir i_love_writing_a_lot_of_useless_things_in_directory_names
jben@germinale /tmp $ cd i_love_writing_a_lot_of_useless_things_in_directory_names/
jben@germinale …/i_love_writing_a_lot_of_usele $                            
```
After:
```
jben@germinale /tmp $ mkdir i_love_writing_a_lot_of_useless_things_in_directory_names
jben@germinale /tmp $ cd i_love_writing_a_lot_of_useless_things_in_directory_names/
jben@germinale …/i_love_writing_a_lot_of_usel… $                            
```
[edit]: I had inverted before and after.
=> Add elision char at the end of cwd when the last dir is shortened

news/hist-tss-fix.rst, xonsh/jobs.py
Fixed an issue with sqlite history backend that a second "exit" do not kill all the unfinished jobs when exiting xonsh.
Very minor one, so I guess no news items is needed.
=> History fix - use tss instead of buffer

.appveyor.yml, .circle.yml, .travis.yml, news/glbf.rst, tests/conftest.py, tests/test_contexts.py, xonsh/__init__.py, xonsh/ast.py, xonsh/built_ins.py, xonsh/contexts.py, xonsh/execer.py, xonsh/tools.py
This includes #2073, which I hope will fix the appveyor issues.
=> Macro contexts refactor

news/tabcomplete_for_click_apps.rst, xonsh/xontribs.json
Hi,
I've made a generic tabcompleter for applications based on [click](http://click.pocoo.org/5/) command line interface framework, which seems to be very popular for newer python applications.
Pypi: https://pypi.python.org/pypi?name=xonsh-click-tabcomplete
Github: https://github.com/Granitosaurus/xonsh-click-tabcomplete
=> add xontrib entry for click-tabcompleter

docs/tutorial.rst
As per issue https://github.com/xonsh/xonsh/issues/2052
Simply updated the class name and the example in the tutorial page.
=> [docs] rename CompletedCommand to CommandPipeline as per v0.5 changes. 

.circle_miniconda.sh
Pinning matplotlib to 1.5.3 avoids the test failures on CircleCI for now. We'll have to update the `mpl` xontrib to work with matplotlib v2.0 soon
=> pin mpl to 1.5.3 for tests

docs/tutorial_events.rst, news/events-keywords.rst, tests/test_base_shell.py, tests/test_dirstack.py, tests/test_events.py, tests/test_vox.py, xonsh/base_shell.py, xonsh/dirstack.py, xonsh/events.py, xonsh/ptk/shell.py, xonsh/shell.py, xontrib/bashisms.py, xontrib/voxapi.py
In discussing the future of command transformation, I realized that history backends might want to log the pre- and post-transformation commands. But changing the signature of `on_precommand` will break  existing users.
So, moving forward, I propose that events are keyword-argument only, and that all handlers have a `**kw` against future expansion. (There is precedent for this. Django--and the PyDispatch it was based on--does the same thing.)
=> [RFC] Events keywords

docs/python_virtual_environments.rst, docs/tutorial.rst
Aids those of use who like custom prompts but also want the same
prompt behaviour as `virtualenv`.
Resolves #2090
=> Add a vox custom prompt section

news/vc_alias_fix.rst, xonsh/commands_cache.py, xonsh/prompt/vc.py
I don't *think* this will have any side effects.
When we build the ``$PROMPT``, we lazily check for ``git`` and ``hg``
binaries to see if we should generate a ``<branch>`` field.
At the same time ``lazy_locate_binary`` doesn't return the path to a
command if it detects that that command is an alias (since aliases won't
have a path).
In the case that ``git`` or ``hg`` is aliased (the specific case here
was replacing ``git`` with ``hub``), ``lazy_locate_binary`` will return
``None`` because the command is an alias.
This breaks the logic in the branch detection. We don't want to change
the logic in the branch detection since there are many potential impacts
on prompt generation speed, which makes for a bad user experience.
So, this is a mildly ugly hack, but it's the best option I could come …
=> ignore vc aliases in command_cache

docs/tutorial_hist.rst
Isn't it possible to store stdout on windows with the new subproc code?
This PR just remove the comments in the Docs that this is not possible.
=> Update info on stdout storage on windows

docs/aliases.rst, news/xip.rst, xonsh/aliases.py
Allows easily calling `pip` for xonsh itself. Fixes #2110.
=> Add `xip` alias

setup.cfg, tests/test_history_sqlite.py
Adding some tests back, which was removed in #2109 (which, BTW, is a good one!)
Though it was the same test code for json and sqlite, but we need duplicate it in `test_history_sqlite.py` and `test_history.py` since they use different `hist` feature one for json and one for sqlite. Since there's two built-in backend, we have to cover them both :)
cc @laerus
=> Adding some tests back

news/hist-be-env.rst, tests/test_history.py, xonsh/environ.py, xonsh/history/main.py, xonsh/tools.py
Just a POC. Will continue if direction is ok.
With some changes like this would [simplify code in xonshrc](https://github.com/xonsh/xonsh/pull/2138#issuecomment-276942858) if the users want to [write their own history backend](https://github.com/xonsh/xonsh/pull/2138#issuecomment-276942858).
=> Make XONSH_HISTORY_BACKEND accept class type

news/insane.rst, xonsh/jobs.py
See gitter discussion: https://gitter.im/xonsh/xonsh?at=5897635df045df0a220c2aa6
=> Allow the TTY to be insane if there is no shell

xonsh/timings.py
A small bug crept in yesterday that prevented the timings to used for commands etc. 
With this fixed, the timing feature can also be used to measure time between prompts:
```
snail@sea ~ $ x = $(echo "hallo world")
Debug level: 0
|----------------|-----------|-----------|
|Event name      | Time (s)  | Delta (s) |
|----------------|-----------|-----------|
|on_post_prompt  |   0.000   |   0.000   |
|on_precommand   |   0.005   |   0.005   |
|on_postcommand  |   0.031   |   0.026   |
|on_pre_prompt   |   0.380   |   0.349   |
|----------------|-----------|-----------|
snail@sea ~ $
```
=> Timings between prompts

docs/tutorial.rst, news/move-tools.rst, tests/test_integrations.py, xonsh/aliases.py, xonsh/proc.py, xonsh/tools.py, xontrib/mpl.py
Moved decorators `unthreadable`, `foreground`, `uncapturable` from `xonsh.proc` to `xonsh.tools`. Because,
- Can reduce potential circle imports, since proc.py have more deps. (major reason)
- These decorators have no deps, and all one/two line of code, suitable in tools.py
- `xonsh.tools` is more suitable than `xonsh.proc` for using by xonsh itself or xonsh users
ideas?
cc @scopatz
=> [RFC] moved unthreadable etc decorators to tools

.gitignore, news/lr.rst, tests/conftest.py, tests/test_imphooks.py, tests/test_main.py, tests/test_replay.py, tests/tools.py, xonsh/__init__.py, xonsh/built_ins.py, xonsh/environ.py, xonsh/execer.py, xonsh/main.py, xonsh/shell.py
This refactor of the loading system linearizes the setup of xonsh. The Shell class is now no longer responsible for creating an execer and loading the rc files. Additionally, it unifies the load path for xonsh-lang rc files and the JSON-based static configuration files. Lastly, this PR should address #870.
=> Xonsh startup loading refactor

news/wrongpred.rst, xonsh/built_ins.py
This should address some of the issued pointed out in #2186
=> Fix for alias resolution in threadable predition

xonsh/main.py, xonsh/proc.py
Try fixes #2196. The current committed code actually fixed the stuck issue, but, obviously, is not the correct way.
The correct way I think should be 1) "not read from stdin or write to stdout/stderr when hand out the terminal" and/or 2) "do not settcattr when should not".
=> Prevent main proc from stopping

xonsh/shell.py
Since it's on the website and all.
(Docs-only change, no news required.)
=> Actually document parameters of `on_postcommand`

docs/events.rst, docs/tutorial_events.rst
Because they really should be cross-linked.
(Docs-only change. No news.)
=> Link the events tutorial and the events references

xonsh/readline_shell.py
This should partially address the issue in #2130. Particularly when the tab completer is responded to with a "no" for more completions. cc @melund
=> windows don't complete fix

news/lookup.rst, xonsh/built_ins.py, xonsh/commands_cache.py
This is an alternative to #2206 and should address  #2198 #220. Thanks to @gforsyth and @mitnk for pointing this out
=> new threadable prediction lookup

news/resetline.rst, xonsh/ptk/shell.py, xonsh/readline_shell.py, xonsh/tools.py
This should address #959 for both ptk and readline.
=> carriage return on the first prompt to properly capture all input

news/rawpath.rst, xonsh/completers/path.py
This should enable more robust raw string path completers on windows. It should address the remaining issues in #983.
=> raw path completer fixes

news/winterm.rst, xonsh/readline_shell.py, xonsh/winutils.py
This fixes the other bug in #2130, where ANSI color sequences don't display properly in windows terminals. cc @melund @laerus This builds on #2207, but shouldn't be a big deal
=> Windows Terminal ANSI color fixes

news/tracer.rst, tests/tools.py, xonsh/aliases.py, xonsh/base_shell.py, xonsh/tracer.py
This updates tracer to correctly print colors and not print extra newline in a headless shell. This should address #960.  The script I was using as a test is:
**test.xsh**
```
#!/usr/bin/env xonsh
trace on
print("yo")
42 + 42
trace off
```
This seems to work in the following cases:
```console
scopatz@artemis ~/temp $ ./test.xsh 
test.xsh:4:print("yo")
yo
test.xsh:5:42 + 42
test.xsh:6:trace off
scopatz@artemis ~/temp $ x = $(./test.xsh); x
'test.xsh:4:print("yo")\nyo\ntest.xsh:5:42 + 42\ntest.xsh:6:trace off\n'
scopatz@artemis ~/temp $ ./test.xsh | less
```
=> Tracer fixes

news/no-fs-over.rst, xonsh/aliases.py, xonsh/environ.py
This PR adds some logic to skip existing foreign shell aliases. This should hopefully address #1064
=> Skip existing foreign shell aliases

news/lex.rst, tests/test_lexer.py, xonsh/built_ins.py, xonsh/lexer.py
This adds a new split() method to the lexer. This is then applied to the `@$(cmd)` syntax. This should address #1091.
=> Lexer splitter

news/wsl_bash.rst, xonsh/platform.py
This should address #2224, where @ericmharris reported that `Windows subsystem for Linux` (WSL) bash did not return a correct version string.
=> Handle if WSL bash misbehaves on Windows

news/ie.rst, tests/test_imphooks.py, xonsh/imphooks.py, xonsh/main.py, xonsh/pytest_plugin.py, xontrib/mpl.py
This PR adds six new events for hooking into Python's import mechanism.  Now you can register a handler for before/after a module is search for, created, or exec'd. There are probably some pretty crazy abuses of this. 
The initial application of this is to help fix some of the interactivity issues with matplotlib. This should close out #1043. Some of the problems mentioned in that issue seemed to related to mpl v1.x and have since been fixed in mpl v2.x.  This PR tries to address the remaining problems.
=> Import Events and Matplotlib Interactive Fixes

news/fix_time_clock.rst, xonsh/timings.py
=> Replace deprecated calls to `time.clock()` by `time.perf_counter()`
