xonsh/shell.py
=> Fix for issue "Multi-line input never terminates #13"

xonsh/built_ins.py, xonsh/environ.py, xonsh/shell.py
Attempt to fix the issue with the repr of Python functions being used as a prompt.
=> Second attempt at fix for #34

.travis.yml
* to run tests with travis-ci.org
* prerun test, pip install ply and nosetests
* discover and run test with nosetests
=> a first approach to a travis file

docs/faq.rst
pasres -> parses
convienece -> convenience
=> Fix typos in faq

xonsh/built_ins.py, xonsh/tools.py
This is a simple first go at fixing #54, prettifying error messages in subprocess mode.
=> subprocess mode error message

setup.py
=> specify full path to README.rst

xonsh/shell.py
Some changes to help support tab completion on OS X as discussed in issue #60
=> Tab Completion on OS X

xonsh/shell.py
Remedy for #96 . Passed the "spam this button" test.
=> Non-recursive refactor of shell.cmdloop()

tests/test_tools.py, xonsh/execer.py, xonsh/tools.py
Should address remaining issues in #92.
=> fix for comment only lines

xonsh/lexer.py
This is an attempt to fix the issues with running scripts from #92 by changing the way comments are parsed.
=> fix for comment parsing

xonsh/lexer.py
I believe this fixes the issue from #92, allowing xonsh to handle multline strings.
=> Modify string regex (allow multiline strings)

tests/test_parser.py, xonsh/parser.py
=> Nested Lists and Tuples

docs/tutorial.rst
It isn't spectacular, but I tried to add some relevant text to the tutorial about running scripts with xonsh (as opposed to using the REPL).  I also fixed a few typos and grammatical issues, and removed trailing whitespace.
=> Documentation for running scripts

xonsh/shell.py
=> `lstrip` the first line of shell input

xonsh/environ.py
This seems to fix #131 for me.
=> attempt to fix #131

.landscape.yaml, README.rst
Hi,
First of all thak you for xonsh, it is awesome!!!
I have added a badge for landscape.io (static code analysis). I think it is a good way of preventing bad code/potential bugs.
You only need to create an account on https://landscape.io and it should work. If you find the rules too strict, feel free to modify ".landscape.yaml"
=> Use landscape.io

tests/test_parser.py, xonsh/parser.py
=> fix and tests for mutliple assignment

docs/tutorial.rst, tests/test_builtins.py, tests/tools.py, xonsh/built_ins.py, xonsh/parser.py
Implements [this proposal](https://github.com/scopatz/xonsh/issues/153#issuecomment-87241729) from #153.
=> implements non-string sequences to @()

tests/test_tools.py, xonsh/ast.py, xonsh/execer.py, xonsh/pyghooks.py, xonsh/tools.py
This should fix #167, and many other relevant cases.
=> more robust subproc injection

xonsh/aliases.py, xonsh/ast.py, xonsh/built_ins.py, xonsh/completer.py, xonsh/dirstack.py, xonsh/environ.py, xonsh/execer.py, xonsh/imphooks.py, xonsh/inspectors.py, xonsh/main.py, xonsh/openpy.py, xonsh/parser.py, xonsh/pyghooks.py, xonsh/shell.py, xonsh/tools.py
With the help of [yapf](https://github.com/google/yapf), I tried to minimize the number of PEP8 violations in the codebase and make things more readable, at least to my eyes.  I think there are no substantive changes here (and the tests I tried suggest that these changes don't break anything).  This may or may not be something we want to try to do now (reformatting like this can always wait, I suppose).
=> Many PEP8 Changes

.landscape.yaml, setup.py, tests/test_builtins.py, tests/test_imphooks.py, tests/test_lexer.py, tests/test_parser.py, tests/test_tools.py, xonsh/aliases.py, xonsh/ast.py, xonsh/completer.py, xonsh/dirstack.py, xonsh/inspectors.py, xonsh/jobs.py, xonsh/openpy.py, xonsh/parser.py, xonsh/pyghooks.py, xonsh/tools.py
Not ready yet.  Just using the PR to trigger landscape.
=> some landscape fixes

tests/test_builtins.py, tests/test_tools.py, xonsh/completer.py, xonsh/tools.py
Should work on everything that is `dir()`-able in xonsh, including environment variables, subprocs!
I was getting pretty annoyed at not having this :)
=> Attribute Completion

xonsh/tools.py
It took a lot of staring to find this one.
=> I see a string and I want to paint it black

setup.py
=> wrap develop too

tests/test_parser.py, xonsh/parser.py
=> unpack targets in comprehension

xonsh/completer.py
Simple implementation of the feature requested in https://github.com/scopatz/xonsh/issues/206
=> completing module to import

docs/index.rst, docs/tutorial.rst, docs/windows.rst
I'm having some trouble getting the right sphinx environment to build the docs (I think sphinx is defaulting to python2 instead of python3), so I haven't tested these.  Thought I would put them out there anyway for comments.
=> windows: doc updates

xonsh/base_shell.py, xonsh/built_ins.py
This is a hack to get shebang lines working on Windows (should fix #233).  It does change the handling in *nix, too, but I think not in a way that has any ill effects.
=> Windows Shebang

xonsh/built_ins.py
I think this should do it (as you suggested, @scopatz, just some shuffling of the checks).
=> proposed fix for alias bug from #241

xonsh/environ.py
Initial solution to #234 as proposed by @wrywerytwreywery.  I will probably still remove it from my prompt in my .xonshrc on my Windows tablet, but it may be acceptably fast on better hardware.
=> windows: enable git branch checking in prompt

xonsh/main.py
Just some quick rearrangement, made the option be `--shell-type` for consistency with other options, and turned choices into a tuple.  Probably for @anula to review and merge since this is her code :)
=> some minor cli changes to shell type

.gitignore, xonsh/parser.py
I believe this should fix #260.  Also made some additions to the gitignore file, to ignore temporary files from vim and emacs (I can remove that or move it to a separate PR if necessary).
=> Change handling of tilde

tests/test_man.py
Just some cleanup for various platforms.
=> improved man tests

xonsh/aliases.py, xonsh/completer.py, xonsh/environ.py
This makes Git and Mercurial integrations more robust on windows.
Prerequisite for #300.
=> Enable `locate_binary` on Windows

docs/api/index.rst, docs/api/pretty.rst, xonsh/built_ins.py, xonsh/environ.py, xonsh/main.py, xonsh/pretty.py
The pretty print module is from the IPython project. Does anyone know how to give proper credit etc...
=> Add pretty printing

xonsh/tools.py
This adds the feature described in #280
=> added command-not-found capability for ubuntu and debian

xonsh/completer.py
Follow up from the pull request that closed #225 (add CDPATH support)
=> Closes #307, do not use full path for completion, use basename only

xonsh/ast.py, xonsh/pretty.py
Changes suggested in the comments to #330.
=> Renaming a few variables

docs/tutorial.rst, tests/test_environ.py, xonsh/environ.py
This should address the issue brought up in #297 by @asmeurer
=> prompt formatting functions may return None

tests/test_execer.py, xonsh/execer.py
=> fixes hanging indent error

docs/tutorial.rst, tests/test_builtins.py, tests/test_man.py, tests/test_tools.py, xonsh/built_ins.py, xonsh/completer.py, xonsh/environ.py, xonsh/tools.py
As requested by @asmeurer. Should close #290.
=> ignore case on completion

docs/tutorial.rst, xonsh/environ.py
Should address the issues #293 raised by @asmeurer
=> Added more cwd formatters

xonsh/built_ins.py
I would appreciate it if @larsks and @adqm could take a look. Thanks!
=> fixed SUID issues, I think

docs/index.rst, tests/test_prompt_toolkit_tools.py
This contains an additional change over and above #334 that allows the tests to pass.
=> Prompt toolkit fixes

docs/tutorial.rst
=> tutorial: remove DEFAULT_ALIASES from aliases section

xonsh/prompt_toolkit_history.py
Hi, in my last "fix", apparently I broke a part of the history. I just noticed that pressing the up-arrow did not always return the last entry.
This should fix it.
=> Fix for 122361eeca5189e70ff81931f80812fb16a75c3d: history was partly broken.

xonsh/environ.py
Also covers `cwd_dir` and `cwd_base`.
=> Expand `FORCE_POSIX_PATHS` behavior to `cwd` in `FORMATTER_DICT`

.appveyor.yml, .gitignore, .travis.yml, appveyor.yml, binstar.yml, docs/previous/0.2_release_notes.rst, landscape.yml, tests/test_parser.py, travis.yml, xonsh/parser.py
Just to test if the CI services support it.
=> some v3.5 updates

.appveyor.yml, .travis.yml, tests/test_parser.py, tests/tools.py, xonsh/parser.py
=> Implementation of Pep448

.appveyor.yml, .travis.yml, tests/test_parser.py, tests/tools.py, xonsh/ast.py, xonsh/lexer.py, xonsh/parser.py, xonsh/tools.py
This closes #389, and builds on top of #395.  Pretty simple actually.
=> Implementation of Pep465

.appveyor.yml, .travis.yml, tests/test_parser.py, tests/tools.py, xonsh/ast.py, xonsh/lexer.py, xonsh/parser.py, xonsh/tools.py
This should close #390 and builds off of #396.
I know the branch name is wrong, but I am too sleepy to fix it :)
=> Implements Pep492

xonsh/completer.py
When using a command with a `"` in it, `bash_complete` was throwing an
uncaught exception. This patch both catches the exception and escapes
the values passed properly to avoid errors.
=> Fix bash completions failing when using double quotes

xonsh/prompt_toolkit_key_bindings.py
=> fix prompt_toolkit tab behavior on blank line

docs/envvars.rst, xonsh/environ.py, xonsh/prompt_toolkit_completer.py, xonsh/prompt_toolkit_key_bindings.py, xonsh/prompt_toolkit_shell.py
Demonstration of new features.
Don't just merge this. Maybe you want to have a configuration somewhere or not have all the features.
This adds:
- mouse support. (Scrolling through completion menus and clicking for selecting the cursor position.)
- auto suggestion (like the fish shell.)
=> New features

xonsh/proc.py, xonsh/teepty.py
This should close #419. I'd really appreciate it if @masasin would try this out. Thanks!
=> prevent multiple exits due to fork

xonsh/environ.py
This should address the issues in #447. I would really appreciate it if @ZyX-I or someone else could test this out. Thanks!
=> locale fixes to rely on the system better

docs/envvars.rst, tests/test_tools.py, xonsh/built_ins.py, xonsh/environ.py, xonsh/proc.py, xonsh/teepty.py, xonsh/tools.py
This should address the remaining issues brought up in #447.  Can you see if this works for you @ZyX-I? Thanks a ton.
=> Encoding fixes for suproc

docs/aliases.rst, xonsh/aliases.py, xonsh/foreign_shells.py
Should help address #420, but is not solely for that.  I would really appreciate a review or test from someone!
=> implements the source-foreign alias and refactors source-bash

docs/windows.rst
Added info about .xonshrc needed to be created and tips about console emulators to use on windows.
Should resolve some of the issues with installing av new user on windows.
=> Added info to windows.rst

scripts/xonsh.bat
As reported in #443. It would be great if @educhana or some other windows user could test this out. Thanks!
=> Updated the windows script for command line args

xonsh/aliases.py
This is in addition to file names.
=> modifies source-foriegn to accept code

docs/envvars.rst, recipe/meta.yaml, xonsh/environ.py
These were first suggested in #486.
=> prompt toolkit windows changes

xonsh/readline_shell.py, xonsh/tools.py
Handles the \001 and \002 replacements.
=> Helper for printing TERM_COLORS

xonsh/foreign_shells.py
Kind of concerned this wasn't causing tests to fail.
=> Fix several calls to `eunsure_string`

xonsh/built_ins.py
@gforsyth - would you mind taking a look at this?
=> modifications to alias expansion

xonsh/proc.py
Resubmit of 528 with minimal bug fix and cleaned up repo.
=> Support 3-tuple alias retval to include return code.

MANIFEST.in
should solve issue https://github.com/scopatz/xonsh/issues/537
=> make pip work again

xonsh/main.py
As with #520, I'm unclear what the best way to test this is, but really happy to amend this if it's heading a promising direction.
Fixes #511
=> Add support for --config-path option

xonsh/prompt_toolkit_shell.py
=> enable string matching on history search

docs/envvars.rst, xonsh/aliases.py, xonsh/main.py, xonsh/shell.py
This prevented prevcmd from being set implicitly from the command line.
=> Logic bug in source-foreign alias 

docs/index.rst
=> Added xonsh channel to the conda install documentation.

xonsh/built_ins.py
Adding the try/except back in for the new settitle call.  I believe this should fix #566.
=> Be more careful about __xonsh_shell__ (potential fix for #566)

xonsh/environ.py
tiny change to make use of `tools.get_sep` in one spot, at least, to avoid repeated code.
=> Use get_sep function instead of repeating code

xonsh/completer.py
Just a quick addition to allow tab completion when opening man pages
=> add `man` to completion skip tokens

xonsh/completer.py
=> added timeit alias to completion skip tokens

xonsh/completer.py
A few updates for the completer that should fix some of the issues that are lying around:
* slight efficiency improvement for the known commands cache
* added code to avoid repeated completions (which I think should fix #575)
* implementation of `from module import <tab>` (#590)
=> Completer Updates

CHANGELOG.rst, docs/previous/changelog.rst, docs/previous/index.rst
This was by request, and is probably a good idea to start doing.
=> init'd a changelog

xonsh/completer.py
Skipping tokens is turning out to be pretty useful!  1 line change.
=> added which to skiptokens

CHANGELOG.rst, docs/tutorial.rst, xonsh/environ.py, xonsh/parser.py
I believe this should fix the issue from #610, by changing the way `__getitem__` and `get` work for `__xonsh_env__`.
=> change behavior of environment get and __getitem__

tests/test_ptk_multiline.py, xonsh/ptk/key_bindings.py
Haven't worked much with mocks before so if this looks crazy, apologies.  
These should hopefully provide a few sanity checks if we want to refactor the multiline parser in the future.
=> Add a few tests of the PTK multiline parser

xonsh/readline_shell.py, xonsh/xonfig.py
Fix for #627. @gforsyth, wanna take a look?
=> a couple of small startup fixes

xonsh/shell.py
As reported by @BYK in #631.  This is a one line change.
=> fix for testing have readline

xonsh/built_ins.py
=> Check whether a file is executable before assuming it is runnable

CHANGELOG.rst, xonsh/built_ins.py, xonsh/completer.py, xonsh/jupyter_kernel.py, xonsh/main.py
This implements a few small fixes to the Jupyter kernel that makes it usable.
=> Jupyter Fixes

xonsh/xonfig.py
Hi @melund, would you mind taking a look at these fixes? I don't really know what is going on with the color issue, because you are getting color in the prompt.
=> wizard robustness fixes

recipe/meta.yaml
Probably for @melund, though anyone is welcome to take a look!
=> added setproctitle to conda recipe

CHANGELOG.rst, xonsh/aliases.py, xonsh/foreign_shells.py
This aims to close #484 and fix #662.  I also discovered a couple of issues related to sourcing from files with spaces in their names.
@moigagoo, would you mind testing this out? My simple tests seemed to indicate that everything works, but it would be nice to test it some more.
=> Zsh support

xonsh/foreign_shells.py
@moigagoo, would you mind trying this out, please? Thanks!
=> Potential zsh fixes

xonsh/environ.py
=> potential fix for encoding errors for config files

xonsh/pretty.py
The pretty printer we are using from ipython project has some advanced features. So it is easy to fix if there are any of the built-in structures in xonsh that doesn't display nicely. So if you have any particular issues I can try to fix it.
=> Updated pretty.py with newest commits from the IPython project

xonsh/environ.py, xonsh/vox.py
This pull request fixes the issue mentioned in this discussion: https://github.com/scopatz/xonsh/commit/5bb1ea76a33e4f9c7f82849d487caf67623ebdd1
=> Fixed `vox rm` and added autodeactivate to `vox activate`

docs/windows.rst
Related to https://github.com/scopatz/xonsh/issues/686
=> Adding ls alias suggestion to Windows guide.

docs/index.rst
Cf Mailing list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/xonsh/Td-qRSntJ4U/V8McHXy3FQAJ
=> Add the x-on shell as a Pun.

tests/test_execer.py, tests/test_tools.py, xonsh/ptk/key_bindings.py, xonsh/tools.py
=> potential fix for indented subproc mode with comments

CHANGELOG.rst, docs/tutorial.rst, tests/tools.py, xonsh/aliases.py, xonsh/ansi_colors.py, xonsh/environ.py, xonsh/mplhooks.py, xonsh/ptk/shell.py, xonsh/ptk/shortcuts.py, xonsh/pyghooks.py, xonsh/shell.py
As requested by @arkhan, here is the right prompt implementation.
=> right prompt implementation

xonsh/environ.py
As per discussion with @melund in #709.  This is basically a one liner.
=> makes ANSICON non-configurable

xonsh/execer.py
Potentially fixes #717.  Would you mind please taking a look @adqm?  It should be a familiar one liner :)
=> lstrip before $[$[ check

xonsh/base_shell.py, xonsh/ptk/shell.py
I believe that this fixes #715.  Very small change.
=> push fix for namespaces

CHANGELOG.rst, docs/tutorial.rst, xonsh/built_ins.py, xonsh/environ.py, xonsh/proc.py, xonsh/tools.py
probably for @adqm to review, though other folks are welcome to as well!
=> minor fixes for !() and ![]

docs/index.rst
My phonetic is not perfect, and might carry a bit of my French accent,
Would like @scopatz review on that.
=> Fix pronunciation of `conch` in readme

CHANGELOG.rst, docs/aliases.rst, xonsh/aliases.py, xonsh/built_ins.py, xonsh/environ.py, xonsh/winutils.py
Not perfect since it doesn't (cannot) capture the `stdin` and `stdout` for the launched process but it works and is a good first step.
=> New: Add `sudo` functionality on Windows

xonsh/pyghooks.py
=> Make pygments highlighter work with !() and ![]

xonsh/execer.py, xonsh/parsers/v34.py, xonsh/parsers/v35.py
Missed a couple of unused imports on the first go-round
=> remove a few missed unused imports

.gitignore
will make my life a tad bit easier when contributing, feel free to reject if you want, it can just stay in my fork if you don't want this upstream.
=> ignore Komodo editor project files

.travis.yml, docs/devguide.rst, requirements-tests.txt
- add new requirments file for all dependencies needed for testing
- update dev guide
- adjust travis to use the requirements specified in the dev guide (eat our own dog food)
=> specify testing dependencies

docs/tutorial.rst, tests/test_environ.py, xonsh/environ.py
fixes gh-769
This code in this PR seems pretty sound to me.  However, I'm not sure the docs are right.  I feel like this feature will be used more in scripting and not interactive mode, but my example is in interactive mode.  Thoughts?
Also, this is the first code I've submitted.  If I've missed any formatting/style issues, I'll be happy to fix them.
=> add kwarg support to Env.swap()

CHANGELOG.rst, tests/test_aliases.py, tests/tools.py, xonsh/aliases.py, xonsh/built_ins.py
Also this implements the long-overdue moving of the Aliases class to aliases.py. This is an attempt to fix #779.  @asmeurer does this work for you?
=> fix for alias expansion

CHANGELOG.rst, xonsh/aliases.py
@scopatz I stumbled on this while looking at source_cmd stuff.
=> Fixes a bug in source_alias

xonsh/aliases.py
This fixes a bug which I added in one of the last commits on source_cmd PR. 
The bug means that arguments to the bat files were skipped. Sorry :)
=> Bugfix for source-cmd

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml, setup.py
This PR updates the install mechanism for the for xonsh Jupyter kernel.  It also updates the conda build recipe to match the one on conda-forge
=> Update jupyter install mechanism

xonsh/shell.py
=> support ptk_1.x

xonsh/aliases.py, xonsh/foreign_shells.py
This fixes #817 by adding a return code to source_foreign
=> Add return code to source_foreign functions

CHANGELOG.rst, xonsh/main.py
In my testing this fixes #770.  @rsyring would you mind testing this out?
=> run xonfig wizard from main thread

docs/index.rst, docs/linux.rst, docs/osx.rst, docs/windows.rst
Also removing a redundant windows installation guide link
=> update docs for conda install to use conda-forge

xonsh/completer.py
As per this discussion: https://groups.google.com/d/msgid/xonsh/308edd19-0565-43d1-9686-8c87b5362c0c%40googlegroups.com?utm_medium=email&utm_source=footer
it is a one line change :)
=> rsplit to rpartition

xonsh/ptk/completer.py
I'm not sure how I could write unit tests for this.
But I tried it with single and multiple line inputs with ptk 0.57 and 1.0 (only the 1.0 was breaking before this fix).
=> fix #846 (compatibility with ptk 1.0)

xonsh/aliases.py
and one other, small change
this should address #868
=> update which to be compatible with python3.4

xonsh/aliases.py
a fix for those things `which` ails you?  I hope?  Maybe?
ping @scopatz @Carreau
=> add potential fix for which ails

xonsh/built_ins.py
=> Add different error message for PermissionError on redirect

CHANGELOG.rst, xonsh/environ.py
=> Fix overriding of user environment with windows fixes

CHANGELOG.rst, xonsh/aliases.py
=> Improve handling of which being absent

README.rst
Anthony suggested to add [gitsome](https://github.com/donnemartin/gitsome) to a 'Projects that use xonsh' section in the README.  Thanks!
=> Add 'Projects that use xonsh' section to README

xonsh/wizard.py, xonsh/xonfig.py
@GuillaumeLeclerc would you mind giving this a try.  This should fix #847
=> reprompt in wizard for invalid input for envvars

tests/test_execer.py
=> fix test error when STORE_STDOUT = True

.gitattributes
=> Adds scripts/xonsh.bat to .gitattribues

docs/api/index.rst, docs/devguide.rst, requirements-docs.txt, xonsh/environ.py
- ~~alphabetically sorted api-toc~~
- more links to numpydoc guide
- clarifies dependencies to build docs
=> Updates to docs

docs/aliases.rst
Also remove documentation for which->where alias
=> Update aliases.rst with deactivate/activate aliases 

xonsh/ptk/shell.py
=> fix vi_mode set but still not enabled in prompt_tookit shell

docs/linux.rst
I don't use ReStructured Text very often, so hopefully I didn't mess up the markup. Or the actual information :P
=> Document Bash config conflicts, according to issue #208.

tests/test_execer.py, tests/test_tools.py, xonsh/execer.py
This should probably go in for the release tomorrow, if possible
=> Fixed echo @("foo") > bar

xonsh/readline_shell.py, xonsh/xonfig.py
Was seeing the escape sequences in certain cases.
=> fixes for wizard in rl shell when storing stdout

docs/tutorial.rst
As requested in #926, this adds a slightly more substantial Tutorial entry about the new ``@$()`` operator.  I'm happy to modify if this doesn't satisfy.
=> Slightly more substantial tutorial entry for @$

setup.py
This should hopefully address the issue in #950, and if not it adds some robustness so that the install doesn't fail and it reports on the problem.
=> Jupyter install hook improvements

CHANGELOG.rst, xonsh/completer.py
This fixed bash completion for me. It failed because files had spaces in their names.
=> Win bash completion

docs/conf.py, xonsh/environ.py, xonsh/wizard.py, xonsh/xonfig.py
=> added store_as_str to vardocs

tests/test_xontribs.py, xonsh/xontribs.json
which provides a modicum of speed benefits.
=> added xo xontrib metadata

xonsh/tools.py
To restore what was removed in #975
=> py3.4 executables_in() performance

CHANGELOG.rst, xonsh/readline_shell.py, xonsh/tools.py
=> Fixed libedit init file problem

CHANGELOG.rst, xonsh/completer.py
Might be a little hacky but it seemed like the best option.  I am open to suggestions.  @melund -- want to try this out and see if it works for you?
=> add completions to ${...}

CHANGELOG.rst, xonsh/foreign_shells.py, xonsh/platform.py, xonsh/readline_shell.py
As discussed in #514, this seems to be the minimum required to get a working prompt.
=> Minor changes to get shell working in Cygwin

CHANGELOG.rst, xonsh/environ.py, xonsh/ptk/shell.py
This change allows multiline prompts to accept colors.  More annoying to implement that you might think :)
=> Multine prompt colors

CHANGELOG.rst, docs/aliases.rst, xonsh/aliases.py, xonsh/completer.py
This comes from this discussion on the mailing list: https://groups.google.com/d/topic/xonsh/rYb3XJLIc2w/discussion
=> Added showcmd alias

CHANGELOG.rst, tests/test_tools.py, xonsh/ast.py, xonsh/environ.py, xonsh/execer.py, xonsh/tools.py
This refactors the `find_next_break()` functionality to make it more accessible.  This allows the context sensitive parser to use it as needed.  This should close #1024.
=> Debug Subprocs, And/Or

xonsh/ast.py
One character fix :)
Resolves #1032
=> fix incorrect parsing of command line flags

tests/test_tools.py
This is an attempt to make the tests deterministic and address #1014.  @melund, if you get a chance would you mind seeing if this works on Windows? Thanks!
=> Deterministic tests

CHANGELOG.rst, tests/test_parser.py, xonsh/parsers/base.py
Adds a test and changelog entry to #1067, probably for @adqm to review and merge.
=> Question mark tests and changelog

docs/index.rst
One is just an improvement over one that's already there, so maybe it ought to
just replace it. The others are Monty Python, from
https://twitter.com/asmeurer/status/701509800530579456.
=> Add some intro taglines

tests/test_tools.py, xonsh/tools.py
closes #1061 
---- 
Might need tests.
=> Don't crash if broken symlink on path.

.travis.yml
-- 
Because 3.6 is the future ?
=> Travis test on nightly

docs/bash_to_xsh.rst
https://groups.google.com/d/msgid/xonsh/CAO41-mNeFfZ88Fx%3D%2B24-EX6S2ZxDYszoGPkUbkeFKy6UCjs%2Bog%40mail.gmail.com?utm_medium=email&utm_source=footer
=> Mention how to mix commands and variables/text

xonsh/parsers/base.py
@mburo or @gforsyth, can you take a look, please? Thanks in advance!
=> hotfix for #1108

xonsh/environ.py
I just completed the wizard, thanks for my new shell!
=> environ.py: fix typo

CONTRIBUTING
GitHub is weird about symlinks and I think this better represents the
desired behavior (if you click CONTRIBUTING, you should see the dev
guide).
@melund -- do hard links work on Windows?
=> make CONTRIBUTING a hard link

CHANGELOG.rst
@BYK could you please help to review this tiny change? Thanks.
=> typo fix in changelog

CHANGELOG.rst, xonsh/aliases.py, xonsh/jobs.py, xonsh/ptk/key_bindings.py
This addresses #1028. Please let me know what you think. I wasn't sure what was most readable regarding clean/kill/etc.
=> Check no stopped or background jobs exist before exiting interactive shell

CHANGELOG.rst, xonsh/platform.py
This a potential fix for the Error when Bash from Windows Subsystem for Linux is on the path. See #1200
=> Fix for bash wsl

xonsh/completers/path.py
I believe this should fix the issue from #1198.  @scopatz, do you mind testing?
=> only do subsequence and fuzzy matching if no normal matches found

xonsh/tools.py
I did a searh of the source code. I think is should be the last.
@gforsyth Do you mind taking a look
=> Use env._defaults 

news/quoted_path_completions.rst, xonsh/completers/path.py
This fixes the missing completions in https://github.com/xonsh/xonsh/issues/1201
If any of the completions needs to be quoted then all completions gets quoted.
=> Fix missing completions

docs/dependencies.rst
in request of #1118 on why would someone want to install the extra dependencies
=> more information about library dependencies

xonsh/aliases.py, xonsh/ptk/key_bindings.py
This should fix #1260. @laerus, would you mind testing this out please?
=> fix for xonsh exit

xonsh/aliases.py, xonsh/xonfig.py
=> xonfig updates

news/wizard_foreign_shell_prompt.rst, xonsh/xonfig.py
=> Be more explicit in foreign shell wizard

news/fix_alias.rst, xonsh/built_ins.py
I think this should fix the problem with aliases that reference them self. #1240 
@scopatz  You had this problem as well, could you verify that this work. 
Also @gforsyth maybe you better check that it doesn't break something else for you.
=> Fix aliases that reference them self

xonsh/timings.py
Hopefully this fixes some of the windows issues.
=> removed literal mu symbol (µ) in comment

amalgamate.py
Hopefully this will fix the remaining issues.
=> more unicode escapes in amagamate for anaconda

xonsh/main.py, xonsh/shell.py
=> xontribs fix

docs/bash_to_xsh.rst
about ${...}.swap functionality
=> bash to xonsh new entry

docs/tutorial.rst
=> updates tutorial about how to use enviroment

tests/test_tools.py, xonsh/tools.py
=> Added support for slices in EnvPath

news/pid.rst, xonsh/jobs.py
I believe that this addresses #1297. @JohnLunzer, would you mind trying this out please?
=> Process Group Fixes

README.rst
trivial update of scopatz -> xonsh in readme links
=> update readme links for organizational account

news/cc.rst, tests/test_aliases.py, tests/test_imphooks.py, tests/test_tools.py, tests/tools.py, xonsh/aliases.py, xonsh/environ.py, xonsh/tools.py, xonsh/xoreutils/_which.py
This should hopefully address the slowdown issues on windows. @JohnLunzer and @melund could you give it a spin?
=> Binary locate speedups

xonsh/jobs.py
This might have been causing the slowdown in #1268, but is definitely a bug.  @JohnLunzer @gforsyth, would you mind taking a look?
=> typo for cygwin job control

tests/test_dirstack.py, tests/test_parser.py, tests/test_replay.py, tests/test_tools.py, tests/tools.py, xonsh/tools.py
i need to see travis run, couldn't make it run on my branch/repo
=> figuring out why travis cries with pytest

tests/test_parser.py, tests/tools.py
@laerus @gforsyth This should fix the pytest skip issue. 
There are probably many more places where it could be use. I will look
=> Fix pytest skip

tests/test_parser.py, tests/test_tools.py
This fixes a failing test on my machine where `XONSH_ENCODING_ERROR` was missing in the mocked environment. 
It also adds a better integration of the assertion check_ast assertion functions, as well as getting rid of all the yield statements.
=> Pytest port

xonsh/ptk/history.py, xonsh/readline_shell.py, xonsh/tools.py
This fixes #1238, but is accidentally also includes #1327
=> JSON load errors.

xonsh/tools.py
This is a potential fix for #1323.
=> fix for os.environ lookup

xonsh/xontribs.json
=> fixed name of apt_tabcomplete.xsh

xonsh/xontribs.json
quick xontrib to improve pacman completion
=> add pacman tab completion xontrib

news/amalfix.rst, setup.py
Critical fix for pypi package.
=> Amalgamate install fix

MANIFEST.in, news/mani.rst
This is needed for #1343 and will require a hotfix v0.4.2 release.
=> Script Manifest

xonsh/built_ins.py
I believe this should fix the original issue described in #1330, by making sure all the processes in a pipeline are part of the same process group.
=> Another pipeline fix

news/readline-case-sensitive.rst, xonsh/readline_shell.py
to fix #1342 
@adqm could you have a look, thanks!
=> fix #1342 readline case sensitive issue

docs/index.rst, docs/linux.rst, docs/osx.rst, docs/previous/index.rst, docs/tutorial_xontrib.rst, docs/windows.rst, setup.py, xonsh/aliases.py
=> update xonsh repo url

xonsh/xontribs.json
Hi,
I've made a clone of [autoenv](https://github.com/kennethreitz/autoenv) for xonsh. It functions very much the same. 
If anyone has any comments or suggestions - let me know!
=> Add xonsh-autoxsh xontrib

xonsh/xontribs.json
Tab completion xontrib for [scrapy](https://github.com/scrapy/scrapy) 
https://github.com/Granitas/xonsh-scrapy-tabcomplete
Let me know if I missed something!
=> add Xontrib entry for scrapy-tabcomplete xontribution

news/rmenv.rst, tests/test_aliases.py, tests/test_builtins.py, tests/test_imphooks.py, tests/tools.py, xonsh/built_ins.py, xonsh/tools.py
Removing this hack was long overdue.
=> Removed ENV

news/path34.rst, xonsh/tools.py
=> path fix for v3.4

news/sub.rst, tests/test_lazyasd.py, xonsh/lazyasd.py
=> LazyObject getitem

setup.py
This is meant as a hotfix for some errors with pip install.
=> Some git version setup imporvements

news/no-bare-except.rst
=> News entry for no-bare-except

news/newstests.rst, tests/test_news.py
This will hopefully help make sure the changelog entries are written correctly.,
=> added news tests

xonsh/aliases.py, xonsh/built_ins.py
=> Some more lazy improvements

docs/_static/console_colors.reg
I messed up the registry colors in the last commit to #1405. Basically forgot to sort them correctly. 
This sorts it out.
=> Fix color mixup

news/cs.rst, xonsh/ansi_colors.py, xonsh/readline_shell.py
Relatively simple change for #1412
=> fixed color style recurssion issue, hopefully.

xonsh/xontribs.py
=> xontrib hotfix

xonsh/__init__.py, xonsh/teepty.py
Can you try this out please @melund?
=> fix for windows debug via lazy imports

news/pip-completer.rst, xonsh/completers/__init__.py, xonsh/completers/pip.py
Seems like this should be in the core.
This completes commands from `--help` and completes `pip list` values for `pip show` and `pip uninstall`.
=> add completer for pip

xonsh/completers/pip.py
=> some minor pip completer cleanup

xonsh/lazyasd.py
This should fix #1421. If @PaulReiber @ned2 or @laerus could test this out that would be great! Thanks
=> more lazy object data models

news/ljbfd.rst, xonsh/lazyjson.py
This should fix #1426.  @laerus, would you mind taking a look?
=> fix for lazyjson del issue

news/od.rst, xonsh/parsers/base.py
@laerus could you try this out to fix #1406 please?
=> parser table fix

xonsh/vox.py
https://github.com/xonsh/xonsh/pull/1433
=> Print to error to sys.stderr

tests/test_tools.py
=> test_partial_string ref

news/freebsd.rst, xonsh/aliases.py, xonsh/platform.py
Relatively minor change to support another platform.
=> Added FreeBSD support

.appveyor.yml, setup.cfg, xonsh/teepty.py
This was preventing py.test from running locally.
=> don't run flake8 for all pytets

docs/linux.rst, news/thunar-custom-actions-doc.rst
=> Docs: how to fix Thunar's "Open Terminal Here" action.

xontrib/vox.py
Add a `sys` import a broke.
Also, all errors now go to stderr.
=> Add sys import, and be more consistent about errors going to stderr.

xonsh/xontribs.json
Publishing avox, the automatic vox. It's based on the idea of projects and projects living in specific directories.
See [README.md](https://github.com/astronouth7303/xontrib-avox/blob/master/README.md) for usage instructions.
=> Publish avox

CONTRIBUTING.rst, docs/index.rst
updated another pull request to speed the improvement of documentation
=> Improve first set of "Developer's Guide" instructions [updated]

news/enc.rst, scripts/xon.sh, xonsh/base_shell.py, xonsh/environ.py, xonsh/xonfig.py
This should help in some situations where encoding and locale  issues crop up.
=> Various Encoding Fixes

amalgamate.py, news/futamal.rst
This isn't super useful to xonsh directly, but we should keep in sync
=> amalgamate handles time machine

news/jupyter.rst, xonsh/jupyter_kernel.py
Updates to the jupyter kernel to work with the new completion framework.
=> Jupyter completion

.travis.yml, tests/tools.py
2 character fix to stop complaints in the travis logs
=> small bash syntax fix

xonsh/aliases.py
A few line change to xexec that should have a minimal speedup
=> some xexec optimizations

xonsh/lazyasd.py
CC @janschulz, This is just to keep updated with xonsh/lazyasd#3
=> more intuitive blocking loop

scripts/xon.sh
Just helps keep the process tree and system resources a little tidier.
=> Use exec in xon.sh

xonsh/history.py
=> Document History access fields

news/xontribs.rst, xonsh/xontribs.json
Submitting a new xontrib: [z](https://github.com/astronouth7303/xontrib-z). (No, I didn't pick the name. It's a port of the zsh script [z](https://github.com/rupa/z).)
Also, new for the first time: A news item to go with new xontribs.
=> Submitting xontrib-z

README.rst
README should point at the current appveyor.
=> Point at the right appveyor

news/srcenc.rst, xonsh/aliases.py
@santagada can you try this out, please?  Probably should be merged no matter what...  Thanks a ton!
=> Source files in XONSH_ENCODING

news/lazy_union.rst, xonsh/lazyasd.py
Fix for #1530 
@santagada, can you try this out?
=> add __or__ to lazyobject

docs/tutorial.rst, xonsh/xonfig.py
Develop info for aliases, and tell user that on first launch that if
they decide to configure now they can resume anytime.
=> Improve documentation and messaging.

news/fix_get_color_index.rst, xonsh/tools.py
This should hopefully fix the startup problem on Windows due to a prompt toolkit refactor.
Adresses https://github.com/xonsh/xonsh/issues/1537
=> Fix color indexes on Windows

news/impacc.rst, xonsh/imphooks.py
Attempts to address #1533.  @melund does this work for you?
=> import hooks access check

news/pcrash.rst, xonsh/completers/pip.py
@astronouth7303 does this fix #1548 for you?
=> pip crash fix

news/ptkeof.rst, xonsh/ptk/key_bindings.py, xonsh/ptk/shell.py
Should address #1556, @OJFord @laerus  would you mind trying this out?
=> EOF fix for prompt-toolkit.

.gitignore, release.xsh
This is an attempt to add conda-forge to the release script.  It also tries to generalize the release script to make it more portable to other projects.
=> Conda(-forge) updates to release script

news/no-bad-shell.rst, xonsh/shell.py
=> Disable SHELL_TYPE=none from the environment

release.xsh
This makes it a little easier to move the release script around.  I might be worth thinking about breaking this out as its own project(?)
=> some more release abstractions

MANIFEST.in
=> ship tests to pypi for downstream folks

CHANGELOG.rst, scripts/xonsh.bat
Uses the trick from http://stackoverflow.com/a/18982410/90297
Fixes #1395.
=> Use pylauncher on Windows when available

CONTRIBUTING.rst, docs/add_to_shell.rst, docs/linux.rst, docs/osx.rst, docs/tutorial.rst
=> change codeblock format from bash to console

news/multiline_string.rst, xonsh/base_shell.py, xonsh/ptk/key_bindings.py
I believe this should fix #1558 by allowing multi-line strings to have more than one line break consecutively.
=> Multiline Strings in Interactive Mode

.travis.yml
maybe it's that simple? can't find a way to test this when no report already on master.
=> coverage report fix

news/funcargs.rst, tests/test_ast.py, tests/test_parser.py, tests/tools.py, xonsh/ast.py
This should fix #1575, if you want to take if for a spin @laerus
=> Added function arguments to scope

news/netbsd.rst, xonsh/aliases.py, xonsh/platform.py
@krytarowski can you try this out please?
=> NetBSD support

news/emptysh.rst, xonsh/foreign_shells.py
=> Foreign shell function empty filename fix

news/syncp.rst, setup.py, xonsh/parsers/base.py
This should address some of this issues in #1521 with package creation.
=> yacc_debug loads parser on same thread.

xonsh/readline_shell.py
https://github.com/xonsh/xonsh/issues/1170#issuecomment-240922451
=> improved #1170 warning message "no readline"

news/foreign-aliases.rst, xonsh/foreign_shells.py
that match xonsh bultin aliases
#1612 #1155
=> ignore foreign aliases

news/fix-bash-completions.rst, xonsh/completer.py, xonsh/completers/bash.py, xonsh/environ.py, xonsh/platform.py
=> New implementation of bash completer

docs/linux.rst
This commit explains how to fix the problem described in #912
Closes #912
=> Add information about utf8 support on linux

news/expandvar.rst, tests/test_parser.py, xonsh/parsers/base.py
This should fix #1615.  It also makes the parser a bit simpler.
=> more expand vars

.circle.yml, .circle_miniconda.sh, .travis.yml, circle.yml
Travis still has python nightly (not on circle ci) and the mac builds
Part of this is seeing how travis and circleci get along
=> [WIP] Use Circle CI for py3.4 and py3.5

news/module-file-attr.rst, tests/test_imphooks.py, xonsh/imphooks.py
=> xonsh module __file__ attribute

tests/conftest.py, tests/test_dirstack.py, xonsh/dirstack.py
Fire an event when the current directory changes for any reason.
=> Add `on_chdir` Event

tests/test_events.py, xonsh/events.py
pytest magic was adding an extra event on my system. @astronouth7303, mind taking a look.
=> Hot fix for pytest events

docs/linux.rst, news/linux-guide.rst
add installation sections for Fedora and Debian/Ubuntu
=> linux guide update

tests/test_vox.py, xontrib/voxapi.py
Adds four venv-related events.
Also improves the vox documentation.
=> Add events to Vox

tests/test_parser.py, xonsh/parsers/base.py
Thanks to @laerus for pointing out that I had totally forgotten about these :)
=> Nested subporcess macros

xonsh/completers/bash.py
@scopatz  So sorry... spoke too soon... one more fix following #1637
=> fix completion of paths starting with '~'

tests/test_parser.py, xonsh/commands_cache.py
=> Stop nightly timeouts

news/cd_single_char.rst, tests/test_dirstack_unc.py, xonsh/commands_cache.py, xonsh/dirstack.py
My fault, here's a fix for #1667, sorry @astronouth7303.
=> fix for #1667, cd <singleCharacter> fails

news/test-news.rst, tests/test_news.py
=> better news testing

news/highlight-cmd.rst, xonsh/pyghooks.py
=> Highlight valid command

tests/test_run_subproc.py
was staring at `run_subproc` for so long.
here are some tests, wanted to write a lot more and i can still can if you want me to @scopatz 
and these probably would be better with `tmpdir` fixture.
=> it's time then

xonsh/completers/bash.py
=> fix bash completion for bash-completer v1.x

news/tildeassign.rst, tests/test_builtins.py, xonsh/built_ins.py
=> Fixed tilde expansion

news/nm.rst, xonsh/parsers/base.py
=> Nested subprocess macro fix

news/fortarg.rst, tests/test_ast.py, xonsh/ast.py
=> Fixed issue with accidentally wrapping generators in function calls

.travis.yml, docs/conf.py
The first commit test should fail see cause of #1695.
If it fails with the same cause I'll push a second commit that fix the build.
=> Build docs on travis

news/split_completion.rst, xonsh/completers/base.py, xonsh/completers/python.py
A couple of fixes for better completion support.  Should address #1708 
@laerus, want to take this for a spin?
=> Completer prefix splitting

xonsh/completers/path.py
potential fix for #1691 
@astronouth7303 -- not sure if path completion will *work* but I think this will stop the infinite recursion
=> remember windows when checking for abs paths

docs/tutorial.rst, news/foreign-aliases.rst, xonsh/environ.py, xonsh/foreign_shells.py
=> control overriding of foreign aliases

news/complete-after-pipe.rst, xonsh/completers/commands.py
=> Completes commands after pipe

xonsh/xontribs.json
adds a powerline xontrib and fix a typo on the json
=> Add xontrib powerline

xonsh/base_shell.py
=> fix base_shell._fix_cwd

news/completions.rst, xonsh/completers/path.py
=> auto quote completion paths that contain 'and', 'or'

tests/test_path_completers.py, xonsh/completers/path.py
This must ghave been a recent regression, so I didn't add a news entry.  Closes #1763
=> new path completer fix and tests

news/srcnl.rst, xonsh/aliases.py
This should address #1517, for real.
=> Source alias newline fix

README.rst
=> Add circle-ci build status badge to readme

docs/aliases.rst, news/bang-aliases.rst, xonsh/aliases.py
=> remove bang aliases

news/prompt-formatter.rst, xonsh/prompt/base.py
=> stringify values that come from FORMATTER_DICT envvar

news/vc_branch.rst, xonsh/prompt/vc_branch.py
=> using --porcelain to find out if git directory dirty

news/aliases.rst, tests/test_xonsh.xsh, xonsh/aliases.py
Add 'echo' to list of aliases defined for Windows only.
Fixes these test failures on current master.  
```
$ py.test tests\test_xonsh.xsh
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: n:\DevWork\work\xonsh, inifile: setup.cfg
plugins: xonsh-0.4.6
collected 3 items
tests\test_xonsh.xsh ..F
================================== FAILURES ===================================
________________________ xonsh test: test_xonsh_party _________________________
xonsh execution failed
File "n:\DevWork\work\xonsh\tests\test_xonsh.xsh", line 17, in test_xonsh_party
out = $(echo @(x + ' ' + y))
File "n:\devwork\work\xonsh\xonsh\built_ins.py", line 642, in subproc_captured_stdout
return …
```
=> fix test failures due to absense of builtin 'echo' on Windows

news/vc_branch.rst, xonsh/prompt/vc_branch.py, xonsh/tools.py
=> prompt git branch

news/pep8_cleanup.rst, setup.cfg, tests/conftest.py, tests/tools.py, xonsh/aliases.py, xonsh/base_shell.py, xonsh/built_ins.py, xonsh/commands_cache.py, xonsh/completers/base.py, xonsh/dirstack.py, xonsh/environ.py, xonsh/parsers/v36.py, xonsh/platform.py, xonsh/proc.py, xonsh/prompt/base.py, xonsh/prompt/gitstatus.py, xonsh/prompt/vc_branch.py, xonsh/ptk/key_bindings.py, xonsh/ptk/shell.py, xonsh/pyghooks.py, xonsh/tokenize.py
As promised, this fixes all the existing PEP8 violations that we missed since we aren't reporting the results of flake8 in CI.  
This is built on top of #1810 so it shouldn't be merged until that's sorted.
=> More cleanup refactor

news/git_branch.rst, xonsh/prompt/vc_branch.py
=> Fix getting git branch name when status.short = true

.gitignore, news/rediralias.rst, tests/test_integrations.py, xonsh/proc.py
This addresses part of #1827 and builds on top of #1840 (for the test suite).
=> System exit fixes.

news/bfchk.rst, xonsh/base_shell.py
This should address #1838.  @derekbrokeit would you mind trying this out, please? Thanks!
=> Robustness fixes to tee

news/bfchk.rst, xonsh/proc.py
@melund, can you try this out, please? Thanks!
=> Buffer in pipeline

news/rediralias.rst, xonsh/proc.py
Should address the remaining parts of #1836
=> Safely flush thread on buffer

news/sa.rst, tests/test_integrations.py, xonsh/proc.py
This should address #1828.  @melund, would you mind taking it for a spin, please? Thanks!
=> fix for streaming aliases

news/not_backgroundable.rst, xonsh/commands_cache.py
This builds on #1845 and should really help with performance for common commands. @laerus, you might be most affected by some of these, so would you mind trying it out?
=> No background certain commands

news/not_backgroundable.rst, xonsh/commands_cache.py
And also cls.  @melund, would you mind seeing if this helps out #1830, please? Thanks!
=> added clear to foreground, since it is not really needed

news/moresafereadble.rst, xonsh/proc.py
@laerus from https://gitter.im/xonsh/xonsh?at=58022358457ae29b71e0506d
=> make safe readble even more safe

news/flake_fix.rst, xonsh/proc.py, xonsh/xontribs.py, xonsh/xoreutils/which.py
Quick fixes for the remaining flake8 issues on master
=> small pep8 fixes so circle stops failing

docs/tutorial.rst, news/tutorial-quoting.rst
=> tutorial quoting section

news/history-help.rst, xonsh/history.py
an itch, also kinda brought up on gitter lately
=> better history help messages

news/test_cleanup.rst, tests/test_base_shell.py, tests/test_lazyjson.py, tests/test_man.py, tests/test_parser.py, tests/test_tools.py, tests/test_xoreutils.py
I know I should never look at landscape.
But, in this case, maybe not so bad.  Fixed some "code smells", but there were a number of straight up duplicated tests which could cause problems down the line if we needed to change something.
=> Test cleanup

news/rs.rst, xonsh/proc.py
=> Parallel delay

news/scp_predict_false.rst, xonsh/commands_cache.py
=> Scp predict false

news/bash-completion-defaults.rst, xonsh/completers/bash.py, xonsh/environ.py, xonsh/platform.py
=> Proper default value and documentation for $BASH_COMPLETIONS

news/rs.rst, tests/bin/cat, tests/bin/cat.bat, tests/bin/wc, tests/bin/wc.bat, tests/test_integrations.py, xonsh/proc.py
This is in an effort to fix #1885. I am not super pleased with the algorithm I wrote here, but I can't think of a better way (after hours of staring at it tonight) and it does seem to work.
=> Pipe fixes(?)

news/fix-readline-completer.rst, xonsh/readline_shell.py
=> fix #1886 - readline completer with space

docs/customization.rst, news/faq_updates.rst
to sort of "resolve" #1725 
no news entry because it's just a docs update
=> add various updates to customization faq

news/rs.rst, tests/test_integrations.py, xonsh/proc.py
Again, this took me way too long.  I shouldn't have tried to refactor the algorithm :)
=> more piping fixes for multiple commands

news/not_backgroundable.rst, xonsh/commands_cache.py
=> add mutt to unthreadables

xonsh/proc.py
duplicated immediately above -- no news entry
=> remove copypasta docstring fragment

news/fix_spspec_repr.rst, xonsh/built_ins.py
Quick fix for an annoyance I ran into while trying to debug some alias stuff
=> Fix SubprocSpec repr

xonsh/completers/pip.py
worst offender in landscape.. mostly just disabled pylint errors
=> heal completers pip

docs/tutorial.rst, news/uncap.rst, xonsh/built_ins.py, xonsh/proc.py
=> Uncaptured aliases

xonsh/pyghooks.py
I realized that I swapped the background colors for PTK completions. 
This doesn't need a news item as it is just a fix to a previous PR.
=> Fix swapped background colors on PTK completions.

xonsh/lazyasd.py
=> lazyasd: Fix typo in docstring

xonsh/lazyasd.py
Turns out xonsh wasn't even at the latest laziness. Fitting(?)
=> lazyasd update from repo

docs/_static/console_colors.reg
This an update to the registry file for setting nicer console colors on windows. 
It is an update to previous unreleased PR, so it doesn't need a news item.
=> Update win color registry file

news/quotes-paths.rst, xonsh/completers/path.py
Trying address #1397. May not be the right way, but open it here for discussions.
=> Make readline completes to max prefix

xonsh/prompt/vc_branch.py
this came out after #1936 was merged.
=> run git/hg only if we can locate binary

xonsh/proc.py
=> signal barrier

xonsh/diff_history.py, xonsh/history.py, xonsh/proc.py
=> safe flush

xonsh/base_shell.py
This should fix #1975. Does not need a news entry
=> set code consistently

xonsh/prompt/vc.py
Spotted this typo while creating #1978 .
=> Fix spell typo

xonsh/proc.py
No news entry needed, should fix #1973
=> robustness for none proc

news/not_backgroundable.rst, xonsh/commands_cache.py
=> unthreadable psql 

xonsh/completers/bash.py
=> added unicode decode error

docs/index.rst, setup.py
=> Python-powered, cross-platform, Unix-gazing shell

docs/tutorial.rst, news/fix-input-output-docs.rst
Fixes https://github.com/xonsh/xonsh/issues/1863
Let me if I need to add anything!
=> Tutorial: Add note about redirection

news/history-show-all-fix.rst, tests/test_history.py, xonsh/history/json.py, xonsh/history/main.py, xonsh/history/sqlite.py
fixes #1909 - `history show all` should contain current session items.
=> History show all contains session items

news/xonsh-failback.rst, tests/test_main.py, xonsh/main.py
=> Make xonsh able to failback to other shells

news/ltok.rst, xonsh/completers/python.py
=> token bug fix

.travis.yml
hoping this fixes the test failures on master re: doc deployment
Unless folks have objections to use being used as a guinea-pig and then we can wait and push out a new doctr release first.
=> try latest version of doctr master

news/sig.rst, xonsh/proc.py
This should allow signals to be reported properly, again.  Mea culpa.
=> fixed segfault regression

docs/customization.rst
=> Add colored man page how to

news/failover-script.rst, tests/scripts/raise.xsh, tests/test_main.py, tests/tools.py, xonsh/main.py
=> xonsh script.xsh should not fail over

.appveyor.yml, .circle.yml, .travis.yml
Seems to be some oddities with Appveyor, though. Help?
Internal. No news.
=> Add Python 3.6 to Continuous Integration

docs/tutorial.rst, news/to2.rst, tests/test_integrations.py, tests/test_parser.py, xonsh/built_ins.py, xonsh/tokenize.py
This is waaaaay overdue and meant to address #323. Really not so bad after the infamous subprocess refactor.
=> Allow stdout to redirect to stderr

news/source.rst, tests/tools.py, xonsh/aliases.py
Some small additions I saw when trying to port conda de/activate to xonsh
=> source alias improvements

news/z.rst, xonsh/jobs.py, xonsh/proc.py
I am not sure that this fixes all use cases, but it does address the vi one for me on Linux.
=> ^Z and fg Fixes

news/querycomp.rst, xonsh/environ.py, xonsh/readline_shell.py, xonsh/tools.py
=> Query Completions 

docs/osx.rst
Info on PR is at https://github.com/xonsh/xonsh/issues/2111
=> Change OSX Installation instructions to use bash-completion2

news/telnet.rst, xonsh/commands_cache.py
Nothing to write home about. See #2102
=> added telnet to unthreadable predictors

news/intrpt.rst, xonsh/proc.py
=> PopenThread SIGINT fix

news/gvim.rst, xonsh/commands_cache.py
=> added gvim to unthreadable predictors

news/jk.rst, tests/test_mpl.py, xonsh/jupyter_kernel.py
I think we were redirecting too much. See #2099.
=> potential fix for jupyter

.circle.yml, .coveragerc, README.rst, codecov.yml
=> adding code coverage back

news/event-envvar.rst, tests/test_environ.py, xonsh/environ.py
fired after an envvar has changed
@astronouth7303 ping!
=> Event on_envvar

news/rllen.rst, xonsh/readline_shell.py
Should address #2141. CC @melund
=> Readline len

news/win_bash_completion.rst, xonsh/platform.py
This fixes the problem I had with bash completion on windows because 'Windows Subsystem for Linux' was installed. 
Fixes #2140
=> Fix bash completions on Windows when WSL is installed

xonsh/proc.py
A one-liner, not sure how it crept in.
=> fixes a sigint recursion issue

news/argcomp.rst, tests/test_python_completers.py, tests/test_tools.py, xonsh/completers/python.py, xonsh/tools.py
This adds the ability for Python function argument names to be completed. This is instead of having jedi completions. See #2127 for more discussion.
=> Argument completion

news/parencomp.rst, xonsh/completer.py, xonsh/readline_shell.py
This addresses #2126 for me.  @laerus, maybe you want to take a look?
=> Paren Completions in Readline

xonsh/built_ins.py
Just found a missing parameter. new news item is needed.
=> added a missing param

news/xonsh-script-fix.rst, xonsh/built_ins.py
=> fix tcsetattr: Interrupted system call

news/valerrargcomp.rst, xonsh/completers/python.py
This should address #2173 CC @gforsyth
=> ValueError in completer fix

news/ppunth.rst, setup.cfg, tests/test_integrations.py, xonsh/proc.py
=> proc proxy aliases

.travis.yml, news/file.rst, tests/bin/printfile.xsh, tests/bin/printname.xsh, tests/bin/sourcefile.xsh, tests/test_integrations.py, tests/test_tools.py, tests/tools.py, xonsh/aliases.py, xonsh/codecache.py, xonsh/main.py, xonsh/tools.py
=> Added __file__ and __name__ to xonsh scripts

docs/index.rst, docs/tutorial_ptk.rst
I could probably add a little more on filters and a few more examples, but this is ready for a glance.
=> Tutorial: Custom keybinding in PTK

news/term-fd.rst, xonsh/jobs.py, xonsh/platform.py
=> Fixes OSError Inappropriate ioctl for device

news/give-term-to-none.rst, xonsh/jobs.py
=> fixes OSError: [Errno 22] Invalid argument

news/ghost-in-the-sh.rst, xonsh/ptk/completer.py, xonsh/ptk/shell.py
This is attempt to solve the long running completion-based-off-of-autosuggestion issue from #981. Now, if `$AUTO_SUGGEST`  is enabled, the first completion will always be the current token of the autosugestion.
=> Complete based on autosuggestion

news/ptkvt.rst, xonsh/ptk/shell.py
=> Enabled virtual terminal processing for the prompt toolkit shell

news/no-thread-nvim.rst, xonsh/commands_cache.py
=> flag nvim as unthreadable

news/delparen.rst, tests/test_parser.py, xonsh/parsers/base.py
Should address #1234, but not #5678
=> Fixed del (x, y)

xonsh/readline_shell.py
=> more windows readline issues

news/extargs.rst, xonsh/foreign_shells.py
This should address the issue in #1293.
=> Added extra_args to foreign shell aliases

news/rediral.rst, xonsh/built_ins.py
This should address #1262. Basically a two-line change.
=> Enable alias redirections

news/generator_at.rst, news/rediral.rst, tests/test_parser.py, xonsh/built_ins.py, xonsh/parsers/base.py
I believe this addresses the issues in #2209 and #2253, or can at least serve as a starting point for continuing work.  Quick port of changes made on my fork.
```
user@machine $ echo @('hi')
hi
user@machine $ echo @(7)
7
user@machine $ echo @([7,8])
7 8
user@machine $ echo @(i**2 for i in range(7))
0 1 4 9 16 25 36
```
=> allow generators and bare tuples in @(...)

news/ic.rst, xonsh/__init__.py, xonsh/codecache.py, xonsh/platform.py
=> Invalidate code cache whenever the xonsh version changes

news/impenc.rst, xonsh/imphooks.py
=> Fixed import encodings

news/winuserexp.rst, xonsh/platform.py, xonsh/tools.py
This is meant to address #1794.
=> Added expand user function for windows

news/nsredir.rst, tests/test_lexer.py, xonsh/lexer.py
This expands the capability for redirections to not require a space. This should address the remaining issue in #1628
=> Redirection no longer require a space

xonsh/jobs.py
Handle this gracefully. No need for news since this hasn't been released yet.
=> Error 25 in give terminal to

news/ntenv.rst, xonsh/environ.py, xonsh/foreign_shells.py, xonsh/platform.py, xonsh/prompt/base.py, xonsh/pyghooks.py, xonsh/readline_shell.py, xonsh/tools.py, xonsh/xoreutils/which.py
This is meant to address #2024.
=> Use nt.environ on windows

news/ao.rst, tests/test_lexer.py, xonsh/lexer.py
This is meant to address #1921
=> Require whitespace for and/or tokens in subproc mode

news/ptkcomp.rst, xonsh/ptk/completer.py
This should address the concern in #1994
=> Fixed up ptk completer a bit

docs/api/index.rst, docs/api/jsonutils.py, news/jsonutils.rst, tests/test_jsonutils.py, xonsh/__init__.py, xonsh/jsonutils.py, xonsh/tools.py, xonsh/wizard.py
This should address the issue in #1808
=> New JSON utils module

.gitignore, tests/conftest.py
(tags in .gitignore for ctags)
no news
=> conftest xonsh_builtins teardown

news/partial.rst, xonsh/proc.py
=> Partial proxy partial friendly

xonsh/xonfig.py
=> Use terminal width when centering text on welcome screen

news/bgfg.rst, xonsh/base_shell.py, xonsh/jobs.py
This addresses the linux part of #2133 for me. Hopefully it works on the mac part too.
=> Some job control fixes

news/none-cmd-ctrl-c.rst, xonsh/jobs.py, xonsh/proc.py
=> fix ctrl-c issue after an invalid cmd

news/openssh_bash_win.rst, xonsh/completers/bash_completion.py, xonsh/platform.py
Fixes #2305 
This should handle the traceback reported @sopoforic...
=> Fix bug when output of 'bash --version' is empty

news/dirstack_ensurer.rst, xonsh/environ.py
should hopefully address #2311
=> add default ensurer for DIRSTACK_SIZE

docs/windows.rst
This updates the windows tutorial with info on the `free_cwd` xontrib, and some fixes to color section.
=> Update win tutorial

news/custom_rc.rst, tests/test_main.py, xonsh/main.py
Quick fix for #2356 
I guess we just forgot to actually implement it?
=> fix `--rc` option for xonsh startup

requirements-docs.txt
No news item -- this is a temporary workaround until the fix in Sphinx master is released
=> Pin sphinx to 1.5.6 to avoid bug in 1.6.1

news/issue-448-add-xonsh_append_newline-var.rst, xonsh/base_shell.py, xonsh/environ.py
=> Add $APPEND_IF_NO_NEWLINE environment variable

news/xontribs.rst, xonsh/xontribs.json
=> Add xontrib-schedule

news/tq.rst, tests/test_tools.py, xonsh/tools.py
=> fixed triple quote issue when open triple quotes are on the last line

news/barestarz.rst, tests/test_parser.py, xonsh/parsers/base.py
=> x, y, *z unpacking

news/srcwrn.rst, xonsh/aliases.py
=> source warnings

news/epadd.rst, tests/test_tools.py, xonsh/tools.py
=> EnvPath __add__() and __radd__() methods

news/asic.rst, xonsh/environ.py, xonsh/ptk/completer.py
=> autosuggest in completions

xonsh/aliases.py
mea culpa. This does not need a news item since it fixes a bug introduced since the last release.
=> stupid file extension logic error

docs/tutorial.rst
added keywords so http://xon.sh/tutorial.html#executing-commands-and-scripts is more searchable due to https://github.com/xonsh/xonsh/issues/2505.
=> tutorial.rst command line arguments / parameters

news/improved_autopair.rst, xonsh/ptk/key_bindings.py
Implements improvements suggested in #2520
=> Improvements to 'autopair' behavior

news/openparen.rst, xonsh/completers/python.py
=> updated python completer to allow for initial open paren

news/hiscor.rst, xonsh/history/json.py
=> fixed JSON history corruption

news/semieat.rst, tests/test_execer.py, tests/test_tools.py, xonsh/ast.py, xonsh/execer.py, xonsh/tools.py
=> fix for eating semicolons

news/emacsclient.rst, xonsh/commands_cache.py
=> emacslient no longer threadable

xontrib/vox.py
=> Fix vox activate

news/moveback.rst, xonsh/pyghooks.py
This is probably partially responsible for some of the slowdowns
=> this never should have been moved

news/2543-lines-columns.rst, tests/test_environ.py, xonsh/environ.py
=> Remove lines/columns from the default environment
