news/fast_hg_branch.rst, xonsh/prompt/vc.py
This needs more work, but I wanted folks to take a look at it (ping @ngoldbaum @laerus) to make sure I'm not missing any `hg` specific issues. 
Also, the usage of `$VC_BRANCH_TIMEOUT` will probably have to change (or be removed entirely)
Preliminary checks on my machine show something like a 1000x speed increase, which ain't too bad.
```
In [1]: import subprocess
In [2]: from xonsh.prompt.vc import _get_hg_root
In [3]: import queue
In [4]: pwd
Out[4]: '/home/gil/git/pygments-main/pygments/styles'
In [5]: subprocess.check_output(['hg', 'root'])
Out[5]: b'/home/gil/git/pygments-main\n'
In [6]: %timeit subprocess.check_output(['hg', 'root'])
10 loops, best of 3: 80.4 ms per loop
In [7]: q = queue.Queue()
In [8]: _get_hg_root(q)
...: q.get_nowait()
...: 
Out[8]: '/home/gil/git/pygments-main' …
```
=> Fast hg branch

news/rlwiz.rst, xonsh/shell.py, xonsh/xonfig.py
This is an attempt to address #956. It turns out there is an underlying issue with readline that eats Ctrl+C in Python (see https://bugs.python.org/issue24266).  Unfortunately, the fix - which has already been merged in - is only applicable to readline v7, which most people are not on yet. 
So as a usability fix, the wizard now prints the correct command to exit. This depends on the shell backend.
Additionally, the fixes another minor issue with the shell type not being set correctly on the shell class.
=> Readline wizard usability fixes

news/fix_pwd.rst, xonsh/base_shell.py, xonsh/dirstack.py
Add the ``RESOLVE_SYMLINKS`` environment variable to control whether the change directory function should follow symlinks or not.
Close #1741
=> Fix how `$PWD` is managed in order to work with symlinks gracefully

xonsh/base_shell.py
Before 72d04e (#2235), the `_fix_cwd` function was having a side effect to reset the `$PWD` environment variable if it was deleted. As #2235 changed this behviour in order to handle symlinks, this implicit side effect is gone.
This commit reintroduce the reset of the `$PWD` environment variable from `_fix_cwd`, but explicitely so it wont be missed again :-)
«Explicit is better than implicit.» [Tim Peters]
Close #2236
=> Fix the regression introduced by #2235 concerning the `$PWD` change

xonsh/aliases.py
It causes an exception when `source-bash foo/bin/activate` to activate python virtual environment in my terminal (Mac OS X 10.11.2).
The content of the exception is here.
```python
AttributeError: 'Namespace' object has no attribute 'overwite_aliases'
```
It seems this value `overwite` is not used in other place (I grepped this), so I changed.
I don't write test for this. but `source-bash` does work well to me.
=> Revised spell miss (overwite -> overwrite)

news/argp.rst, xonsh/ptk/shell.py, xonsh/readline_shell.py
This PR catches SystemExits, like KeyboardInterrupts. This should address #1235
=> Catch system exits

news/win_line_cont.rst, xonsh/base_shell.py, xonsh/ptk/key_bindings.py, xonsh/tools.py
Ensure that line continuations are preceded by a space in interactive mode on windows. This ensures that we can handle subproc commands like: `cd Users\Documents\` or other commands that ends with windows paths.
This only applies to interactive mode to ensure that xonsh scripts are still somewhat portable. 
Fixes #2213 and #2243
=> Fix line continuations on windows

news/q.rst, tests/test_parser.py, tests/test_tools.py, xonsh/parsers/base.py, xonsh/tools.py
This PR contains a number of fixes for wrapping subprocesses that happen to have partially open triple quotes. This is in an attempt to fix #1152.
=> Wrapping Triple Quotes for Subprocs

news/ji.rst, xonsh/jobs.py
This PR only prints job info when in interactive mode when preforming backgrounding and foregrounding tasks.  The `jobs` command will always display, of course. This addresses part of what is in #1174.
=> print jobs when interactive

news/unthreadsig.rst, xonsh/xontribs.py
This enables signals to be used inside of xontribs on load. Should address #1481
=> Unthreadable xontrib command

news/zsh.rst, xonsh/aliases.py, xonsh/foreign_shells.py
This is an attempt to address #1134, which fixes some of the foreign shell issues with zsh v5.2.
=> zsh v5.2 fixes

news/nullsub.rst, xonsh/built_ins.py
This prevents the error listed in #1771.
=> Escape null bytes before Popen

news/delcwd.rst, xonsh/base_shell.py, xonsh/prompt/vc.py, xonsh/pyghooks.py
This is meant to address #1744. The example expression I was using to test this is:
```console
$ rm -rf ~/x; mkdir ~/x; cd ~/x; rm -r ~/x
```
=> No longer crash when PWD is removed

news/fix_history_replay.rst, xonsh/tools.py
Attempt to fix #2264 which only rears its head during history replay (on
linux).
=> only remove attribute if it exists

news/oserr.rst, xonsh/history/json.py
This is meant to prevent the kind of issue seen in #2122
=> Defense against collecting history files

news/foreign_shells_names.rst, xonsh/foreign_shells.py
Closes #2282. This should handle the case where foreign shell names are not written i lower case in config.json
=> Ensure shell names are lower case

news/os_env.rst, xonsh/platform.py
fixes #2297 
This PR wraps `os.environ` with a case-preserving case-insensitive class on Windows.
=> Make os_environ case-preserving and case-insensitive on Windows

news/scandir_bug.rst, tests/test_prompt.py, xonsh/prompt/vc.py
Fixes #2294. `os.scandir()` is not supported on py34, so we should use our internal version instead.
=> Never use os.scandir

news/recall_last_arg.rst, xontrib/bashisms.py
As requested in #1480 this adds the `Alt .` shortcut to insert the last argument from the previous command into the current prompt buffer at cursor position.
=> add Alt-. cmd to recall last arg to bashisms

news/pretty_path.rst, xonsh/tools.py
Fixes #2321 
This will pretty print $PATH
```python
EnvPath(
['C:\\Users\\mel\\Anaconda3\\Library\\bin',
'C:\\Program Files\\ImageMagick-7.0.4-Q16',
'C:\\Program Files\\Docker\\Docker\\Resources\\bin',
<snip>
'C:\\Users\\mel\\AppData\\Local\\Microsoft\\WindowsApps',
'C:\\Program Files\\CMake\\bin',
'']
)
```
=> Pretty path

.travis.yml
doctr now requires the deploy directory as an argument and ``--gh-pages-docs``
is deprecated.
No news item on this since it's purely internal.
=> fix for small changes to doctr API

news/sudo.rst, xonsh/aliases.py, xonsh/winutils.py
Ideally, we'd move this to a `xontrib` but at least this patch makes it unbroken.
=> Make sudo on Windows work again

xonsh/xontribs.json
xontribs should be installed with xip now, so recommend that for the xontribs I'm responsible for.
This is mostly to try to improve on #2318.
(No news required.)
=> Recommend `xip` to install my xontribs

news/win_path.rst, xonsh/environ.py
Fixes #2320 (Hopefully)
It ensures that if the `Path` variable from windows is renamed to `PATH`.
=> Fix win paths

codecov.yml, news/codecov.rst
so we don't get so many failing builds.
=> codecov raised threshold at 5%

news/linecont.rst, xonsh/base_shell.py, xonsh/ptk/key_bindings.py, xonsh/tools.py
I encountered a problem with line continuations not working as expected on Windows. 
Since `$XONSH_INTERACTIVE` changes state during startup, the [`LINE_CONTINUATION`](https://github.com/xonsh/xonsh/blob/c9f1ea7a4f8f8f5b01e25bb017fe73cac28f7aa4/xonsh/tools.py#L408) string can't be a Lazy object. If `LINE_CONTINUATION` was instantiated during startup it becomes the non-interactive version, and stay that way.
This PR makes line continuation a normal function again.
=> Line continuations not always working on Win

news/fix_at_dollar.rst, tests/test_integrations.py, xonsh/built_ins.py
This was borking out when using `@$` with aliased commands (due, I think, to a
trailing newline character that wasn't being stripped out).
Should resolve #2340
Testing this is tricky since it touches a lot of the xonsh internals...
=> Fix at dollar

news/add_fzf_widgets_extension.rst, xonsh/xontribs.json
I'm trying to port some of useful [fzf](https://github.com/junegunn/fzf) widgets developed for Bash/ZSH to Xonsh And thought that it might be a good idea to share it with the Xonsh community as a Xontrib.
=> Add xontrib-fzf-widgets

news/autorelease.rst, release.xsh
Should close out #1793 
No unit tests (:tada:) but I have tried it out on a test repo and it seems to work. We'll know if it's borked when we do the next release.
=> Use github3.py to do github release in release.xsh

news/xonfig-output.rst, xonsh/xonfig.py
Before this change:
```
nhoad@nhoad-laptop ~ $ xonfig | grep linux
| on linux         | <xonsh.lazyasd.LazyBool object at 0x7f869e059e10> |
```
After this change:
```
nhoad@nhoad-laptop ~ $ xonfig | grep linux
| on linux         | True                 |
```
=> Don't show the repr of the LazyBool for whether or not xonsh is running on Linux.

tests/tools.py
tests Heizenbug
```
Error in atexit._run_exitfuncs:
File "/Users/travis/build/xonsh/xonsh/xonsh/built_ins.py", line 1201, in _lastflush
builtins.__xonsh_history__.flush(at_exit=True)
AttributeError: 'DummyHistory' object has no attribute 'flush'
```
no news
=> Add flush method to tests/tools::DummyHistory

news/gitstatus-fix-leftover-index-lock.rst, xonsh/prompt/gitstatus.py
Instead, ask it nicely to terminate using SIGTERM.
=> gistatus: Don't SIGKILL git to avoid leftover .git/index.lock.

news/compute-prompt-after-event.rst, xonsh/ptk/shell.py
Under PTK, any changes made to `$PROMPT` in an `on_pre_prompt` handler take effect with a one-prompt delay.
This moves when `on_pre_prompt` is fired to before any prompt calculations are made.
The readline shell already behaved this way (all of its logic being in `.prompt`). The base shell doesn't raise the event at all.
=> Fire on_pre_prompt before any prompt calculations are done.

news/alias-command.rst, xontrib/bashisms.py
I thought this might be useful for others as a means to minimise typing, e.g. `alias foo="echo hey"` instead of `aliases['foo'] = ['echo', 'hey']`. I find myself creating aliases a lot, so this is something I find pretty useful.
=> Implement an alias alias, matching what sh's alias does.

news/ipython_not_threadable.rst, xonsh/commands_cache.py
`IPython` is considered as threadable by the default predictor, and strange behavior occur when the terminal is resized, in particular when `IPython` is using `ptk`.
=> Ipython threadable

xonsh/commands_cache.py
See #2438. Use `predict_shell` instead of `predict_help_ver`. Sorry for this mistake on my last commit.
I didn't add new item in changes, I think it is not necessary.
=> ipython not threadable: predict_shell should be used

docs/aliases.rst, docs/tutorial_xontrib.rst, news/TEMPLATE.rst, xonsh/aliases.py, xonsh/completers/init.py, xonsh/readline_shell.py, xonsh/xontribs.json, xonsh/xontribs.py
Try to use `xip` instead of `pip` in places where it should be used.
There is a known conflict with the name `xip`, though. Mac has an archival program [xip](https://en.wikipedia.org/wiki/.XIP).
Considering renaming `xip` to `xpip`.
=> Substitute xip for pip in places it should be used.

news/win_escape.rst, tests/test_tools.py, xonsh/tools.py
@santagada Can you try "source-cmd" that failed for you with this fix?
=> Fixed `escape_windows_cmd_string` not handling ^ correctly

news/predictor_libgpm.rst, tests/test_commands_cache.py, xonsh/commands_cache.py
When ``gpm`` is used, we can assume the command is not backgroundable. I had the problem with ``links``, but I had a look on why the predictor with binary analysis fails. Adding in the exception list is not a general fix, so I prefer fix the predictor.
=> Adding `libgpm` in pattern used for bin analysis in default backgroundable predictors

news/numeric_underscores.rst, tests/test_lexer.py, tests/test_parser.py, xonsh/parsers/base.py, xonsh/tokenize.py
This adds support for PEP-515 (underscores in numeric literals). Support
is added unconditionally on underlying python version by patching the
tokenizer with the regexes used in cpython 3.6, then modifying the
parser to unconditionally remove underscores before evaluating numeric
literals, which avoids needing to check for the underlying version.
=> PEP-515 Support (Underscores in Numeric Literals)

news/add_fstrings_to_check_quotes.rst, tests/test_tools.py, xonsh/tools.py
This allows using f-strings inside @() when command not explicitly enclosed inside ![]
=> Allow f-strings in check_quotes

news/no_rc_for_scripts.rst, tests/test_main.py, xonsh/main.py
As per discussions with @asmeurer -- if xonsh is being used to launch a script,
e.g.
```
xonsh run_my_cool_deploy.xsh
```
then it should not load the `xonshrc` file since this should be reserved for
interactive functionality and we don't want side effects in the script.
Basically, if you need a xontrib to be loaded for your script, load it in your
script
=> Don't load xonshrc is xonsh is running a script

news/escape_regex.rst, tests/test_path_completers.py, xonsh/completers/path.py
Fix for #2534 
We append a `*` to the prefix before trying path globbing and for prefixes with `[]` that was throwing errors. There's a `glob.escape` to fix that.
=> Escape regex in path completion

news/free_cwd_only_on_win.rst, xonsh/xontribs.json, xontrib/free_cwd.py
This fixes the problem reported by @paulschellin in #2548 
It ensures that ``free_cwd`` xontrib can only be active on windows.
=> Free cwd on win

news/synstar.rst, tests/test_parser.py, xonsh/parsers/base.py
Should close #2547.  The parser was being too loose. This was trickier to fix than expected because of how PLY special cases SyntaxError: http://www.dabeaz.com/ply/ply.html#ply_nn35
=> Fixed def spam(*): pass issue

.appveyor.yml, .appveyor_install.cmd, .appveyor_test.cmd, news/msys2.rst, tests/test_vox.py, tests/tools.py, xonsh/foreign_shells.py, xonsh/jobs.py, xonsh/platform.py, xonsh/proc.py, xonsh/prompt/base.py, xonsh/readline_shell.py, xonsh/xonfig.py, xontrib/free_cwd.py
Hey there,
while running xonsh within an MSYS2 environment on Windows 10 I encountered issues similar to #2370 and in addition short-running processes seemed to randomly suspend themselves to the jobs list. When processes freezed, they did however not consume any resources, but instead seemed to have just stopped. Since this happens nondeterministically (and after some debugging) I believe there is some race condition within MSYS2 (Cygwin) with calling `Popen.send_signal` in ` pause_call_resume` in `proc.py` which unexpectedly suspends processes.
Anyway, this pull request adds support for MSYS2 and fixes those issues (at least for me :D).
Thank you all very much for this great piece of software. Windows became finally somewhat usable with xonsh. ;)
Best regards,
Maximilian
=> add MSYS2 support and fix Cygwin support

docs/api/execer.rst
compiliation -> compilation
(See http://xon.sh/api/execer.html)
=> Fix typo in Execer page title

setup.py
The current xonsh version will break when prompt_toolkit 2.0 is released.
Set version to <2.0.0 until 2.0 compatibility has been merged.
=> Set prompt_toolkit version to <2.0.0 in requirements.

docs/tutorial_xontrib.rst, docs/xontribs.rst
Fixes #2619 
h/t to @melund for noticing
=> Remove references to static config file from xontrib docs

docs/osx.rst
Inspired by [this discussion](https://gitter.im/xonsh/xonsh?at=5ade2a2b3fe1be3704cafde0), provide users and package managers with guidance on configuring the path helper under xonsh.
I use the preferred "macOS" moniker even though "OSX" is used in other parts of the document. I'd recommend using macOS throughout the document, but avoided making that change as it's incidental to the primary goal of this contrib.
=> Document path helper on macOS.

xonsh/environ.py
Before the shell object has been fully instantiated.  Hot fix for code that hasn't been released yet, so does not need news
=> Don't print in color

docs/osx.rst
This adds documentation for bash_completion to the osx page as per #2030.
I also changed all OSX to macOS in the file as per Apple's naming conventions.
I added Macports instructions.
=> macOs bash_completion documents

docs/conf.py, docs/devguide.rst, news/docs_build_win.rst, xonsh/commands_cache.py
This updates xontrib description to leave out the installation section when the xontrib is bundled with xonsh. 
It also adds a 'Usage' section with the command to enable the xontrib. I always thought this was missing from here. 
Finally, it fixes a few issues with building the docs on Windows. 
(Disregard the change in fonts. This is from building locally).
=> Update xontrib description

news/pc.rst, setup.cfg, xonsh/__init__.py, xonsh/ansi_colors.py, xonsh/pyghooks.py, xonsh/pygments_cache.py
This adds the `pygments-cache` project (which is being developed at https://github.com/xonsh/pygments-cache) to xonsh.  The purpose of this project is to enable faster initial searches for pygments components (lexers, styles, etc).  
In xonsh, we use pygments styles in a couple of places. This PR helps reduce the startup time of the interactive modes of xonsh by using cached entries to find styles.  It is hard to get timings on this stuff, but I have estimated the reduction to be ~200 ms.
To maintain no dependencies other than Python, this project has been included in the xonsh source tree.
Let me know if you have any questions!
=> Added pygments-cache

.travis.yml, requirements-docs.txt, requirements-tests.txt
Temporary fix (that we implemented everywhere else) to prevent failures
due to the prompt_toolkit release
No news item required for this one
=> Pin `prompt_toolkit` in travis setup

news/raisesub.rst, xonsh/proc.py
even in the event of `$RAISE_SUBPROC_ERROR = True`. Should fix #2654
=> properly return terminal in interactive mode

news/cdpath_completion_fix.rst, tests/test_path_completers.py, xonsh/completers/path.py
The `path` completer runs for many commands (which is the correct
behavior) but we are adding in possible `CDPATH` completions for commands
other than `cd` which doesn't make any sense since only `cd` supports
path resolution via `CDPATH`.
This adds a naive check to only add in the `CDPATH` completions if the
current command is `cd`.
This resolves #2677 
There's a trade-off here.  It will prevent invalid path completion for non `cd` commands but will also disable path competion relative to `CDPATH` if `cd` is part of a chained command with an `and` or `or`
=> Fix `$CDPATH` completion misfire

news/remove_dup_completer.rst, xonsh/completers/init.py
`xpip` just uses the regular `pip` completer and it doesn't need its own entry
in the `__xonsh_completers__` dict.  That will just run the same checks twice
and slow down completions overall.
=> Remove duplicate `pip` completer

news/update_bash_completion.rst, xonsh/completers/bash_completion.py
Porting over from `xonsh/py-bash-completion`
Should fix the assertion errors popping up in the prompt toolkit shell
=> Update py-bash-completion with prefix length fix

news/windows_redirection.rst, tests/test_integrations.py, xonsh/proc.py
The call to os.set_handle_inheritable expects a Windows handle, but it is being passed a posix file descriptor.
fileno() returns a posix file descriptor which is a small integer. The method os.set_inheritable() does accept a posix file descriptor. The fix is to simply replace set_handle_inheritable to set_inheritable.
This PR includes an regression test that will fail without the fix described.
=> Windows redirection bug fix

news/2696-which-next-statement.rst, xonsh/xoreutils/_which.py
Fixes #2696 . The python 2.x style next statement in _which.py is replaced with a python 3.x style one.
=> convert a next() statement in _which.py to python 3.x style.

news/ptk2fallback.rst, xonsh/platform.py, xonsh/shell.py
Rather than throwing an error, added functionality for falling back to readline shell when version 2.x of prompt toolkit is installed. Please see see discussion on #2570
=> Fallback to readline when launching with prompt toolkit 2.x installed

news/bash_completion_spacetime_continuum.rst, xonsh/completers/bash_completion.py
*Note*: This PR is tracking xonsh/py-bash-completion#8 
The current behavior of this code in xonsh right now is as follows:
```
mkdir -p "this is a test"  # in otherwise empty dir to avoid multiple
matches
ls th[tab] -> ls t'this is a test/'
ls 'th[tab] -> ls 't'this is a test/'
ls "th[tab] -> no results
```
Initially the leading double-quote seemed to work in xonsh but that is
actually the bash completer failing completely and then xonsh falling
back on to the path completer which works correctly for this completion.
Wild.
If I directly import the `bash_completions` function in the same test
directory with that folder name and call it directly:
```
gil@bad_cat ~/tmp shell  bash_completions('"th', 'ls "th', 5, 6)
(set(), 0)
gil@bad_cat ~/tmp shell  bash_completions("'th", "ls 'th", 5, 6) …
```
=> Bash completion spacetime continuum

news/pr-2706-restore-augassign_ops, xonsh/tokenize.py
Following up on the comment in #2639, restore the prior expectation of AUGASSIGN_OPS on Python 3.7.
Also, I took the liberty in a separate commit to define the value once and tweak it for older Python versions. Feel free to omit that commit.
=> Restore AUGASSIGN_OPS

news/aaron-sprint-2018.rst, xonsh/aliases.py
Added an aliases to clear the pythonic variables within the xonsh shell.
=> SciPy sprint new aliases.

news/blockout.rst, xonsh/proc.py
=> CommandPipeline.output is now fully non-blocking

news/dev_quote.rst, xonsh/ptk2/key_bindings.py
`whitespace_or_bracket_before` and `whitespace_or_bracket_after` is no argument required.
https://github.com/xonsh/xonsh/issues/2719
=> entering quotation

.github/issue_template.md, .github/pull_request_template.md
Github apparently now supports multiple issue templates, which may be something we want to look at to distinguish between bug reports, feature requests and general questions.  That said, this should get us underway.
Also added a PR template requesting that contributors add a news entry.
Having said that, I don't think this particular PR requires a news entry.  
Resolves #2727
=> First crack at issue and pr template

news/fix-xonfig-styles.rst, xonsh/ptk/shell.py, xonsh/ptk2/shell.py
The "xonfig styles" command was reporting
AttributeError: module 'pygments' has no attribute 'styles'
Now we import the styles package from pygments explicitly
=> Fixed a regression with xonfig styles

news/color_win.rst, xonsh/jobs.py, xonsh/tools.py
This fixes a problem with the [`INTENSIFY_COLORS_ON_WIN` hack](http://xon.sh/envvars.html#intensify-colors-on-win), which stopped working when we add PTK2 support. 
The hack is still useful for older versions of Windows. 
But there is a nicer workaround on Win10 where PTK2 now uses ANSI escapes to give full color support. The default colour scheme in the terminal still have unreadable blue and red colors. Instead, we could create a win10 style with hard-coded colour values, and use that as the default style on Win10. I will try to look into that.
=> Fix regression for INTENSIFY_COLORS_ON_WIN due to PTK2

news/change_auto_suggest_default.rst, xonsh/environ.py
Up for debate -- I think it causes more confusion since it provides
"wrong" completions.
=> Change default for `AUTO_SUGGEST_IN_COMPLETIONS`

news/fix-default-style-dict.rst, xonsh/ptk2/shell.py
This fixes one of the failure modes raised in #2734 (starting up without Pygments present on ptk2)
The other issue is due to backwards incompatibilities in the xontribs due to the ptk shift.
=> Fix for `DEFAULT_STYLE_DICT` error on ptk2

news/fix_xontrib_ptk_ptk2.rst, xontrib/bashisms.py, xontrib/whole_word_jumping.py
This should take care of the remaining issues raised in #2734 -- all of the xontribs (that we bundle) that make use of custom keybindings should now work in both ptk1 and ptk2
=> Make ptk xontribs compatible with ptk1 and ptk2

setup.cfg
This warning has been popping up for ages, so I've finally made the
change.  Time to see what else breaks.
No news entry needed here.
=> Update pytest syntax in setup.cfg

news/null-delim-history.rst, tests/test_history.py, xonsh/history/main.py
Resolves feature request #2746 - "Add option for history builtin to output null-delimited results"
For example usage see [this commit](https://github.com/laloch/xontrib-fzf-widgets/commit/313e163767dbe80d3ecc5b36fde980113d2032e5) in my fork of xontrib-fzf-widgets.
=> history show - add optional null-delimited output

news/no_default_style.rst, xonsh/ptk2/shell.py
This fixes a problem with styles in PTK2. PTK2 (by default) merges in the default pygments style with the style we provide. 
This is not what we want since the xonsh style is already complete.
=> Do not mixin default pygment style on PTK2

news/convert_color_names.rst, xonsh/pyghooks.py, xonsh/tools.py
While reviewing @scopatz's #2761 I stumble on a bug I think I caused. 
First, the new PTK ansi-color names should also be converted back when the shell-type is 'jupyter'. This fixes a bug with the pygments and the `XonshTerminal256FormatterProxy` in the notebook.
Fixing this, it turned out there was another bug in the code causing ansi-color names to be converted multiple times. Resulting in bugs like: `wrong color format '##ansidarkblue'` 
This PR fixes both. @scopatz you should probably merge it into #2761
=> Fixed a bug when converting new ptk2 ansi-color names to old names

news/fix_readline_colors.rst, xonsh/pyghooks.py
Fixes #2773. This solves the problem with colors in the readline shell. 
Sorry, about this @scopatz, I completely missed that the readline backend also uses the ansi-colors. We better get a hotfix released soon. 
Is there any chance that our integration test could catch errors like this in the future?
=> Hotfix for colors in readline shell

news/color_py35.rst, xonsh/tools.py
Fixes #2780  The logic was clearly wrong here, and I think the reason it worked on py36 was the guaranteed ordering of dicts in Python 3.6.
=> Fix a bug with colors beeing converted to old format multiple times

docs/tutorial.rst, news/compstack.rst, tests/test_integrations.py, xonsh/built_ins.py, xonsh/completers/_aliases.py, xonsh/proc.py
This is probably one of the more nefarious hacks I have implemented in a while. Basically, it gives callable aliases a way to access the call stack of their call site. I have tried to make it so that the alias has to ask for the stack, so we aren't computing these stacks all over the place. 
Folks can probably do some fun things with this :smiling_imp: 
This fixes #2779
=> Callable alias stack - with completer fix

news/ptk2_pygments_formatter.rst, setup.cfg, xonsh/platform.py, xonsh/pyghooks.py, xonsh/tools.py
Fixes #2778 (hopefully)
The fix ads a patch to pygments's terminal formatter. To make it work with PTK2 color names, which we now use in xonsh. 
I know this is a hack. But I couldn't come up with something better. And this should temporary until the next release of pygments which will hopefully include our color name fix: 
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/777/change-ansi-color-names-to-more-saying/diff
=> Pygments codes

news/fix_Env_swap.rst, tests/test_environ.py, xonsh/environ.py
Code executed under `with ${...}.swap()` might throw an exception in which case the swapped values will not be restored. This pull request fixes this bug. Here is a minimal test case which demonstrates the bug:
$VAR='original value'
try:
with ${...}.swap(VAR='inner value'):
echo $VAR
raise Exception() 
except:
print('hi')
echo $VAR
echo $VAR
This produces the following output:
inner value
hi
inner value
inner value
Note: test_integration.py fails on both this branch and master with the exact same error message.
=> Fix env swap

news/cache-by-realpath.rst, xonsh/codecache.py
Cache scripts by realpath, resolving symlinks,
as per discussion in #2776.
I chose realpath(...) over abspath(realpath(...)),
as realpath does call abspath internally.
=> cache scripts by realpath

news/history_match_anywhere.rst, xonsh/environ.py, xonsh/ptk2/history.py, xonsh/ptk2/shell.py
Default behavior of prompt_toolkit on an up-arrow history search is to use a
`startswith` check to match previous entries.
This introduces an environment variable `XONSH_HISTORY_MATCH_ANYWHERE` that, if
`True`, will instead perform a history search with an `is in` to allow matching
anywhere.
This could potentially have performance impacts depending on how many history
items are being searched, so I've defaulted it to `False` but I'm open to input
on that (or any of the rest of it).
This addresses #2762
=> Add history matching toggle to search entire line

news/tab_deep.rst, xonsh/ptk2/key_bindings.py
The keybinding logic for multiple `TAB`s brought up the selection menu if the event was repeated, hence why tabbing into a deep folder tree would bring up the selection menu every other time.
We had originally forked the code there from prompt_toolkit -- simply removing the keybinding seems to have fixed it (change only implemented for ptk2).
Fixes #2791
=> Fix multi-item path completion

news/fix_voxapi_create_params.rst, xontrib/vox.py
It is looks like it was a little bug, I hope I did not break anything, but I can not run tests on my computer even for code from master:
```
py.test test_vox.py                                    
File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 342, in _getconftestmodules
return self._path2confmods[path]                                                                   
KeyError: local('/home/worldmind/code/xonsh/tests')
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.5/dist-packages/_pytest/config.py", line 373, in _importconftest
return self._conftestpath2mod[conftestpath]
KeyError: local('/home/worldmind/code/xonsh/tests/conftest.py')
During …
```
=> Pass all params to voxapi.create

docs/tutorial.rst
More discussion in #2819 . The example shows how to pass arguments to subprocess command.
I'm not sure if `vi -b` is the best example since I've never used it, I can change it if necessary.
=> Add example of arguments for callable aliases

news/allow_off_as_falsy.rst, xonsh/tools.py
Just a simple one.
I think some users might want to use 'off' as a falsy value (e.g. me).
=> Allow 'off' as falsy value

news/path_completer_exception.rst, xonsh/completers/path.py
Fix path completer crash on attempted f-string completion. Fixes the second part of #2822 .
`ast.literal_eval()` can't handle f-strings and raises `ValueError` for them. The patch just silences the exception and gives up on the completion.
=> fix path completer issue with f-strings

news/fswiz.rst, xonsh/xonfig.py
We weren't using defaultdict correctly. Closes #2823
=> fix wizard crash when an unknown foreign shell is given

.circleci/config.yml, xonsh/tools.py
There's one line in `xonsh/tools.py` that snuck through our manual reviews, which is actually great.  This should fail when we run `black` now and it finds changes to make, then I can push up the fix to confirm it's working as expected.
=> Add black check to CircleCI

xonsh/ptk2/key_bindings.py
Removing some unnecessary checks again PTK version in keybindings.
Just code cleanup, no news entry required for this
=> Remove extraneous `try-except`s from ptk2 keybindings

azure-pipelines.yml
This adds a publishing step to the azure pipeline. That may make it a little easier to see what tests fail, maybe there is a chance it can be reported right back to GitHub.
No news item for this is necessary.
=> Publish results from tests on Azure

xonsh/completers/bash_completion.py
This fixes #2856 
No news item required since it's fixing a regression introduced since the last release.
=> Fix for string index error in bash completion

tests/test_tools.py
Fixes the deprecation warning reported by pytest. No news item needed I think.
=> Fix deprecation warnings when running pytest

news/fix_escape_deprecation_warning.rst, release.xsh, rever.xsh, tests/test_lexer.py, xonsh/tools.py
This fixes some deprecation warnings from unallowed escape sequences as well as importing abstract base classes directly from `collections` . 
It may solve some of the problems reported in #2863. But probably not all, since some of the deprecation warnings may come from xonsh dependencies.
=> Escaped deprecation

news/style-overrides.rst, xonsh/environ.py, xonsh/ptk2/shell.py, xonsh/style_tools.py, xonsh/tools.py
Introduces `$XONSH_STYLE_OVERRIDES` env-var, which is a Python dictionary of prompt_toolkit style definitions.
Closes #2838 and #2840.
=> PTK2 style overrides

xonsh/parsers/base.py
(No news item needed for this since #2713 was not release yet) 
I was getting the following:
```
AttributeError: 'XonshSession' object has no attribute 'xonsh_list_of_list_of_strs_outer_product'
```
The xonsh session restructure broke the @() expansion in subproc mode.
This PR restores it. 
```
snail@sea ~\Documents\xonsh 
$ echo 18.10.@(f"{x:02d}" for x in range(1,10))
18.10.01 18.10.02 18.10.03 18.10.04 18.10.05 18.10.06 18.10.07 18.10.08 18.10.09
```
=> Fix a regression with subproc @() evaluation

tests/test_ast.py
Potential fix for the test failures on master and several open PRs (the `AttributeError` when trying to access `builtins.__xonsh__`)
No news entry for this one (if it works).  Deeply confused by this but the test with a call to `check_parse` that didn't have a `xonsh_builtins` argument wasn't failing, so thought this was worth a shot.
=> Potential fix for ast test failures from attribute error

.circleci/config.yml, news/pin-black-in-ci.rst
Resolves xonsh#2846 by updating CircleCI config to explicitly use version 18.9b0 (latest at the time of this writing).
When staging this PR in my local fork, the Circle CI builds for `master` had the same output as this branch: 
* `build_black` and `build_34` pass
* `build_35` fails 1 test
```
tests/test_ast.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
input = 'l = 1\nls -l\n'
def check_parse(input):
>       tree = builtins.__xonsh__.execer.parse(input, ctx=None)
E       AttributeError: module 'builtins' has no attribute '__xonsh__'
```
* `build_36` fails the lint check
```
/home/circleci/project/xontrib/bashisms.py:35:14: W504 line break after binary operator
```
=> Pin black version in CI config

news/TEMPLATE.rst, xonsh/proc.py
Fixes #2883.
Although the Python's `subprocess` module does its best to not send signals to child processes that have already died, the protection is not atomic/race-free. We need to protect ourselves.
=> Fix exception when trying to send SIGSTOP to finished sudo child

docs/linux.rst
pacman uses the official repositories, not the AUR.
=> Update arch linux install instructions

news/shell-attr.rst, tests/test_replay.py, xonsh/built_ins.py, xonsh/foreign_shells.py, xonsh/main.py, xonsh/proc.py, xonsh/pyghooks.py, xonsh/style_tools.py, xonsh/tools.py
Since #2866 the `__xonsh__.shell` attribute most probably always exists (unless it gets intentionally deleted). We should rather check for its nullity instead of its existence.
Fixes #2899.
=> Test for value of __xonsh__.shell instead of its existence

news/fix-unclosed-scandir-iterator.rst, xonsh/imphooks.py
Another possible fix would be:
```diff
diff --git a/xonsh/imphooks.py b/xonsh/imphooks.py
index e83f06f8..a0ff63b1 100644
--- a/xonsh/imphooks.py
+++ b/xonsh/imphooks.py
@@ -84,7 +84,7 @@ class XonshImportHook(MetaPathFinder, SourceLoader):
continue
if not os.path.isdir(p) or not os.access(p, os.R_OK):
continue
-            if fname not in (x.name for x in scandir(p)):
+            if fname not in {x.name for x in scandir(p)}:
continue
spec = ModuleSpec(fullname, self)
self._filenames[fullname] = os.path.join(p, fname)
```
But this would consume the whole iterator, thus loosing the iterator benefits.
Let me know which patch do you prefer, if any :)
=> Fix ResourceWarning: unclosed scandir iterator in imphooks.py

news/update-collapsed-pwd.rst, xonsh/prompt/cwd.py
Hi, I'm excited about what xonsh will enable us to do.
I found the current _collapsed_pwd only show "." for collapsed hidden directory.
I feel this makes it ambiguous, so I made this PR.
```
$ pwd
/Users/qqhann/.tmp/foo/.bar/hoge
$ def _collapsed_pwd():
.     sep = xt.get_sep()
.     pwd = _replace_home_cwd().split(sep)
.     l = len(pwd)
.     leader = sep if l > 0 and len(pwd[0]) == 0 else ""
.     base = [i[0] if ix != l - 1 else i for ix, i in enumerate(pwd) if len(i) > 0]
.     return leader + sep.join(base)
.
$ _collapsed_pwd()
'~/./f/./hoge'
```
```
$ pwd
/Users/qqhann/.tmp/foo/.bar/hoge
$ def _collapsed_pwd():
.     sep = xt.get_sep()
.     pwd = _replace_home_cwd().split(sep)
.     l = len(pwd)
.     leader = sep if l > 0 and len(pwd[0]) == 0 else ""
.     base = [i[0]
. …
```
=> Update _collapsed_pwd to return two chars if a dir begins with "."

news/jake.rst, tests/test_main.py, xonsh/main.py, xonsh/timings.py
Running `xonsh --timings` would cause the following error:
```
File "/home/jake/xonsh/xonsh/main.py", line 400, in main
args = premain(argv)
File "/home/jake/xonsh/xonsh/main.py", line 310, in premain
setup_timings(argv)
File "/home/jake/xonsh/xonsh/timings.py", line 263, in setup_timings
@events.on_timingprobe
File "/home/jake/xonsh/xonsh/events.py", line 72, in __call__
if debug_level():
File "/home/jake/xonsh/xonsh/events.py", line 25, in debug_level
if hasattr(builtins.__xonsh__, "env"):
AttributeError: module 'builtins' has no attribute '__xonsh__'
Xonsh encountered an issue during launch
Failback to /bin/sh
```
Fixed by creating `XonshSession` before calling `setup_timings()` in `premain()`. 
The bug was introduced by …
=> --timings crash fix

news/eoferror.rst, xonsh/ptk2/key_bindings.py
https://github.com/xonsh/xonsh/issues/2951
before:
```
$ $IGNOREEOF
True
$ [ctrl + d]
Unhandled exception in event loop:
File "~~/prompt_toolkit/eventloop/posix.py", line 154, in _run_task
t()
File "~~/prompt_toolkit/eventloop/context.py", line 115, in new_func
return func(*a, **kw)
File "~~/prompt_toolkit/application/application.py", line 555, in read_from_input
self.key_processor.process_keys()
File "~~/prompt_toolkit/key_binding/key_processor.py", line 273, in process_keys
self._process_coroutine.send(key_press)
File "~~/prompt_toolkit/key_binding/key_processor.py", line 163, in _process
matches = self._get_matches(buffer)
File "~~/prompt_toolkit/key_binding/key_processor.py", line 123, in _get_matches
return [b for b in self._bindings.get_bindings_for_keys(keys) if b.filter()]
File …
```
=> fix EOFError when press c-d

news/fix-ptk2-pygments-colors.rst, xonsh/pyghooks.py
Fixes #2948.
@melund It turned out to be fairly simple. Let's hope your upstream PR gets merged before 2.3.1 ;)
Edit: Maybe it requires clarification that I intentionally set the upper bound to 2.3.0. The upstream PR has already been approved, so I expect the color monkey patching to not be needed for 2.3.1 any more.
=> Fix interpretation of color names with PTK2 and Pygments 2.3

CHANGELOG.rst
I noticed a minor typo while perusing the changelog.
=> Fix typo in changelog.

news/ptk2-pygments-2_3_1-colors.rst, xonsh/pyghooks.py
This is a follow-up to #2954. The [upstream PR](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/777/change-ansi-color-names-to-more-saying/diff) was already merged for Pygments 2.4, so this should be the last time we need to take care about it.
=> Fix color names for PTK2 and Pygments 2.3.1

news/pf_strings.rst, tests/test_lexer.py, tests/test_parser.py, xonsh/parsers/base.py, xonsh/tokenize.py
Ok, this still needs some documentation but I got it working and wanted to put it up for review (plus it's fun!).
This resolves #2524 and adds a new bit of syntax which combines p-strings and f-strings.  
This means you can now do things like:
```
gil@bad_cat ~ $ repos = 'github.com'                                           
gil@bad_cat ~ $ fp"~/{repos}"
PosixPath('/home/gil/github.com')
```
but since @scopatz also enabled xonshy f-strings, you can also do things like
```
gil@bad_cat ~ $ pF"{$HOME}"                                              
PosixPath('/home/gil')
```
or you can keep going deeper and try
```
gil@bad_cat ~ $ pf"/home/${'US' + 'ER'}"                                 
PosixPath('/home/gil')
```
This currently doesn't support combining the `pf` prefix with the raw-string …
=> Add `pf` strings

docs/python_virtual_environments.rst, news/vox-virtualenvs.rst, tests/test_news.py, xontrib/vox.py, xontrib/voxapi.py
This PR allows one to pass a `-p` or `--interpreter` argument to `vox new` in order to specify a specific interpreter to virtual environment creation.
If not passed, the interpreter will be determined by the value of the `$VOX_DEFAULT_INTREPRETER` environment variable. If not set, vox will default to using `xonsh`'s `sys.executable`.
This PR addresses the following issues:
#2347
#692
=> allow user to invoke specific interpreter for vox virtualenv creation

news/duck_tape.rst, xonsh/built_ins.py
It's a hack to fix #2999 and other freaky issues. This is what's causing #2999:
If XONSH_STORE_STDOUT is True
1. [this](https://github.com/sagartewari01/xonsh/blob/27067b6d4e55cc6503c52e221d7ac6aa84176eaa/xonsh/built_ins.py#L863) function returns False.
2. The call to `pause_call_resume` is skipped (https://github.com/sagartewari01/xonsh/blob/27067b6d4e55cc6503c52e221d7ac6aa84176eaa/xonsh/built_ins.py#L907)
3. `pause_call_resume` sends `SIGCONT` to the process.
So it appears to be a `RAII` problem.
As far as I know, sending multiple `SIGCONT`s shouldn't be a problem, so this PR shoudn't have any side effects.
=>  send SIGCONT in run_subproc

docs/tutorial.rst, news/envprepost.rst, news/prompt-env-vars.rst, tests/test_prompt.py, xonsh/built_ins.py, xonsh/prompt/env.py
Partially implements pypa/virtualenv#1299. Ping @scopatz for comment.
Fully implements the suppression of virtualenv name display when `$VIRTUAL_ENV_DISABLE_PROMPT` is defined and truthy.
Implements the xonsh-side "catch" of a custom prompt defined via the `--prompt` argument to `virtualenv`. In order for this to work, `activate.xsh` will need to be modified on the virtualenv side to define `$VIRTUAL_ENV_PROMPT` during activate (and *undefine/restore* it during deactivate!), if the environment is created with `--prompt="foo"`.
A user could also manually manage `$VIRTUAL_ENV_PROMPT`.
Still needed, at least:
=> Implement VIRTUAL_ENV_PROMPT and VIRTUAL_ENV_DISABLE_PROMPT

.github/issue_template.md
Just noticed this on a conda-forge feedstock and it's nice to not have the issue
text all cluttered up with tracebacks and config outputs
=> Add `<details>` block to issue template

news/spaceitallout.rst, xonsh/completers/commands.py
Followup to #3002 -- in the event that the last token on a line (without a trailing space) is one of `&&`, `|`, `||`, `and` or `or`, completer will now insert a single space, allowing the next completer call to complete without issue.
=> Tweak `command_skipper` to avoid overwriting tokens with completer output

news/on_anaconda.rst, xonsh/platform.py
This fixes a regression with `ON_ANACONDA` in `platform.py`. This can no longer detect if we are using an Anaconda based Python. The new method to detect conda is more robust. 
This fixes the environment not showing up in the prompt, and the `activate`/`deactivate` script which has stopped working on Windows.
=> Fix detection of Anaconda

xonsh/aliases.py
No news items needed for this. 
This fixes a problem with Partial aliases not having a `__name__` attribute in the same location as the previous aliases. @scopatz I don't know if this is the correct fix. 
Without this I get the following error when running a simple aliases: 
```
snail@sea ~\Documents\xonsh
$ cdx
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
File "C:\Users\mel\anaconda3\lib\site-packages\xonsh\proc.py", line 1856, in __init__
proc = spec.run(pipeline_group=pipeline_group)
File "C:\Users\mel\anaconda3\lib\site-packages\xonsh\built_ins.py", line 538, in run
event_name = self._cmd_event_name()
File "C:\Users\mel\anaconda3\lib\site-packages\xonsh\built_ins.py", line 612, in _cmd_event_name
return …
```
=> Fix problem with partial aliases not having __name__ attribute

news/3036-change-xontrib-autojump.rst, xonsh/xontribs.json
Changed to the [repository link](https://github.com/sagartewari01/autojump-xonsh) that linked from [PyPI](https://pypi.org/project/xontrib-autojump/).
Maybe this PR fixes #3036.
=> Change url of xontrib-autojump

news/bang-commands.rst, tests/test_bashisms.py, xontrib/bashisms.py
While the 'bashisms' xontrib provides the `!!` command, several related commands are notably missing:
```
!$        # The last argument of the previous command.
!*        # All arguments but the first of the previous command.
!^        # The first argument of the previous command.
!<cmd>    # The last command beginning with the string "cmd".
```
This commit implements these commands in the same fashion as `!!`.  Note that this remains far from a complete implementation of the bash bang command syntax, but it covers the comands that I use on a daily basis and is hopefully a step in the right direction.
If there's interest, I could also implement more of the bash syntax, e.g.:
```
!!:2      # The second argument of the previous command.
!!:2-3    # The second and third arguments of the …
```
=> Implement more bang commands: !$ !* !^ !<cmd>

news/nllpr-ptk2.rst, xonsh/ptk2/__init__.py
As per an insightful comment by @matheus2740:
https://github.com/xonsh/xonsh/issues/2944#issuecomment-443534690
pull request #2695 only covered ptk1.
This commit replicates it for ptk2.
Closes #2944.
=> no lazy load pkg_resources, ptk2 edition

CHANGELOG.rst
While reading through 0.8.7..0.8.12 in the CHANGELOG,
found those typos, and fixed along.
I didn't create a news entry, since this only affects the CHANGELOG.
=> Fix various typos in the recent release notes

news/stty_lookup_bug.rst, xonsh/readline_shell.py
Was getting this error after running any shell command in xonsh 0.8.12, Win 10, cygwin, Python 3.6.4:
```
$ git diff . | vim -
Vim: Reading from stdin...
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
File "_env/lib/python3.6/site-packages/xonsh/base_shell.py", line 360, in default
run_compiled_code(code, self.ctx, None, "single")
File "_env/lib/python3.6/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
func(code, glb, loc)
File "<xonsh-code>", line 1, in <module>
File "_env/lib/python3.6/site-packages/xonsh/built_ins.py", line 987, in subproc_captured_hiddenobject
return run_subproc(cmds, captured="hiddenobject")
File "_env/lib/python3.6/site-packages/xonsh/built_ins.py", line 950, in run_subproc …
```
=> Fix "'NoneType' object is not iterable" on stty lookup

MANIFEST.in, news/test-manifest.rst
While packaging xonsh for Fedora, I lacked all of the files necessary for running the tests. This patch should fix that.
https://bugzilla.redhat.com/show_bug.cgi?id=1695139
=> Add all test files to MANIFEST.in

news/pty_size.rst, xonsh/built_ins.py
Commands which are threadable are run with separated PTY. For some usage, PTY should have the same size as the command is not threadable. For example, before this branch:
```
jben@garance ~ $ __xonsh__.commands_cache.threadable_predictors['tput']=xonsh.commands_cache.predict_false # we want tput as NOT threadable                    
jben@garance ~ $ tput cols                                                                                                                                     
159
jben@garance ~ $ __xonsh__.commands_cache.threadable_predictors['tput']=xonsh.commands_cache.predict_true # we want tput threadable                            
jben@garance ~ $ tput cols …
```
=> Set PTY size to same size as main terminal for threadable commands

news/not_threadable_asciinema.rst, xonsh/commands_cache.py
`asciinema` (terminal recorder tool) can have very strange behavior when threaded. Seems to be resolved when pty size is correctly specified (see #3079) but, I think it is safer to add this command in not threadable commands.
=> Not threadable asciinema

news/not_threadable_tput.rst, xonsh/commands_cache.py
Usually when a user play with `tput`, they want to interact with the main terminal, not a PTY created between the command and the terminal.
=> Not threadable tput

news/tests_git_commit_no-gpg-sign.rst, tests/test_lib/test_os.xsh, tests/test_prompt.py
The command `gpg commit` is used in some tests. I have a `gitconfig` with `gpgsign = true`, therefore, `git` interact to `gpg` during tests, tests fails or skipped if I do not sign.
For testing, there is no reason to sign commits, so this PR add `--no-gpg-sign` to `git commit` commands.
Since the change is only on `tests/`, I think no news item is necessary. I have commited a empty news item to satisfy the tests on CI.
=> Tests git commit no gpg sign

news/tests_main_AttributeError.rst, tests/test_main.py, tests/test_ptk_highlight.py
I had same problems than in #3070. For my understanding, it is because objects are not properly cleaned between different tests. So I propose this patch.
I use a empty news item, because I think this PR doesn't not fix a bug for a user, but a bug in the tests (and the CI).
Should solve issue #3070 and complete PR #3075.
=> Solve AttributeError in test_main and test_ptk_highlight

azure-pipelines.yml
CondaEnvironment is deprecated.
Rewrite to follow this instruction:
https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=vs2017
This PR fixes causing ImportError in Azure Pipelines Python 3.7 Conda Environment ([like this](https://dev.azure.com/xonsh/xonsh/_build/results?buildId=565)) , but the results of some tests become unstable. (I checked some testcase causes `AttributeError: module 'builtins' has no attribute '__xonsh__'
`)
=> CI: use `conda` directly instead of CondaEnvironment

news/fix-cat-empty-file.rst, tests/test_xoreutils.py, xonsh/xoreutils/cat.py
Fixed causing infinite loop when doing `cat` empty file 
and add test about `cat`.
Reproduce problem:
```sh
xonsh --no-rc
xontrib load coreutils
touch empty_file
cat empty_file
```
Reproduce `xonfig`:
```
+------------------+----------------------+
| xonsh            | 0.8.12.dev19         |
| Git SHA          | 5d87fc76             |
| Commit Date      | Mar 23 23:55:33 2019 |
| Python           | 3.7.3                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.3.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on darwin        | …
```
=> Fix cat empty file

news/tests_usrbinenv_args.rst, scripts/xonsh, scripts/xonsh-cat
Arguments passed to python in `scripts/xonsh` and in `scripts/xonsh-cat` are now passed by a portable hack in sh, not anymore by `/usr/bin/env`, because `/usr/bin/env` can be not able to handle arguments.
Some tests in `test_integrations.py` was failing on my system, and are now passing.
Similar to #3068, but this PR concerns other scripts.
=> Tests usrbinenv args

.circleci/config.yml, news/black_xontribs.rst, xonsh/completers/commands.py, xonsh/lib/collections.py, xonsh/parsers/base.py, xonsh/prompt/env.py, xonsh/xoreutils/uptime.py
This is a really trivial fix. I changed black to run on directories instead of `*.py`.
I also ran black once on all the files that had previously been skipped over. For security, please verify that I did not inject any malicious code.
=> The black check no longer skips files buried deeper in the directory tree

news/environ_do_not_delete_default_value.rst, tests/test_environ.py, xonsh/environ.py
If `Env.__delitem__` is called to delete a value only in default, do nothing
solves #3077
=> Environ do not delete default value

news/abc-warning.rst, xonsh/lib/collections.py
A trivial fix to get rid of a warning that I would get while running the tests.
=> Import MutableSet from colections.abc to circumvent DeprecationWarning

news/py38.rst, xonsh/parsers/base.py
This is a minimal fix to stop xonsh from throwing errors on Python 3.8.  It doesn't implement all of 3.8 yet.  This is done to allow the virtualenv test suite to pass. CC @gaborbernat @gforsyth
=> minial Python 3.8 fix

news/pyg2.4.rst, xonsh/pyghooks.py, xonsh/tools.py
This probably deserves an patch release on its own, once merged, since output will be hidden for python expressions and a traceback will be shown.  It would be great to have some manual windows testing on this, but it is probably not required. 
closes #3122
=> pygments v2.4 fixes

news/pyreq.rst, setup.py
@gaborbernat - is this the kind of thing that you are looking for?  Happy to do a release after this gets in.  Also, for the python v3.4 tests, is it possible for us to just pin xonsh to `=0.8.12`?  I don't think it makes sense for the 0.9 series to support Python 3.4 anymore.
=> python_requires

news/aliases_predictor_threadable.rst, xonsh/commands_cache.py
I had problems with aliases and predictors in command cache.
For example:
```
jben@garance ~ $ ipython                                                                                         
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import os 
...: [os.readlink(f'/proc/self/fd/{i}') for i in range(3)]                                                    
Out[1]: ['/dev/pts/5', '/dev/pts/5', '/dev/pts/5']
```
Ok, we are not threaded (because ipython have a predictor). Let's do a alias:
```
jben@garance ~ $ aliases['ipy']='ipython'                                                                        
jben@garance ~ $ ipy …
```
=> Aliases predictor threadable

news/command_cache_env_pred.rst, xonsh/commands_cache.py
For `env`, a special predictor based on the predictor for the executed command.
Fixes #2759 and #3103.
=> Command cache env pred

azure-pipelines.yml, news/allow-avoid-overwrite-in-run-tests.rst, run-tests.xsh
Executing `run-tests.xsh` with setting files in options cause unwanted overwriting such like `junit/test-results.xml`.
Add processing `%d` for avoid overwriting in `run-tests.xsh`.
=> Add process to avoid overwrite files that specified in options in `run-tests.xsh`

news/noexpand-raw-string.rst, tests/test_parser.py, xonsh/parsers/base.py
Closes #2943 
Previously, there was no way to prevent Xonsh from expanding environment variables in strings:
```
~ 🐚  $BAI="BYE"
~ 🐚  env BAI=HAI bash -c "echo $BAI"
BYE
~ 🐚  env BAI=HAI bash -c r"echo $BAI"
BYE
```
Now:
```
~ 🐚  $BAI="BYE"
~ 🐚  env BAI=HAI bash -c "echo $BAI"
BYE
~ 🐚  env BAI=HAI bash -c r"echo $BAI"
HAI
```
Edit: relates also to #1783
=> Do not attempt to expand raw strings in subprocess mode

tests/test_environ.py
Change the `key, value` used for testing delitem of a var with default value. Previously, sometime the `LS_COLORS` var was used, which is evaluated. The test was failing (and should not) and was not deterministic.
=> Test delitem default env

news/revert_portable_env_args_trick.rst, scripts/xonsh, scripts/xonsh-cat
Revert portable trick to pass args. See #3125.
=> Revert portable env args trick

news/fix-ptk1-bashisms.rst, xontrib/bashisms.py
PTK1 `Condition` expects one positional argument.
Fixes #2843
=> Fix bashisms xontrib startup on PTK1

news/fix_crash_intensify_color.rst, xonsh/tools.py
This fixes a crash when `$INTENSIFY_COLORS_ON_WIN` is set in xonshrc, and xonsh is somehow invoked without a shell, because `__xonsh__.shell.shell` did not exist. 
It happend to me when running Pytest for different project in xonsh. 
```
INTERNALERROR>   File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\environ.py", line 1504, in __setitem__
INTERNALERROR>     val = ensurer.convert(val)
INTERNALERROR>   File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\tools.py", line 1935, in intensify_colors_on_win_setter
INTERNALERROR>     if builtins.__xonsh__.shell is not None:
INTERNALERROR> AttributeError: 'XonshSession' object has no attribute 'shell'
```
This PR fixes the problem
=> Fix crash when setting $INTENSIFY_COLORS_ON_WIN

news/preserve_newline_during_bashisms_transform.rst, xontrib/bashisms.py
Haven't included a news entry yet since this is my first PR and I wanted to make sure it makes sense first.
No test for regression here - was curious if there's even a places for this? `tests/integration.py` seems the most likely since it tests the interaction between multiple components and the interactive prompt, but I'm not seeing any other tests that similarly test xontribs there.
Fixes #3120
=> Preserve newline during bashisms transformation.

.circleci/config.yml, .travis.yml, azure-pipelines.yml, docs/tutorial_hist.rst, news/allow-avoid-overwrite-in-run-tests.rst, news/command_cache_env_pred.rst, news/env-dash-S.rst, news/fix-ptk1-bashisms.rst, news/fix_crash_intensify_color.rst, news/noexpand-raw-string.rst, news/revert_portable_env_args_trick.rst, news/unthread-sudoedit.rst, run-tests.xsh, scripts/xon.sh, scripts/xonsh, scripts/xonsh-cat, tests/test_environ.py, tests/test_parser.py, xonsh/commands_cache.py, xonsh/parsers/base.py, xonsh/tools.py, xontrib/bashisms.py
Not sure if this a known bug with the sqlite history backend or just not implemented (yet) and somebody forgot to mention it in the documentation.
Whichever, this does not work:
```
15-11:57[confus@jcgbx ~]
$ history info
backend: sqlite
sessionid: 2965636d-6679-4f21-848d-5a9ca0bf17bd
filename: /home/confus/.local/share/xonsh/xonsh-history.sqlite
session items: 0
all items: 23
gc options: (16256, 'commands')
15-11:57[confus@jcgbx ~]
$ history info
backend: sqlite
sessionid: 2965636d-6679-4f21-848d-5a9ca0bf17bd
filename: /home/confus/.local/share/xonsh/xonsh-history.sqlite
session items: 0
all items: 23
gc options: (16256, 'commands')
```
but with the json-backend it does:
```
15-11:55[confus@jcgbx ~/devel/unix/xonsh/docs]  master|✓
$ history info
backend: json
sessionid: …
```
=> Document missing output history with sqlite

news/fix-pred-thrdable-on-win.rst, tests/test_commands_cache.py, xonsh/commands_cache.py
```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.3                                                 |
| Git SHA          | 3b011dcf                                              |
| Commit Date      | May 16 04:11:49 2019                                  |
| Python           | 3.7.3                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | 2.3.1                                                 |
| on posix         | …
```
=> Fix for raising error in get_predictor_threadable on win

xonsh/xontribs.json
New xontrib!
Searches the command history output for URLs and copy's the user selection to clipboard or opens them in browser. Complete with key-bindings!
See: https://github.com/con-f-use/xontrib-histcpy
=> Add histcpy to the xontribs

news/ansi_colors_style_bw.rst, tests/test_ansi_colors.py, xonsh/ansi_colors.py
This PR add backgrounds color for `bw` style. These background color can not be deduced from other color like all other styles (except the default style).
This PR add also tests to ensure that all colors are set or can deduced for all styles.
Should fix #3130.
=> Ansi colors style bw

news/fix_pip_completer.rst, tests/completers/test_pip_completer.py, xonsh/completers/pip.py
Requires a word-ending before `pip`, also adding in support for `xpip`
Resolves #3142
=> Fix `pip` completer misfires on `bagpipes` and similar

xonsh/commands_cache.py
When I wrote threadabilty predictor for aliases in #3086, I was considering "normal" aliases as a `list`. Today I add a aliases with a tuple, I works perfectly with xonsh, but the predictor was returning the default prediction.
This is a very minor change, I think this does not desserve a news item.
=> aliases can be any sequence, not only list

ci/environment-3.5.yml
=> remove matplotlib from 3.5 deps

xonsh/xontribs.json
Thanks for this awesome shell, I just discovered it last week and I'm already in love with it.
Since I use `ssh` a lot, I've created a xontrib to start `ssh-agent` and add ssh identities "automatically".
=> xontrib-ssh-agent added

news/zipapp.rst, setup.py, xonsh/xontribs.py
Make the xontrib machinery zipapp friendly.
The resulting checking is more complicated than I'd like, but there's a lot of edge cases. Good news: All of it can be removed when 3.5, 3.6 are no longer supported.
Full disclosure: This is part of my own use of building xonsh zipapps and using them in my homelab. They should make xonsh more robust against being installed with other applications and being started inside of active venvs.
=> Xontrib zipapp support

CONTRIBUTING.rst
* black likes double quotes instead of single quotes.
* Python 3.4 is not a target anymore.
=> Update style guide to match reality

news/fix_DAP_completion.rst, tests/test_main.py, xonsh/built_ins.py
This restores tab-completion to objects proxied through
DynamicAccessProxy
=> Add `__dir__` to `DynamicAccessProxy`

news/vi_mode_enter.rst, xonsh/ptk2/key_bindings.py
Closes #3218 
h/t to @ivanov for noticing the inconsistent behavior
When not in `insertmode`, whether this is in VI mode or Emacs mode, a carriage return should execute the current block, regardless of cursor position.  This makes that happen.
=> Fix behavior of enter key in VI_MODE

news/get_next_task.rst, xonsh/jobs.py
Two of the three callers of get_next_task already called _clear_dead_jobs
to update the task state before searching for active tasks.
xonsh.prompt.job._current_job did not call _clear_dead_jobs, which lead to
tasks still being displayed in the title, even though they had already
finished.
Moving the call to _clear_dead_jobs into get_next_task ensures that it
always returns correct data.
=> Avoid stale data when determining active tasks

news/add_async_comp.rst, xonsh/environ.py, xonsh/ptk2/shell.py
This is very early.
https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#asynchronous-completion
I think by default True is fine, but I have not tried working in multi platform.
=> add $COMPLETION_IN_THREAD

news/subprocess-help.rst, xonsh/built_ins.py
This makes for example 'sh?' equivalent to 'man sh', unless there actually
exists a 'sh?' executable.
Resolves #3204.
=> Try to open man page as help for subprocess commands

news/gitstatus.rst, xonsh/prompt/gitstatus.py
Setting $XONSH_GITSTATUS_* to an empty string lead to the number of files
still being displayed, without any way to see to which category those
belonged. It might even display "11", which could be "1 changed file" and
"1 staged file" or "11 staged files".
Changing the logic to hide the entire entry if the corresponding
$XONSH_GITSTATUS_* setting is empty allows for an easy way to disable some
of the categories.
=> Allow disabling individual items in gitstatus prompt

.pre-commit-config.yaml, CONTRIBUTING.rst, requirements-docs.txt, requirements-tests.txt
After sitting next to @gforsyth and seeing him have broken tests due to not running `black`, he mentioned [pre-commit](https://pre-commit.com) and I was _hooked_[1]. So, I put it into a PR and sent it up.
[1] @scopatz and @gforsyth have been making terrible puns all week.
=> Create a pre-commit hook for black

news/3182-fix-cat-proc-file.rst, tests/test_xoreutils.py, xonsh/xoreutils/cat.py
I hope this patch will fix #3182 and #3199.
I tried `cat /proc/cpuinfo` in my machine.
=> Fix `cat` can't read pseudo files with zero size

news/command-not-found.rst, xonsh/tools.py
Fixes: https://github.com/xonsh/xonsh/issues/3247
Motivation: command-not-found is available on a different location under
NixOS.
=> command-not-found: look up in PATH instead of using hard-coded location

xonsh/tools.py
The last change in #3249 has introduced a regression as
command-not-found does not reside on the $PATH on Ubuntu systems.
Additionally `CommandsCache` is introduced instead of `shutil.which` to
cache the result of $PATH lookup.
---
Question does a repeated failing lookup in `CommandsCache` hurt on Ubuntu?
=> command-not-found: fix lookup of command-not-found in Ubuntu

news/logical_op_aliases.rst, tests/test_aliases.py, xonsh/aliases.py
This fixes #3270 and logical operators within aliases now resolve correctly.
I've added in `&&`, `||`, `and`, and `or`
```
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ aliases['echocat'] = 'echo "hi" and echo "there"'
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ echocat
hi
there
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ aliases['echocat'] = 'echo "hi" or echo "there"'
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ echocat
hi
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ aliases['echocat'] = 'echo "hi" && echo "there"'
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ echocat
hi
there
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ aliases['echocat'] = 'echo "hi" || echo "there"'
(base)   ~/githu/xonsh/xonsh logical_op_aliases $ echocat
hi
```
=> Allow logical operators within aliases

docs/tutorial_completers.rst, news/correct_completer_tutorial.rst
Corrects the code in the "lou carcolh" example for custom xonsh <kbd>TAB</kbd>-completers. Previously it would not correct on "lou", despite what the docstring said. Also it would throw an `IndexError` if empty.
Also corrects the description of `endidx`, which is not actually the index of the last character in prefix, but the length (i.e. "index of last character plus one").
Btw., I have written this decorator to debug completers more readily:
<details>
<summary>Completer debug decorator</summary>
import tempfile, time
from functools import wraps
from pprint import pformat
from pathlib import Path as P
def complete_watcher(
func=None, dirname=tempfile.gettempdir(),
filename='xonsh_complete_watcher.txt',
context=False
):
if func is None:
return functools.partial(complete_watcher, …
=> Correct completer tutorial

.coveragerc, AUTHORS.rst, news/vox-activate-absolute-path.rst, tests/test_vox.py, xontrib/voxapi.py
Currently, when I use `vox activate venv/`, a _relative path_ is prepended to `$PATH`, and this means that if I change away from the current directory (which would typically be the project root), the path no longer resolves correctly.
This PR proposes to insert the _absolute path_ into `$PATH`.
```
$ xonfig
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.9                                                 |
| Git SHA          | 5aac8711                                              |
| Commit Date      | Jul 19 17:43:33 2019                                  |
| Python           | 3.7.4                                                 |
| PLY              | 3.11                                                  |
| have readline    | False …
```
=> vox activate: use absolute path in $PATH

news/fnf_exit_1.rst, tests/test_main.py, xonsh/main.py
Fixes #3292 
Not sure if we want the `on_exit` event to still fire for this -- I've put it in for now.
=> Non-zero exit code when script path not found

docs/python_virtual_environments.rst, news/autovox.rst, tests/test_vox.py, tests/tools.py, xonsh/xontribs.json, xontrib/autovox.py
Add a xontrib to support automatic vox xontribs (such as avox).
This deals with all the mechanics of handling events, searching up the directory tree for venvs, and dealing with multiple policies.
Example policy:
```python
@events.autovox_policy
def dotvenv_policy(path, **_):
venv = path / '.venv'
if venv.exists():
return venv
```
The user does need to invoke `xontrib load autovox` to enable this functionality.
Closes #3246
=> Add autovox xontrib

news/fix-cd-completion.rst, xonsh/completers/path.py
Previously using tab completion for cd combined with the `$CDPATH` environment variable led to strange behaviour.
Consider the following scenario
```
mkdir -p /tmp/cdpath/outer/inner
$CDPATH = ['tmp/cdpath']
```
entering `"cd outer<tab>"` would be completed to `"cd outer "` (note the trailing space) and entering `"cd outer/<tab>"` would be completed to `"cd inner "` (also with a trailing space).
The first tab completion is of no use, while the second tab completion is simply invalid (the correct one would be `cd outer/inner/`)
This path fixes this bug by returning the path relative to the `$CDPATH` entry in `_add_cdpaths`.
Furthermore to enable repeated presses of `<tab>` `_quote_paths` had to be changed to consider paths within $CDPATH
=> fix tab completion of cd with $CDPATH

news/posonlyargs.rst, xonsh/parsers/base.py
Fixes #3271 
I thought I'd give that issue a spin, even though I'm not at all familiar with the codebase. Please keep in mind that this PR is purely touching in the dark, but I hope that it gives some insights to someone who knows the codebase better.
I learnt from the Python docs that `ast.arguments` was changed to also take `posonlyargs` as argument. So I figured I'd look up all the places where `ast.arguments` pop up, and simply plug in `posonlyargs` as argument. Sure enough, this fixed the raised exception. And curiously enough, it doesn't break on Python 3.7 for me.
This PR doesn't actually implement posonlyargs, however. See the following output:
```
(xonsh38) carmenbianca@thinkpad-x395 ~/Projektoj/xonsh posonlyargs $ def f(a, b, /, c, d, *, e, f): …
```
=> Python 3.8: Prevent posonlyargs error

news/fix-ctrl-c-event-windows.rst, xonsh/proc.py
```
+------------------+-------------------------------------------------------+
| xonsh            | 0.9.11                                                |
| Git SHA          | 6724d418                                              |
| Commit Date      | Dec 15 12:12:56 2018                                  |
| Python           | 3.7.1                                                 |
| PLY              | 3.11                                                  |
| have readline    | False                                                 |
| prompt toolkit   | 2.0.9                                                 |
| shell type       | prompt_toolkit2                                       |
| pygments         | 2.4.2                                                 |
| on posix         | …
```
=> On Windows, don't sent SIGINT, send CTRL_C_EVENT instead

news/bottom_bar_keypress_issue.rst, xonsh/ptk2/shell.py
This fixes [an issue I encountered](https://github.com/xonsh/xonsh/issues/1048#issuecomment-531497811) when using `$XONSH_UPDATE_PROMPT_ON_KEYPRESS` where the bottom bar is rendered as a grey block.
Root cause was essentially passing `"bottom_toolbar": lambda: None`. I only fixed `ptk2` because I'm not sure if it was an issue elsewhere.
The second gray bar is `tmux`, confirmed it appears outside of it though:
=> Fix gray empty bar when updating on keypress

news/script_unicode.rst, xonsh/codecache.py
This PR changes the way xonsh reads script files so they always assumed to be utf-8, even on
Windows where the default encoding can vary. 
This allows for writing unicode characters in script files on Windows (most importantly `xonshrc`). 
Read this [PEP for more info](https://discuss.python.org/t/pep-597-use-utf-8-for-default-text-file-encoding/1819).
=> Assume xsh scripts are in UTF-8

.pre-commit-config.yaml, xontrib/jedi.xsh
This is just a followup to #3331 to fix both cases of jedi loops. Also, because I couldn't commit since I didn't have python 3.5, I needed to relax the version to just `3.x`. Sorry for putting two things into one pull request.
=> Refactor jedi and fix pre-commit hook

news/fix-ansi-colors.rst, xonsh/ansi_colors.py
The ANSI color code definitions for the "default" scheme preventing any of the modifiers (bold, underline, blink) from taking effect.
The `0;` code currently resets any of the modifiers specified before it - meaning that the current Xonsh code for "bold cyan" (`1;0;36m`) produces the same output as `36m` (cyan) rather than `1;36m` (bold cyan).
This change should fix it for the default color scheme.
=> Fix ANSI color default scheme

CHANGELOG.rst, news/sigstp.rst, xonsh/built_ins.py, xonsh/proc.py
I kept getting `AttributeError: module 'signal' has no attribute 'SIGTSTP'` exceptions when I `^C`d out of a process and turns out there are a few places where we forgot to protect `signal.SIGSTP` on Windows.
This patch fixes those remaining places.
Follow up to #3344.
=> fix(signals): Fix SIGSTP not an attribute on Windows

news/no_more_xonda.rst, xonsh/xontribs.json
It was great while it lasted.
(For context, `xonda` functionality has been folded into upstream `conda` so there is no longer a need for a standalone `xontrib`)
=> Remove `xonda` from `xontrib` list

news/kill-win.rst, xonsh/jobs.py
This fixes an issue on Windows where pressing ctrl-c could sometimes result   in a traceback if the process had already quit before being killed by xonsh.
It also prevent the taskkill command from printing its error messages.
=> Fix ctrl-c traceback on windows

news/fix-prompt-interval-refresh-docs.rst, xonsh/environ.py
Prior documentation incorrectly stated behavior was dependent on `$UPDATE_COMPLETIONS_ON_KEYPRESS`.
=> Correct and clarify docs for $PROMPT_REFRESH_INTERVAL

news/appimage.rst, news/issue-3814.rst, tests/test_integrations.py, xonsh/built_ins.py, xonsh/proc.py
Fix issue #3418 
Typo in xonsh.built_ins.py when creating subprocess; another unhandled exception when termios.setattr() fails (for some kinds of consoles).
There wasn't any existing unit test coverage, which is how we got here.  I'd love to add some, but need some help getting started.
=> Issue 3418

.circleci/config.yml, azure-pipelines.yml, news/parser38.rst, xonsh/parser.py, xonsh/parsers/base.py, xonsh/parsers/v38.py
This builds on earlier work by @carmenbianca -- I've moved the 3.8+
specific parser code (involving the `posonlyargs`) to a python 3.8
parser class that inherits from the 3.6 parser.
=> Create python3.8 parser

news/autovox-cd.rst, xontrib/autovox.py
autovox does not currently handle cd and manual activation correctly.
To reproduce:
1. `vox activate myenv`
2. `cd mydir` (Any directory without an associated venv)
What should happen: The venv is still `myenv`
What does happen: venv is deactivated.
This happens because it compares the current venv with the venv associated with the new dir. What should happen is that the venv associated with the old dir should be compared to the venv of the new dir.
=> autovox: Fix algorithm to cd correctly

README.rst
Added [xxh](https://github.com/xonssh/xxh) to the list of projects that use xonsh.
=> xxh is for using xonsh wherever you go through the ssh.

news/container-interactive.rst
Adds a news item for the new [`xonsh/interactive`](https://hub.docker.com/r/xonsh/interactive) container.
=> Add news item for the new container.

docs/tutorial.rst
Hi!
The description of `${...}` is looks like that it is the synonym of `os.environ`. But it's not exectly true.
In this PR added the note about $UPDATE_OS_ENVIRON to the tutorial. It is great to know about special flags in the beginning of the tutorial and save time to understanding why:
```
True
False
```
=> Tutorial: note about $UPDATE_OS_ENVIRON

docs/tutorial.rst
Hi!
After reading the tutorial about ``g`...` `` and `p"..."` there is a question: how to globbing certain path because `` g`{mypath}/**` `` is not working (and gp/gf/gpf too). I've added info about one elegant way how to do it with Path object. And a bit more.
Thanks!
=> Add useful tricks with Path object to the tutorial

news/pyghooks-whitespace.rst, xonsh/pyghooks.py
Pygments lexer yields an extra whitespace token for inputs with leading whitespace. This probably was not a problem for PTK2/Pygments, but breaks command line rendering on PTK3.
Relates to #3391
=> XonshLexer: skip leading whitespace

news/fix-get_source.rst, tests/test_imphooks.py, xonsh/imphooks.py
get_source() takes a dotted module name, not a file path.
This was breaking local sphinx builds.
=> Fix get_source()

news/cd_symlinks.rst, xonsh/dirstack.py
Calling abspath() before realpath() suppresses some information about symbolic links in some cases. To illustrate this case here is what is expected to happen (and what happens in the standard /usr/bin/cd) with `$PROMPT = "{cwd} >>> "`:
```
/ >>> ls -l lib
lrwxrwxrwx 1 root root 7 13. Nov 17:23 lib -> usr/lib
/ >>> cd lib
/lib >>> cd -P ..
/usr >>> 
```
But this is what the current version brings:
```
/ >>> ls -l lib
lrwxrwxrwx 1 root root 7 13. Nov 17:23 lib -> usr/lib
/ >>> cd lib
/lib >>> cd -P ..
/ >>> 
```
This change implements the first behavior instead.
=> Fix behavior of cd -P and dot-dot paths

news/execx-evalx-newline.rst, tests/test_execer.py, tests/tools.py, xonsh/execer.py
* ``execx`` does not require the input string to be newline-terminated.
* ``evalx`` accepts newline-terminated input string.
`execx` and `evalx` now behave consistently with `exec` and `eval` respectively.
Only `"\n"` is considered to be a valid newline character in this context (see PEP 278).
Fixes #3481.
=> Fix execx / evalx trailing newline

news/add-xontrib-pyenv.rst, xonsh/xontribs.json
This PR adds [xontrib-pyenv](https://github.com/dyuri/xontrib-pyenv) to the list of registered xontribs.
=> Register xontrib-pyenv in list of available xontribs.

news/abbrevs.rst, xonsh/xontribs.json, xontrib/abbrevs.py
Closes #3471.
Expands abbreviations from `abbrevs` dictionary on <kbd>Space</kbd> key press. I did not ~~(and will not)~~ implement expanding abbreviations on <kbd>Return</kbd>, ~~because I don't like it - it is too dangerous in my opinion.~~
To test it:
```
$ xontrib load abbrevs
$ abbrevs["gst"] = "git status"
$ gst # hit <space> and "gst" should get epanded into "git status"
```
=> Add fish-like command abbreviations

xontrib/abbrevs.py
The abbrevs expansion may be especially annoying if triggered after dash or equality sign. Let's reduce it to space-delimited word completion.
No news entry needed - alters unreleased code.
=> abbrevs: only trigger completion if the word is preceded by space

xontrib/abbrevs.py
The xontrib was disrupting functionality of `$COMPLETIONS_CONFIRM`.
No news entry needed - alters unreleased code.
=> abbrevs: do not handle return key while a completion is selected

xonsh/xontribs.json
I've migrated my repositories from bitbucket to github (due to the end of mercurial support on bitbucket).
=> xontrib-ssh-agent moved to github

news/win-scandir-trailing-space.rst, xonsh/tools.py
Fixes a bug on Windows if Path elements has trailing spaces. Windows in general and ``os.path.isdir()`` 
doesn't care about trailing spaces but ``os.scandir()`` does. 
Fixes #3504
=> Fix Windows bug when PATH entries has trailing spaces

news/fix-executables_in.rst, xonsh/tools.py
os.stat() on Windows seems to strip the trailing spaces off the path parameter, so noone can be sure the path does really exist.
Fixes #3504.
=> Fix executables_in() exception on Windows

news/autovox-fstrings.rst, xontrib/autovox.py
We still can't use f-strings because of Python 3.5 support.
=> Make autovox work with Python 3.5

tests/test_ast.py
Make comments in the `test_multiline_...`-testcases easier to comprehend by using correct grammar and spelling and by stating more relevant aspects.
Comment on test parameters with inline instead of block comments, as this makes it easier to associate code lines with comments, without having to resort to additional blank lines for separation.
(No changelog entry, as this is a comments-only change.)
=> make comments in test_multiline_... testcases easier to comprehend

news/xontrib-output-search.rst, xonsh/xontribs.json
**[xontrib-output-search](https://github.com/anki-code/xontrib-output-search)** is to get identifiers, names, paths, URLs and words from the previous command output and use them for the next command.
* <b>Save time</b>. Forget about using mouse, touchpad or trackball to get any words from output to the next command.
* <b>Secure</b>. The xontrib-output-search is not writing any output on the hard disk. Only latest not empty output stored in the memory. It works the same way as xonsh shell and the security level is the same.
* <b>Universal</b>. Forget about searching autocomplete plugins for every app you use and get the identifiers from the output.
Details in the [README](https://github.com/anki-code/xontrib-output-search).
=> New xontrib-output-search

docs/tutorial_xontrib.rst
Since laerus seems to have left github, and took the cookiecutter repo with him, I recreated it under the xonsh org from my fork.
This updates the docs to the new URL.
Docs-only change, no news required.
=> Update reference to xontrib cookiecutter repo

news/utf8.rst, xonsh/webconfig/main.py
=> Use UTF-8 encoding to write .xonshrc with webconfig

news/fix_pip_completer.rst, tests/completers/test_pip_completer.py, xonsh/completers/pip.py
Need a word-boundary now after the initial match
Resolves #3526
Resolves #3379
Signed-off-by: Gil Forsyth <gil@forsyth.dev>
=> Fix `pip` completer misfires for `pipx`

docs/tutorial_hist.rst, news/add-history-flush.rst, xonsh/history/main.py
This adds often-requested `history` `flush` action.
=> Add history `flush` action

news/ulimit.rst, xonsh/aliases.py, xonsh/xoreutils/ulimit.py
It was asked for in #3569.
```
$ ulimit --help
Usage: ulimit [-h] [-SH] [-a] [-cdefilmnqrstuv] [LIMIT]
Set or get shell resource limits.
Provides control over the resources available to the shell and processes it
creates, on systems that allow such control.
Options:
-h, --help
show this help message and exit
-S, --soft
use the 'soft' resource limit for the following arguments
-H, --hard
use the 'hard' resource limit for the following arguments (default)
-a, --all
show all current limits
-c, --core-size
the maximum size of core files created.
By setting this limit to zero, core dumps can be disabled.
-d, --data-size
the maximum size of a process' data segment
-e, --nice
the maximum scheduling priority (`nice')
-f, --file-size
the maximum size of files created by the shell and its children …
```
=> Add ulimit command to xoreutils

xonsh/xontribs.json
I'm now the owner of the [PyPI package](https://pypi.org/project/xontrib-fzf-widgets).
Thanks @shahinism for the contribution and for handing the ownership to me!
No news entry needed.
=> Update links to xontrib-fzf-widgets

news/fix-completion-out-of-bounds.rst, xonsh/completers/path.py
I got the following exception:
```
Unhandled exception in event loop:
File "C:\<redacted>\Python38\lib\concurrent\futures\thread.py", line 57
, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\<redacted>\Python38\lib\site-packages\prompt_toolkit\eventloop
\async_generator.py", line 43, in runner
for item in get_iterable():
File "C:\<redacted>\Python38\lib\site-packages\xonsh\ptk_shell\complete
r.py", line 44, in get_completions
completions, l = self.completer.complete(
File "C:\<redacted>\Python38\lib\site-packages\xontrib\free_cwd.py", li
ne 86, in wrapper
out = func(*args, **kwargs)
File "C:\<redacted>\Python38\lib\site-packages\xonsh\__amalgam__.py", l
ine 126, in complete
out = func(prefix, line, begidx, endidx, ctx)
File …
```
=> fix(completer): Add bounds check in path completer

news/fix-cwd.rst, xonsh/parsers/base.py
`os.path.dirname(__file__)` returns nothing because `__file__` contains only the file name. `os.path.realpath` has to be called first in order to retrieve the base path.
=> Fixed error in getting current working directory

.github/workflows/pytest.yml
This hopefully fixes the CI timeouts on Windows.
Closes #3616 
No news entry needed.
=> CI: increase pytest timeout

news/xontrib-failok.rst, xonsh/xontribs.py
`xontrib load` action can load multiple xontribs at once. If, however, one of the xontribs fails to load, because, for instance, of a missing dependency, the command exits and the rest of the modules is not attempted to load at all.
This patch modifies the `load` action behavior to only print exception on error, but to continue loading remaining xontribs.
=> xontrib: don't stop loading xontribs on error

news/failback_shell_env.rst, tests/test_environ.py, tests/test_main.py, xonsh/environ.py, xonsh/main.py
Re: #3523 
Proposed enhancement to try $SHELL (user's login shell) as first failback shell before trying ``/etc/shells``.
It requires the shell path to to exist and be different from the current (failing) Xonsh shell or it falls through to the system-wide file.
=> Failback shell env

news/improve-completers.rst, xonsh/aliases.py, xonsh/completers/base.py, xonsh/completers/completer.py, xonsh/completers/tools.py, xonsh/ptk_shell/completer.py, xonsh/readline_shell.py, xonsh/xontribs.json, xontrib/jedi.xsh
Hi!
This PR contains a few changes to the completers ecosystem:
These are two proposed API changes for completers.
A completer can return a `RichCompletion` object that can create better completion displays:
```python
return set(
RichCompleter(value, prefix_len, display, description)
for c in completions
)
```
```python
ptk_completer = xonsh.completers.tools.get_ptk_completer()
if ptk_completer is not None:
full_text = ptk_completer.current_document.text
row = ptk_completer.current_document.cursor_position_row + 1
```
* Use new Jedi API (inspired by #3594)
* Replace the existing python completer
* Create rich completions with extra info (inspired by IPython)
* Use entire multiline document if available (so the completion is more accurate)
* Complete xonsh special tokens
* Be aware of _ …
=> Improve completers and Jedi xontrib

news/fix-alias-return.rst, xonsh/proc.py
Callable aliases returning tuple may raise `TypeError` exception effectively hanging the shell, if the tuple contains values of unexpected type.
Fixes #3598.
=> Fix TypeError triggered by unexpected return from callable alias

news/fix-linecont.rst, tests/test_integrations.py, xonsh/execer.py
Fixes #3629. 
`_parse_ctx_free` uses `str.splitlines` to separate lines of the input for subsequent processing. `splitlines`, however ignores the trailing newline character, which is later missing in the re-assembled input string. This change makes sure that we don't lose the trailing newline.
=> Fix ctx-free parser stripping the trailing newline

news/xontrib-pdb.rst, xonsh/xontribs.json, xontrib/pdb.py
Once loaded, the xontrib runs pdb debugger on reception of SIGUSR1 signal.
=> Add pdb xontrib

.github/issue_template.md
I'm using this footer for issues and feature requests around a couple of years:
> **For community:**
>⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**
It works really great. People can react on issues or features and then we can [sort the list](https://github.com/xonsh/xonsh/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) of issues by count of reactions.
You can see how it works in real life if you open any issue in Metabase repo. For example - https://github.com/metabase/metabase/issues/1300
**For community:**
=> Issue template footer

xontrib/vox.py
The error message for `vox rm` wrongly assumed that `vox deactivate` needs an argument.
Example of the error in action:
```
(jnov) fermigier@mbp-stefane-abilian ~/projects/jnov master $ vox rm jnov
The "jnov" environment is currently active. In order to remove it, deactivate it first with "vox deactivate jnov".
(jnov) fermigier@mbp-stefane-abilian ~/projects/jnov master $ vox deactivate jnov
usage: vox [-h] {new,create,activate,workon,enter,deactivate,exit,list,ls,remove,rm,delete,del,help} ...
vox: error: unrecognized arguments: jnov
(jnov) fermigier@mbp-stefane-abilian ~/projects/jnov master $ vox deactivate
Deactivated "jnov".
```
=> Fix error message for `vox rm`

news/revert-abbrev.rst, xontrib/abbrevs.py
`abbrevs` word expasion can now be reverted by pressing the space bar second time immediately after the previous word got expanded.
Relates to (but does not close) #3642.
=> Revert abbrevs expansion on the second consecutive space keypress

news/fix-help-def.rst, xonsh/inspectors.py
This was broken two years ago by exceptionally inapt commit in #2918, that somehow passed completely unchecked and untested.
Closes #3621
=> Fix help operator not displaying definitions

news/fix-json-history.rst, xonsh/history/json.py
Due to $HISTCONTROL setting some history entries may not be always flushed to the file and the on-disk history may actually be shorter than it was in the in-memory buffer. This patch fixes the indexing error occuring under such condition.
This also fixes race condition between `JSONHistory` and `JSONHistoryFlusher` leading to on-disk history truncation.
Closes #3562
=> Fix json history

news/argv0.rst, tests/bin/checkargv0.xsh, tests/test_integrations.py, xonsh/built_ins.py
Currently Xonsh passes a resolved path of an executable as argv[0] argument. This changes the argv[0] to contain the command as inserted by the user. The new behavior is consistent with bash and other shells. Some programs behave differently in dependence on the argv[0] value.
Fixes #3617.
=> Set argv[0] of a subprocess to the command as inserted by the user

news/print-mocks-correctly.rst, xonsh/main.py
When evaluating mock objects, `pretty` returns the object's `.xonsh_display` attr which is itself a mock, and this fails later on:
We can handle it by calling `repr()` when it fails.
=> Call repr() when pretty() fails in _pprint_displayhook

xonsh/environ.py
This fixes a regression introduced in #3377, 
The fact that LC_MESSAGES could be missing was handled before. 
https://github.com/xonsh/xonsh/pull/3377/files#diff-b08c376dd29024ccd6f9aef90f2ea96fL836-L838
=> Fix regression with LC_MESSAGES missing in locale [No news entry needed.]

xonsh/environ.py
Improved fix for #3658, does not add `LC_MESSAGES` to environment if it's not defined in `locale`. Preapproved by @melund.
=> Fix regression with LC_MESSAGES, don't add to environment unconditionally [no news article needed].

news/test_suite.rst, tests/test_lib/test_os.xsh, tests/test_ptk_completer.py, tests/test_tools.py
Turned out that a few legitimate versions of the infamous 
```
AttributeError: module 'builtins' has no attribute '__xonsh__'.
```
had sneaked into the test suite. This fixes it.
=> Fix test suite

xonsh/platform.py
This fixes a bug when checking Prompt-toolkit version which @laloch  pointed out
This was addition to #3659  so no new entry needed.
=> Fix small issue when checking PTK version

setup.py
This fixes the problem where vended prompt-toolkit packages where not install when using `pip install .`
It uses setuptools.find_packages() to locate the prompt-toolkit packages. It works for me. @laloch can also test this?
=> Fix vended prompt_toolkit packages not beeing installed with pip

.github/workflows/black.yml, .github/workflows/elm.yml, .github/workflows/pytest-linux-3.6.yml, .github/workflows/pytest-linux-3.7.yml, .github/workflows/pytest-linux-3.8.yml, .github/workflows/pytest-macos-3.6.yml, .github/workflows/pytest-macos-3.7.yml, .github/workflows/pytest-macos-3.8.yml, .github/workflows/pytest-windows-3.6.yml, .github/workflows/pytest-windows-3.7.yml, .github/workflows/pytest-windows-3.8.yml, .github/workflows/pytest.tmpl
Fixes a problem with github CI running twice in pull requests
~It also removes the Appveyor CI scripts. They don't seem to be used any more~ (OK: let us do that in an other PR)
No news item needed.
=> Only run ci once per PR / push

news/env-yield-str.rst, tests/test_environ.py, xonsh/environ.py
Since #3377, the environment contains compiled regular expression patterns. Those `re.Pattern` objects are being returned as environment variable keys while iterating over `__xonsh__.env`. That unfortunately breaks the existing code, that expects the keys to be strings. For instance
```
File "/home/str/code/xonsh/xonsh/completer.py", line 36, in complete
out = func(prefix, line, begidx, endidx, ctx)
File "/home/str/code/xonsh/xonsh/completers/path.py", line 335, in complete_path
paths.update(filter(filtfunc, _env(prefix)))
File "/home/str/code/xonsh/xonsh/completers/path.py", line 103, in _env
return {
File "/home/str/code/xonsh/xonsh/completers/path.py", line 104, in <setcomp>
"$" + k for k in builtins.__xonsh__.env if get_filter_function()(k, key)
File …
```
=> Only return string keys while iterating over __xonsh__.env

news/abbrevs-set-cursor.rst, xontrib/abbrevs.py
`abbrevs` expansion now allows for setting cursor to a specific position within the expanded abbrev. For instance
```
abbrevs["eswap"] = "with ${...}.swap(<edit>):\n    "
```
expands `eswap` as you type to environment context manager ``swap()`` syntax and places the cursor at the position of the `<edit>` mark removing the mark itself in the process.
=> Allow for setting cursor position within expanded abbrev

news/env-hostname.rst, xonsh/environ.py
Adds `$HOSTNAME` and `$HOSTTYPE` variables that the user might expect to exist.
`$HOSTNAME` defaults to `platform.uname().node`.
`$HOSTTYPE` defaults to `platform.uname().machine`.
=> Add $HOSTNAME and $HOSTTYPE environment variables

news/fstrings.rst, tests/conftest.py, tests/test_parser.py, xonsh/ast.py, xonsh/built_ins.py, xonsh/codecache.py, xonsh/parsers/base.py, xonsh/parsers/fstring_adaptor.py
This replaces the current method of scanning f-strings for special Xonsh syntax using `string.Formatter`. The current code does only work in the simplest cases, because the syntax of `__format__` fields is just not the same as the syntax of f-string expressions plus the current code is simply buggy.
The replacement code tries to parse the f-string using `ast.parse` and only steps in if the parser raises `SyntaxError`. It then attempts to locate the offending expression and replaces it by a wrapper call which in turn calls `evalx` with the failing expression as an argument. It can already handle complex strings:
```
$ a=18
$ f"""foo {$TERM!s:{a}} {f"hot {${'LA'+'NG'}:{a}} dog"} bar"""
'foo xterm-256color     hot en_US.UTF-8        dog bar'
```
It can even handle captured subprocess …
=> Improve handling of f-strings

xontrib/vox.py, xontrib/voxapi.py
This is a follow-up to #3702.
No news item needed.
Virtual environment was impossible to delete after activation/deactivation cycle.
=> vox: Fix virtual environment removal

news/fix-multi-if-comps.rst, tests/test_parser.py, xonsh/parsers/base.py, xonsh/parsers/v36.py
List comprehensions do not ignore the second and subsequent ``if`` clauses in multi-if comprehension expressions anymore.
For instance `[x for x in "mom" if True if x in "mo" if x == "m"]` comprehension now correctly yields `['m', 'm']`, whereas previously it yielded `['m', 'o', 'm']`, because the parser was only generating AST for the first `if True` condition.
Closes #3713
=> Fix list comprehensions with multiple if clauses

news/return-star-expr.rst, tests/test_parser.py, xonsh/parsers/v38.py
Working towards Python 3.8 full compatibility.
This enables `return`s and `yield`s with starred expressions:
```python
def foo():
mylist = [2, 3]
return 1, *mylist
```
=> Add support for Python 3.8's starred expressions in return statement

news/pos-only-args.rst, tests/test_parser.py, tests/tools.py, xonsh/parsers/v38.py
Adds Python 3.8 PEP 570 positional-only parameters:
```python
def foo(x, /, y):
pass
min = lambda x, y, /: y if y < x else x
min(1, x=1)
TypeError: <lambda>() got some positional-only arguments passed as keyword arguments: 'x'
```
=> Add support for PEP 570 positional-only parameters

.github/workflows/black.yml
Current Black 20.8b0 version doesn't quite suite our needs right now.
This reverts back to v19.10b0 to make our CI green again.
It uses adjusted black-action from [laloch/black-action](http://github.com/laloch/black-action).
=> Stick to Black v19.10b0 for now

news/vox-combo-actions.rst, xontrib/vox.py
This adds `new --activate` and `deactivate --remove` actions to `vox` xontrib. Useful to create + activate and deactivate + remove virtual environments in a single command.
=> vox: Add combo new+activate and deactivate+rm actions

news/non-default-follows-default.rst, tests/test_parser.py, xonsh/parsers/base.py, xonsh/parsers/v38.py
Prevents parser from accepting argument lists where non-default parameter follows default parameter (`def foo(x=1, y):`)
Closes #3721
=> Raise error if non-default argument follows default argument

CHANGELOG.rst, news/incorrect-XONSH_HIST_SIZE-env.rst, xonsh/history/json.py
Fixed incorrect reference to $XONSH_HIST_SIZE instead of $XONSH_HISTORY_SIZE
=> Fixed incorrect reference to XONSH_HIST_SIZE

docs/_static/landing/js/theme.js
This fixes browsers complaining about
> Refused to display 'https://www.youtube.com/watch?v=uaje5I22kgE&feature=youtu.be' in a frame because it set 'X-Frame-Options' to 'sameorigin'."
We need to expand the shortened youtu.be link ourselves in order to be able to play it within an iframe.
No news item needed.
=> Fix video playback on xon.sh landing page

news/run-on-python39.rst, xonsh/lexer.py, xonsh/parsers/base.py, xonsh/parsers/v36.py
Make Xonsh run in Python 3.9
There's a lot of parser test cases failing in Python 3.9, but at least the shell runs and integration tests are green.
Closes #3618
=> Run in Python 3.9

news/argcomplete.rst, xonsh/xontribs.json
Added [xontrib-argcomplete](https://github.com/anki-code/xontrib-argcomplete) to support [kislyuk/argcomplete](https://github.com/kislyuk/argcomplete) - tab completion for argparse.
Closes  #1409
=> xontrib-argcomplete

docs/bash_to_xsh.rst, news/simple-variables.rst, tests/test_integrations.py, tests/test_parser.py, xonsh/built_ins.py, xonsh/parsers/base.py
This adds support for bash-like environment variable assignments preceding subprocess command.
```
$ $FOO="foo" $BAR=2 xonsh -c r"echo $FOO$BAR"
foo2
$ # Also works in pipelines...
$ $FOO="foo" $BAR=2 xonsh -c r"echo -n $FOO$BAR" | $FOO="nofoo" xonsh -c r"cat; echo $FOO"
foo2nofoo
```
=> Add optional variable initializers preceding command

news/shift-arrow.rst, xonsh/ptk_shell/key_bindings.py, xonsh/ptk_shell/shell.py
This incorporates shift-selection from prompt-toolkit, as suggested here https://github.com/xonsh/xonsh/issues/3515
Sample of the functionality. I don't know why the gif is so slow 😛 
Note: this issue https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1157 will need to be fixed before shift-selection will work. I gave it a shot here https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1212/files
=> Add shift selection from prompt-toolkit

xonsh/ptk_shell/shell.py
This only fixes formatting in xonsh/ptk_shell/shell.py, that someone recently merged despite the black test failing.
No news item needed.
=> Black ptk_shell

docs/conf.py, docs/guides.rst, docs/keyboard_shortcuts.rst, news/shortcut-docs.rst
Figured it might be nice to follow up the shift-selection ticket with a doc page on all the various keyboard shortcuts available to xonsh.
=> Docs for keyboard shortcuts

news/xontrib-shift-select.rst, xonsh-in-docker.py, xonsh/ptk_shell/shell.py
Resolves #3759. Caused because https://github.com/xonsh/xonsh/pull/3697/ created a regression on xontrib loading -- sorry! This feels like not a great fix, but just wanted to leave xontribs in a not-broken state on master.
```
$ gst
xonsh: subprocess mode: command not found: gst
Did you mean one of the following?
ls:   Alias
gtb:  Alias
git:  Command (/usr/local/bin/git)
rs:   Command (/usr/bin/rs)
su:   Command (/usr/bin/su)
$ xontrib load abbrevs
$ abbrevs['gst'] = 'git status'
$ [typed gst, turned into git status] git status
On branch abbrevs
Your branch is up to date with 'origin/abbrevs'.
nothing to commit, working tree clean
$
```
=> Fix error on xontribs loading

news/simple-variables.rst, tests/test_parser.py, xonsh/parsers/base.py
#3745 introduced huge amount of shift/reduce conflicts around DOLLAR_NAME token breaking the parser in some cases. This restricts the leading variable assignment (`$FOO="bar" command`) syntax by forbidding whitespace around the `=` equals operator.
I'm sorry about breaking the parser and I really dislike this change. Perhaps, there's a better solution, but it's currently beyond my parser-fu to find it.
Fixes #3764
Thanks @anki-code for reporting the bug.
=> Fix environment variable assignment grammar ambiguity

xonsh/built_ins.py
@scopatz This is just a black fix to something I accidentally pushed directly to master. When rolled back it will become a proper PR. 
This fixes a problem where a running windows 10 app execution aliases causes xonsh to throw a traceback. Fixes #3752 
The reason is that app execution aliases behave weirdly with Python.  They show up when running os.listdir() and they can be used as arguments to popen (esentially CreateProcess resolves them). But we can't open them and os.path.exists() returns False. `pathlib.Path(fname).exists()` throws an invalid argument error. 
This fixes the problem and allows xonsh to run the app execution aliases on Windnows.
=> Fix app execution aliases on windows

news/ptk-complete-select-first.rst, xonsh/ptk_shell/key_bindings.py
An unsolicited "enhancement" to ptk completion.
TAB character now automatically selects first completion when it starts completion, rather than simply displaying the completion options.  This more closely mimics behavior of `TAB menu-complete` in readline.  I'd argue this is more in the nature of a bug fix than enabling new behavior, so  I didn't implement a configuration option, simply changed the behavior.
=> TAB key automatically selects first completion when starting completion.

news/cache-executables-in.rst, tests/test_tools.py, xonsh/tools.py
When you put a not-recognized command, it takes a second to respond the error. The vast majority of this time seems to be finding command suggestions. If we use the commands_cache instead, it speeds up ~6x when there's no suggestions.
BEFORE:
```
$ timeit "asdfasdfasdf"
...
xonsh: subprocess mode: command not found: asdfasdfasdf
1 loops, best of 3: 544 ms per loop
```
AFTER:
```
$ timeit "asdfasdfasdf"
...
xonsh: subprocess mode: command not found: asdfasdfasdf
10 loops, best of 3: 90.4 ms per loop
```
On the other hand, there's basically no change in performance when it does find a suggestion.
=> Use commands_cache when finding suggestions

news/shift_del.rst, xonsh/completers/tools.py, xonsh/history/json.py, xonsh/parsers/fstring_adaptor.py, xonsh/xoreutils/ulimit.py, xontrib/whole_word_jumping.py
xi! xonsh is amaxing and xool! xanks!
Added Shift+Delete hotkey to delete whole word in xontrib whole_word_jumping.
The hotkey should be Control+Backspace like in many editors (i.e. Kate) but https://github.com/prompt-toolkit/python-prompt-toolkit/issues/257#issuecomment-190328366
=> xontrib whole_word_jumping: Delete whole word with Shift+Delete

news/ansi_osc.rst, tests/test_ptk_shell.py, xonsh/ptk_shell/shell.py
Improved version of #3781, with generic ANSI OSC escape sequence support.
Fixes #374 and #1403.
=> ANSI OSC escape sequence support (including title setting)

docs/tutorial_hist.rst, news/history_testing-ead.rst, tests/test_history.py, tests/test_history_sqlite.py, xonsh/environ.py, xonsh/history/base.py, xonsh/history/json.py, xonsh/history/main.py, xonsh/history/sqlite.py
Solves #3033.
Provides `history clear` which purges past commands from the current session; `history off`, which stops any history from being saved from the entire current session; and `history on`, which re-enables history saving in the current session. 
Works for both JSON and SQLite backends, and it works on both the history buffer and on history already saved to disk.
Builds off of #3691. Thank you @Itay4 for starting out.
=> Commands to easily manage deletion of history from the current session.

news/prompt-speed.rst, xonsh/prompt/vc.py
There is a fraction of a delay on the prompt when you press enter. I imagine this is quite a tough case to crack, so this is just a start!
1. Showing the branch name seems to re-roll the `git rev-parse --abbrev-ref HEAD` function. This probably isn't great if there's lots of local branches for a user. I swapped it.
2. Locate binaries even more lazily. To be honest, I can't really track that much of a performance increase from this one, so down to revert it.
3. More efficient ways of finding whether a dirty working directory. Borrowed this from [this github conversation](https://github.com/sindresorhus/pure/issues/115).
**Results**:
Hard to evaluate this since the terminal speed is different each time ya run it. But for me, when in the xonsh repo, it seems to switch from an average of …
=> Minor performance improvements to the prompt

news/onepath.rst, xonsh/xontribs.json
Added [xontrib-onepath](https://github.com/anki-code/xontrib-onepath) to associate files with apps in xonsh shell like in graphical OS.
=> Added xontrib-onepath

news/dwd-bugfix.rst, xonsh/prompt/vc.py
Oops! The "||" did not do what I thought it did.
(It ran the first command, and if that command gave a 1, then ran the second command and returned the result of the second command.) Instead, I'll just keep the two checks in their own commands.
=> Fix logic in working directory check

news/xontrib-powerline-binding.rst, xonsh/xontribs.json
Added `xontrib-powerline-binding` to xontrib list.
It's not a *yet another* powerline like prompt theme, but actually uses `powerline` to render the prompt (+ the bottom toolbar, if configured).
=> xontrib-powerline-binding added to xontrib list

docs/tutorial.rst, news/tutorial_literal.rst
Closes #3820
The code to getting an rst table of literals: 
<details>
```python
#!/usr/bin/env xonsh
import pandas as pd
import pytablewriter
str_literal = [
'"/$EVAR/\\\'{var}\\\'"',
'r"/$EVAR/\\\'{var}\\\'"',
'f"/$EVAR/\\\'{var}\\\'"',
'fr"/$EVAR/\\\'{var}\\\'"',
'p"/$EVAR/\\\'{var}\\\'"',
'pr"/$EVAR/\\\'{var}\\\'"',
'pf"/$EVAR/\\\'{var}\\\'"',
]
def code(s):
return f"``{s}``"
$EVAR = 1
var = 2
tbl = {}
for s in str_literal:
locs = {'var': var}
tbl[code(s)] = {
'As python object': code(repr(evalx(s, locs=locs))).replace('Posix', ''),
'print(<String literal>)': code(evalx(f'str({s})', locs=locs)),
}
execx(f'echo {s} > 1.tmp', locs=locs)
with open('1.tmp') as f:
l = f.readline()
tbl[code(s)]['echo <String literal>'] = code(l.strip())
df = pd.DataFrame.from_dict(tbl).T …
```
=> Added "Advanced String Literals" to the "Tutorial".

news/no_color_deprecation.rst, xonsh/aliases.py, xonsh/base_shell.py, xonsh/diff_history.py, xonsh/inspectors.py, xonsh/readline_shell.py, xonsh/style_tools.py, xonsh/tracer.py, xonsh/wizard.py, xonsh/xonfig.py, xonsh/xontribs.py
=> changed internal usage of NO_COLOR to reset

xonsh/ptk_shell/key_bindings.py
This reverts the changes made in #3774 and fixes #3833 
As I outlined in #3833 this makes some assumptions that impact a bunch of tab-completion features.
Another example I've come across today is if I `cd <TAB>` -- the `..` present in every directory on a *nix is automatically selected, preventing me from typing another character to narrow the completion possibilities.
=> Revert completion auto-selection

news/args.rst, news/norc_no_welcome.rst, xonsh/main.py
Hello! xonsh is the most interesting thing in world ocean! Thanks!
In this PR xonsh arguments improved with love:
1. Capitalized first letter in args help text.
2. Used [argparse "version" action](https://docs.python.org/3.5/library/argparse.html#action) to show version.
3. Suppressed old deprecated `--config-path` (deprecated since 2018).
4. ~Disabled the welcome screen if `--no-rc` was passed.~ (reverted)
5. Improved formatting of help for `--shell-type`:
Before - ugly "usage" lines and description:
```
$ xonsh --help
usage: xonsh [-h] [-V] [-c COMMAND] [-i] [-l] [--rc RC [RC ...]] [--no-rc] [--no-script-cache]
[--cache-everything] [-D ITEM]
[--shell-type {b,best,d,dumb,ptk,ptk1,ptk2,prompt-toolkit,prompt_toolkit,prompt-toolkit1,prompt-toolkit2,prompt-toolkit3,prompt_toolkit3,ptk3,rand,r …
```
=> xonsh arguments improvement

docs/bash_to_xsh.rst, docs/tutorial.rst, news/printx.rst, xonsh/built_ins.py
Hi! xonsh is better and better after every PR!
The second thing (after builtin exit) I really miss while writing xonsh scripts is a simplest way to print colored messages. Colors make terminal alive and this is the good way to give developers easiest way to do print with colors without imports/xonshrc/xontribs.
Before this PR:
```python
from xonsh.tools import print_color   # imports... I love imports... but when I'm doing it every day...
print_color('{RED}Color!')      # long names... I love long names... but my keys are erased already...
```
After this PR:
```python
printx('{RED}Color!')    # any time, everywhere, just when the thought got into the head
```
=> Added printx to builtins

news/completer_exception.rst, xonsh/completer.py
Closes #3844
Before - in case of exception in completer there will be crash and fallback to bash.
After:
```python
def bad_completer(pref, line, *args):
1/0
completer add test bad_completer start
$ <Tab>
```
Result:
```
File "/opt/miniconda/lib/python3.8/site-packages/xonsh/completer.py", line 39, in complete
out = func(prefix, line, begidx, endidx, ctx)
File "<xonsh-code>", line 2, in bad_completer
ZeroDivisionError: division by zero
Completer bad_completer raises exception when get (prefix='', line='', begidx=0, endidx=0):
division by zero
$ # stay in xonsh
```
=> More stable exception handling in the completer.

docs/tutorial.rst, news/env_path_imp.rst, tests/test_environ.py, xonsh/environ.py, xonsh/tools.py
1. Fixed missing `*DIRS` (mention was in the doc but missing in the code) + test
2. Added section "Register typed environment variables" to the Tutorial.
3. Improved `str_to_path` converter.
After many closed PRs around environ register this should be in the near release.
=> Environ improvements: DIRS, tutorial, converter

docs/tutorial.rst, news/env_path_imp.rst
Reverted docs because improvement of `register` postponed (#3850).
=> Reverted "Register typed environment variables"

news/prevent-git-locking-when-getting-status.rst, xonsh/prompt/vc.py
Set GIT_OPTIONAL_LOCKS=0 to prevent locking a git repo when updating the prompt.
=> Prevent loging git when building prompt

xonsh/environ.py
Should only be used for setting
No news item needed, because no release has happened. 
CC @xonsh/xore
=> removes validation on getting environment variables. 

news/no_color_deprecation.rst, xonsh/color_tools.py, xonsh/style_tools.py, xonsh/tools.py
This commit improves the current deprecation warning for NO_COLOR by allowing to show the traceback if XONSH_SHOW_TRACEBACK is set to True.
See https://github.com/xonsh/xonsh/pull/3793#issuecomment-703290727 for reasoning.
It also adds a new xonsh tool function: print_warning.
It is similar to print_exception, however it requires a message, as there is no exception.
=> Add an optional message to the deprecation warning

news/fix-async-prompt-invalid-cache-hit.rst, xonsh/prompt/base.py
this causes the getter to return every one in two times.
run 1-> the prompt is built the cache is cleared , but the async worker
updates the cache
run 2 -> the value is get from cache and no async worker created for
that field. cache is cleared after the prompt is built
=> fix: async prompt workers update cache at the end

news/xontrib_list_reset.rst, xonsh/xontribs.py
=> Fix reset color xontrib list

news/COMPLETIONS_CONFIRM.rst, xonsh/environ.py
Closes #2364
1. _Originally posted by **gforsyth** in https://github.com/xonsh/xonsh/issues/2364#issuecomment-433938037_
> Hey @ahundt -- I'm definitely game for setting `$COMPLETIONS_CONFIRM=True` as the default -- if we get a quorum of @xonsh/xore to agree to that we can change the default.
2. _Originally posted by **scopatz** in https://github.com/xonsh/xonsh/issues/2364#issuecomment-440098857_:
> I am in favor of `$COMEPLETIONS_CONFIRM = True` if someone wants to put in a PR
3. _Originally posted by **anki-code** in https://github.com/xonsh/xonsh/issues/2364#issuecomment-706241263_
> I also use COMPLETIONS_CONFIRM as True value because when you choose the item from list you want to choose next but you can't (in case of `False` setting) because Enter key will execute the command. BUT …
=> COMPLETIONS_CONFIRM is True by default

docs/bash_to_xsh.rst, news/doc-bash-env-escape.rst
This method was already documented in the tutorial, but it took me a while to find it there. I thought it would be a good addition to the bash to xonsh guide as well.
=> Document variable escaping in bash_to_xonsh

news/fix-v39-fstrings.rst, xonsh/parsers/fstring_adaptor.py
The f-strings parser is very sensitive to changes in the textual representation of the exceptions raised by the Python parser. There seems to be a bug introduced in Python 3.9 causing the exception text to be terminated by an extra newline character.
Fixes #3865
=> Fix f-string parsing in Python 3.9

news/appimage_python.rst, rever.xsh
Pin AppImage python until full support of python 3.9.
Update Rever before merge: https://github.com/regro/rever/pull/235
=> Rever: pin AppImage python version

docs/bash_to_xsh.rst
News file is not required.
Closes #3889
=> Docs: Get PID of the current shell.

docs/_templates_overwrite/index.html
Fix typos on index page. Don't think this really deserves a news item, but let me know if you want me to do one up.
=> docs: fix typos

news/xog.rst, xonsh/xontribs.json, xontrib/xog.py
This adds `xog` internal xontrib - a simple command to establish and print temporary traceback log file.
Feel free to reject this as being more suitable for external xontrib.
=> Add xog xontrib

news/fix_prompt_toolkit_version.rst, requirements/docs.txt, requirements/tests.txt, setup.py
Fixed dependency problem with prompt-toolkit. Xonsh required version >=2.0 but in code features from >=3.0 was used.
=> Updated prompt-toolkit version requirement

news/exec-aliases-on-io-operators.rst, tests/test_aliases.py, xonsh/aliases.py
Currently after setting
```python
aliases['test'] = 'ls | wc'
```
Running `test` will result in `ls | wc` being printed to the screen.
The reason is `Aliases.__setitem__` parses this into a list instead of into an `ExecAlias` object.
The fix is to add the IO operators (`>`, `<`, and `|`) to the regex that decides whether to create an `ExecAlias` or not.
=> Create ExecAlias for aliases that contain IO operators

news/timing_lexer.rst, xonsh/ptk_shell/shell.py, xonsh/readline_shell.py, xonsh/shell.py, xonsh/timings.py
Hi! 
1. I've found that PygmentsLexer takes much time on first start and I add timing probe to show it.
2. I've found that `prompt_tokens` takes much time and I add timing probe to show it.
3. Added `on_before_prompter_prompt` event to show timings in the right place.
Example of no-rc start:
```
xonsh --timings --no-rc
|-------------------------------|-----------|-----------|
|Event name                     | Time (s)  | Delta (s) |
|-------------------------------|-----------|-----------|
|start                          |   0.000   |   0.000   |
|pre_execer_init                |   0.016   |   0.016   |
|post_execer_init               |   0.064   |   0.048   |
|on_pre_rc                      |   0.064   |   0.000   |
|on_post_rc                     |   0.064   |   0.000   |
|on_ptk_create …
```
=> Added timing probes

news/zoxide_gitinfo.rst, xonsh/xontribs.json
Adds `xontrib-zoxide` and `xontrib-gitinfo` to the list of xontribs.
"Fixes" #3910.
=> zoxide & gitinfo xontribs added to the list of xontribs

.github/workflows/genbuilds.xsh, .github/workflows/pytest-linux-3.6.yml, .github/workflows/pytest-linux-3.7.yml, .github/workflows/pytest-linux-3.8.yml, .github/workflows/pytest-linux-3.9.yml, .github/workflows/pytest-macos-3.6.yml, .github/workflows/pytest-macos-3.7.yml, .github/workflows/pytest-macos-3.8.yml, .github/workflows/pytest-macos-3.9.yml, .github/workflows/pytest-windows-3.6.yml, .github/workflows/pytest-windows-3.7.yml, .github/workflows/pytest-windows-3.8.yml, .github/workflows/pytest-windows-3.9.yml, .github/workflows/pytest.tmpl, news/github_workflow.rst
Xonsh currently has a good number of broken tests when run under Python 3.9, but they are invisible when no tests are run for them. This PR adds Python 3.9 to the CI.
=> Add Python 3.9 to GitHub workflows

news/custom_prompt_tokens_formatter.rst, scent.py, xonsh/environ.py, xonsh/prompt/base.py, xonsh/ptk_shell/formatter.py, xonsh/ptk_shell/updator.py
Now the users can format the prompt as they like.
=> feat: add settings to set custom function to format prompt

news/print_color_3840.rst, xonsh/tools.py
Added a fallback for `xonsh.tools.print_color` (and `xonsh.tools.format_color`) if shell is not yet initialized, thus enabling their use in `.xonshrc`.
Fixes #3840 .
=> Fallback for `print_color` if shell is not yet initialized

news/run-tests-xsh.rst, run-tests.xsh
Adding this because I tried running `./run-tests.xsh` a few times and didn't understand what was going on :)
=> run-tests.xsh without arguments now prints help

news/add-xontrib-powerline2.rst, xonsh/xontribs.json
Development of `xontrib-powerline` has been halted.  
- https://github.com/santagada/xontrib-powerline/issues/25
- https://github.com/vaaaaanquish/xontrib-powerline2/issues/5
`xontrib-powerline2` is a fork of `xontrib-powerline`.  I've only developed a few. I salute the @santagada :)
Add an `xontrib-powerline2` to the documentation for new xonsh users.
=> Add xontrib-powerline2

news/path_warn.rst, xonsh/environ.py
The limit 10000 was for counter of files read but because we use count of unique keys in the check for warning the limit should be decreased to make it valuable.
Closes #3948
=> Decrease command cache warn limit

news/ptk-menu-complete.rst, tests/test_tools.py, xonsh/environ.py, xonsh/ptk_shell/key_bindings.py, xonsh/tools.py
Improving on #3774, this implements TAB completion like `readline` `menu-complete` mode., along with an option to enable it, environment variable `$COMPLETION_MODE`.  Default is, umm, `default`, which retains the current tab completion behavior.  `menu-complete` enables the new behavior.
=> Add $COMPLETION_MODE='menu-complete' to enable readline menu-complete

news/fix-ptk-completion-window-reserve_space.rst, xonsh/ptk_shell/completer.py
=> fix: 'Window' object has no attribute 'children'

docs/tutorial.rst, news/command-pipeline-raw-out.rst, tests/test_pipelines.py, xonsh/built_ins.py, xonsh/procs/pipelines.py
This PR allows using a command's binary output as a python object.
For example:
```python
x = !(head -c 100 /bin/python3).raw_out
```
Also closes #3954
=> procs: Add CommandPipeline.raw_out for retreival of the raw stdout bytes

news/path_complete_path_literal.rst, tests/test_path_completers.py, xonsh/completers/path.py
Hey,
Thanks for all your great work - this is my first PR to `xonsh`, so let's see how I do ;-)
This is a PR to enable path completion of path literals, which without can be very frustrating
```
path = p"some/super/duper/long/path/to/comple<TAB> # :-(
```
I've added some minor modifications such that the `p` prefix is removed from the string passed to `ast.literal_eval` in `xonsh.completers._path_from_partial_string`, and also removed from the start of the path used by `xonsh.completers.complete_path`.
Please note that I don't have a deep understanding of these functions, but have implemented a few tests.
Let me know what you think.
Many thanks
=> Path complete given path literal

xonsh/commands_cache.py
=> some logic cleanup

news/ulimit-default-soft.rst, xonsh/xoreutils/ulimit.py
It makes more sense for `ulimit` builtin to manipulate "soft" limits by default, because those are the limits intended to be user-adjustable. It is also what bash does. Originally, I made `ulimit` to default to "hard" limits, because I was for some reason convinced that it's what bash does.
Relates to #3988
=> ulimit: Change default to access soft limits

docs/xonshrc.rst, news/vc_branch-in-docs.rst
i assume this module got renamed at some point, but the docs weren't updated to reflect that
=> Fix the import in the branch colour override example.

news/colorize-and-or.rst, xonsh/pyghooks.py
Really tiny fix that bothered me :)
Before:
After:
=> pygments: Colorize 'and'/'or' keywords like '&&'/'||'

news/xontrib-commands.rst, xonsh/xontribs_meta.py
not exactly the same. but a small start
#3977 
Let me know if you want to add this to xonsh itself. I wanted to use nice rich.Table . I know you would be against using 3rd party libs. So here it is .
=> feat: add xontrib-commands

xonsh/style_tools.py
- happens when the prompt field returns non-strings
- not including news item since it is a small change no significant change and no reported issues
=> fix: make sure that tokens are strings before showing in prompt

news/hist_sqlite_stdout.rst, xonsh/history/sqlite.py
Current inconsistent logic of storing stdout in memory:
```python
echo 123
__xonsh__.history[-1].out
echo 123
__xonsh__.history[-1].out
```
After this PR the logic becomes consistent:
```python
echo 123
__xonsh__.history[-1].out
echo 123
__xonsh__.history[-1].out
```
=> SQLite history backend now has the same logic of storing stdout to the memory like json history backend

news/edit-pythonpath-while-loading-rcs.rst, tests/test_main.py, xonsh/environ.py
This PR makes it so that xonsh changes the `sys.path` while loading RC files, to make sure that it can load modules located in the same folder. This closes #3936.
=> Edit sys.path while loading RC files

news/history_json_faster.rst, xonsh/history/json.py, xonsh/lazyjson.py
Closes #4000
Test:
```python
pip uninstall ujson
XONSH_DEBUG=1 xonsh
pip install ujson
XONSH_DEBUG=1 xonsh
```
=> Using ujson (if installed) in LazyJSON to loading json history 15% faster

news/alias_merging.rst, tests/test_aliases.py, xonsh/aliases.py
This PR allows you to do the following:
```python
my_aliases = {
'ip': 'ip -c',
'gst': 'git status'
}
aliases |= my_aliases
```
=> Add 'dict' merging operation for the aliases class

README.rst, news/google_cloud_shell_button.rst
Will look like this: 
<a align="center" href="https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/xonsh/xonsh.git"><img alt="Open in Cloud Shell" src ="https://gstatic.com/cloudssh/images/open-btn.svg"></a>
=> Add `Open in google cloudshell` in the readme.

setup.py, xontribs.json
so that will work with relative paths
- update extras-requirement full
- remove invalid link
fixes #4039
=> fix: update setup.py table generation function

xontrib/distributed.py
Without the brackets python defaults to assuming that the iterable is a tuple. In the reference guide `__all__` is explicitly stated to be of type `list`.
Functionally I'll admit this doesn't change anything but to observe the correct usage pattern of `__all__`, simply add the brackets.
=> Add brackets to ambiguous data type

news/fix_freebsd_libc_uptime.rst, xonsh/platform.py, xonsh/xoreutils/uptime.py
This is a possible fix for the libc detection bug on Freebsd, as discussed in #4048.
- Fix libc detection on FreeBSD
- sysctlbyname needs bytes, not unicode strs
- Add news item for FreeBSD libc fix
=> Fix libc detection and uptime functionality on FreeBSD

appimage/pre-requirements.txt
Added `ujson` to AppImage to support #4025 #4000
News is not needed.
=> Added ujson to appimage

README.rst, rever.xsh
The rever command hasn't been tested with the new parameters to
`run-tests.xsh` (spoiler alert, it breaks).
Also converted the `raw` block to regular RST since PyPI doesn't allow
`raw` directives in the `long_description` on upload to PyPI
=> Fix readme and rever test call for release

docs/aliases.rst, docs/tutorial.rst, news/job-ctrl-disown.rst, xonsh/aliases.py, xonsh/environ.py, xonsh/jobs.py, xonsh/procs/posix.py, xonsh/procs/specs.py
Relevant issues: #2346 and #1246
This pr adds a "disown" command to the shell. The behavior is modeled after zsh's "disown" builtin command, with the main differentiating factor being that zsh's `disown [job] &|` syntax is super esoteric so I decided to replace it with the options `-c` or `--cont`
Example usage:
```sh
nate@spicy-tuna ~/ > nemo &
[1]+ running: nemo & & (107246)
nate@spicy-tuna ~/ > disown
Removed job 1 (running)
```
```sh
nate@spicy-tuna ~/ > $THREAD_SUBPROCS=False
nate@spicy-tuna ~/ > nemo
^Znate@spicy-tuna ~/ > jobs
[1]+ stopped: nemo (107323)
nate@spicy-tuna ~/ > disown -c 1
Removed job 1 (running)
```
```sh
nate@spicy-tuna ~/ > $THREAD_SUBPROCS=False
nate@spicy-tuna ~/ > nemo
^Znate@spicy-tuna ~/ > jobs
[1]+ stopped: nemo (107408)
nate@spicy-tuna ~/ > disown
warning: …
```
=> add disown command

news/xontrib-cd.rst, xonsh/xontribs_meta.py
this xontrib allows a user to `cd` to any path without escaping by automatically replacing `cd ` with `cd! ` in the beginning of any command
=> feat: add xontrib-cd

news/chmod_history_file.rst, xonsh/history/json.py, xonsh/history/sqlite.py
History files (json, sqlite) now have ``600`` (``-rw-------``) permission by default.
=> Strict permission for history file (json, sqlite)

news/fix-cd-rmdir-completions.rst, xonsh/completers/dirs.py, xonsh/completers/path.py
This fixes issues with the cd and rmdir completers not working correctly due to `os.path.isdir` returning false for paths like '\~/example'. That causes the filtering in `complete_path` to always remove all path completions when the prefix has a '~', which in turn causes the cd and rmdir completers to return nothing. That seems to trigger the general path completer to run, which returns all paths with the given prefix, including files.
This PR moves the filtering step in `complete_path` to before the 'unexpanding' step, which seems to resolve the issue. I have not added a test for this case, as it's not clear to me if the infrastructure in tests/competers can handle this case.
=> Perform path completion filtering based on expanded path

CHANGELOG.rst
Noticed a typo in the RST text that prevents parsing a link as such.
Not sure this is the proper way to fix this typo, but the [devguide](https://xon.sh/devguide.html#changelog) only mentions adding news to the new releases, not fixing typos in the already released changelog
=> fix: RST link typo

news/xontrib-linuxbrew.rst, xonsh/xontribs_meta.py
Since Homebrew on Linux doesn't support xonsh and rejected a PR to it natively, made this xontrib to automatically update shell environment on Linux to include Homebrew's vars and paths
=> feat: add xontrib-linuxbrew

news/welcome_message.rst, xonsh/xonfig.py
Closes #4141
Closes #2401
* Added warning about shell type.
* A bit fix of colors.
* Removed two phrases about bash because xonsh is not sh-compatible in fact.
Appearance:
<details>
</details>
=> Welcome message: fix color, add ptk warning

docs/_templates_overwrite/index.html, docs/packages.rst
To avoid errors in zsh/xonsh we need to add quotes
```python
zsh
pip install xonsh[full]
xonsh
pip install xonsh[full]
```
No news
=> docs: added quotes to pip install

docs/_templates_overwrite/robots.txt
Hi @gforsyth !
I've added `robots.txt` file to avoid crawling` / dev / `content.
But I'm not sure that this file will appear as `https://xon.sh/robots.txt` because I don't understand how the building of the site is working. Please check me.
No news file
=> docs: added robots.txt

news/fix_xonfig.rst, xonsh/xonfig.py
=> fix: xonfig exception without rc

news/BOM-bug.rst, xonsh/imphooks.py
Since the changed encoding is only used to decode a file and 'utf-8-sig' behaves the same way as 'utf-8' when no BOM is present, we can use it as a drop-in replacement and not detect BOM separately
Closes #4160
=> fix: use 'utf-8-sig' instead of 'utf-8' to allow importing modules with a BOM

xonsh/shell.py
This is the small fix for #4178 that bring back the previous logic in the check to properly load gc.
@gforsyth please merge asap.
No news file
=> fix: fix gc check

docs/_static/robots.txt
Removing old documentation from search:
https://xon.sh/docs-ahundt-sphinx-readable-theme-pypi/api/aliases.html
No news
=> docs: Update robots.txt to removing old documentation from search

news/fix_prompt_like_title.rst, xonsh/environ.py
According to the documentation $TITLE should work like $PROMPT but it was restricted to be `string` instead of `string_or_callable`.
Fixes #4148 .
=> #4148 $TITLE can be set to a function

news/PEP263upd.rst, xonsh/imphooks.py
Noticed the PEP 263 update while fixing a BOM bug, though not sure this has any effect
=> update imphooks encoding regex to match the newer version at PEP 263

news/improve-which-output.rst, xonsh/aliases.py, xonsh/xoreutils/which.py
```python
aliases['a'] = 'ls'
aliases['b'] = 'ls | grep b'  # ExecAlias
aliases['c'] = lambda args: print(args)
```
Before:
```python
which a b c
```
After:
```python
which a b c
```
=> Improve `which` output

news/fix-json-hist-gc-seconds.rst, tests/test_history.py, xonsh/history/json.py
I was getting the warning "History garbage collection would discard more history than it would keep" every time I opened a shell. I use JSON history with XONSH_HISTORY_SIZE specified in seconds. As of #3600, the history filter was returning the timestamp of the oldest history file, but this value was being interpreted as the amount of history that would be removed. (That value should be oldest_kept - oldest_removed.) Thus whenever the gc was supposed to trigger, instead it issued a warning and did nothing.
=> Fix garbage collection of JSON history specified in seconds.

CONTRIBUTING.rst, docs/_templates_overwrite/index-old.html, docs/_templates_overwrite/index.html, docs/links.rst, docs/packages.rst, docs/tutorial.rst, docs/tutorial_xontrib.rst
Couldn't update to `HEAD` since the link was pointing to the outdated `master.zip`, so changed that and also edited a few other outdated references
Didn't add a changelog entry as I think these edits are too minor to mention, but let me know if you think otherwise
=> Updated references to point to 'main' instead of 'master'

news/subproc_captured_print_stderr.rst, tests/test_integrations.py, xonsh/environ.py, xonsh/procs/pipelines.py
Closes #4021
Related #4220
Added XONSH_SUBPROC_CAPTURED_PRINT_STDERR environment variable to hide unwanted printing the stderr when using captured object.
Example:
```python
def _test_stream(args, stdin, stdout, stderr):
print('hallo on err', file=stderr)
print('hallo on out', file=stdout)
return 1
aliases['test-stream'] = _test_stream
x = !(test-stream)
print(x.returncode)
with __xonsh__.env.swap(XONSH_SUBPROC_CAPTURED_PRINT_STDERR=False):
x = !(test-stream)
print(x.returncode)
```
=> feat: Added environment variable to hide unwanted printing the stderr when using captured object.

news/improve-bash-completions.rst, tests/completers/test_bash_completer.py, xonsh/completers/bash.py, xonsh/completers/bash_completion.py
This PR passes the parsed command line (the real arguments and quotes to use).
Generally, the following scenarios functioned badly until now:
```
ls '/pro<TAB>
ls '/pro<TAB>'
ls './spa<TAB>'
ls './spa'<TAB>
ls './spaced d<TAB>
```
A matching PR is open at https://github.com/xonsh/py-bash-completion/pull/19
=> Improve bash completions - Pass parsed command line to py-bash-commands

news/json_history_dir.rst, xonsh/history/json.py
Hi!
To keep `XONSH_DATA_DIR` clean the history json files now will be in `XONSH_DATA_DIR/history_json` directory.
The backwards compatibility of reading the history json from `XONSH_DATA_DIR` is on board.
=> Put history json to subdirectory

docs/tutorial.rst, news/alias_args.rst, tests/test_aliases.py, xonsh/aliases.py
This PR adds `$args` and `$arg0`..`$arg<n>` environment variables to the `ExecAlias` context. Motivation: https://github.com/xonsh/xonsh/pull/4201#issuecomment-810754606
Exampls:
```python
aliases['my'] = "echo Hello @($args)"    # ExecAlias
my 'world!'
```
```python
aliases['cl'] = "cd $arg0 && ls $arg0"
cl /tmp
```
=> feat: Added ability to get arguments list in ExecAlias

xonsh/aliases.py, xonsh/ansi_colors.py, xonsh/ast.py, xonsh/built_ins.py, xonsh/commands_cache.py, xonsh/events.py, xonsh/foreign_shells.py, xonsh/inspectors.py, xonsh/lexer.py, xonsh/openpy.py, xonsh/pyghooks.py, xonsh/tools.py, xonsh/winutils.py, xonsh/wizard.py
this uses https://github.com/Carreau/velin to try to autoreformat all
docstrings in xonsh/*.py
In particular in Parameters section the space before the colon is
necessary for numpydoc to properly find the name and the type.
When no type is there numpydoc says that colon should be removed.
This also try to find if there are typo in parameter names and fix them
when possible.
As a sideeffect of parsing with numpydoc and reconstructing the
docstring from the parsed data some whitespace information is lost; but
that has the advantage of making the whitespace rules uniform
everywhere.
=> DOC: Autoreformat most of the docs.

news/fix_aliases_infinite_loop.rst, tests/test_commands_cache.py, tests/test_integrations.py, xonsh/procs/proxies.py, xonsh/procs/specs.py
Closes #3159
Now we have transparent way to wrap commands into callable aliases.
Example 1:
```python
def _echo(args):
echo @(args)
aliases['echo'] = _echo
echo ok
```
Example 2 - elegant ExecAlias (it will be awesome with #4201):
```python
aliases['echo'] = "echo @('ok')"  # ExecAlias
echo
```
Example 3 - show error for the user without freezing
```python
aliases['first'] = "second @(1)"  # ExecAlias just for demo
aliases['second'] = "first @(1)"  # ExecAlias just for demo
first
```
=> feat: Ability to call the program by name from callable alias with the same name without the infinite loop error

news/xonfig_history_backend.rst, xonsh/xonfig.py
To review the reports around history like in #4268 we need history backend in the `xonfig` output.
=> Added history backend name to the xonfig.

news/ptk-autopair-with-selection.rst, xonsh/ptk_shell/key_bindings.py
Supports `"`, `'`, `(`, `[`, `{`
=> ptk: Wrap selection with quotes/parens with $XONSH_AUTOPAIR

docs/xonshrc.rst, news/rc_dir.rst, tests/test_main.py, xonsh/environ.py, xonsh/main.py
This adds support for `rc.d` style configuration directories, where all contained config files are sourced in order. This technique is used by other shells (eg, `fish` supports `~/.config/fish/conf.d/*.fish`) and various unix tools (see all the `*.d` directories in `/etc`).
I find this useful as a way to split my configuration into a set of drop-in files rather than a single one, which means it's easy to share common bits of config across machines, while also having machine or account specific files.
This adds a new environment variable `XONSHRCDIR` (compare `XONSHRC`), which sets a list of directories to search. The defaults are `/etc/xonsh/rc.d` and `~/.config/xonsh/rc.d`, and from those any `*.xsh` files are sourced, after sorting to ensure predictable loading order. This happens after …
=> Add support for rc.d drop-in configuration directories

news/test_startup_order.rst, tests/test_main.py
This is a followup to @anki-code in https://github.com/xonsh/xonsh/pull/4256 and https://github.com/xonsh/xonsh/issues/4096#issuecomment-791991841
This adds a parameterised test with all the combinations of startup flags from #4096, and a few more, and checks which RC files are loaded. It should enforce the current behaviour, although having expanded many cases, I think some are probably arguable (eg, an explicit RC file `xonsh --rc foo.xsh bar.xsh` is not loaded unless you also specify interactive mode, which is probably not obvious).
=> Test RC loading in different startup configurations

news/asyncprompt-handle-cancelled-future.rst, xonsh/ptk_shell/updator.py
Prevent cancelled future errors for async prompt fields from bubbling up (and destroying the prompt's formatting). This happens for example when I keep holding down my enter key: after a while I will get tracebacks about uncaught `concurrent.futures.CancelledError`. This fixes this issue and prevents them from bubbling up.
=> Handle cancelled futures in AsyncPrompt

.pre-commit-config.yaml, amalgamate.py, requirements/tests.txt, setup.cfg, xonsh/base_shell.py, xonsh/cli_utils.py, xonsh/commands_cache.py, xonsh/completers/bash_completion.py, xonsh/completers/python.py, xonsh/dirstack.py, xonsh/history/json.py, xonsh/inspectors.py, xonsh/main.py, xonsh/parsers/base.py, xonsh/procs/posix.py, xonsh/procs/readers.py, xonsh/procs/specs.py, xonsh/prompt/vc.py, xonsh/ptk_shell/shell.py, xonsh/pyghooks.py, xonsh/pygments_cache.py, xonsh/pytest_plugin.py, xonsh/tokenize.py, xonsh/tools.py, xontrib/abbrevs.py, xontrib/voxapi.py
=> feat: add flake8-bugbear

news/update-completer-cli.rst, tests/aliases/test_completer_alias.py, xonsh/completers/_aliases.py, xonsh/completers/completer.py
1. Print which completers are non exclusive in `completer list`:
2. When adding a new completer via `completer add`, add it before the **exclusive** completers.
This means it won't interfere with the non-exclusive ones. (see more detailed comment in code)
=> Update completer cli

news/fix_wsl_detection.rst, xonsh/platform.py, xonsh/xonfig.py
Solution for #4310
```python
return "microsoft" in platform.release().lower()
return "wsl" in platform.release().lower()
```
one of these may be a better solution depending on if the result of `platform.release()` varies by distro/wsl version
Output for ArchLinux WSL2:
`5.4.72-microsoft-standard-WSL2`
=> Address ON_WSL() bug #4310

news/empty-command-handling.rst, tests/test_integrations.py, tests/test_platform.py, xonsh/platform.py, xonsh/procs/specs.py
Fixes #2329
Fixes #4287 
Prints a helpful error message (`xonsh: subprocess mode: command is empty`) when an empty command is run (for example using `@$(echo)` or `$['']`).
=> Fix empty command error message

tests/test_integrations.py
This test was failing on Windows because of an incorrect indentation. The `echo` command was not actually getting aliased to the `_echo` function.
=> Fix atdollar_no_output test

news/command-not-found-quote.rst, xonsh/tools.py
To reproduce:
```
$ aliases['a'] = 'bad(command'
$ a
subprocess.CalledProcessError: Command '/usr/lib/command-not-found bad(command); exit 0' returned non-zero exit status 2.
```
=> linux: Quote command-not-found argument

news/fix-colon-comment-handling.rst, tests/test_execer.py, tests/test_tools.py, xonsh/execer.py, xonsh/ptk_shell/key_bindings.py, xonsh/readline_shell.py, xonsh/tools.py
Fixes incorrect `SyntaxError` when a subprocess command is preceded by a comment ending with a colon:
Fixes #3502
Fixes #4033 
Also fixes issues with auto-indentation in prompt_toolkit and readline:
If you enter the line below:
```python
if True: # comment
```
the next line will _not_ get auto-indented (it should be).
If you enter the line below:
```python
```
the next line will get auto-indented (it should _not_ be).
The issue is that the method which xonsh currently uses to determine whether a line ends with a colon token:
```python
line.rstrip()[-1] == ":"
```
does not work when the line contains a comment. 
This PR instead [uses the lexer](https://github.com/xonsh/xonsh/commit/b278a16caf08fef8208e4322df22f74bc5300f99#diff-dc6388ab2415b7a836976e59822abb75c28f9c81b9a0308fef6d9eef51249c13 …
=> Fix the handling of colons when mixed with comments

docs/installation.rst
There is currently an "Installation" heading with another "Installation" subheading under it (and no other subheadings).
=> docs: Remove duplicate Installation heading

news/fix-subproc-leading-space.rst, tests/test_parser.py, xonsh/parsers/base.py
=> Fix parser for subprocess command with leading whitespace

news/enable-bracketed-paste.rst, xonsh/readline_shell.py
Closes #1154
This PR protects users against paste jacking when using the readline shell. When a user pastes a line containing a newline character, they now have to press Enter to execute the line.
See [dxa4481/Pastejacking](https://github.com/dxa4481/Pastejacking) for a detailed explanation on paste jacking, [https://security.love/Pastejacking/](https://security.love/Pastejacking/) for a working demo.
=> Enable bracketed paste mode for readline

news/capture-stdout-without-stderr.rst, tests/procs/test_specs.py, xonsh/procs/specs.py
Fixes #3786 
Currently, doing something like:
```xonsh
result=$(ls /root)
```
silently fails. This is because `$()` captures both stdout and stderr, but does not do anything with the stderr.
This PR makes `$()` only capture stdout, so that the stderr is printed to the console. This way, running `result=$(ls /root)` prints the error message:
```
ls: cannot open directory '/root': Permission denied
```
=> Stop $() from silently capturing stderr

news/fix-4363.rst, tests/test_execer.py, tests/test_integrations.py, xonsh/execer.py, xonsh/main.py
Fixes #4363
(copied from the linked issue)
`execx` and `xonsh -c` expose xonsh-internal code in the caller's global scope. They also do not support defining variables and then referring to them in comprehensions, generators, functions, or lambdas.
`execx` and `xonsh -c` both ultimately wrap calls to python's [exec](https://docs.python.org/3/library/functions.html#exec), and by default both set `globals=None` and `locals=None`. That is to say, they effectively call `exec(<code>, None, None)`. Here's the relevant line for [execx](https://github.com/xonsh/xonsh/blob/7cf0307a0d53d198b8c05c83456d86af14c0daa4/xonsh/execer.py#L196) and here are the relevant lines for [xonsh -c](https://github.com/xonsh/xonsh/blob/7cf0307a0d53d198b8c05c83456d86af14c0daa4/xonsh/codecache.py#L62-L66). …
=> fix surprising scoping behavior in `execx` and `xonsh -c` (#4363)

news/fix_short_color_names.rst, tests/test_pyghooks.py, xonsh/pyghooks.py
Short color token support for `register_custom_style()`, even before shell is initialized, so they can be used in `.xonshrc`.
Fixes #4339.
=> Short color token name support for `register_custom_style()` (#4339)

tests/conftest.py, tests/procs/test_specs.py, xonsh/procs/proxies.py
it fixes following scenarios
even though they are the same objects, different signature returned when referenced from aliases dict.
=> feat: support var-args signature for aliases

docs/keyboard_shortcuts.rst, news/auto-suggest-word-alias.rst, xonsh/ptk_shell/key_bindings.py, xonsh/ptk_shell/shell.py
Closes #4330 
Closes #3639
This adds a `CTRL-Right` shortcut to add a single auto-suggestion word (like in fish).
This is already implemented in ptk as in `ALT-f` which isn't very ergonomic or expected, so we add a comfortable alias!
=> Auto suggest word alias

xonsh/platform.py
`lazybool`s that rely on other `lazybool`s need to explicitly call
`bool()` on those values or else a non-bool value gets returned when the
parent's `__bool__` method is called.
No news item since this is fixing up a recent change.
=> Fix WSL lazybools

news/capture-object-background.rst, tests/procs/test_specs.py, xonsh/procs/specs.py
Closes #4392 
This PR makes `!()` to also capture information for background subprocesses. Currently, `!()` returns `None` for background subprocesses.
In the final `if` structure of the `run_subproc()` function, the `captured == "object"` branch does not call `command.end()` before returning (unlike all the other branches), so it can be used for background subprocesses.
https://github.com/xonsh/xonsh/blob/f5acbe30d40322ecab40d4e46d0c5f4417e59aaa/xonsh/procs/specs.py#L898-L909
=> Change !() to also capture background subprocesses

news/ctrl-backspace-delete-word.rst, xonsh/environ.py, xonsh/ptk_shell/key_bindings.py
Closes #4407 
@yaxollum I've fixed the way I do this thanks to @paul-ollis 's comment (https://github.com/xonsh/xonsh/issues/4407#issuecomment-893680405).
I missed that pkt remaps the normal backspace to `^H`, but now I'm treating it correctly.
This still needs to be configurable and off by default as stated by paul.
No need for added news item
=> Make CTRL-Backspace configurable via $XONSH_CTRL_BKSP_DELETION

tests/aliases/test_xexec.py
=> refactor: flaky test_xexec.

news/improve-import-completions.rst, tests/test_python_completers.py, xonsh/built_ins.py, xonsh/completers/imports.py, xonsh/completers/init.py, xonsh/completers/python.py
Previously the 'import' completions only completed loaded modules (from `sys.modules`).
Now it uses ipython's logic which involves finding modules in the `sys.path` and finds modules that weren't imported yet!
Also completing `import A,B` and `from A import a,b` statements has been added.
=> Improve import completions

news/ptk-completion-desc-newline.rst, xonsh/ptk_shell/completer.py
=> fix: ptk completer renders new line as ^J

news/rcdir-cli.rst, tests/test_main.py, xonsh/main.py
This is a followup to https://github.com/xonsh/xonsh/pull/4408#issuecomment-899629748, adding support for `--rc DIR` (which loads, in sorted order, `DIR/*.xsh` during startup).
This also completely drops `--config-path`, which still existed as an option but was no longer actually used anywhere (but was the only other user of `path_argument()`, which I redefined to accept files or directories).
=> Support `--rc DIR`

xonsh/environ.py
Restoring pretty repr for the `Env` class, raised in #4424
Now when you type just `${...}` you see your environment printed
=> Restore _repr_pretty_ for ${...} Env class

news/env-swap-thread-safety.rst, tests/test_environ.py, tests/test_integrations.py, tests/tools.py, xonsh/environ.py, xonsh/procs/posix.py, xonsh/procs/proxies.py
This makes `env.swap` thread safe, meaning it doesn't leak to other threads.
This is needed to swap in multiple threads in the same time, for example in the following code which used to fail before this PR:
```python
aliases['a'] = 'print 1 and sleep 1 and print 2'
a | a  # works but leaks $__ALIAS_STACK
a | a  # fails with `Exception: Recursive calls to "a" alias.`
```
This PR is needed for #4445
=> Env swap thread safety

news/fixduplicatepaths.rst, tests/test_tools.py, xonsh/tools.py, xonsh/xontribs_meta.py
Fixes #4366
Tested via docker python.
Original credits for the filter out duplicates to source: https://stackoverflow.com/a/25251306/1621381  
Seems to work great when testing.
=> Fix: EnvPath.add() not maintain uniqueness with Path objects on replace

news/always-capture-aliases.rst, tests/conftest.py, tests/procs/test_specs.py, tests/prompt/test_vc.py, tests/test_main.py, xonsh/procs/proxies.py, xonsh/procs/specs.py
Since `$XONSH_CAPTURE_ALWAYS` was introduced aliases containing `![]` notation weren't being captured properly, for instance:
```bash
aliases['a'] = '![echo hi]'
print($(a))  # ''
```
Depends and rebased on #4465
=> Always capture aliases

news/gitstatus-style-separator.rst, xonsh/prompt/gitstatus.py
Allows styling the separator in gitstatus. After #4229 "fixed" it, I just can't stand those bright white bars.
=> Allow styling gitstatus separator

news/fix-reserve-menu.rst, xonsh/ptk_shell/shell.py
fixes https://github.com/xonsh/xonsh/issues/3775
I think it was set to 0 because there is a `reserve_space` method in `PTKCompleter` class. Anyhow it doesn't seem to be working. This change fixes the issue with completions not having enough space
=> fix: not enough space for completions

news/pwd-curly-escape.rst, tests/prompt/test_cwd.py, xonsh/prompt/cwd.py
If a directory was named for example '{RED}', that would get
interpreted as a color string and the prompt would not show the
direcotry name and would color it instead. Using dir names like
'{{foo}}' or simply '{' would break the prompt outright.
There was not much documentation on the prompt formating, but it seems
that escaping a curly by doubling it makes the prompt display all
curlies correctly.
fixes #4381
=> fix: escape curly braces for the prompt cwd

news/fix-xonshrc-dir-welcome.rst, xonsh/main.py
Currently, even if there is an `$XONSHRC_DIR` in use, xonsh shows the welcome banner. I prefer to use an `rc.d` approach for configuring my system, so I'd rather not create an empty `.xonshrc` just to disable the banner!
I don't know whether we also want to check that these directories are non-empty. I think probably not - simply creating this special directory is enough to suggest that the user knows what they're doing.
=> Fix: don't display welcome if $XONSHRC_DIR member is found

.gitattributes
This override was introduced in 387340d435, on Oct 1st, 2020.
However, github/linguist has since incorporated Xonsh as a language.
See https://github.com/github/linguist/pull/5274, and it automatically
matches `.xsh` files.
This change will just give nicer languages stats, because the actual
syntax highlighting is still MagicStack/MagicPython.
E.g. my dotfiles repo's stats show up like this:
----
I don't think this is worth a changelog entry as it only affects this repos.
=> Remove syntax override for .xsh files

docs/aliases.rst, docs/platform-issues.rst, news/simplify-foreign-functions.rst, xonsh/aliases.py, xonsh/foreign_shells.py
- The default ZSH FUNCSCMD was not working for me using ZSH 5.8.
- I have simplified the foreign function implementation so that it no longer attempts to identify the file a function was defined in, I found this to cause issues for me when I had functions defined in a file that had implicit dependencies on environment variables/functions/aliases defined in other files that would be referenced from one of my zsh config files.
- Foreign functions now default to streaming.
- Sourcing multiple foreign files now works correctly.
=> Simplify foreign functions

xonsh/foreign_shells.py
When addressing review comments in https://github.com/xonsh/xonsh/pull/4393 I accidentally made a typo with a format string.
=> fix: sourcing files before foreign aliases/functions

news/ap-long-opts.rst, xonsh/cli_utils.py, xonsh/environ.py
=> feat: option to show only longest/descriptive arg-completions

news/fix-conda-env-system.rst, xonsh/prompt/env.py
Xonsh currently doesn't display the virtual environment if the user is not running xonsh under Conda:
https://github.com/xonsh/xonsh/blob/7331d8aee50e8939f8fe4d5b7133ed3907f204f4/xonsh/prompt/env.py#L15
I have xonsh running under pipx, which uses a virtualenv based on the system Python. I still use Conda to provision other virtualenvs (mainly for the ability to set the Python version; I used to use pyenv). As observed in my case, the environment that xonsh is running in should be independent from activated environments. This PR decouples the platform from the environment.
This PR changes the logic here _slightly_. `$CONDA_DEFAULT_ENV` returns the _name_ of the environment, so we don't need to invoke `os.path.basename`. I also use the `bool("") is False` idiom as I assume that only strings …
=> Fix: support Conda environments when running on non-conda interpreter

news/fix-windows-oserror.rst, xonsh/environ.py
On Windows, if you have [GnuWin32](http://gnuwin32.sourceforge.net/) installed in your `PATH`, when `xonsh` tries to run `dircolors`, it produces an `OSError` due to lack of elevation, which isn't caught by `xonsh`. See [the full error in this gist](https://gist.github.com/evhub/a84a986a947c821faaf0b7612fdfa9ac). This PR fixes the error by catching `OSError` arising from the `dircolors` call in addition to `CalledProcessError` and `FileNotFoundError`.
=> Fix OSError on Windows with GnuWin32

tests/xontribs/test_fish_completer.py, xonsh/parsers/completion_context.py, xontrib/fish_completer.py
Not including news item, because fish-completer is not released yet.
=> fix: append space at the end of fish completions

news/fix-list-comp-boolop.rst, tests/test_ast.py, xonsh/ast.py
Fixes #4529
The example code in #4529:
```xonsh
def f(x):
return [i for i in x if i is not None and i < 10]
print(f([1,2,3]))
```
currently fails because of a bug in the AST `CtxAwareTransformer`. When the transformer visits the boolean operation in the list comprehension, it sees that `i` is not in scope (because list comprehensions aren't currently handled by the transformer), so it parses the entire expression as a subprocess command:
https://github.com/xonsh/xonsh/blob/35d44068d399398ec8bb3979d7f26a35a2914ad9/xonsh/ast.py#L513-L522
This PR solves the problem by not allowing `CtxAwareTransformer` to descend into any comprehensions (list comprehensions, set comprehensions, dictionary comprehensions, and generators). This seems to be the expected behavior, because the `isdescendable` …
=> ast: do not descend into any comprehensions

news/fix-ptk-osc-in-prompt.rst, tests/test_ptk_shell.py, xonsh/ptk_shell/shell.py
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/finalterm-shell-integration.py
fixes #374
=> fix: remove custom handling of osc tokens for ptk prompt

news/refactor-lexer-parser.rst, xonsh/execer.py, xonsh/lexer.py, xonsh/parsers/base.py
This is a small PR to clean up the lex/parse logic of xonsh. Right now, we have a lot of global state through `XSH.execer.parser.lexer`, and a large API surface. This PR will reduce the size of public API, whilst also simplifying / cleaning up the code. 
I'm not very familiar with the xonsh codebase, so the direction might change as I learn more. 
=> Refactor: reduce API surface of lexer

news/feat-add-alias-decorator.rst, tests/test_aliases.py, xonsh/aliases.py
This PR adds `Aliases.register` to register functional aliases. In these cases, we already have a name from the function itself, and this decorator simplifies user code (slightly).
Usage:
```python3
>>> @aliases.register
>>> def _some_cmd(args):
>>>     print(args)
>>> some_cmd 1 2
['1', '2']
```
=> Feat: add `Aliases.register`

news/feat-shlvl.rst, tests/test_integrations.py, xonsh/aliases.py, xonsh/environ.py, xonsh/tools.py
Implement `$SHLVL` as a typed (int) environment variable.
The semantics are taken directly from bash's source:
- [conversion/validity rules](https://github.com/bminor/bash/blob/f3a35a2d601a55f337f8ca02a541f8c033682247/variables.c#L817) implemented in tools.py
- [increment SHLVL](https://github.com/bminor/bash/blob/f3a35a2d601a55f337f8ca02a541f8c033682247/builtins/exec.def#L240) on starting a new shell
- [decrement SHLVL](https://github.com/bminor/bash/blob/f3a35a2d601a55f337f8ca02a541f8c033682247/builtins/exec.def#L193) on xexec
Also, never source `$SHLVL`.
Fixes https://github.com/xonsh/xonsh/issues/4579.
=> feat: implement $SHLVL mirroring bash's implementation

tests/test_lib/test_subprocess.xsh, xonsh/lib/os.py, xonsh/lib/subprocess.py
I think the intention of adding the lib module was to expose subproc part of the xonsh. It is better to do them in Python, it will get parsed faster and we can lint.
Not including a news item, since this doesn't add/change any functionality of these modules
=> chore: update libs

.github/workflows/docs.yml
we need to create the token so that it lives in the appropriate target repository (in this case, xonsh-docs)
=> chore: fix generated token for docs push

news/fix_tracebacks.rst, tests/test_integrations.py, tests/test_main.py, xonsh/base_shell.py, xonsh/codecache.py, xonsh/environ.py, xonsh/main.py, xonsh/parsers/base.py, xonsh/tools.py
When reporting errors, one should differentiate between:
* Expected errors, like a syntax error in the users input, or an exception thrown in the users code
In this case, only the part of the stacktrace pertaining to the users code is relevant, since the xonsh part only called the users code and did nothing wrong.
* Unexpected errors, where something unforseeable inside xonsh fails.
In this case, the whole stackstrace should be shown.
I studied how CPython does this and ported it over.
See examples below.
```shell
<user>@96f01cccfc63 /xonsh fix_tracebacks # xonsh -c "syntaxerror())"
File "<string>", line 1
syntaxerror())
^
SyntaxError: Unmatched ")" at line 1, column 13
```
```shell
<user>@4bf7f9865baf /xonsh main # xonsh -c "syntaxerror())"
File …
```
=> feat: make stracktraces behave like in python

news/bash-autocompletion.rst, tests/completers/test_bash_completer.py, xonsh/completers/bash_completion.py
* add protection againts bash completion scripts which changes ~ to /home/user (#4664)
=> fix: '~' replaced to `home/user` by bash  completion scripts breaks autocompletion

CONTRIBUTING.rst, conftest.py, xonsh/events.py
Since pytest 3.0 (2016) - the recommended commandline invocation is pytest (without the dot).
py.test is still available for backwards compatibility but might be removed at some point in the future and the new entry point is already well established.
I didn't add a changelog enry as this is only a teeny tiny correction/improvement of the docs and comments and not really worth mentioning.
=> use recommended pytest entry point in docs and comments

news/vox-respect-prompt.rst, tests/prompt/test_base.py, xonsh/prompt/env.py
prompt.env.env_name is now aware of the "prompt" key in ``pyvenv.cfg`` - search order from first to last is: ``$VIRTUAL_ENV_PROMPT``, ``$VIRTUAL_ENV`` (prompt from ``pyvenv.cfg`` or basename of venv path if not set), ``$CONDA_DEFAULT_ENV``.
fixes #4670
=> make env_name aware of prompt in pyvenv.cfg

news/feat-colored-tracebacks.rst, xonsh/tools.py
Since pygments includes `PythonTracebackLexer`, we can use it to make tracebacks prettier during interactive use.
=> feat: colored tracebacks during interactive use

docs/_templates_overwrite/index.html
See goatcounter.com for more information.
Goat Counter strives to be privacy preserving and complies with GDPR.  Also doesn't use cookies for tracking so no annoying cookie announcement banner -- this is really just to track hits to the xonsh documentation to maybe start to get a sense of the size of the userbase.  Who knows?
Anyone in @xonsh/xore who wants access just ping me.
=> Add goat counter to track hits on the docs

news/fix-vim-integration.rst, xonsh/execer.py
This change makes some statements that were syntax errors previously like
```bash
(ls) > /x
```
valid syntax, which solves #4343 and replaces #4694.
=> fix 4343 by always trying greedy=True in _parse_ctx_free

requirements/tests.txt, xonsh/dirstack.py
Github stopped allowing `git+ssh` installs and we were due to move to `0.940`
=> chore: update `mypy`

news/fix-globbing-path-containing-regex.rst, tests/test_builtins.py, xonsh/built_ins.py
Fixes #4690
This PR fixes the issue that regex globbing for paths like `test+a/model` and `test*1/model` is broken. Currently, these paths do not get matched by the pattern `.*/model`.
The cause of the issue is that `reglob()` currently joins `base` (part of the file path containing problematic special characters) with `parts[i]` (part of the intended regular expression), and _compiles the whole thing as a regular expression_. This causes special regex characters in file paths to be incorrectly interpreted as part of the search pattern:
https://github.com/xonsh/xonsh/blob/78f91952273f0a81dc226abf91ae16e07c125103/xonsh/built_ins.py#L95-L100
This PR fixes the issue by not joining `base` into the regular expression, and instead matching `parts[i]` on the last component of the current path. …
=> Fix regex globbing for paths that contain special regex characters

news/virtualenv-activator-plugin.rst, requirements/tests.txt, setup.py, tests/test_virtualenv_activator.py, xonsh/virtualenv/__init__.py, xonsh/virtualenv/activate.xsh
Closes #3689
Unfortunately virtualenv removed support for the xonsh activator since we gave them too much trouble :(
So now as recommended we can implement a virtualenv plugin so that new environments will contain the `activate.xsh` script as long as xonsh is installed where `virtualenv` is invoked from.
=> Virtualenv activator plugin

docs/comparison.rst, docs/tutorial_subproc_strings.rst, xonsh/completers/bash_completion.py, xonsh/environ.py, xonsh/platform.py, xonsh/procs/specs.py
Small language changes as flagged by @jaraco in #4737
=> fix: add M1 bash-completion path to osx defaults

requirements/tests.txt
xref: https://github.com/psf/black/issues/2964
TLDR: Click removed an internal module that `black` was relying on and it broke stuff.  Updating `black` to unbreak CI.
=> chore: update black to fix CI broken with new click release

news/fix-abbrevs.rst, xontrib/abbrevs.py
=> fix: setting builtins access to abbrevs

news/guard_cursor_shape.rst, xonsh/ptk_shell/shell.py
We shouldn't fail to start if the available PTK version doesn't support
modal cursor stuff.
(We should probably also make modal cursor stuff optional, but that can
happen later)
=> fix: guard modal cursor import for prompt toolkit

news/fix-bash-completion-after-equal-sign.rst, tests/completers/test_bash_completer.py, xonsh/completers/bash_completion.py
=> fix: completions for command argument paths after equal signs

news/fix-git-branch-name.rst, xonsh/prompt/vc.py
I don't know why the `os.path.basename()` was called on the git branch name in the first place but it's wrong.
I usually create branches named: `refactor/*`, `bugfix/*` and `feature/*` so I require the full branch name.
=> fix: remove os.path.basename from _get_git_branch()

news/fix-pretty-print-dict.rst, tests/test_pretty.py, xonsh/pretty.py
=> fix: item order of pretty-printed dictionaries

xonsh/webconfig/xonsh_data.py
These newlines get properly formatted by the file writers, so we don't
need to double-escape them.
Fixes #4789
=> fix(xonfig): remove escaped newlines in xonfig web options

CONTRIBUTING.rst
Resolves:
```
docs/devguide.rst:304: ERROR: Unknown target name: "sphinx-autosummary<https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html>".
```
=> Add missing space before link in CONTRIBUTING.rst

tests/test_virtualenv_activator.py
Debian doesn't currently ship a `/usr/bin/python` binary, unless a user specifically installs `python-is-python3`.
However, we can safely assume that a `python3` binary exists.
=> We can't be sure there's a python binary

news/fix_exit_error.rst, xonsh/base_shell.py
Fixes #4806 
If `self.std` or `self.mem` is already set to `None` then we've cleaned up already and being able to `flush` doesn't really matter.  So let's not worry about them missing.
=> fix: workaround method calls on attributes set to `None`

news/cleanup-use-sighup.rst, xonsh/jobs.py
Allows `nohup` command to work properly.
Fixes #2346
=> Send SIGHUP instead of SIGKILL to clean up jobs

news/extend-whole-word-jumping.rst, xontrib/whole_word_jumping.py
This binds Alt/Control+Delete/Backspace to support deletion matching
the motion bindings in `whole_word_jumping`.
Should work mostly out of the box on terminals that generate `\x7f`
when `backspace` is pressed and `\x08` when `control+backspace` is
pressed.  Tested to work on Microsoft Terminal (WSL2).  For
incompatible terminals, users can set `$XONSH_WHOLE_WORD_CTRL_BKSP
= False` to avoid configuration of the `control+backspace` binding.
=> Support deletion in whole_word_jumping xontrib

news/backgrounding-return-hiddenobject.rst, tests/procs/test_specs.py, tests/test_pipelines.py, xonsh/procs/pipelines.py, xonsh/procs/specs.py
Fixes #4595
Addresses https://github.com/xonsh/xonsh/pull/4406#issuecomment-899892668
=> Change ![] to return an object for background command

news/fix-execalias_rtn.rst, tests/test_aliases.py, xonsh/aliases.py
Fixes part of the ExecAlias issue described in #4752 
This PR fixes the returncode of an ExecAlias, but the stdin/stdout are still not set properly.
=> Fix ExecAlias return value

news/xonshlexer-fix.rst, tests/test_pyghooks.py, xonsh/pyghooks.py
=> fix(pyghooks): Fix some errors caused by an unset Xonsh session env when using XonshLexer as a Pygments plugin.

docs/python_virtual_environments.rst, setup.py, xonsh/procs/specs.py, xontrib/abbrevs.py
There are small typos in:
- docs/python_virtual_environments.rst
- setup.py
- xonsh/procs/specs.py
- xontrib/abbrevs.py
Fixes:
- Should read `interpreter` rather than `intrepreter`.
- Should read `dictionary` rather than `disctionary`.
- Should read `descriptors` rather than `descriptiors`.
- Should read `because` rather than `becuase`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

pyproject.toml, xonsh/virtualenv/__init__.py
This should fix the failing `tests/test_virtualenv_activator.py::test_xonsh_activator` test
=> Fix virtualenv Path import and bump version

news/dont_crash_without_pygments.rst, xonsh/ansi_colors.py
The fallback is already the default behavior if the user has `pygments`
installed, but if they don't we were awkwardly bailing out here and
preventing startup.
Fixes #4905
=> fix(styles): fall back to default style if style not found

news/fix-callable-alias-subproc.rst, tests/test_integrations.py, tests/test_jobs.py, tests/test_pipelines.py, xonsh/jobs.py, xonsh/procs/pipelines.py, xonsh/pytest/plugin.py
Fixes #4277
Fixes #4281
Piping a callable alias containing a subprocess call into another command is currently broken. This is because the job control inside the callable alias gets confused by the main thread's job control. For example, the following example is given in #4277:
```xonsh
def _callme(args):
$(echo 1)
print('one\ntwo\nthree')
aliases['callme'] = _callme
callme | grep t
```
After the callable alias `callme` spawns the `echo 1` command, it calls `wait_for_active_job`:
https://github.com/xonsh/xonsh/blob/1e20ee04c83389500a6328262af83982e35e865e/xonsh/jobs.py#L200-L230
The first active job is `echo 1`. `wait_for_active_job` correctly waits for `echo 1` to complete, and then it starts waiting for the *next* active job, which it determines is the `grep t` command. This causes a …
=> Fix job control for callable aliases

news/fix-bash-completion.rst, tests/completers/test_bash_completer.py, tests/test_completion_context.py, xonsh/completers/bash_completion.py, xonsh/parsers/completion_context.py
This fixes a bug in bash completion when the argument being completed was prefixed with certain characters such as when piping output to a file.
For example, `ls >/dev/nul<TAB>` would complete to `ls >/dev/nu/dev/null` instead of `ls >/dev/null`.
I noticed that issue #2976 was related, so I fixed it as well.
=> Fixing bash completion bug when prefix started with '>', '<', or ':'

news/fix-term-title-update.rst, tests/prompt/test_base.py, tests/prompt/test_job.py, xonsh/procs/pipelines.py, xonsh/procs/specs.py, xonsh/prompt/base.py, xonsh/prompt/job.py, xonsh/readline_shell.py
Fixes #4913 
#4913 was caused by the caching mechanism in `PromptFields`. The cache needs to be cleared in order for the current job's name to be updated in the terminal's title.
Fixes #4034 (I've tested `swaymsg` with this fix)
#4034 was caused by `swaymsg` being stopped by `pause_call_resume` in the middle of the `recv` system call. This PR eliminates the need to use `pause_call_resume` by setting the terminal's title before the job is started. See https://github.com/xonsh/xonsh/issues/4034#issuecomment-1207513794 for more details about the system call issue.
=> Update terminal title before executing subprocess

news/fix-procproxy-capture.rst, tests/procs/test_specs.py, xonsh/procs/specs.py
Fixes #4882
When `$THREAD_SUBPROCS=False`, `cd a_non_existent_directory` currently does not display an error message because xonsh silently captures the stderr.
When a callable alias that isn't threaded is run using `![]`, its output should not be captured because doing so requires a separate thread in order to both capture the output and stream the output to the terminal while the alias is running.
=> Do not capture unthreaded callable aliases run with `![]`

news/fix-gitstatus-no-git.rst, tests/prompt/test_gitstatus.py, xonsh/prompt/gitstatus.py
Fixes #4900
This PR makes the values of all `gitstatus` prompt fields `None` when there is no git repository. This allows format strings like `{gitstatus: hello {}}` to work as expected.
=> Make gitstatus prompt field values `None` when there is no git repo

.github/workflows/docs.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes.
Here is an example of the permissions in one of the workflow runs:
https://github.com/xonsh/xonsh/runs/8196887287?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- docs.yml
The following workflows already have the least privileged token permission set:
- check-news-item.yml
- publish.yml
- test.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- GitHub recommends defining minimum …
=> ci: add minimum GitHub token permissions for workflow

news/no_background_inherit.rst, xonsh/pyghooks.py
Pygments does not understand a "background" of `noinherit`, only `noinherit` -- so if we are setting `noinherit`, even for a background color, we do not prepend `bg:`
Fixes #4432 
Fixes #4934
=> fix: do not prepend `bg:` to `noinherit` style directives

news/4668-fix-autocomplete-suggest.rst, tests/test_ptk_completer.py, xonsh/ptk_shell/completer.py
Fixes #4668 
It's possible I missed some edge cases, worked fine on 2 simple tests:
```sh
$ test-missing-command
test-missing- #<TAB>
```
```sh
$ ssh foobar@non-existent-host
$ ssh foobar@non- #<TAB>
```
=> Fix auto-suggestion completion stacking if no normal completion exists

xonsh/webconfig/file_writes.py, xonsh/webconfig/routes.py
hi guys, this is my first commit. please let me know if i've done anything wrong :)
previously using the xonsh web config tool to set a prompt with a newline added "^M" at the end of the prompt. this fix strips all \r characters in the config file and strips all \r characters in the prompt page's post request.
closes #4960 
=> fix: web config tool including \r in prompt

xonsh/aliases.py
Change from `anyway.You` to `anyway. You`.
=> Add whitespace after full stop in alias message

news/bugfix_commands_cache.rst, tests/test_commands_cache.py, xonsh/commands_cache.py, xonsh/environ.py
darwin's stat uses nano seconds accuracy for the files mtime property, whereas
on linux it returns a unix timestamp (seconds), meaning we cannot rely on that
field when checking for dir modifications per each path for creating `CommandsCache`.
consider the following shell script:
```shell
cp /path/to/executable /bin/new_executable
new_executable
```
=> commands_cache: ignore mtime check on non-darwin os

CHANGELOG.rst, docs/platform-issues.rst, docs/xonshrc.rst
Updating docs to remove remaining references to deprecated RC location and added a (late) notice to the changelog about the breaking change.
cc @das-g @samlukeyes
xref #4761 #4635
=> doc: remove references to deprecated RC location, update changelog

.github/workflows/test.yml, tests/test_history_sqlite.py, tests/test_ptk_highlight.py, xonsh/aliases.py
~temporary fix while we sort out what broke upstream~
`Token.Text` for `\n` is now `Token.Text.Whitespace` -- doesn't really matter on our end since `prompt_toolkit` does the right thing, but I've updated the expected tokens in our tests.
Also adding 3.11 to CI, just to make things interesting.
=> ci: Add 3.11 to CI and fix existing failures

docs/tutorial_hist.rst, news/history_pull.rst, xonsh/history/base.py, xonsh/history/main.py, xonsh/history/sqlite.py
Added `history pull` command to SQLite history backend to pull the history from parallel sessions into the current sessions.
To review just open two parallel terminal windows. Run a couple of commands in the first terminal window. Run `history pull` from the second terminal window to get the commands from the first terminal.
Closes #5044
=> history pull

.gitignore
subj
> xontrib is an implicit namespace package. DO NOT add an `__init__.py` file to this directory.
no news
=> Update .gitignore: exclude xontrib/__init__.py

news/5056.rst, xonsh/ptk_shell/key_bindings.py
=> key_bindings: map `escape-right` as another word completer for macOS (#5056)

.gitignore, news/multil.rst, xonsh/environ.py, xonsh/ptk_shell/shell.py
This PR allows marking each line of the multiline continuation prompt to allow the terminal to separate user input from the `...` continuation dots and do something useful with it (e.g., select&copy all the multiline input that you can safely paste elsewhere)
It does so by adding two environment variables that other [xonribs](https://github.com/jnoortheen/xontrib-term-integrations/pull/9) can then use to insert invisible markers that a given terminal supports
(this also fixes a bug where an empty `{BLUE}` dots would lead to a concatenation error)
Tested it live, but don't understand how to make a proper test for this, tried to copy the `test_ptk_multiline.py`'s https://github.com/xonsh/xonsh/blob/eae3fcc255d9c540b3fae34a35e659f5fd7c1e7d/tests/test_ptk_multiline.py#L69
by adding 
```py …
```
=> Add Semantic Prompt support to multiline continuation lines

news/not_found_repr.rst, tests/procs/test_specs.py, xonsh/procs/specs.py
The `command not found` error will show the ``repr(cmd)`` to uncover the cases when the command name has ``\n``, ``\t`` or not visible color codes and raises the error.
Before:
```xsh
aliases['my'] = 'echo echo'
$(@(my))
#
$(@(my))
```
=> Using `repr(cmd)` for `command not found`

news/tools_chdir.rst, tests/test_dirstack.py, xonsh/tools.py
Now you can use `chdir` from tools:
```xsh
from xonsh.tools import chdir
cd /tmp
pwd
with chdir("/"):
pwd
pwd
```
=> Moving `chdir` to `xonsh.tools`

news/vc.rst, tests/prompt/test_vc.py, xonsh/prompt/vc.py
The xonsh prompt now shows the currently active Fossil branch, while inside a Fossil checkout.
See also https://fossil-scm.org
The feature works similarly to how git and hg are currently handled: While inside a Fossil checkout, the currently active branch is shown in the prompt between the path and `$`.
Note: 
There are further possibilities for refactoring in [vc.py](https://github.com/xonsh/xonsh/blob/main/xonsh/prompt/vc.py). The old code used for git and hg uses manual thread management and passes data via queues to implement a command timeout. This can be replaced completely by using the `timeout` parameter of [`subprocess.check_output()`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output). I guess the code once targeted Python < 3.3
I did not include the …
=> Add support for Fossil SCM branch names in vc.py.

news/fix_missing_icon.rst, pyproject.toml
=> Fix missing webconfig/js/xonsh_sticker.svg

README.rst, news/load_autoloaded.rst, xonsh/pytest/plugin.py, xonsh/xontribs.py
Xontrib template creates autoloaded xontribs in a `xontrib_X` folder instad of a `xontib/X.py`file, so you can't `xontrib load X` right after you install them
For example,
```xsh
xpip install xontrib-skim
xontrib load skim
xpip install xontrib-cd
xontrib load cd
```
This also breaks **pytests**, so this PR 
Fixes: https://github.com/xonsh/xontrib-template/issues/22
I've added the extra module field data needed for this to work to `def xontrib_data():`, but haven't added it to the formatted output of the command `xontrib list` (not sure it's needed), though it's data-dumping friend `xontrib list -j` does include this new field
=> fix: load autoloading (but not yet autoloaded) xontribs

news/multil.rst, xonsh/environ.py
Unset the default Semantic Prompt line continuation environment variables (``$MULTILINE_PROMPT_PRE`` and ``$MULTILINE_PROMPT_POS``) to allow differentiating between user setting an empty value (so nothing should be added) and not setting anything (so it's ok to set them to something useful)
=> Unset the default Semantic Prompt line continuation environment variables

news/add_history_delete.rst, xonsh/history/base.py, xonsh/history/json.py, xonsh/history/main.py, xonsh/history/sqlite.py
This MR adds the `delete` command to `history`, which allows the user to only delete commands from the history,
that matches a specific pattern (in the form of a regular expression).
This is done by extending `xonsh.history.base.History` and `xonsh.history.main.HistoryAlias` as well as provide default implementations for the `JsonHistory` and `SqliteHistory` backends.
=> Add `history delete` #4929

news/fix_xpip_unwriteable_sitepackages.rst, xonsh/xontribs.py
`xpip` should always install `xontribs` in a place where the invoking instance of `xonsh` can find them.
In the case where `xonsh` resides in a non-user-writeable `site-packages` directory, we need to ensure that the location of the installed `xontribs` is part of `sys.path`.
Originally, this was handled by pre-pending `sudo` to the `python -m pip` call, but no one thought that was a good thing.  However, when we switched it to calling `--user` instead of `sudo`, we didn't add an additional step to ensure that the site-packages directory in userspace was included.
Here we add that in, using the same check of writeability of the `sys.executable` location to determine if we need to patch `sys.path`.
Fixes #5229 
=> fix(xpip): patch in user site packages for xpip where needed

xonsh/aliases.py
**Security:**
* Security fix for vulnerability on Windows; Xonsh will no longer execute default cmd commands†
using a malicious "cmd.bat" file in the current directory.
† cls, copy, del, dir, echo, erase, md, mkdir, mklink, move, rd, ren, rename, rmdir, time, type, & vol
#issuenumber 5254
=> Use %COMSPEC% not "cmd" to prevent hijacking. Fixes #5254

news/fix-pymode-ioredirect.rst, tests/test_lexer.py, xonsh/lexer.py, xonsh/parsers/completion_context.py, xonsh/tokenize.py
Fixes #4994 
Currently, the tokenizer always recognizes `2>` as an `IOREDIRECT`, regardless of the context:
https://github.com/xonsh/xonsh/blob/a587e7ec8c92f3640a4f3a62a52845c3f75c81f7/xonsh/tokenize.py#L1012-L1013
As a result, when the Python expression `2>0`  is passed to the lexer, the output is
```python
[LexToken(IOREDIRECT,'2>',1,0), LexToken(NUMBER,'0',1,2)]
```
instead of
```python
[LexToken(NUMBER,'2',1,0), LexToken(GT,'>',1,1), LexToken(NUMBER,'0',1,2)]
```
In this PR, when the lexer gets an `IOREDIRECT` token from the tokenizer, it checks whether the current state is Python mode. If it is not Python mode, then the lexer leaves the `IOREDIRECT` token unchanged and outputs it. If it *is* Python mode, then the token's string gets passed through the tokenizer again with the …
=> Fix incorrect IOREDIRECT tokens in Python mode

news/fix-redirect-structure.rst, tests/test_integrations.py, tests/test_lexer.py, xonsh/lexer.py, xonsh/parsers/base.py, xonsh/parsers/completion_context.py, xonsh/procs/specs.py, xonsh/tokenize.py
Fixes #2335
This fix changes the parser so that a command like `echo test > a.txt < b.txt o>e` is passed like `['echo', 'test', ('>', 'a.txt'), ('<', 'b.txt'), ('o>e',)]` to [`cmds_to_specs`](https://github.com/xonsh/xonsh/blob/7461c507b210d1492cac6d2f517ba459ec86bea8/xonsh/procs/specs.py#L827).
Currently, the command is passed like `['echo', 'test', '>', 'a.txt', '<', 'b.txt', 'o>e']`, which is what causes the ambiguity between a `>` redirect token and a `">"` string literal.
=> Fix parsing of redirect tokens

news/fix-abs-path-completions-on-keypress.rst, xonsh/completers/man.py
fixes #5127, an error in fetching command completions when `UPDATE_COMPLETIONS_ON_KEYPRESS` is enabled and the command is specified by absolute path.
Prior to this patch, typing `/usr/bin/ls -a` with `$UPDATE_COMPLETIONS_ON_KEYPRESS = True` set causes an exception while trying to write to `/usr/bin/ls.json` (assuming that the user does not have write access to `/usr/bin/`). The crux of the error was that the absolute path of the command was used during the path join. A join using an absolute path causes the other portion of the path to be discarded.
=> fix: Error in completions with absolute paths (#5127)

news/source_foreign_notinteractive.rst, tests/aliases/test_source.py, xonsh/aliases.py
supercedes #5343 because I forgot which remote I was on
=> refactor(aliases): source foreign shell funcs without interactive mode

tests/test_tools.py
`os.sep` - The character used by the operating system to separate pathname components i.e. `/` in posix.
`os.pathsep` - The character conventionally used by the operating system to separate search path components i.e. `:` in posix.
Fixed wrong usage `os.pathsep` instead of `os.sep` in test_tools.
=> test_tools: fix pathsep

news/no_env.rst, xonsh/built_ins.py, xonsh/environ.py, xonsh/main.py
Basically we use `xonsh --no-rc` to have pure xonsh. 
I noticed many times when parent environment can affect `xonsh --no-rc` e.g. `$XONSH_HISTORY_FILE`.
Current workaround is `env -i @$(which xonsh) --no-rc` but I think we need to have pure xonsh way.
Closes #4921
```xsh
xonsh --no-rc
$QWE = 1
xonsh --no-rc
$QWE
```
```xsh
xonsh --no-rc
$QWE = 1
xonsh --no-rc --no-env
$QWE
$XONSH_ENV_INHERITED  # Marker to have a way to catch this situation.
```
=> feat: add --no-env flag to avoid inheriting parent-shell env

xonsh/xoreutils/which.py
=> which: fix handling of `None` results (#5358)

news/xonfig_env.rst, xonsh/xonfig.py
I continue adding the information that can help to investigate cases around subprocess. Any time we have issues around subprocess behavior the main question is what `THREAD_SUBPROCS` and `XONSH_CAPTURE_ALWAYS` state because some old xontribs could change the behavior. It will be good to show this in xonfig.
```xsh
xonfig
+----------------------+----------------------+
| xonsh                | 0.16.0               |
| Git SHA              | e30dd960             |
| Commit Date          | Apr 20 20:33:07 2024 |
| Python               | 3.12.3               |
| PLY                  | 3.11                 |
| have readline        | True                 |
| prompt toolkit       | 3.0.40               |
| shell type           | prompt_toolkit       |
| history backend      | json …
```
=> Xonfig: show sensitive env variables that could affect the shell behavior.

news/main_d.rst, tests/test_integrations.py, xonsh/main.py, xonsh/pygments_cache.py, xonsh/shell.py, xonsh/tools.py
Case 1:
```xsh
xonsh --no-rc --no-env -DCOLOR_OUTPUT 0  # space between -DVAR and VALUE
```
```xsh
File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/main.py", line 478, in main
args = premain(argv)
^^^^^^^^^^^^^
File "/Users/pc/.local/xonsh-env/lib/python3.12/site-packages/xonsh/main.py", line 420, in premain
env.update([x.split("=", 1) for x in args.defines])
File "<frozen _collections_abc>", line 987, in update
ValueError: not enough values to unpack (expected 2, got 1)
Xonsh encountered an issue during launch
```
Case 2:
```xsh
xonsh --no-rc --no-env -DXONSH_HISTORY_BACKEND=dummy
history info
```
Case 1:
```xsh
xonsh --no-rc --no-env -DCOLOR_OUTPUT 0
```
Case 2:
```xsh
xonsh --no-rc --no-env -DXONSH_HISTORY_BACKEND=dummy
history info …
```
=> Fixed ``xonsh -DVAR=VAL`` behavior: initiate env variables before shell initialization.

news/downgrade_ptk.rst, pyproject.toml
This downgrade continues previous (#5288). Found issue in prompt-toolkit 3.0.40 (#5393).
JFYI #5241
=> Downgrade prompt-toolkit to `>=3.0.29,<3.0.40`

news/sig_exit_fix.rst, tests/procs/test_specs.py, tests/test_integrations.py, xonsh/built_ins.py, xonsh/main.py, xonsh/ptk_shell/shell.py, xonsh/readline_shell.py
Case 1: Handler catches the exit signal and do not pass it forward. As result xonsh could be suspended by OS or crash. Also exit code is wrong. See repeatable examples with SIGHUP in https://github.com/xonsh/xonsh/issues/5381#issuecomment-2097961804.
Case 2: From bash/zsh as login shell run xonsh. Then send quit signal to xonsh. The terminal state will be broken: disabled SIGINT, mouse pointer produces mouse state codes.
Case 1: Xonsh exit normally with right exit code. Fixed #5381 #5304 #5371. 
Case 2: After exiting with right exit code the state of the terminal is good.
=> Fixed processing exit signals and exit exception

xonsh/ptk_shell/shell.py
Because we downgraded ptk in https://github.com/xonsh/xonsh/pull/5403
```xsh
xonsh --no-rc
#@
```
```xsh
xonsh --no-rc
#@
```
=> Ignore ptk warning

news/history_save_unload.rst, tests/test_history_json.py, xonsh/built_ins.py
```xsh
echo 1 
echo 2
```
Closes #2657
```xsh
echo 1 
echo 2
```
=> History: Saving history in case of any type of exiting the shell.

.github/workflows/test.yml, .gitignore, tests/completers/test_python.py, tests/procs/test_specs.py, tests/test_integrations.py, xonsh/ast.py, xonsh/parsers/base.py, xonsh/pretty.py
=> chore: use stable 3.12 for CI jobs

docs/bash_to_xsh.rst, news/last_cp.rst, xonsh/built_ins.py, xonsh/procs/specs.py
There is no way to access to the CommandPipeline of executed command in uncaptured mode. This causes:
* No chance to get return code in one universal way.
* Barrier to trace and inspection.
```xsh
$(ls nofile)
```
```xsh
$(ls nofile)
__xonsh__.last.rtn  # In interactive or not interactive.
```
```xsh
last = type('LastCP', (object,), {'__getattr__':lambda self, name: getattr(__xonsh__.last, name) })()
ls nofile
last.rtn
```
JFYI #5342
=> Now last executed CommandPipeline is available in ``__xonsh__.last``

news/prompt_superuser.rst, xonsh/prompt/base.py
```xsh
sudo xonsh --no-rc
```
```xsh
sudo xonsh --no-rc
```
It's in sync with:
```xsh
docker run -it ubuntu bash
echo $USER
```
=> Show ``root`` and ``@#`` in prompt if user is superuser.

news/fix_interactive_suspended_subproc.rst, tests/procs/test_specs.py, tests/test_integrations.py, xonsh/jobs.py, xonsh/main.py, xonsh/procs/pipelines.py, xonsh/procs/posix.py, xonsh/tools.py
Reading stop signals from the process and update the process state.
Technically. In a couple of places that critical for processing signals we have `os.waitpid()`. The function behavior is pretty unobvious and one of things is processing return code after catching the signal. We had no good signal processing around this and this PR fixes this. See also `proc_untraced_waitpid` function description.
From user perspective. For example we have process that is waiting for user input from terminal e.g. `python -c "input()"` or `fzf`. If this process will be in captured pipeline e.g. `!(echo 1 | fzf | head)` it will be suspended by OS and the pipeline will be in the endless loop with future crashing and corrupting std at the end. This PR fixes this.
Technically. The key function is …
=> Read stop signals from the process and update the process state.

news/fix_nix.rst, tests/test_commands_cache.py, xonsh/commands_cache.py
Closes #5003
Core utils in Nix are symlinks to one binary file that contains all utils:
```xsh
docker run --rm -it nixos/nix bash
which echo
ls -la /nix/store/k6h0vjh342kqlkq69sxjj8i5y50l6jfr-coreutils-9.3/bin/
```
When [`default_predictor_readbin`](https://github.com/xonsh/xonsh/blob/61bda708c992a300eab212f877718cf0050a5e3a/xonsh/commands_cache.py#L392) read `coreutils` it catches `(b'isatty', b'tcgetattr', b'tcsetattr')` and return `threadable=False` forever.
The list of Nix coreutils tools are exactly the same as in [brew coreutils](https://formulae.brew.sh/formula/coreutils). So I can check the real predicts on distinct binaries and see that only 2 tools among 106 are unthreadable and they already covered by `default_threadable_predictors` (If it's wrong please add unthreadable tools …
=> Added support of NixOS core tools in ``predict_threadable``

news/prompt_end_nl.rst, news/prompt_env_name_yel.rst, xonsh/aliases.py, xonsh/prompt/base.py
When interact with default prompt I noticed that`env_name` has no color and when you type command or see the output it mix with `env_name` visually. Prompt is not highlighted when `env_name` has default color.
Output and env_name are visually mixed:
Output and env_name are visually distinct:
=> prompt: yellow env_name

docs/platform-issues.rst, news/5477.rst, pyproject.toml, tests/test_commands_cache.py, xonsh/commands_cache.py
=> Perform proper case-insensitive matching in command_cache on Windows

xonsh/webconfig/routes.py
Added links to xontribs in `xonfig web`
=> xonfig: added links

.github/ISSUE_TEMPLATE/new-issue.md, news/spec_raise_subproc_error.rst, tests/procs/test_specs.py, xonsh/procs/pipelines.py, xonsh/procs/specs.py
Add `spec.raise_subproc_error` to have an ability to use `SpecModifierAlias` to manage the errors. Also this is the first step to #4351.
Generally in scripts it's good to have  RAISE_SUBPROC_ERROR=True to avoid processing the error for every executed command. But in some cases (e.g. `![]`) it's needed to avoid raising the error. To more elegant doing this we can make an ability to create SpecModifier.
```xsh
from xonsh.procs.specs import SpecModifierAlias
class SpecModifierNoErrAlias(SpecModifierAlias):
def on_modifer_added(self, spec):
spec.raise_subproc_error = False
aliases['noraise'] = SpecModifierNoErrAlias()
$RAISE_SUBPROC_ERROR = True
if ![noraise git pull]:
git add --all
```
Cc #5443 
=> spec: added raise_subproc_error

xonsh/history/main.py
After testing xonsh on ALT linux (https://github.com/xonsh/xonsh/issues/5517#issuecomment-2187069017) I see that we need to make sqlite3 loading optional.
=> sqlite3: optional loading

news/prompt_switch_to_ptk.rst, xonsh/lib/__init__.py, xonsh/shell.py
There is an edge case that we're using mostly in integration tests from the beginning of the world:
`echo 'echo 1' | xonsh -i` and it's not working with `TERM=dumb` because dumb is readline.
So in this case we need to force using prompt_toolkit to avoid hanging.
Closes #5462 #5517
These all produces hanging because reading stdin is not implemented in readline backend:
```xsh
echo whoami | TERM=dumb xonsh -i --no-rc   # dumb is readline in fact
echo whoami | xonsh -st dumb -i  # dumb is readline in fact
echo whoami | xonsh -st readline -i
```
Switching to prompt_toolkit in these cases.
=> prompt: switching to prompt_toolkit in case of stdin with interactive mode

news/commands_cache_fix_update.rst, news/opt_sqlite.rst, tests/test_commands_cache.py, xonsh/commands_cache.py
I noticed that when I type every letter in the prompt on the remote server the typing is lagging. I thought it's ssh but no.
After inspection the commands cache code I found that on every key press there is reading all 2000+ files in PATH because the code for cache update has funny issue.
```xsh
def f():
print(1)
yield False
print(2)
yield True
print(3)
print(any(f()))
```
What will be in the output? Answer:
<details>
```
1
2
True
```
The execution of `print(3)` ignored because `any()` interrupts the execution of the function. 
If we call `print(list(f()))` the output will be `1 2 3 [False, True]`.
</details>
* Updating cache (read all files in PATH and list of aliases) two times after start.
* Updating cache (read all files in PATH and list of aliases) on every key press in prompt.
* …
=> Command cache: fix update cache logic

tests/completers/test_command_completers.py, xonsh/cli_utils.py
PS.
https://github.com/python/cpython/commit/e47ecbd0420528f1f9f282d9e7acfcf586a4caa1
fixes #5471
=> fix: argparse based completions should work in newer python versions

news/disable_colors_non_int.rst, xonsh/main.py
Running commands with disabled `COLOR_RESULTS` around 40% faster. It should be by default.
```xsh
zsh
time xonsh --no-rc --no-env -c '2+2'
time xonsh --no-rc --no-env -DCOLOR_RESULTS=0 -c '2+2'
```
You can switch it to `True` any time by providing `-DCOLOR_RESULTS=1`:
```xsh
zsh
xonsh --no-rc --no-env -DCOLOR_RESULTS=1 -c '{"q":1}'
COLOR_RESULTS=1 xonsh --no-rc --no-env -c '{"q":1}'
```
Closes #5561
=> colors: ``COLOR_RESULTS`` switched to ``False`` for non-interactive command case

docs/tutorial.rst
When found only in the 'Captured Subprocess' section, it implies that the behavior is only available for captured subprocesses, when in fact it's available for any command. This bit could have gone into its own section, but since it's already carved out as a 'Note', it seems fine to put it here in the Running Commands section.
Closes #5591
=> Move note about last subprocess

pyproject.toml
The zulip email is too long and breaks publishing:
```
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
'xonsh-email.d8c44838e5348844fa397b54d705ce30.show-sender.include-foote
r.include-quotes@streams.zulipchat.com' is not a valid email address:
The email address is too long before the @-sign (22 characters too
many). See https://packaging.python.org/specifications/core-metadata
for more information.
```
I don't care what email we use, but I'm putting in a temporary one so I can get the release out.
=> chore(metadata): swap in shorter email address

news/locate_relative.rst, tests/procs/test_executables.py, tests/test_integrations.py, xonsh/procs/executables.py, xonsh/pyghooks.py
Added locate_relative_path functionality to locate_file for cases:
* `./binfile`
* `../binfile`
* `~/binfile`
* `/full/path/to/binfile`
Closes #5615 #5617
=> executables: Added ``locate_relative_path`` functionality to ``locate_file``.

news/fix_python_only_completion.rst, tests/test_completer.py, xonsh/completer.py
Closes #5625
The comments on [CompletionContext](https://github.com/xonsh/xonsh/blob/ec5f4d85595a004b4a72c881893379d404da5b0c/xonsh/parsers/completion_context.py#L130) say CompletionContext.command is None when in a Python context, but [Completer.complete_with_context](https://github.com/xonsh/xonsh/blob/ec5f4d85595a004b4a72c881893379d404da5b0c/xonsh/completer.py#L261) and [Completer.complete_line](https://github.com/xonsh/xonsh/blob/ec5f4d85595a004b4a72c881893379d404da5b0c/xonsh/completer.py#L43) depend on it to get the prefix.
This PR fixes the above: the python context prefix is favored if available, otherwise the command context prefix is used. Completer.complete_line now only raises an exception if both the command and python contexts are None.
⬇️  **Please click the 👍 reaction …
=> Fix: exception when completing in python-only context

news/fix-procproxy-sys-exit.rst, tests/test_integrations.py, xonsh/procs/proxies.py
Fixes #5689
Instead of catching SystemExit in ArgParserAlias (which I tried in #5697), it makes more sense to catch it at the ProcProxy level so that `sys.exit` is works for all unthreadable callable aliases.
Also see explanation in https://github.com/xonsh/xonsh/issues/5689#issuecomment-2381902081
=> Catch SystemExit in ProcProxy

tests/parsers/test_parser.py, tests/procs/test_pipelines.py, tests/procs/test_specs.py, xonsh/cli_utils.py, xonsh/pytest/tools.py
The upstream private API for `_parse_optional` changed, needed to update this.
Fixes at least one of the failing CI tests
=> fix(ArgparseCompleter): adjust parsing for upstream private changes

news/ast-fix-deprecation-warnings.rst, xonsh/parser.py, xonsh/parsers/ast.py, xonsh/parsers/v313.py
=> parsers: fix deprecation warnings triggered on python3.13 (#5710)

news/remove-caseinsdict.rst, pyproject.toml, tests/test_commands_cache.py, xonsh/commands_cache.py
closes #5627 
replaces #5633 
option 1: just import `CaseInsensitiveDict` from `requests.strucures`
pros: 
- not much typing
cons: 
- replaces one dependency with another
- requests is not typed natively so either has to be excluded from mypy, or also import `types-requests` as an additional dependency
Option 2: hard code `CaseInsensitiveDict` by overriding python native dict.  below is a possibility.
pros: behavior is then native in xonsh
cons: more code to maintain
```
class CaseInsensitiveDict(Dict[str, Any]):
def __init__(self, *args, **kwargs):
super().__init__()
self._store = {}
self.update(*args, **kwargs)
def __setitem__(self, key, value):
self._store[key.lower()] = key
super().__setitem__(key.lower(), value)
def __getitem__(self, key):
return super().__getitem__(key.lower())
def …
```
=> try just using CaseSenssitiveDict from requests to see if it works

tests/shell/test_ptk_highlight.py
(moving non-Win commands like ls to a separate test)
was checking why some of the newer commits failed CI tests on non-Windows and to allow for testing on Windows split this failing test that was skipped due to some non-Win commands (`ls`) into two:
- one with those commands, and
- another without them (but now working on Win)
so non-Win should have the same tests, but Win gets an extra coverage
(internal test, so no news)
=> test: split a test to include Windows

.pre-commit-config.yaml
Any reason why pre-commit requires an install of an old python version?
=> pre-commit: use current 3.13 version of python

news/update_bash_completion.rst, xonsh/completers/bash_completion.py
Copied from xonsh/py-bash-completion.
I've also archived that repository and left a link in the README to point to this file.
I think we can (and should) keep this file as actionless on import so that it can still be used as a standalone tool, but we don't need to deal with multiple repositories anymore.
=> chore: update bash_completion.py

xonsh/procs/executables.py
Windows has slow IO operation on is_file check. So this PR is to reduce running is_file two times.
=> refactor: Disable double check is_file on Windows systems to speedup IO

xonsh/procs/jobs.py
Resolve #5745. The existing behavior [was introduced in 2015](https://github.com/xonsh/xonsh/commit/3aa37682f9441bb7c8bfb492325c88e0900ed327#diff-75c83180c6250bfa7c142ed214f8c71e7704872f3b0c63b167895cf0ae892989R106-R107) ~~and I suspect was because there was no equivalent to [signal.CTRL_C_EVENT](https://docs.python.org/3/library/signal.html#signal.CTRL_C_EVENT) at the time in Python 2.7, it was introduced in Python 3.2.~~ Xonsh only supported 3.4+ at the time and [signal.CTRL_C_EVENT](https://docs.python.org/3/library/signal.html#signal.CTRL_C_EVENT) was already available; it's unclear why the existing implementation choice was made by @adqm .
When pressing Ctrl+C on Windows a forceful terminate was sent using the taskkill command.
```
localhost@ ssh remote
remote$ hello <Press Ctrl+C> …
```
=> feat: #5745 - send Ctrl+C event on Windows instead of forceful terminate

tests/test_main.py, xonsh/main.py
Addresses https://github.com/xonsh/xonsh/issues/5872:
- 79036030 fix(main): Respect xontribs autoload disabled in RC file
- 20e7fc8a test(main): Setup failing test to disable xontrib auto-loading in RC file
1. Launch a clean Docker environment
2. `$XONTRIBS_AUTOLOAD_DISABLED = False` by default
3. Install contrib that supports auto-loading (eg, `pip install coconut`)
4. Run xonsh to auto-load xontrib
5. Verify xontrib is loaded (eg, `"hello, world" |> print`)
<details>
```xsh
uv run python xonsh-in-docker.py 
Building and running Xonsh
Using python  3.11
Using prompt-toolkit  3.0.47
[+] Building 1.5s (12/12) FINISHED                                                    docker:desktop-linux
=> [internal] load build definition from Dockerfile …
```
=> fix(main): Respect xontribs autoload disabled in RC files

tests/test_main.py, xonsh/main.py
Allows specifying any existing non-directory path as a script to run. Primarily I intend for this to allow running scripts out of named pipes (FIFOs). Examples here use bash, but the principal is not tied to any shell, see the unit tests for how this can be done in python.
Before:
```console
$ xonsh <(echo "print('Hello')")
xonsh: /dev/fd/63: No such file or directory.
```
After:
```console
$ xonsh <(echo "print('Hello')")
Hello
```
This type of script specification is supported by many interpreters including python and bash:
```console
$ python3 <(echo "print('Hello')")
Hello
$ bash <(echo "echo Hello")
Hello
```
You could accomplish something similar using `echo "print('Hello')" | xonsh` or `xonsh < <(echo "print('Hello')")` however that prevents reading from stdin as part of your …
=> feat: Allow specifying special files as scripts
