xonsh/xonsh

news/iglob.rst
tests/test_tools.py
xonsh/tools.py

Make iglobpath() more robust

---

news/teenc.rst
xonsh/base_shell.py

Give sensible defaults when encoding bytes

---

docs/guides.rst
docs/tutorial_subproc_strings.rst

Hopefully this closes #621 and #1432

tutorial for subproc strings

---

news/setup.rst
xonsh/main.py

This will be useful in rever and elsewhere.

added setup function

---

news/catout.rst
xonsh/xoreutils/cat.py

cat outputs in configured encoding

---

news/checkend.rst
xonsh/proc.py

Fixed process hanging issue.

---

news/e2o.rst
tests/test_integrations.py
xonsh/built_ins.py

fixed callable alias e>o redirection

---

news/complete_line.rst
xonsh/completers/bash_completion.py

Should fix #2596, see https://github.com/xonsh/py-bash-completion/pull/4

bash autocomplete space deduplication bugfix

---

news/pktnl.rst
xonsh/base_shell.py
xonsh/environ.py

Better Append Newline Default

---

.circleci/config.yml
.gitignore
news/rawlambda.rst
tests/test_ast.py
xonsh/ast.py
xonsh/parsers/base.py

lambda AST fixes

---

docs/guides.rst
docs/subproc_types.rst
docs/tutorial.rst
docs/tutorial_subproc_strings.rst

to make the subprocess distinctions a little clearer hopefully

doc improvements

---

news/trail.rst
xonsh/completers/bash_completion.py

Same as https://github.com/xonsh/py-bash-completion/pull/5

fixed trailing bash whitespace completion issue

---

news/xdgconf.rst
xonsh/environ.py

Added support for configuration through ~/.config/xonsh/rc.xsh

---

news/escape_pound.rst
xonsh/completers/path.py

One character fix for question raised in #2602

Add `#` to chars that need autoquotes

---

news/curltru.rst
xonsh/commands_cache.py

curl predict_true()

---

news/pefnf.rst
xonsh/built_ins.py
xonsh/jobs.py
xonsh/proc.py

fix command not found error

---

news/srcerror.rst
xonsh/aliases.py

Source Forigen error Improvements

---

news/wizwrite.rst
tests/test_wizard.py
xonsh/wizard.py
xonsh/xonfig.py

fixed wizard writing of more sophisticated container types

---

news/fixTestNews.rst
tests/test_news.py

Uses regex to check changelog file format. 
Fixes #2667

fixed buggy rst file checker

---

news/fixCommandsCacheGen.rst
xonsh/commands_cache.py

A typo on line 97 was the reason behind #2313 
Fixes #2313

non directories in $PATH are now ignored

---

news/addToEnvPath.rst
xonsh/tools.py

added an add function to xonsh.tools.EnvPath

---

news/hgi.rst
xonsh/commands_cache.py

threadable false for interactive mercurial

---

docs/comparison.rst
docs/devguide.rst
docs/index.rst
docs/tryitnow.rst
news/replit.rst

Regains the xonsh live idea!  It isn't perfect, but I think it is good enough.  
Thanks again to @astronouth7303! The events system was essential here to routing around some weird bugs in repl.it

Added repl.it to the docs

---

news/ctypesutil.rst
setup.cfg
xonsh/platform.py

Ctypes.util fix 

---

news/aaron-sprint-(special-method-printing)-2018.rst
xonsh/pretty.py

Added a hook for a special method printing on an object. The method is called xonsh_display.

WIP SciPy sprint, printing special methods to prompt.

---

news/atml.rst
tests/test_execer.py
tests/test_tools.py
xonsh/tools.py

fixed multiline autowrapping in @(expr)

---

news/firstse.rst
tests/test_integrations.py
xonsh/execer.py

First SyntaxError no longer always reported

---

news/pygments_cache.rst
setup.cfg
xonsh/ptk/shell.py
xonsh/ptk2/shell.py
xonsh/pygments_cache.py

Add the `get_all_styles()`  function which @scopatz added to the ``pygments_cache`` module

Pygments get_all_styles

---

news/indir.rst
tests/test_lib/test_os.xsh
xonsh/lib/os.xsh

Return to original directory if exception during indir

---

docs/api/index.rst
docs/api/jupyter_shell.rst
news/xernel.rst
requirements-docs.txt
setup.cfg
xonsh/__init__.py
xonsh/jupyter_kernel.py
xonsh/jupyter_shell.py
xonsh/main.py
xonsh/shell.py

This fixes #2712, in so far as that issue is actually addressable. 
I have completely removed the dependence on `ipykernel`, and instead forked the pyzmq-based [simple kernel](https://github.com/dsblank/simple_kernel/blob/master/simple_kernel.py).  I needed to do this in order to avoid some of the AST transformations that were interfering with xonsh's syntax. 
Things should more or less be working now.

Jupyter Xernel

---

news/pcat.rst
scripts/xonsh-cat
scripts/xonsh-cat.bat
setup.py
tests/test_commands_cache.py
xonsh/aliases.py
xonsh/commands_cache.py
xonsh/jupyter_kernel.py
xonsh/main.py
xonsh/xontribs.py
xonsh/xoreutils/cat.py

This addresses some of the further issues brought up in #2712

Jupyter printing with cat

---

news/voxapi_ValueError.rst
xontrib/voxapi.py

Fix ValueError when executing `vox list`

---

news/autojump_xontrib.rst
xonsh/xontribs.json

added autojump xontrib 

---

.travis.yml
xonsh-in-docker.py

Rebased @traverseda's work from #2550 against current master to take care of the changes to the `setup.cfg` file and tweaked some defaults -- seems to be "passing" now (with allowed failures for the pypy test)
No news item needed for this.  This can also supercede #2550

Pypytravis

---

news/fix_2785.rst
xontrib/voxapi.py

Improves iteration over virtual environments 

---

.travis.yml
news/multiwrap2.rst
tests/test_execer.py
xonsh/execer.py

Should fix #2675.  CC @CJ-Wright @laloch

multiwrap fix

---

.travis.yml

Removing some of the lines that @scopatz added to the `travis.yml` file to get the build to work right -- should work now without those now that installing `xonsh` doesn't mess with repo state

Remove extra cleans and resets from doc builds

---

news/fssup.rst
xonsh/aliases.py
xonsh/environ.py

skip foreign

---

news/rlcomp.rst
xonsh/readline_shell.py

Deceptively simple, closes #2769

readline completer fixes

---

news/emptysrc.rst
xonsh/completers/bash_completion.py

fixes empty source

---

docs/tutorial.rst
news/atin.rst
tests/test_builtins.py
tests/test_parser.py
xonsh/built_ins.py
xonsh/parsers/base.py

This closes #2640 
This was fun to implement.

@(expr) in subprocess tokens

---

news/aurman.rst
xonsh/commands_cache.py

unthread aurman

---

news/hgsplit.rst
xonsh/commands_cache.py

unthread hg split

---

news/dragonfly_support.rst
xonsh/aliases.py
xonsh/platform.py

Add DragonFly BSD support

---

news/subproc-whitespace-fix.rst
tests/test_ast.py
xonsh/ast.py
xonsh/color_tools.py

Fix issues #2584 and #2430

---

news/cryptop.rst
xonsh/commands_cache.py

don't capture cryptop output

---

news/pbc025.rst
xonsh/completers/bash_completion.py

bash completions v0.2.5

---

azure-pipelines.yml
news/azure-pipelines.rst

Wild.  They have built-in support for conda environments.  No idea if any of this will work and very much a work in progress, but let's see how this goes...

Set up CI with Azure Pipelines

---

.appveyor.yml

Leaving in msys and Py34 for now

recude appveyor build matrix

---

news/xonsh_session.rst
xonsh/built_ins.py

no longer deprecate all proxies

---

news/fix_string_index.rst
xonsh/completers/bash_completion.py

copied from @gforsyth in py-bash-completion

Fix string index

---

.circleci/config.yml
news/test-fix.rst
tests/conftest.py
tests/test_lib/test_os.xsh
xonsh/built_ins.py
xonsh/dirstack.py
xonsh/environ.py
xonsh/lib/os.xsh
xonsh/platform.py
xonsh/proc.py
xonsh/pytest_plugin.py
xonsh/readline_shell.py
xonsh/tokenize.py

I was seeing a bunch of strange test failures locally. This fixes them.

test fixes

---

docs/linux.rst
news/updatedlinux.rst

Fixes #2877

---

news/TEMPLATE.rst
news/sudo-permission-error.rst

I'm very sorry about this guys. It's a shame.

Restore TEMPLATE.rst

---

docs/xonshrc.xsh

This partially addresses https://github.com/xonsh/xonsh/issues/2364#issuecomment-433540042, but I'm not sure if there is another place I'd need to make a change to include this in the setup wizard.
I'm not sure this really deserves a news item, does it?

xonshrc.xsh now links to more details

---

.appveyor_install.cmd
news/fstrenv.rst
requirements-tests.txt
tests/test_news.py
tests/test_parser.py
xonsh/ansi_colors.py
xonsh/parsers/base.py
xonsh/prompt/base.py
xonsh/pyghooks.py
xonsh/style_tools.py
xonsh/tools.py

This fixes #2870, and also updates the news format to the newer format which confuses fewer people with the None removal

f-strings, again

---

docs/tutorial.rst

Fix typo in docs

---

docs/sidebar.rst
news/docs_sidebar_dedupe.rst

Remove lots of duplicated sections already covered by index.

docs: Deduplicate sections on sidebar page

---

news/fix-flake8-errors.rst
xonsh/dirstack.py
xonsh/proc.py
xontrib/bashisms.py

This PR could be merged before #2916 to fix the CI.

Fix Flake8 errors

---

news/filepath-to-logfile.rst
xonsh/tools.py

make $XONSH_TRACEBACK_LOGFILE accept path objects

---

news/fix-import-names.rst
tests/test_parser.py
xonsh/parsers/base.py

Fix import statement with trailing comma within parenthesis

---

news/annoassign.rst
tests/test_parser.py
xonsh/ast.py
xonsh/parsers/base.py
xonsh/parsers/v36.py

Brings us back to full Python compatability.

added prelim support for annotation assignement

---

news/fix-exec-candidates.rst
xonsh/tools.py

fix no candidates if no permission files in PATH

---

news/fix-resource-warnings.rst
tests/bin/wc
tests/conftest.py
tests/test_main.py
tests/test_xoreutils.py

A clean-up PR for resources leak fixes.

Fix several ResourceWarning: unclosed file

---

docs/sidebar.rst

Removed duplicate API link in sidebar

---

news/extranl.rst
xonsh/main.py

Weird that this is needed, but it does fix the problem.  Closes #2910

fix extra newlines in ptk2

---

news/base16-shell.rst
xonsh/xontribs.json

Adding base16 shell on xontrib https://github.com/xonsh/xonsh/issues/1228#issuecomment-446711013

Add base16 shell

---

docs/api/dumb_shell.rst
docs/api/index.rst
news/dumbterm.rst
xonsh/__init__.py
xonsh/dumb_shell.py
xonsh/platform.py
xonsh/shell.py

This should fix the issues with emacs support. closes #2891

dumb terminal support

---

news/cdex.rst
tests/test_integrations.py
xonsh/proc.py

fix for callable aliases raising error when RAISE_SUBPROC_ERROR = True

---

news/ls_predict_true.rst
xonsh/commands_cache.py

Add `ls` to `threadable_predictors` as `predict_true`

---

.github/issue_template.md
.github/pull_request_template.md

It is worth to update repo description as well.

https for github templates

---

docs/bash_to_xsh.rst

Document file extension and shebang

---

azure-pipelines.yml
news/broke-sym.rst
requirements-tests.txt
xonsh/tools.py

Broken symlinks

---

xonsh/tools.py

Resolved issue on Windows when broken symlinks were present on the path (#2982)

Fix for #2982

---

azure-pipelines.yml
docs/tutorial.rst
news/broke-sym.rst
news/envprepost.rst
requirements-tests.txt
xonsh/prompt/base.py
xonsh/prompt/cwd.py
xonsh/prompt/env.py
xonsh/tools.py

This came up in https://github.com/pypa/virtualenv/issues/1299 and is probably the right way to implement the env name printing.
@gforsyth - will this mess you up for xonda?
I have based this on #2993, mostly so I don't have redo all of the CI work.  Also I ran black on the prompt subpackage

env_prefix and env_postfix

---

news/pv.rst
xonsh/jobs.py

don't set empty signal masks

---

docs/_static/xonsh_sticker.svg

I put in a trial run of these to Stickermule and they came out great!
Putting it here so it's available for others, although I'm planning to
put in a big order so I can bring some to PyCon

Add SVG of xonsh sticker to docs/_static

---

news/dubs-tab.rst
xonsh/completers/base.py

fixed completer issue

---

news/recurr-jobs.rst
xonsh/jobs.py

attempt to fix wait_for_active_job recurrsion

---

news/linecont.rst
tests/test_execer.py
xonsh/execer.py
xonsh/tools.py

This was actually easier than expected. Closes #3005

fixed indentation errors

---

docs/dependencies.rst
docs/index.rst
docs/installation.rst

Clarify installation layout in docs

---

news/spec.rst
tests/test_aliases.py
xonsh/aliases.py
xonsh/proc.py
xonsh/tools.py

Partial Eval Aliases

---

news/cfd.rst
tests/test_integrations.py
xonsh/built_ins.py
xonsh/proc.py

Don't close file descriptors

---

news/astatemacro.rst
tests/test_builtins.py
xonsh/built_ins.py

Closes #3016 and adds more tests

fixed macro issues

---

docs/tutorial.rst
news/ptk-colors.rst
tests/test_pyghooks.py
xonsh/color_tools.py
xonsh/pyghooks.py
xonsh/style_tools.py

PTK colors refactor

---

CHANGELOG.rst
CONTRIBUTING.rst
docs/tutorial.rst
xonsh/built_ins.py
xonsh/commands_cache.py

Reduced warnings which occurs when building docs. (`cd docs/ && make html`)
Sorry, This PR doesn't remove all warnings. I didn't know how to fix the remaining warnings.

Reduce sphinx build warnings

---

xonsh/prompt/vc.py

Following the comment on #3061, I reduce the Try/Except to the minimum. I tried to reopen the PR, but it seems not possible, so I open a new one.

.hg lookup, OSError, reduce the Try/Except to the minimum

---

.circleci/config.yml
news/black_xontribs.rst
xontrib/bashisms.py
xontrib/coreutils.py
xontrib/distributed.py
xontrib/free_cwd.py
xontrib/mpl.py
xontrib/mplhooks.py
xontrib/vox.py
xontrib/voxapi.py
xontrib/whole_word_jumping.py

Black xontribs

---

news/fix-ansi-colors.rst
xonsh/ansi_colors.py
xonsh/color_tools.py

Closes #3091 
Edit: This now also fixes #3100.

color_tools: protect short2rgb against values with leading zeroes

---

news/tests_usrbinenv_args_update.rst
scripts/xonsh
scripts/xonsh-cat

This PR fixes a bug shown by @carmenbianca in #3082.

Tests usrbinenv args update

---

news/prompt_error.rst
tests/test_prompt.py
xonsh/prompt/base.py

Final touches to close issue `#1564`.

Added emphasis to the error source

---

news/unthread-sudoedit.rst
xonsh/commands_cache.py

Predict sudoedit unthreadable

---

news/hist-gc.rst
xonsh/history/json.py

fixed history gc

---

run-tests.xsh

test main to run seprately

---

news/fix-help-ver-predictor.rst
xonsh/commands_cache.py

Fix exception in help_version threadable predictor

---

news/patch-gitstatus-delete.rst
xonsh/prompt/gitstatus.py

Fixes gitstatus prompt so that it also reports deleted files
Finally got round to submitting this #2817

Patch gitstatus delete

---

news/ptk2-mlp0.rst
xonsh/ptk2/shell.py

fixes ptk2 multiline prompt issue

---

news/stderr-pre.rst
xonsh/tools.py

fixed XONSH_STDERR_POSTFIX issue

---

docs/_static/numpy_friendly.css_t
xonsh/environ.py

+ Show default value instead of `<function function_name at FUNC_ID_HEX>`.
+ Show default PATH instead of the PATH which set when building document.
This is just document update so I didn't add news file.

Change default environment value of document.

---

news/bashism_altdot.rst
xontrib/bashisms.py

Is part of prompt toolkit now
fixes https://github.com/xonsh/xonsh/issues/3160.

Remove hard coded Alt+. binding

---

news/dev_syun.rst
xonsh/ptk2/completer.py

fix: https://github.com/xonsh/xonsh/issues/3161

Fix completer error

---

news/add_xontrib.rst
xonsh/xontribs.json

New xontrib.
Please look this repo.
https://github.com/6syun9/xontrib-readable-traceback

add xontrib readable-traceback

---

news/bash-comp-0.2.6.rst
xonsh/completers/bash_completion.py

Bash comp 0.2.6

---

.github/issue_template.md

fix issue template, no news needed.

details needs space

---

news/xontrib-kitty.rst
xonsh/xontribs.json

Also, I realphabetized the xontribs

xontrib-kitty

---

news/rmws.rst
xonsh/foreign_shells.py

Really weird bug that I encountered in the tutorial writing, but this seemed to fix it.

remove newlines

---

news/xonsh_dunder.rst
xonsh/built_ins.py

Remove deprecated __xonsh__* mappers

---

news/proxy_cleanup.rst
xonsh/built_ins.py
xonsh/execer.py
xonsh/main.py

Also removed `DeprecationWarningProxy`, as it is no longer needed.

Cleaned up proxy loading and unloading.

---

README.rst

remove landscape badge

---

docs/comparison.rst

Not CHANGELOG worthy
Discussed a bit in #3250

Clarify man-page parsing feature

---

xonsh/environ.py

fix XONSH_DATETIME_FORMAT VarDoc formatting

---

xonsh/environ.py

- fix typos
- fix formatting
- re-word

revamp COMPLETION_IN_THREAD VarDoc

---

news/target-color.rst
tests/test_environ.py
xonsh/environ.py

Target color

---

news/co.rst
tests/test_integrations.py
xonsh/lib/subprocess.xsh

There is already a test for this. Addresses #3284

check_output() fix

---

news/co.rst
news/space-logical.rst
tests/test_integrations.py
xonsh/aliases.py
xonsh/lib/subprocess.xsh

Space logical

---

docs/api/lib/index.rst
docs/api/lib/itertools.rst
news/lib_itertools.rst
tests/test_lib/test_itertools.py
xonsh/lib/itertools.py

Add as_iterable to itertools

---

news/jedierr.rst
xontrib/jedi.xsh

jedi error fix

---

news/percol.rst
xonsh/commands_cache.py

percol false

---

docs/guides.rst
docs/tutorial_xonsh_projects.rst
xonsh/main.py

add setup docs

---

news/ctxvars.rst
tests/test_integrations.py
xonsh/aliases.py

Context vars fix

---

news/badcol.rst
tests/test_ansi_colors.py
xonsh/ansi_colors.py
xonsh/environ.py

more color code fixes and robustness

---

news/openbsd-alias.rst
xonsh/aliases.py
xonsh/platform.py

In response to issue #3354, here is a PR for the patch.
Cheers,

Added openbsd aliases and platform detection

---

docs/appimage.rst

Update https://github.com/xonsh/xonsh/pull/3357

Update PR 3357

---

web_config/webconfig.py
xonsh/xonfig.py

Start on #1798 during scipy19.

WIP: Add initial webconfig from fish

---

news/fixup-rmtree-windows.rst
xonsh/lib/os.xsh

Fixup rmtree on windows

---

.gitignore
news/unit_tests1.rst
scripts/xonsh
scripts/xonsh-cat

Correcting unexpected unit test failures.  My environment is ubuntu 19.10 but Python 3.8.0 in a venv.
See #3397 for details.

correct xonsh invocation for unit tests

---

news/3427-fix-vc-prompt-color.rst
tests/test_prompt.py
xonsh/prompt/vc.py

3427 fix vc prompt color

---

docs/containers.rst
docs/installation.rst

Put a page in the actual docs about the xonsh containers.

Add some docs about the xonsh containers

---

news/umask.rst
xonsh/aliases.py
xonsh/xoreutils/umask.py

I saw #3268 and thought this might be helpful.  This adds a `umask` command to `xoreutils`.

add umask command

---

news/trace_subproc_fix_pipeline.rst
xonsh/built_ins.py

Hi! It's a simple fix. Please merge after tests or restart the tests if it fails by other reasons.

trace subproc: fix pipeline case

---

docs/editors.rst
docs/installation.rst
news/emacs-mode.rst

editor suport docs page, with emacs mode

---

README.rst
news/readme_xxh.rst

readme: xxh new repo name

---

CONTRIBUTING.rst
news/update-pylint-doc.rst

update docs - running pylint for specific files

---

news/sqlite-history-errordups.rst
tests/test_environ.py
tests/test_history_sqlite.py
xonsh/environ.py
xonsh/history/sqlite.py

feat: add HISTCONTROL(erasedups) support to sqlite backend

---

xontrib/abbrevs.py

Fixes some minor issues of #3484.
No news entry needed (fixes unreleased code).
Sorry for the mess.

abbrevs: fix possible exception and do some cleanup

---

news/unthread-xdg-open.rst
xonsh/commands_cache.py

Unthread xdg open

---

.github/workflows/black.yml
.github/workflows/elm.yml
.github/workflows/pytest.yml
news/github_actions.rst

Add PRs to event triggers for github actions

---

news/fix-captured-inject.rst
tests/test_integrations.py
tests/test_parser.py
xonsh/built_ins.py
xonsh/parsers/base.py

See the trail in #3156, #3510.
Closes #2328
Closes #2755
Closes #3457

Fix @$() subprocess operator

---

.github/workflows/pytest.yml
.travis.yml

Add OSX to gh actions matrix

---

xonsh/xonfig.py

Typo in WELCOME_MSG

---

.gitignore
news/add_directory_history_navigation.rst
xonsh/xontribs.json

feat: added xontrib for directory history navigation

---

news/is_3551.rst
tests/test_builtins.py

fix test case for convert_macro_arg

---

tests/test_integrations.py

PRing this to see if it "fixes" CI

Mark flaky test

---

news/fix-unary-position.rst
tests/test_integrations.py
xonsh/parsers/base.py

Fix column offset of unary operator AST node

---

docs/bash_to_xsh.rst
news/exit.rst

exit to docs

---

news/xontrib-xpg.rst
xonsh/xontribs.json

Adding a new xontrib.   Run/explain sql query from xonsh to postgresql.

adding xontrib-xpg

---

README.rst

the matrix room is bridged to the gitter chat

Add link to matrix room

---

.gitignore
news/fix-history-gc.rst
tests/test_history.py
tests/test_integrations.py
xonsh/history/base.py
xonsh/history/json.py
xonsh/history/main.py

Addressing issue #3599.
As mentioned there, need feedback whether to add a warning or an extra option before this fix deletes a lot of someone's old history.

fix history gc for json backend

---

news/hg-get-branch-topic.rst
xonsh/prompt/vc.py

Mercurial [topics](https://www.mercurial-scm.org/doc/evolution/tutorials/topic-tutorial.html) are not taken into account by xonsh.
This function works fine in my .xonshrc. I didn't try to run the xonsh tests with these modifications. I hope the CI will do that for me :slightly_smiling_face:

get_hg_branch aware of topics

---

docs/xonshrc.rst

- Document the XDG compatible location for `xonshrc` (see https://github.com/xonsh/xonsh/pull/2611#issuecomment-642324760)
- Snippet: Change date format for every other prompt
- Snippet: Use Nix Package Manager with Xonsh

Expand xonshrc documentation

---

.github/workflows/pytest-linux.yml
.github/workflows/pytest-macos.yml
.github/workflows/pytest-windows.yml

Needed  because GH hasn't fixed https://github.community/t/re-run-jobs/16145

make GH Actions more restartable

---

news/goodbye-distutils.rst
pyproject.toml
setup.py

Fixes #3638.
Also remove Python 2 compatibility imports.
Also declare build-time dependency on setuptools.

Remove distutils fallback.

---

docs/bash_to_xsh.rst
news/bash-to-xsh-improvements.rst

1. Mention of `UPDATE_OS_ENVIRON`
2. Mention of `dotglob` option
3. Mention of `readline` completion style

bash to xsh improvements

---

docs/tutorial.rst

Closes #3648 
The tone of the new example is a bit less "serious", so let me know if I need to change that!

docs: More examples of what SubprocSpec can do

---

news/improve-completers2.rst
tests/test_ptk_completer.py
tests/test_readline_shell.py
tests/xontribs/test_jedi.py
xonsh/ptk_shell/completer.py
xontrib/jedi.xsh

Continuing #3643, I wrote some tests and fixed some small bugs

Add tests and fix bugs for RichCompletion and Jedi xontrib

---

news/pyupgrade.rst
xonsh/xoreutils/_which.py
xonsh/xoreutils/cat.py
xonsh/xoreutils/tee.py
xonsh/xoreutils/tty.py
xonsh/xoreutils/ulimit.py
xonsh/xoreutils/umask.py
xonsh/xoreutils/uptime.py
xonsh/xoreutils/which.py

See #3664 for some of the changes this does; mostly converting to
f-strings when possible.

Apply pyupgrade --py36-plus to all xoreutils.

---

.github/workflows/genbuilds.xsh
.github/workflows/pytest-linux-3.6.yml
.github/workflows/pytest-linux-3.7.yml
.github/workflows/pytest-linux-3.8.yml
.github/workflows/pytest-macos-3.6.yml
.github/workflows/pytest-macos-3.7.yml
.github/workflows/pytest-macos-3.8.yml
.github/workflows/pytest-windows-3.6.yml
.github/workflows/pytest-windows-3.7.yml
.github/workflows/pytest-windows-3.8.yml
.github/workflows/pytest.tmpl

This should allow us to restart individual CI jobs.

generate workflows

---

news/walrus.rst
tests/test_parser.py
tests/tools.py
xonsh/ast.py
xonsh/lexer.py
xonsh/parsers/v38.py
xonsh/tokenize.py

~~WIP; missing lexer/parser tests.~~
Suggestions welcome...
Relates to #3101

Add Python 3.8 assignment expressions ("walrus"/PEP 572)

---

news/pip-files.rst
setup.py

fixed pip install && setup.py sdist to include generated files

---

news/enviter.rst
tests/test_environ.py
xonsh/environ.py

fixes issue in https://github.com/xonsh/xonsh/pull/3679#discussion_r470211364

Env.rawkeys()

---

news/unlocked.rst
xonsh/history/json.py

locked issue

---

amalgamate.py
docs/cmdhelp.py
docs/conf.py
tests/aliases/test_xexec.py
tests/test_environ.py
tests/test_history.py
tests/test_imphooks.py
tests/test_parser.py
tests/test_ptk_completer.py
tests/test_ptk_highlight.py
tests/test_ptk_history.py
tests/test_ptk_multiline.py
tests/test_readline_shell.py
tests/test_vox.py
tests/test_xoreutils.py
tests/tools.py
tests/xontribs/test_jedi.py

black updates to tests and docs

---

.authors.yml
.mailmap
CHANGELOG.rst
xonsh/xontribs.json

excising old, dead names.
and fixing links.

The Great Renaming of 2020

---

docs/_templates_overwrite/index.html

Fix typo on index.html

---

news/parser-emit-error.rst
xonsh/parsers/base.py
xonsh/parsers/v36.py

Propagate parser errors from production rules

---

tests/tools.py

Fixes (locally) failing vox test. I don't understand why GitHub CI is not failing.

tests: Add VIRTUAL_ENV key to DummyEnv

---

news/docker-pytest.rst
xonsh-in-docker.py

Automates pytest installation into the docker container.
No news entry needed.

Add --pytest argument to xonsh-in-docker script

---

news/conda-suggest.rst
xonsh/tools.py

This adds an optional hook into [conda-suggest](https://github.com/conda-incubator/conda-suggest), if it is available.

conda-suggest

---

news/name_in_error.rst
xonsh/environ.py

Provide name of env var that fails to validate

---

news/xontrib_descr.rst
xonsh/xontribs.json

xontrib-argcomplete and xontrib-pipeliner description improvement

---

README.rst
docs/contents.rst
news/docs.rst

The order of sections in docs changed 2

---

README.rst

Sorry for the noise around this micro PRs but I fixed the link to xontribs list :)

Fix xontribs link

---

docs/bash_to_xsh.rst
news/bashisms.rst
xonsh/xontribs.json
xontrib/bashisms.py

Hi! xonsh is great!
1. "Bash to Xonsh Translation Guide" improvements.
2. Added bash-like functions `unset`, `export`, `set`, `shopt`, `complete` to bashisms just for fun :)
Closes #3795 #2041

"Bash to Xonsh Translation Guide" improvements and added commands to bashisms xontrib

---

news/add-flake8-docstrings.rst
requirements/tests.txt
setup.cfg
xonsh/aliases.py
xonsh/environ.py
xonsh/lexer.py
xonsh/parsers/base.py
xonsh/ptk_shell/updator.py
xonsh/tools.py

most of the rules are disabled since it will take longer to fix them all
maybe in future version we can fix them one by one

feat: integrate flake8-docstring

---

docs/api/ptk_shell/updator.rst
news/add-api-docs-for-ptk-updator-module.rst
xonsh/ptk_shell/updator.py

docs: add api-docs for ptk_shell.updator module

---

.gitattributes
docs/todo.rst
news/gh_xsh.rst

Details - https://github.com/github/linguist#using-gitattributes

Syntax highlighting for xsh on Github

---

news/fix_env_subst.rst
tests/test_tools.py
xonsh/tools.py

Hello! Xonsh is super cool!
Closes #3818 + new tests added.
Please merge 3816, 3814, 3817, 3822 🙏

Fix env variables wrong substitution

---

CONTRIBUTING.rst
docs/advanced_events.rst
docs/editors.rst
docs/events.rst
docs/tutorial.rst
docs/tutorial_macros.rst
docs/xonshrc.rst

Resolves #3800. No news entry.

Fix some typos in docs

---

docs/editors.rst
news/editors_vscode_vim.rst

Thanks to @jnoortheen for https://github.com/jnoortheen/vscode-xonsh

Added Visual Studio Code (VSCode) extension and Vim syntax file to the Editors page

---

xonsh/ansi_colors.py
xonsh/pyghooks.py
xonsh/style_tools.py

Fix differing PTK and readline background handling

---

.github/workflows/elm.yml
.github/workflows/pytest-linux-3.6.yml
.github/workflows/pytest-linux-3.7.yml
.github/workflows/pytest-linux-3.8.yml
.github/workflows/pytest-macos-3.6.yml
.github/workflows/pytest-macos-3.7.yml
.github/workflows/pytest-macos-3.8.yml
.github/workflows/pytest-windows-3.6.yml
.github/workflows/pytest-windows-3.7.yml
.github/workflows/pytest-windows-3.8.yml
.github/workflows/pytest.tmpl

goanpeca -> conda-incubator

---

news/xontribs_nocolor.rst
xontrib/mplhooks.py
xontrib/prompt_ret_code.xsh

Fixed NO_COLOR to RESET in prompt_ret_code and mplhooks.

xontribs no_color to reset

---

news/random.rst
tests/test_tools.py
xonsh/shell.py
xonsh/tools.py

Remove import random

---

news/fix-async-worker-setting.rst
tests/test_tools.py
xonsh/environ.py
xonsh/tools.py

handle None value for ASYNC_PROMPT_THREAD_WORKERS
fixes #3858

fix: env handle optional values

---

news/fix-async-prompt-nested-format-string.rst
xonsh/prompt/base.py
xonsh/ptk_shell/formatter.py
xonsh/ptk_shell/updator.py

fix: async prompt update nested-format-string

---

tests/test_parser.py

get_repo_url() test

---

news/cookiecutter.rst

~1. First of all merge https://github.com/xonsh/xontrib-cookiecutter/pull/2~ DONE
2. And then here is no changes only news :)

Cookiecutter template to creating new xontribs has many improvements

---

news/xonfig_xontribs.rst
tests/test_xontribs.py
xonsh/readline_shell.py
xonsh/xonfig.py
xonsh/xontribs.json
xonsh/xontribs.py

_Originally posted by @scopatz in https://github.com/xonsh/xonsh/issues/3864#issuecomment-710591574_:
> We really need to have `xonfig` print out what xontribs have been loaded.

xonfig xontribs

---

news/CommandsCache_path_speed.rst
news/all_commands.rst
tests/test_environ.py
xonsh/commands_cache.py

Reading the directory from PATH and the symlink to this directory from PATH only once while create CommandCache

---

news/update-prompt-vc-branch-tests.rst
tests/test_prompt.py

since recent changes, many could have main as the default branch. The highly correct method would be to get default branch config from git. Let me know if you need that.

test: update vc-branch test. default branch could be main as well

---

news/xontrib-cmd-durations.rst
xonsh/xontribs.json

chore: add xontrib-cmd-durations

---

news/commandpipeline-repr.rst
xonsh/procs/pipelines.py

Fixes #3938. Super simple fix. Currently on a super slow machine, so waiting to see if any tests break on CI because of this.

repr() all attributes in CommandPipeline.__repr__

---

news/commandpipeline-repr.rst
xonsh/procs/pipelines.py

Continue the #3939
Additional news aren't required

Format CommandPipeline.__repr__

---

news/flake8-ambiguous-variable-name-error.rst
setup.cfg
xonsh/jupyter_kernel.py
xonsh/procs/readers.py
xonsh/prompt/cwd.py
xonsh/ptk_shell/completer.py
xonsh/ptk_shell/key_bindings.py
xonsh/readline_shell.py
xonsh/tools.py
xontrib/voxapi.py
xontrib/xog.py

refactor: some backlog from when flake8 setup

---

docs/tutorial_history_backend.rst
news/fix_history_tutorial.rst

Updated some `History` interface prototypes to match the current implementation.
Closes #3961

Docs: Updated History Backend tutorial

---

news/fix-xonfig-wizard-make-xontrib.rst
xonsh/xonfig.py

fix: xonfig wizard - make_xontrib

---

.github/workflows/elm.yml

v1 uses some deprecated features

update setup-minniconda to v2

---

news/xontrib-broot.rst
xonsh/xontribs_meta.py

feat: add xontrib-broot package

---

docs/aliases.rst

fix aliases.rst

---

news/use-black-20.8.rst
requirements/tests.txt
xonsh/commands_cache.py
xonsh/completers/bash_completion.py
xonsh/jobs.py
xonsh/lib/collections.py
xonsh/lib/itertools.py
xonsh/parsers/base.py
xonsh/parsers/v36.py
xonsh/parsers/v38.py
xonsh/platform.py
xonsh/pretty.py
xonsh/pyghooks.py
xonsh/pytest_plugin.py
xonsh/wizard.py
xontrib/free_cwd.py
xontrib/voxapi.py

- I think it is time to upgrade black. 
- It can now support new lines with comma
- Docstring formatting is also nice

Upgrade black 20.8b1

---

news/feat-clipboard-support.rst
setup.py
xonsh/ptk_shell/shell.py

feat: use PyperClipboard if available for ptk

---

docs/api/cli_utils.rst
docs/tutorial_completers.rst
news/completer-py-api.rst
tests/test_cli_utils.py
xonsh/__init__.py
xonsh/built_ins.py
xonsh/cli_utils.py
xonsh/completers/_aliases.py
xonsh/completers/completer.py
xonsh/completers/tools.py
xonsh/history/sqlite.py
xonsh/ptk_shell/completer.py

Completer py api

---

news/nuitka_fix.rst
xonsh/environ.py

Hi!
Please read the detailed report before the PR review - https://github.com/xonsh/xonsh/issues/2895#issuecomment-743382262
Closes #2895

The change that allows Nuitka build the xonsh binary

---

xonsh/xontribs_meta.py

Update avox description

---

news/xontrib-avox-poetry.rst
xonsh/xontribs_meta.py

feat: add xontrib-avox-poetry

---

.coveragerc
.github/workflows/genbuilds.py
.github/workflows/pytest-linux-3.6.yml
.github/workflows/pytest-linux-3.7.yml
.github/workflows/pytest-linux-3.8.yml
.github/workflows/pytest-linux-3.9.yml
.github/workflows/pytest-macos-3.6.yml
.github/workflows/pytest-macos-3.7.yml
.github/workflows/pytest-macos-3.8.yml
.github/workflows/pytest-macos-3.9.yml
.github/workflows/pytest-windows-3.6.yml
.github/workflows/pytest-windows-3.7.yml
.github/workflows/pytest-windows-3.8.yml
.github/workflows/pytest-windows-3.9.yml
.github/workflows/pytest.tmpl
.github/workflows/qa-linux-3.8.yml
.gitignore
news/code-coverage.rst
run-tests.xsh

Also fix `run-tests.xsh test` accepting pytest arguments

chore: bring back codcoverage report

---

.travis.yml
docs/Makefile
docs/conf.py
docs/envvars.jinja2
docs/envvars.rst
docs/jinja_rst_ext.py
docs/rst_helpers.py
docs/serve_docs.py
news/group-env-variables.rst
requirements/docs.txt
requirements/tests.txt
tests/test_environ.py
xonsh/environ.py
xonsh/xonfig.py

Add groups to env vars

---

news/xontrib-powerline3.rst
xonsh/xontribs_meta.py

feat: add xontrib-powerline3

---

news/welcome.rst
xonsh/xonfig.py

Welcome message cosmetic changes

---

codecov.yml

refactor: make codecov checks informational

---

news/ignorespace.rst
tests/test_history.py
tests/test_history_sqlite.py
xonsh/base_shell.py
xonsh/history/json.py
xonsh/history/sqlite.py
xonsh/ptk_shell/shell.py

Add $HISTCONTROL=ignorespace support

---

news/callback-in-abbrevs.rst
tests/xontribs/test_abbrevs.py
xonsh/xontribs_meta.py
xontrib/abbrevs.py

Feat abbrevs callback

---

.github/workflows/genbuilds.py
.github/workflows/pytest-linux-3.6.yml
.github/workflows/pytest-linux-3.7.yml
.github/workflows/pytest-linux-3.8.yml
.github/workflows/pytest-linux-3.9.yml
.github/workflows/pytest-macos-3.6.yml
.github/workflows/pytest-macos-3.7.yml
.github/workflows/pytest-macos-3.8.yml
.github/workflows/pytest-macos-3.9.yml
.github/workflows/pytest-windows-3.6.yml
.github/workflows/pytest-windows-3.7.yml
.github/workflows/pytest-windows-3.8.yml
.github/workflows/pytest-windows-3.9.yml
.github/workflows/qa-linux-3.8.yml
news/py39-support.rst
tests/test_main.py
tests/test_parser.py
xonsh/parser.py
xonsh/parsers/base.py
xonsh/parsers/v39.py

this is an easy way to solve all py39 subscriptor related issues https://github.com/xonsh/xonsh/issues?q=is%3Aissue+is%3Aopen+label%3Apy39
Note:
`container[obj.attr] = Value` is still not parsed correctly. It may require some more time investment. But atleast now py39 is usable. (there is a test commented out, anyone implementing that may use it to test the case)

Py39 support

---

docs/bash_to_xsh.rst

Hi! 
A bit docs around subprocess strings for sh-ers.
No news needed.
Thanks!
Related to #1432

A bit docs around subprocess strings for sh-ers

---

news/sqlite_disk_full_fix.rst
xonsh/history/sqlite.py

Fixed #4084 and a bit cleaning the wipe function.

SQLite History Backend: show message instead of exiting when disk is full

---

news/xontrib-history-encrypt.rst
xonsh/xontribs_meta.py

Added xontrib-history-encrypt

---

pyproject.toml
setup.cfg
setup.py
tests/test_ptk_shell.py

No news needed -- just cleaning up a few remaining bits

Cleanup remaining vended ptk bits

---

news/gitstatus_lines.rst
xonsh/prompt/gitstatus.py

This patch adds the number of lines added and removed as part
of the gitstatus line.

add lines changed and removed in gitstatus

---

docs/_templates_overwrite/index.html

Update index.html: install xonsh[full]

---

news/XONSH_HISTORY_FILE.rst
xonsh/environ.py
xonsh/parsers/base.py
xonsh/shell.py

Closes #4118
I've fixed this variable instead of deleting and update the issue description.

Fix XONSH_HISTORY_FILE

---

news/update-bash-completion.rst
xonsh/completers/bash_completion.py

bash-completion: Update to 0.2.7

---

news/shelltypes.rst
xonsh/shell.py

Clean up shell check aliases

---

docs/conf.py

I've read about simpler way then html_extra_path. Let's try it first

docs: copy robots.txt

---

docs/_static/robots.txt
docs/_templates_overwrite/robots.txt
docs/conf.py

docs: copy robots.txt second try

---

news/fix_history_reading.rst
xonsh/main.py
xonsh/shell.py

fix: Not load history in not interactive

---

.github/workflows/pytest-linux-3.6.yml
.github/workflows/pytest-linux-3.7.yml
.github/workflows/pytest-linux-3.8.yml
.github/workflows/pytest-linux-3.9.yml
.github/workflows/pytest-macos-3.6.yml
.github/workflows/pytest-macos-3.7.yml
.github/workflows/pytest-macos-3.8.yml
.github/workflows/pytest-macos-3.9.yml
.github/workflows/pytest-windows-3.6.yml
.github/workflows/pytest-windows-3.7.yml
.github/workflows/pytest-windows-3.8.yml
.github/workflows/pytest-windows-3.9.yml
.github/workflows/pytest.tmpl
.github/workflows/qa-linux-3.8.yml

No news -- restoring github workflows after branch rename

Change master -> main in github workflows

---

docs/contact.rst

docs: Fix contact.rst

---

xonsh/xonfig.py

Reduced expectations of implementing fish.
No news file.

docs: fix wizard text

---

docs/tutorial.rst

docs: mention $RIGHT_PROMPT and $BOTTOM_TOOLBAR

---

xonsh/aliases.py

I know, I know, it's a really small silly PR 🤡 
No news needed

showcmd: Fix docs

---

news/appimage_xpip_sudo.rst
xonsh/aliases.py
xonsh/platform.py

fix: xpip sudo behavior in xonsh appimage

---

news/fix_orend.rst
xonsh/pyghooks.py

fix: and/or colorize

---

news/catch_callable.rst
xonsh/procs/specs.py

Catch callable in the arguments list

---

news/xontrib_macro_lib.rst
xonsh/xontribs_meta.py

[xontrib-macro-lib](https://github.com/anki-code/xontrib-macro-lib) - Library of the useful macroses for the xonsh shell.

Added xontrib-macro-lib

---

.github/pull_request_template.md

To have a reaction and emotional support from the community.
No news.

docs: Added community reaction section to the PR template

---

news/subproc_captured_print_stderr.rst
tests/test_integrations.py
xonsh/environ.py

XONSH_SUBPROC_CAPTURED_PRINT_STDERR to False

---

docs/_templates_overwrite/index.html

Add anchor links for better usability (allows ctrl/middle clicking to open link in new tab).
Would you like a changelog for this? It only changes the website so I wasn't sure and didn't add one yet.

Add anchor links to website navigation bar to improve usbability

---

xonsh/prompt/gitstatus.py

Removed branch color from vertical bar in gitstatus

---

news/ignore_dots.rst
tests/completers/test_base_completer.py
tests/completers/test_dir_completers.py
xonsh/completers/path.py
xonsh/environ.py

Close #4215
I've caught this because I just want to have this in the near release.

Close 4215: Added env variable to ignore ./ and ../ in filepath completion

---

xonsh/prompt/vc.py

Fix IndexError with commands 'cd' or 'ls' a repo

---

requirements/docs.txt
requirements/tests.txt
run-tests.xsh
setup.cfg
tests/test_commands_cache.py
xonsh/aliases.py
xonsh/commands_cache.py
xonsh/jobs.py
xonsh/parsers/base.py
xonsh/parsers/completion_context.py
xonsh/platform.py
xonsh/procs/specs.py
xonsh/prompt/vc.py
xonsh/ptk_shell/key_bindings.py
xonsh/pytest_plugin.py
xonsh/tools.py
xonsh/xonfig.py
xonsh/xontribs_meta.py

Also it has some other works 
1. update mypy and black. Not including news since it is mostly internal
2. fix ply `output_dir` different from default `tab_module` (you could see in the screenshot, how it generates parser tables under directory `xonsh/parsers` instead of `xonsh/` before this fix.)

Fix commands cache testing

---

news/get-obj-name-in-help.rst
xonsh/built_ins.py

Get obj name in help

---

news/improve-import-completions.rst
tests/test_python_completers.py
xonsh/completers/init.py
xonsh/completers/python.py

Improve import completions

---

news/improve-jedi-completer.rst
tests/conftest.py
tests/xontribs/test_jedi.py
xontrib/jedi.py

Before:
After:
Before:
After (wrong case gets corrected):

Improve jedi completer

---

xonsh/__init__.py

fix: skip xonsh.built_ins from amalgam

---

xonsh/execer.py

refactor: speed up getting stack frame

---

.pre-commit-config.yaml

pre-commit: Lint tests dir

---

xonsh/ansi_colors.py

style: remove unused constant

---

docs/api/completers/tools.rst
docs/api/completion_context.rst
docs/tutorial_completers.rst
news/update-completers-tutorial.rst
xonsh/completer.py
xonsh/completers/tools.py
xonsh/environ.py
xonsh/parsers/completion_context.py

Promotes #4285
Promotes #4305
Also adds `$XONSH_TRACE_COMPLETIONS` to allow completions tracing

Update completers tutorial

---

news/git-status-prompt-hide-fields.rst
requirements/tests.txt
tests/prompt/test_gitstatus.py
tests/prompt/test_vc.py
tests/tools.py
xonsh/color_tools.py
xonsh/diff_history.py
xonsh/environ.py
xonsh/prompt/gitstatus.py
xonsh/tools.py

feat: add config option to hide gitstatus prompt fields

---

run-tests.xsh
setup.cfg
tests/test_news.py

chore: move news items check to qa

---

requirements/tests.txt

not including news item as this is development only

chore: update mypy to 0.902

---

xonsh/procs/specs.py

Try running:
```
@(lambda: print(1)) | grep 1
```
@anki-code can you take a look at this?
(no need for news because this was added after the previous version release)

aliases: Fix $__ALIAS_NAME for anonymous functions

---

news/completers-support-generators.rst
xonsh/completer.py

feat: make completer accept generators

---

tests/completers/test_bash_completer.py
xonsh/completers/bash.py
xonsh/completers/bash_completion.py

No need for news since this bug was introduced after the last version

completers: bash: Fix completing an empty prefix

---

docs/tutorial.rst

docs: fix typo in prompt tutorial

---

setup.py
tests/test_parser.py
xonsh/parsers/base.py
xonsh/parsers/v36.py
xonsh/parsers/v38.py

Just some refactoring. Not including a news item since it is internal only.

refactor: remove unused argument to parser

---

xonsh/color_tools.py
xonsh/commands_cache.py
xonsh/tools.py

refactor: small speedup by late import

---

news/simplify.rst
xonsh/codecache.py

code simplifications

---

xonsh/completers/base.py
xonsh/completers/commands.py
xonsh/completers/environment.py
xonsh/completers/path.py
xonsh/completers/pip.py
xonsh/completers/python.py
xonsh/completers/xompletions.py

Start with uppercase and end with a period
No need for news item

completers: Normalize descriptions

---

tests/test_aliases.py

test: remove redundant xonsh session mock fixture

---

news/procs-wsl1-check.rst
xonsh/platform.py
xonsh/procs/specs.py
xonsh/xonfig.py

Procs wsl1 check

---

requirements/tests.txt
tests/test_news.py

this is mostly internal detail and thus not including a news item. 
will solve situations like in #4389 

feat: use rst-linter for news items check

---

news/xontrib-homebrew.rst
xonsh/xontribs_meta.py

replaces xontrib-linuxbrew by expanding OS support to Homebrew on macOS

feat: add xontrib-homebrew

---

news/fix-jedi-path-completion.rst
tests/xontribs/test_jedi.py
xontrib/jedi.py

Fix jedi path completion

---

.pre-commit-config.yaml
pyproject.toml
requirements/tests.txt

chore: upgrade black and mypy

---

news/complete-environment-description.rst
tests/completers/test_environment_completer.py
xonsh/completers/environment.py

Shows the env var's description when completing it 🔥 
Also show its type in the display:

Complete environment description

---

docs/keyboard_shortcuts.rst
news/ctrl-backspace-delete-word.rst
xonsh/ptk_shell/key_bindings.py

This completes xonsh's usage as a complete text editor 📝 

Ctrl backspace delete word

---

news/env-not-none.rst
xonsh/commands_cache.py

Small robustness fix for https://github.com/xonsh/xonsh/pull/4106#issuecomment-894497581

Env is not None

---

tests/conftest.py
tests/test_parser.py
xonsh/built_ins.py

- Not including a news item as it doesn't affect the users

test: speedup test suit by reusing costly vars

---

news/fix-vox-ssp.rst
tests/test_vox.py
xontrib/voxapi.py

fix: vox system_site_packages option not passed

---

xonsh/ptk_shell/shell.py

refactor: pass the file and extra arguments to ptk_print

---

xonsh/completers/_aliases.py

completer: Update 'add' documentation

---

news/xontrib-pyrtn.rst
xonsh/xontribs_meta.py

Added `xontrib-pyrtn` to xontrib list. See discussion #4239

Added `xontrib-pyrtn` to xontrib list

---

docs/keyboard_shortcuts.rst

These feel pretty stable by now, does anyone experience any unstable behaviors with them?
No need for news item

docs: Remove highlight shortcuts 'beta' tag

---

news/fix-app-exec-alias.rst
xonsh/procs/specs.py

fix check for app execution alias

---

xonsh/completer.py

completions: Trace correct completions with $XONSH_TRACE_COMPLETIONS

---

run-tests.xsh

This is an internal change. not including news item. 

feat: use cli_utils to scaffold run-tests.xsh

---

news/ap-xonfig.rst
tests/completers/test_completer_command.py
tests/completers/test_xompletions.py
tests/conftest.py
tests/test_xonfig.py
xonsh/aliases.py
xonsh/cli_utils.py
xonsh/completers/init.py
xonsh/completers/xompletions.py
xonsh/xonfig.py

ArgparserAlias - xonfig2

---

news/ap-xexec.rst
tests/aliases/test_xexec.py
tests/test_cli_utils.py
xonsh/aliases.py
xonsh/cli_utils.py

feat: use argparserAlias for xexec

---

README.rst

Jnoortheen patch 1

---

.github/workflows/genbuilds.py
.github/workflows/pytest-linux-3.9.yml
.github/workflows/pytest-macos-3.9.yml
.github/workflows/pytest-windows-3.9.yml
.github/workflows/pytest.tmpl

also upgrade codecov-action version
* internal change: no news item

chore: combine coverage reports from all platforms supported

---

.coveragerc
tests/conftest.py
tests/test_readline_shell.py
xonsh/base_shell.py
xonsh/readline_shell.py

internal change: no need for news item.

Add test for readline shell

---

requirements/tests.txt
tests/test_ptk_shell.py

test: improve ptk_shell tests

---

xonsh/completers/_aliases.py

refactor: remove unused code

---

news/path-completion-in-python-code.rst
tests/test_path_completers.py
xonsh/completers/path.py

Path completion in python code

---

docs/customization.rst

Fix typo in xpip command for updating xonsh

---

news/sub-proc-tracer.rst
run-tests.xsh
xonsh/environ.py
xonsh/procs/specs.py

feat: add new environment variable to customize tracing

---

tests/procs/test_specs.py
tests/procs/tools.py

refactor: remove redundant code

---

setup.cfg
tests/aliases/test_xexec.py
tests/completers/test_base_completer.py
tests/completers/test_command_completers.py
tests/completers/test_dir_completers.py
tests/completers/test_environment_completer.py
tests/test_aliases.py
tests/test_completion_context.py
tests/test_dirstack_unc.py
tests/test_environ.py
tests/test_integrations.py
tests/test_lexer.py
tests/test_main.py
tests/test_parser.py
tests/test_python_completers.py

chore: enable flake8 for tests

---

news/feat-pip-completer.rst
tests/completers/test_completer_command.py
tests/completers/test_pip_completer.py
tests/conftest.py
xonsh/completer.py
xonsh/completers/pip.py

feat: improve pip completer

---

docs/editors.rst

Fixed typo.
Fix typo in editors.rst

Fix typo in editors.rst

---

tests/test_cli_utils.py
xonsh/aliases.py
xonsh/cli_utils.py
xonsh/completers/completer.py
xonsh/dirstack.py
xonsh/history/main.py
xonsh/jobs.py
xonsh/xonfig.py
xonsh/xontribs.py
xontrib/vox.py

Not adding news item. This is just an internal refactoring. This will reduce the boilerplate code required to make an argument a flag

adding convention for short boolean flags

---

CONTRIBUTING.rst

docs: update header image link for Contributing.md

---

news/3766.rst
xonsh/completers/path.py

Add quotes in autocomplete when filename contains brackets

---

xonsh/tracer.py

fix: docs build fail on tracer calls without spec

---

docs/editors.rst
news/sublime-xonsh.rst

Add Sublime Text 4 extension to the Editors page

---

news/xontrib-default-command.rst
news/xontrib-up.rst
xonsh/xontribs_meta.py

Added new xontribs for "up" and "default-command". These are hosted at https://github.com/oh-my-xonsh and PyPI:
- https://pypi.org/project/xontrib-up
- https://pypi.org/project/xontrib-default-command

New xontribs

---

news/vox-improvements.rst
tests/test_vox.py
xonsh/cli_utils.py
xontrib/vox.py
xontrib/voxapi.py

Vox improvements

---

news/foreign-funcs-completions.rst
tests/aliases/test_source.py
xonsh/aliases.py
xonsh/cli_utils.py

feat: auto-completion support for source-foreign

---

docs/conf.py
tests/test_xoreutils.py
xonsh/ptk_shell/shell.py

code refactor

---

docs/tutorial_hist.rst
xonsh/environ.py

Clarify behavior for capturing and storing output in the history.

---

README.rst

docs: add "The xonsh shell community" to the readme

---

news/cmd-completion-desc.rst
tests/completers/test_base_completer.py
tests/completers/test_command_completers.py
xonsh/commands_cache.py
xonsh/completers/base.py
xonsh/completers/commands.py
xonsh/environ.py

feat: update command completions to show description as well

---

news/completer-cmd.rst
tests/completers/test_completer_command.py
tests/conftest.py
tests/test_cli_utils.py
xonsh/cli_utils.py
xonsh/completer.py
xonsh/completers/_aliases.py

feat: add sub-command to print current completions

---

news/history-transfer.rst
tests/test_cli_utils.py
tests/test_history_dummy.py
xonsh/cli_utils.py
xonsh/history/main.py

history transfer

---

news/vc-current-branch.rst
xonsh/prompt/vc.py

fix: prompt getting git branch

---

.coveragerc
setup.cfg

test: update test configs

---

news/vox-upgrade.rst
tests/conftest.py
tests/test_vox.py
xonsh/cli_utils.py
xonsh/commands_cache.py
xonsh/history/main.py
xonsh/tools.py
xontrib/vox.py
xontrib/voxapi.py

feat: add upgrade command

---

news/loading-coreutils.rst
xonsh/aliases.py
xontrib/coreutils.py

refactor: do not override sys coreutils

---

news/fix-dict-unpacking-into-dict.rst
tests/test_parser.py
xonsh/parsers/base.py

Fix unpacking of dictionaries inside a dictionary

---

xonsh/xoreutils/uptime.py

fix: boottime on haiku getting

---

news/env-vars.rst
requirements/tests.txt
tests/completers/test_xompletions.py
xonsh/completers/commands.py
xonsh/completers/imports.py
xonsh/environ.py
xonsh/jobs.py
xonsh/parsers/completion_context.py

Completers path

---

xontrib/fish_completer.py
xontrib/voxapi.py

ignore error in fish completions

refactor: break multi-line question

---

run-tests.xsh
setup.cfg
xonsh/cli_utils.py
xonsh/parsers/completion_context.py
xonsh/proc.py
xonsh/pygments_cache.py
xonsh/readline_shell.py
xonsh/style_tools.py
xontrib/abbrevs.py
xontrib/autovox.py
xontrib/vox.py

as well as match dmypy semantics

chore: type check xontribs,xompletions

---

.github/workflows/docs.yml

build docs in PR

---

xonsh/parsers/v38.py

refactoring code with starred pythonic idiom which is more pythonic, concise, readable and efficient; how do think this change which has practical value？

refactoring code with starred pythonic idiom

---

.github/ISSUE_TEMPLATE/config.yml

chore: point to discussions in case of Q&A

---

docs/tutorial.rst
news/time-format-docs.rst

Clarified the use of `time_format` in tutorial
Discussion #4711

Clarified use of time_format in docs

---

docs/tutorial.rst

very minor spelling correction

do to following -> do the following

---

Makefile
docs/Makefile
docs/_templates/api-summary-module.rst
docs/conf.py
docs/serve_docs.py
docs/tutorial.rst
news/prompt.rst
tests/completers/test_xompletions.py
tests/prompt/test_base.py
tests/prompt/test_gitstatus.py
xonsh/base_shell.py
xonsh/completers/commands.py
xonsh/environ.py
xonsh/lib/modules.py
xonsh/prompt/__init__.py
xonsh/prompt/base.py
xonsh/prompt/gitstatus.py
xonsh/ptk_shell/formatter.py
xonsh/ptk_shell/shell.py
xonsh/tools.py

This is created after needing to reuse and extend gitstatus from prompt function in efficient way. 
Possibly we can close #1831 #1756 #4493 after this

gitstatus modular

---

.github/workflows/test.yml
tests/test_xonfig.py

chore: add back codecov reports

---

tests/conftest.py
tests/test_aliases.py
tests/test_vox.py
xonsh/cli_utils.py
xontrib/vox.py

Fix vox env dir

---

.github/workflows/check-news-item.yml
.github/workflows/check-news.py

Comment pr

---

.github/workflows/check-news-item.yml

chore: pass env variables

---

.github/workflows/check-news-item.yml
.github/workflows/check-news.py
xonsh/base_shell.py
xonsh/pytest/plugin.py

This will fix https://github.com/xonsh/xonsh/runs/5952906070?check_suite_focus=true once for new PRs.

fix: pr commentor

---

news/fix-vox-rm.rst
xonsh/pytest/plugin.py
xontrib/vox.py

Some fixes

---

news/fix-gitstatus.rst
tests/prompt/test_gitstatus.py
xonsh/prompt/base.py

fix: gitstatus prompt

---

.github/workflows/test.yml
news/refactor-drop-py37.rst
setup.py
xonsh/lexer.py

https://numpy.org/neps/nep-0029-deprecation_policy.html
fixes #4706 

chore: drop py3.7

---

news/fix-broken-bg.rst
xonsh/jobs.py

Fixes #4380 
Fixes #3361 
Fixes #2353 

Fix `bg` command behaviour

---

news/fixEnvironmentCompletion.rst
tests/completers/test_environment_completer.py
xonsh/completers/environment.py

Fix environment variable completion in strings

---

news/refactor-fish-completer.rst
tests/xontribs/test_fish_completer.py
xontrib/fish_completer.py

feat: filter completions from fish

---

news/ignorespace-doc.rst
xonsh/environ.py

This is a simple change to document the HISTCONTROL "ignorespace" option. I also reformatted the HISTCONTROL documentation as a bulleted list to make it easier to read.

Documenting the HISTCONTROL ignorespace option

---

docs/Makefile
docs/api/index.rst
docs/installation.rst

fix: docs building

---

docs/tutorial.rst
news/feat-f-glob-strings.rst
tests/test_parser.py
xonsh/parsers/base.py
xonsh/tokenize.py

feat: f-glob strings

---

news/fix-str-literal-concat.rst
tests/test_parser.py
xonsh/parsers/base.py
xonsh/pytest/tools.py

fix: string literal concatenation

---

.github/workflows/publish.yml

fix-pypi-gha

---

CHANGELOG.rst
news/main.rst
xontrib/whole_word_jumping.py

#4845: conditional import of ptk_win32 → windows only

---

CONTRIBUTING.rst

Also stripped out reference to an imaginary release process and cleaned
up some style issues in the RST

docs(devguide): update how to build the docs

---

docs/_templates/index.html

Removed GTM

---

news/xpip_perms.rst
xonsh/aliases.py

fix(xpip): never add `sudo`, append `--user` instead

---

docs/_templates/index.html

Hi,
Let me know if I should add a news entry for this PR.

docs: Add GNU Guix information

---

README.rst

Update README.rst: add link to xontrib-template

---

README.rst

Update README.rst: install from pip

---

news/fix-empty-gitstatus.rst
tests/prompt/test_gitstatus.py
xonsh/prompt/gitstatus.py

fix: empty gitstatus on paths without repo

---

docs/packages.rst

It's weirdly hard to find anything about installing xonsh into Windows Terminal (even though that info's right here on the website).  So link to that hard-to-find info directly; if someone wants to find out what Windows Terminal is they can Google it on their own :)

Link to xonsh-specific Windows Terminal info

---

news/xpip.rst
xonsh/aliases.py

Fix #4879 because `basecmd.extend` returns `None` ;)

Fix: xpip return None instead of command

---

docs/tutorial_hist.rst

Update tutorial_hist.rst: remove description of not implemented logic 

---

docs/tutorial.rst
docs/xonshrc.rst

Document that xonshrc files not applied on non-interactive mode

---

news/cmds-cache.rst
tests/completers/test_base_completer.py
tests/test_commands_cache.py
tests/test_pipelines.py
tests/test_ptk_completer.py
tests/test_vox.py
xonsh/aliases.py
xonsh/built_ins.py
xonsh/commands_cache.py
xonsh/environ.py
xonsh/pyghooks.py
xonsh/pytest/plugin.py
xonsh/tools.py

cmd cache refactor - optimize cache usage

---

news/fix-windows-alias-override.rst
xonsh/commands_cache.py

cmd cache: check possibilities when checking if alias overrides

---

.github/workflows/publish.yml
news/publish311.rst

chore: add 3.11 to wheel release action

---

news/appimage311.rst
rever.xsh
xonsh/aliases.py

Bump APPIMAGE_PYTHON_VERSION to 3.11 and fix xpip for AppImage

---

docs/tutorial.rst

It's just a little documentation update.
﻿Came from #5032.

Add a warning to the docs about $args in ExecAlias

---

xonsh/built_ins.py

This PR fixes https://github.com/xonsh/xonsh/issues/4993
I'm only specifically catching that error and throwing an error message. Let me know if I need to change something or maybe phrase the error message better.

Handle regex error

---

docs/customization.rst
docs/editors.rst

docs: remove reduntant table of contents

---

xontrib/abbrevs.py

fix(abbrevs): remove incorrect override of carriage return in abbrevs

---

docs/_templates/index.html
tests/prompt/test_vc.py
xonsh/tools.py

Mini fix chdir

---

news/pr-5072.rst
tests/test_main.py
xonsh/main.py
xonsh/tools.py

This PR aims to Improve the error message when RAISE_SUBPROC_ERROR is set to True
This is a follow-up for PR #5066 

Improve error message for RAISE_SUBPROC_ERROR=True

---

README.rst

The issues around Jupyter and JupyterLab was fixed so let's mention them.
Also the Euporie project is awesome!

Add mention of jupyter

---

CONTRIBUTING.rst
docs/_templates/index.html
docs/customization.rst
docs/platform-issues.rst
docs/python_virtual_environments.rst
docs/tutorial.rst
docs/tutorial_history_backend.rst
docs/xonshrc.rst
news/new_prompt_end_char.rst
xonsh/prompt/base.py

Closes #4152
Vote result - https://github.com/xonsh/xonsh/issues/4152#issuecomment-794178842
Key comments:
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-794875983 - XEP-like description
* https://github.com/xonsh/xonsh/issues/4152#issue-823993141 - Prerequisites
Xonsh looks like bash and it's confusing:
* https://youtu.be/EbX2fhfwOWc?t=832
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-1183368071
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-1435521549
TODO:
Next steps after merge:
* Update images
* Update xonsh docker container on dockerhub

New prompt end character

---

xonsh/environ.py

Example for XONSH_HISTORY_IGNORE_REGEX

---

FUNDING.yml
README.rst
docs/_templates/index.html
news/become-a-sponsor-to-xonsh.rst

https://github.com/xonsh/xonsh/issues/3375#issuecomment-1614672370

Become a sponsor to xonsh

---

news/pr-5174.rst
xonsh/tools.py

Fix the issue pointed by https://github.com/xonsh/xonsh/commit/2a63f1f875754d04d71a1f4937ce68312223ea3c#r121718023
The error was introduced by #5072

fix: Fix wrong verification for the simple output, introduced by PR5072

---

news/always_load_rc_except_norc.rst
tests/test_main.py
xonsh/main.py

This change fixes issue #4855.

Always load rc files except --no-rc is passed

---

README.rst

Update README.rst: added one another way to help

---

README.rst

Update README.rst: micro fix

---

news/bugfix-sudo-history.rst
xonsh/history/json.py

history: fix json file permissions upon `sudo` (#5220)

---

.github/pull_request_template.md
news/pin-ptk.rst
pyproject.toml

Workaround for [#5241](https://github.com/xonsh/xonsh/issues/5241#issuecomment-1961889489)

Pin prompt-toolkit version

---

news/fix_dircolors_NotADirectoryError.rst
xonsh/environ.py

Fix dircolors NotADirectoryError

---

xonsh/procs/specs.py

Fixes error pointed out by @jnoortheen in https://github.com/xonsh/xonsh/pull/5322#issuecomment-2045091900

Flatten redirects before passing command to job control

---

news/brackets-in-args.rst
tests/test_parser.py
xonsh/parsers/base.py

feat: allow square brackets in command arguments

---

README.rst

docs: link to dev guide and emphasis on solving issues

---

xonsh/environ.py

Update environ.py: doc microfix

---

.gitignore
news/cli-utils-update.rst
tests/test_virtualenv_activator.py
xonsh/cli_utils.py
xonsh/history/main.py
xonsh/xonfig.py

Update cli utils

---

.github/workflows/docs.yml
.github/workflows/publish.yml
.github/workflows/test.yml

and use PyPI OICD to publish packages
@gforsyth  need to update https://pypi.org/manage/project/xonsh/settings/publishing/  for it to work

feat: use uv for installing test deps

---

.github/ISSUE_TEMPLATE/new-issue.md

Reverting xonsh/xonsh#5389 with update by comments

Revert "Update new-issue.md: update issue template"

---

tests/test_virtualenv_activator.py
xonsh/virtualenv/__init__.py

fix: update virtualenv activator

---

tests/test_cli_utils.py
xonsh/cli_utils.py
xonsh/xontribs.py

fixed the issue caused by regression 

Fix argparser

---

news/typerr.rst
xonsh/xoreutils/_which.py

Fix described in https://github.com/xonsh/xonsh/issues/5358#issuecomment-2104322754
Closes #5379, #5429

Fix 5379, 5429

---

appimage/pre-requirements.txt
news/unpin_ptk.rst
pyproject.toml

Merge this after https://github.com/xonsh/xonsh/pull/5437

Unpin prompt-toolkit version

---

docs/tutorial.rst

Tutorial: add note about rtn

---

docs/tutorial.rst
news/tutorial_callias_capturing.rst
tests/procs/test_specs.py

Tutorial: Callable alias and capturing

---

CONTRIBUTING.rst
docs/_templates/index.html
docs/packages.rst
news/TEMPLATE.rst

I'm using [xonsh-install](https://github.com/anki-code/xonsh-install) pretty long time and I see that it works pretty predictable, expected and stable. I suggest to mention this approach in our docs to get more attention and testing around this from users and some day move xonsh-install to the xonsh project.

docs: install xonsh as a core shell

---

docs/_templates/index.html

* fix section
* added link to latest release
Please update https://xon.sh after merge this.

fix main page

---

docs/xonshrc.rst
tests/test_integrations.py

* Added py mention to docs
* Added tests
* Microfix

xonshrc: add docs and tests for py files

---

docs/tutorial.rst

Added SpecModifierAlias (#5443) to the tutorial.

docs: SpecModifierAlias to the tutorial

---

tests/test_integrations.py

tests: SpecAttrModifierAlias: integration test

---

docs/api/index.rst

- Updated authorship for 0.18.2
- bumped version to 0.18.2
- Updated CHANGELOG for 0.18.2
- docs: fix up api doc paths

docs: fix up broken apidocs links

---

.github/workflows/test.yml
news/multiline_prompt.rst
xonsh/environ.py

I see that #5624 is not working well for light theme. So let's use space without background.

MULTILINE_PROMPT: using space without background

---

.coveragerc
run-tests.xsh

use faster coverage

---

xonsh/cli_utils.py

Make_cli_utils.py_compatible_with_argparse_new_private_API (duplicates PR #5725 to rerun CI and avoid rebase)

---

.github/workflows/publish.yml
pyproject.toml

chore: add 3.13 to release jobs and remove stale dependency

---

news/pipelines_fix_check_self_proc.rst
xonsh/procs/pipelines.py

Update pipelines.py: fix checking `self.proc`

---

.pre-commit-config.yaml

ci: Update .pre-commit-config.yaml

---

xonsh/built_ins.py
xonsh/parser.py
xonsh/parsers/rd_parser.py
xonsh/tools.py

An [experimental parser](https://github.com/jnoortheen/xonsh-rd-parser), based on [Ruff's Python parser](https://github.com/astral-sh/ruff/tree/main/crates/ruff_python_parser) is now availabe.
You can try the new parser after installing it with ``env XONSH_RD_PARSER=1 xonsh``.

feat: New experimental Rust based parser for xonsh
